- package.json
> chore(package): update @types/node to version 6.0.54

- package.json
> chore(package): update jest to version 18.1.0

- package.json
> chore(package): update @types/jest to version 16.0.3

- package.json
Closes #37
https://greenkeeper.io/
> chore(package): update @types/request to version 0.0.39

- package.json
> chore(package): update @types/node to version 6.0.55

- package.json
> chore(package): update @types/node to version 6.0.56

- package.json
> chore(package): update @types/node to version 6.0.59

- package.json
> chore(package): update @types/graphql to version 0.8.6

- package.json
> chore(package): update typescript to version 2.1.5

- package.json
> chore(package): update @types/jest to version 16.0.4

- package.json
Closes #62
https://greenkeeper.io/
> chore(package): update @types/jest to version 18.1.1

- package.json
> chore(package): update tslint to version 4.4.2

- package.json
> chore(package): update @types/node to version 7.0.5

- dev-test/githunt/API.swift
- dev-test/githunt/typings.d.ts
- dev-test/star-wars/API.swift
- dev-test/star-wars/typings.d.ts
The dev-test files were out of date. They're a good example of the types generated by the library so I think it's important to keep them updated. 
I'd suggest adding a script to do so automatically. I just manually ran the commands for now. 
BTW this library is GREAT! It's the best one I've found so far so awesome job!
> update dev-test type files

- src/handlers/model-handler.ts
- src/handlers/operation-handler.ts
> Prevent multi-file outputs from having duplicate imports

- packages/graphql-codegen-cli/README.md
- packages/graphql-codegen-cli/src/cli.ts
- packages/graphql-codegen-compiler/README.md
- packages/graphql-codegen-compiler/src/handlebars-extensions.ts
- packages/graphql-codegen-generators/README.md
- packages/graphql-codegen-generators/src/types.ts
Also added some more cool helpers and fixed some issues with `ifDirective`.
Related to: https://github.com/dotansimha/graphql-code-generator/issues/134
> Add support for custom helpers

- packages/graphql-codegen-compiler/tests/typescript-multi-file.spec.ts
- packages/graphql-codegen-compiler/tests/typescript-single-file.spec.ts
- packages/graphql-codegen-generators/src/typescript-multi-file/operation.handlebars
- packages/graphql-codegen-generators/src/typescript-multi-file/type.handlebars
- packages/graphql-codegen-generators/src/typescript-single-file/documents.handlebars
- packages/graphql-codegen-generators/src/typescript-single-file/schema.handlebars
- packages/graphql-codegen-generators/src/typescript-single-file/selection-set.handlebars
- packages/graphql-codegen-generators/src/typescript-single-file/type.handlebars
> feat(typescript): emit nullable fields as optional

- packages/graphql-codegen-core/src/schema/resolve-type.ts
- packages/graphql-codegen-core/tests/transform-fields.spec.ts
Quick and dirty fix for #169. I will try to publish custom fork to NPM soon unless @dotansimha will respond here. Anyone feeling for adding some tests for this?
> Handle lists and non-null properly

- packages/graphql-codegen-compiler/tests/multiple.spec.ts
- packages/graphql-codegen-generators/README.md
- packages/graphql-codegen-generators/src/typescript-multi-file/config.ts
- packages/graphql-codegen-generators/src/typescript-single-file/config.ts
`enum` on `typescript` represents a value therefore it can't be imported from `d.ts` (type definition file);
> Export file as .ts instead of .d.ts

- CHANGELOG.md
- package.json
- packages/graphql-codegen-cli/src/utils/document-finder.ts
- packages/graphql-codegen-cli/tests/document-finder.spec.ts
- packages/graphql-codegen-cli/tests/test-files/6.ts
Closes:
https://github.com/dotansimha/graphql-code-generator/issues/233
> Fixes for document finder bugs 

- CHANGELOG.md
- packages/graphql-codegen-compiler/README.md
- packages/graphql-codegen-compiler/src/handlebars-extensions.ts
- packages/templates/typescript-multiple/tests/typescript.spec.ts
- packages/templates/typescript/tests/typescript.spec.ts
> Support jsdocs comments in typescript template

- packages/graphql-codegen-cli/.vscode/settings.json
- packages/graphql-codegen-cli/package.json
- packages/graphql-codegen-cli/src/utils/strip-comments.ts
The old code wasn't so pretty, my bad :(
> refactor strip-comments

- packages/graphql-codegen-cli/src/loaders/introspection-from-file.ts
- packages/graphql-codegen-cli/tests/introspection-from-file.spec.ts
- packages/graphql-codegen-cli/tests/test-files/ByteOrderMask.json
> workaround bom in json

- packages/graphql-codegen-core/package.json
- packages/graphql-codegen-core/src/debugging.ts
- packages/graphql-codegen-core/src/utils/logger.ts
- yarn.lock
> Update winston to 3.0.0

- packages/graphql-codegen-cli/src/utils/document-finder.ts
> Support backticks

- dev-test/test-schema/schema-with-imports.graphql
- packages/graphql-codegen-cli/package.json
- packages/graphql-codegen-cli/src/loaders/schema/schema-from-export.ts
- packages/graphql-codegen-cli/src/loaders/schema/schema-from-typedefs.ts
- packages/graphql-codegen-cli/tests/cli.spec.ts
- packages/graphql-codegen-cli/tests/schema-from-typedefs.spec.ts
- packages/graphql-codegen-cli/tests/test-files/schema-dir/query.graphql
- yarn.lock
Found that issue by trying to publish this package to my own scope so I could test my #480 PR on my own project. 
Seems to me like a good change nonetheless..
Thanks ahead!
> Fixed relative import to the core package

- packages/templates/typescript/src/enum.handlebars
> [typescript] fix pascalcase enum names

- packages/templates/typescript/src/schema.handlebars
- packages/templates/typescript/tests/resolvers.spec.ts
> fix(typescript): non optional arguments in Resolver

- packages/graphql-codegen-cli/src/codegen.ts
- packages/graphql-codegen-cli/src/loaders/documents/document-loader.ts
Hi!
This is quick implementation of a fix for: #356. I don't know if this is the right place for the validation but more of starting point of a discussion how this could be implemented. Please let me know what you think.
> Validate queries against the graphql schema

- package.json
> wip: Run yarn test before yarn build

- examples/typescript-react-apollo/package.json
- lerna.json
- packages/graphql-codegen-cli/package.json
- packages/graphql-codegen-compiler/package.json
- packages/graphql-codegen-core/package.json
- packages/scripts/codegen-templates-scripts/package.json
- packages/templates/introspection/package.json
- packages/templates/typescript-apollo-angular/package.json
- packages/templates/typescript-mongodb/package.json
- packages/templates/typescript-react-apollo/package.json
- packages/templates/typescript/package.json
> fix versioning

- packages/templates/typescript-apollo-angular/src/components.handlebars
- packages/templates/typescript-apollo-angular/tests/components.spec.ts
> Make sure documents are not html escaped

- packages/graphql-codegen-cli/src/codegen.ts
- packages/graphql-codegen-cli/tests/codegen.spec.ts
> Fix missing error message in logger

- examples/typescript-react-apollo/src/generated-models.tsx
- examples/typescript-react-apollo/src/schema/user-fragment.graphql
- examples/typescript-react-apollo/src/schema/user.query.graphql
- examples/typescript-react-apollo/yarn.lock
- packages/templates/typescript-apollo-angular/src/components.handlebars
- packages/templates/typescript-apollo-angular/tests/components.spec.ts
- packages/templates/typescript-react-apollo/src/components.handlebars
- packages/templates/typescript-react-apollo/src/hoc.handlebars
- packages/templates/typescript-react-apollo/tests/components.spec.ts
> [typescript-react-apollo/apollo-angular] append inline fragments in generated components

- package.json
- yarn.lock
more info here: https://github.com/lerna/lerna/issues/1638
> Revert lerna version

- packages/graphql-codegen-cli/src/loaders/schema/schema-from-export.ts
Just noticed this while I was looking through the code. Thanks for the useful tool!
> Fix typo in a debug log.

- packages/graphql-codegen-compiler/src/handlebars-extensions.ts
- packages/templates/typescript/src/documents.handlebars
- packages/templates/typescript/tests/typescript.spec.ts
- yarn.lock
https://github.com/dotansimha/graphql-code-generator/issues/605
> Fix for Issue #605

- packages/graphql-codegen-cli/src/codegen.ts
- packages/graphql-codegen-cli/src/loaders/documents/document-loader.ts
- packages/graphql-codegen-cli/tests/cli.spec.ts
- packages/graphql-codegen-cli/tests/load-documents-sources.spec.ts
- packages/graphql-codegen-cli/tests/test-documents/invalid-fields.graphql
- packages/graphql-codegen-cli/tests/test-documents/schema.graphql
- packages/graphql-codegen-cli/tests/test-documents/valid.graphql
- packages/graphql-codegen-core/src/utils/logger.ts
This is an attempt to solve #621.
I have not been able to test it. Is there some easy way to test?
Fixes #621.
> Print file path and number of errors when validating queries against schema

- packages/graphql-codegen-core/src/index.ts
- packages/graphql-codegen-core/src/utils/parse.ts
- packages/graphql-codegen-core/tests/parse.spec.ts
> Catch an error while parsing

- packages/graphql-codegen-core/src/schema/transform-enum.ts
- packages/graphql-codegen-core/tests/transform-enum.spec.ts
https://github.com/dotansimha/graphql-code-generator/issues/418
> added directives to enum values

- packages/templates/typescript/README.md
> Correct the name of no namespaces env variable

- packages/graphql-codegen-compiler/package.json
- packages/scripts/codegen-templates-scripts/package.json
- packages/templates/apollo-angular/package.json
- packages/templates/introspection/package.json
- packages/templates/typescript-mongodb/package.json
- packages/templates/typescript-react-apollo/package.json
- packages/templates/typescript/package.json
This makes it a lot easier to find the code when wanting to contribute to the project.
> Add a repository to package.jsons that are missing it

- dev-test/githunt/types.avoidOptionals.ts
- dev-test/githunt/types.d.ts
- dev-test/githunt/types.immutableTypes.ts
- dev-test/githunt/types.noNamespaces.ts
- dev-test/githunt/types.reactApollo.tsx
- dev-test/githunt/types.ts
- dev-test/star-wars/types.avoidOptionals.ts
- dev-test/star-wars/types.d.ts
- dev-test/star-wars/types.immutableTypes.ts
- dev-test/star-wars/types.noNamespaces.ts
- dev-test/star-wars/types.ts
- dev-test/test-schema/typings.avoidOptionals.ts
- dev-test/test-schema/typings.immutableTypes.ts
- dev-test/tsconfig.json
- examples/typescript-react-apollo/src/components/TestWithComponent/TestWithComponent.tsx
- examples/typescript-react-apollo/src/components/TestWithFragment/TestWithFragment.tsx
- examples/typescript-react-apollo/src/components/TestWithHOC/TestWithHOC.view.tsx
- examples/typescript-react-apollo/src/generated-models.tsx
- examples/typescript-react-apollo/tsconfig.json
- packages/templates/typescript-react-apollo/src/components.handlebars
- packages/templates/typescript-react-apollo/src/config.ts
- packages/templates/typescript-react-apollo/tests/components.spec.ts
> [react-apollo] Support strict TypeScript

- packages/templates/typescript/README.md
- packages/templates/typescript/src/config.ts
- packages/templates/typescript/src/enum.handlebars
- packages/templates/typescript/src/helpers/get-enum-value.ts
- packages/templates/typescript/tests/typescript.spec.ts
Fixes https://github.com/dotansimha/graphql-code-generator/issues/576
> Add support for internal enum values in typescript template

- README.md
this readme is not correct, the default config file is `gql-gen.json`
> readme: gql-gen.json

- packages/templates/typescript/README.md
- packages/templates/typescript/src/enum.handlebars
- packages/templates/typescript/tests/typescript.spec.ts
- yarn.lock
As described here: 
https://www.typescriptlang.org/docs/handbook/enums.html#const-enums
> [TypeScript] Added support for const enums

- packages/graphql-codegen-cli/package.json
- packages/graphql-codegen-cli/src/codegen.ts
- packages/graphql-codegen-cli/tsconfig.json
- yarn.lock
> Added support for graphql-config

- packages/templates/typescript/src/helpers/get-field-resolver.ts
- packages/templates/typescript/src/resolver.handlebars
- packages/templates/typescript/tests/resolvers.spec.ts
- packages/templates/typescript/tests/typescript.spec.ts
- packages/templates/typescript/tests/utils.ts
> SubscriptionResolver is not used in Subscription-related fields

- packages/templates/typescript/src/resolver.handlebars
- packages/templates/typescript/src/schema.handlebars
- packages/templates/typescript/src/selection-set.handlebars
- packages/templates/typescript/src/type.handlebars
- packages/templates/typescript/tests/typescript.spec.ts
> Move comments on top of fields

- packages/graphql-codegen-cli/src/loaders/documents/validate-documents.ts
- packages/graphql-codegen-cli/tests/load-documents-sources.spec.ts
- packages/graphql-codegen-cli/tests/test-documents/unused-variable.graphql
Related: https://github.com/dotansimha/graphql-code-generator/issues/726
> Improve document validation

- packages/templates/apollo-angular/src/components.handlebars
- packages/templates/apollo-angular/tests/components.spec.ts
- packages/templates/typescript-react-apollo/src/components.handlebars
- packages/templates/typescript-react-apollo/tests/components.spec.ts
> Skip Apollo templates if no operations

- dev-test/githunt/feed.query.graphql
- dev-test/githunt/graphql-declared-modules.d.ts
- dev-test/githunt/types.avoidOptionals.ts
- dev-test/githunt/types.d.ts
- dev-test/githunt/types.immutableTypes.ts
- dev-test/githunt/types.noNamespaces.ts
- dev-test/githunt/types.reactApollo.noNamespaces.tsx
- dev-test/githunt/types.reactApollo.tsx
- dev-test/githunt/types.ts
- packages/templates/typescript/src/selection-set.handlebars
> Fix query typings

- packages/graphql-codegen-cli/src/codegen.ts
- packages/graphql-codegen-cli/src/generate.ts
- packages/graphql-codegen-cli/src/loaders/schema/introspection-from-file.ts
- packages/graphql-codegen-cli/src/loaders/schema/introspection-from-url.ts
- packages/graphql-codegen-cli/src/loaders/schema/schema-from-export.ts
- packages/graphql-codegen-cli/src/spinner.ts
> Silet spinner

- packages/graphql-codegen-cli/src/codegen.ts
Right now when you try to use `typescript-common` plugin it says codegen couldn't find it but the real reason is the plugin has an internal issue. This PR shows that and helps a user a bit to install a proper package.
> v2: Don't ignore plugin-level errors

- packages/graphql-codegen-cli/src/loaders/documents/document-loader.ts
- packages/graphql-codegen-cli/src/loaders/schema/schema-from-typedefs.ts
- packages/graphql-codegen-cli/src/utils/prettier.ts
> Handle graphqls files

- dev-test/githunt/types.reactApollo.noNamespaces.tsx
- dev-test/githunt/types.reactApollo.tsx
- dev-test/test-message/types.reactApollo.noNamespaces.tsx
- packages/templates/typescript-react-apollo/src/components.handlebars
> Add MutationFn typings

- dev-test/githunt/types.reactApollo.noNamespaces.tsx
- dev-test/githunt/types.reactApollo.tsx
- dev-test/test-message/types.reactApollo.noNamespaces.tsx
- packages/templates/typescript-react-apollo/src/components.handlebars
- packages/templates/typescript-react-apollo/tests/components.spec.ts
> Add TChildProps for props callback

- packages/plugins/typescript-apollo-angular/src/helpers/generate-fragments.ts
- packages/plugins/typescript-apollo-angular/src/helpers/gql.ts
- packages/plugins/typescript-apollo-angular/src/root.handlebars
- packages/plugins/typescript-apollo-angular/tests/apollo-angular.spec.ts
> should generate Component with noGraphqlTag enabled and fragments

- dev-test/githunt/types.avoidOptionals.ts
- dev-test/githunt/types.d.ts
- dev-test/githunt/types.immutableTypes.ts
- dev-test/githunt/types.noNamespaces.ts
- dev-test/githunt/types.reactApollo.noNamespaces.tsx
- dev-test/githunt/types.reactApollo.tsx
- dev-test/githunt/types.ts
- dev-test/star-wars/types.avoidOptionals.ts
- dev-test/star-wars/types.d.ts
- dev-test/star-wars/types.immutableTypes.ts
- dev-test/star-wars/types.noNamespaces.ts
- dev-test/star-wars/types.skipSchema.ts
- dev-test/star-wars/types.ts
- dev-test/test-message/types.reactApollo.noNamespaces.tsx
- dev-test/test-schema/resolvers-root.ts
- dev-test/test-schema/resolvers-types.ts
- dev-test/test-schema/typings.ts
- packages/plugins/typescript-common/src/enum.handlebars
- packages/plugins/typescript-common/tests/typescript-common.spec.ts
- yarn.lock
> Convert enums with the specified case algorithm

- packages/graphql-codegen-cli/package.json
- packages/graphql-codegen-cli/tests/codegen.spec.ts
- packages/plugins/typescript-apollo-angular/tests/apollo-angular.spec.ts
- yarn.lock
>  Should be able to use root schema object (in apollo-angular)

- packages/graphql-codegen-cli/package.json
- packages/graphql-codegen-cli/src/execute-plugin.ts
- packages/graphql-codegen-cli/tests/codegen.spec.ts
> Load local plugins correctly, absolute to process.cwd()

- packages/plugins/typescript-client/src/helpers.ts
- packages/plugins/typescript-client/src/index.ts
- packages/plugins/typescript-client/src/selection-set.handlebars
- packages/plugins/typescript-client/tests/typescript-client.spec.ts
- yarn.lock
> Fix field naming in typescript-client

- packages/plugins/typescript-resolvers/src/directive.handlebars
- packages/plugins/typescript-resolvers/src/helpers.ts
- packages/plugins/typescript-resolvers/src/index.ts
- packages/plugins/typescript-resolvers/src/mappers.ts
- packages/plugins/typescript-resolvers/src/parent-type.ts
- packages/plugins/typescript-resolvers/src/resolve-type.handlebars
- packages/plugins/typescript-resolvers/src/root.handlebars
- packages/plugins/typescript-resolvers/src/scalar.handlebars
- packages/plugins/typescript-resolvers/tests/typescript-resolvers.spec.ts
- yarn.lock
> Resolvers for unions, interfaces and directives

- packages/graphql-codegen-cli/src/config.ts
- packages/graphql-codegen-cli/tests/schema-from-typedefs.spec.ts
- yarn.lock
@dotansimha Maybe even in `v0.14.3` 👀 ?
> Load and Parse JS config

- packages/graphql-codegen-cli/src/codegen.ts
- packages/graphql-codegen-cli/src/execute-plugin.ts
- packages/graphql-codegen-cli/tests/codegen.spec.ts
- packages/graphql-codegen-cli/tests/custom-plugins/checks-extended-schema.js
> Add plugin's addition to the schema before executing plugins

- packages/plugins/add/src/index.ts
- packages/plugins/time/src/index.ts
> Use '\n' as a new line

- dev-test/test-schema/schema.graphql
- packages/utils/plugins-handlebars-helpers/src/index.ts
> Fix multiline comments

- packages/plugins/typescript-client/src/helpers.ts
- packages/plugins/typescript-client/tests/typescript-client.spec.ts
> Should preserve a prefix on Unions

- README.md
> Fix typo GraphlQL

- packages/plugins/typescript-resolvers/src/helpers.ts
- packages/plugins/typescript-resolvers/src/index.ts
- packages/plugins/typescript-resolvers/src/root.handlebars
- packages/plugins/typescript-resolvers/tests/typescript-resolvers.spec.ts
> Import GraphQL types for scalars only if schema has scalars

- packages/plugins/typescript-common/src/helpers.ts
- packages/plugins/typescript-common/src/index.ts
- packages/plugins/typescript-common/tests/typescript-common.spec.ts
#1018 was a sub PR of #1017, to the `maybe` branch
Related #1012
> Custom Maybe

- packages/plugins/typescript-resolvers/src/root.handlebars
- packages/plugins/typescript-resolvers/tests/typescript-resolvers.spec.ts
> Fix IResolvers with noNamespaces

- packages/graphql-codegen-cli/src/loaders/schema/schema-from-typedefs.ts
- packages/graphql-codegen-cli/tests/schema-from-typedefs.spec.ts
- packages/graphql-codegen-cli/tests/test-files/schema-dir/schema.ts
> Load typeDefs wrapped with graphql-tag

- packages/graphql-codegen-core/src/operations/build-selection-set.ts
- packages/graphql-codegen-core/src/types.ts
- packages/plugins/typescript-client/src/root.handlebars
- packages/plugins/typescript-client/tests/typescript-client.spec.ts
- packages/utils/plugins-helpers/src/flatten-types.ts
> Non optional __typename field when requested

- packages/plugins/flow/src/visitor.ts
- packages/plugins/flow/tests/flow.spec.ts
> [Flow] Add empty DirectiveDefinition handler

- packages/plugins/flow/src/variables-to-object.ts
- packages/plugins/flow/tests/flow.spec.ts
> [Flow] Fix optional sign for args with default values

- packages/plugins/flow-resolvers/src/visitor.ts
- packages/plugins/flow-resolvers/tests/flow-resolvers.spec.ts
> [Flow Resolvers] Add typesPrefix to function args

- dev-test/githunt/flow.flow.js
- dev-test/test-mongodb/types.ts
- dev-test/test-schema/flow-types.flow.js
- dev-test/test-schema/resolvers-root.ts
- dev-test/test-schema/resolvers-types.ts
- dev-test/test-schema/typings.ts
- packages/plugins/typescript-resolvers/src/root.handlebars
- packages/plugins/typescript-resolvers/tests/typescript-resolvers.spec.ts
- yarn.lock
Related to https://github.com/Urigo/graphql-modules/issues/182#issuecomment-451788118
> Pass context generic to IResolvers

- docs/getting-started/schema-field.md
> Fix custom schema loader example in docs

- packages/graphql-codegen-cli/src/init.ts
Should be "graphql-codegen-typescript-graphql-files-modules"
> Init has an incorrent package name

- packages/graphql-codegen-cli/src/utils/document-finder.ts
> Add borken document to error report

- packages/graphql-codegen-cli/src/codegen.ts
- packages/graphql-codegen-cli/src/loaders/documents/documents-from-glob.ts
- packages/graphql-codegen-cli/src/loaders/documents/validate-documents.ts
- packages/graphql-codegen-cli/src/loaders/schema/introspection-from-url.ts
- packages/graphql-codegen-cli/src/loaders/schema/schema-from-typedefs.ts
- packages/graphql-codegen-cli/src/utils/listr-renderer.ts
- packages/graphql-codegen-cli/src/utils/watcher.ts
- packages/graphql-codegen-cli/src/yml.ts
- packages/graphql-codegen-core/src/debugging.ts
- packages/graphql-codegen-core/src/index.ts
> Format and align errors

- packages/plugins/typescript-react-apollo/src/index.ts
> Do not enforce tsx if only hooks used

- packages/plugins/typescript-client/src/helpers.ts
- packages/plugins/typescript-client/tests/typescript-client.spec.ts
> Apply interfacePrefix to enums in typescript-client

- packages/graphql-codegen-cli/src/generate-and-save.ts
- packages/graphql-codegen-cli/src/utils/file-system.ts
- packages/graphql-codegen-cli/tests/generate-and-save.spec.ts
- packages/graphql-codegen-core/src/yml-config-types.ts
> Allow to specify overwrite option for a specific output

- packages/graphql-codegen-cli/src/merge-schemas.ts
Waiting for `graphql-toolkit` version `0.1.1` to be released
> Migrate changes with graphql-toolkit@0.1.1 (WIP)

- packages/graphql-codegen-core/src/schema/resolve-arguments.ts
- packages/graphql-codegen-core/src/schema/transform-fields.ts
- packages/graphql-codegen-core/src/types.ts
- packages/graphql-codegen-core/tests/transform-arguments.spec.ts
- packages/plugins/flow/src/variables-to-object.ts
> Add Default Value to Plugin Context

- packages/graphql-codegen-cli/src/yml.ts
- packages/graphql-codegen-cli/tests/cli-flags.spec.ts
> Support env variables in yml

- packages/graphql-codegen-cli/src/utils/watcher.ts
- packages/graphql-codegen-core/src/yml-config-types.ts
> Allow to pass glob or list of files to watch

- packages/graphql-codegen-cli/package.json
- packages/graphql-codegen-cli/src/load.ts
- packages/graphql-codegen-cli/tests/codegen.spec.ts
- packages/graphql-codegen-cli/tests/test-documents/gatsby-and-custom-parsers.ts
- packages/graphql-codegen-cli/tests/test-files/schema-dir/gatsby-and-custom-parsers/custom.ts
- packages/graphql-codegen-cli/tests/test-files/schema-dir/gatsby-and-custom-parsers/gatsby.ts
- packages/graphql-codegen-cli/tests/test-files/schema-dir/gatsby-and-custom-parsers/graphql-tag.ts
- packages/graphql-codegen-core/package.json
- packages/graphql-codegen-core/src/yml-config-types.ts
- yarn.lock
> Allow to customize graphql-tag-pluck settings

- packages/graphql-codegen-core/src/schema/schema-to-template-context.ts
- packages/plugins/typescript-apollo-angular/src/index.ts
- packages/plugins/typescript-client/src/index.ts
- packages/plugins/typescript-common/src/index.ts
- packages/plugins/typescript-common/tests/typescript-common.spec.ts
- packages/plugins/typescript-mongodb/src/index.ts
- packages/plugins/typescript-react-apollo/src/index.ts
- packages/plugins/typescript-resolvers/src/index.ts
- packages/plugins/typescript-server/src/index.ts
- packages/plugins/typescript-stencil-apollo/src/index.ts
> Include used introspection types in typescript-common based on documents

- packages/plugins/flow/tests/flow.spec.ts
> Apply fix to Flow plugins: #1413
The fix was already there, I just applied the test.
> Make sure bug with useFlowReadOnlyTypes on Enums is fixed #1413

- website/live-demo/package.json
- website/live-demo/src/App.css
- website/live-demo/src/App.js
- website/live-demo/src/examples.js
It takes around 1.53s to load.
> Remove prettier and use graphql-codegen-core directly

- dev-test/githunt/types.reactApollo.hooks.tsx
- dev-test/githunt/types.reactApollo.tsx
- dev-test/githunt/types.stencilApollo.class.tsx
- dev-test/githunt/types.stencilApollo.tsx
- packages/graphql-codegen-cli/src/utils/listr-renderer.ts
- packages/graphql-codegen-cli/src/utils/watcher.ts
Related to https://github.com/dotansimha/graphql-code-generator/issues/1350#issuecomment-473040953
> Fix isGlob import

- packages/plugins/flow-resolvers/src/index.ts
- packages/plugins/typescript-resolvers/src/index.ts
- packages/plugins/typescript-resolvers/src/visitor.ts
- packages/plugins/typescript-resolvers/tests/ts-resolvers.spec.ts
- packages/plugins/visitor-plugin-common/src/base-resolvers-visitor.ts
```graphql
type Query {
foo: [User]
bar: [User!]
baz: [User!]!
}
```
Should give:
```ts
Maybe<ArrayOrIterable<Maybe<User>>>  // in foo
Maybe<ArrayOrIterable<User>>         // in bar
ArrayOrIterable<User>                // in baz
```
> Support Iterable in ListNode

- docs/plugins/typescript-apollo-angular.md
- packages/plugins/typescript-apollo-angular/src/index.ts
- packages/plugins/typescript-apollo-angular/src/visitor.ts
- packages/plugins/typescript-apollo-angular/tests/apollo-angular.spec.ts
> Global config for ngModule and namedClient

- packages/plugins/typescript-resolvers/src/index.ts
If someone wants to have easier testing then use a wrapper type that turn all arguments to optional as we do it in our projects
> No more optional arguments

- packages/graphql-codegen-cli/src/init/helpers.ts
- packages/graphql-codegen-cli/tests/init.spec.ts
We moved files one level deeper
> Fix a path to cli's package.json

- packages/plugins/flow/src/index.ts
- packages/plugins/flow/src/visitor.ts
- packages/plugins/flow/tests/flow.spec.ts
- packages/plugins/typescript/src/index.ts
- packages/plugins/typescript/src/visitor.ts
- packages/plugins/typescript/tests/typescript.spec.ts
- packages/plugins/visitor-plugin-common/src/base-types-visitor.ts
- packages/plugins/visitor-plugin-common/src/mappers.ts
- packages/plugins/visitor-plugin-common/src/types.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/1495
> Fixes for `enumValues` configuration

- packages/plugins/typescript-resolvers/tests/ts-resolvers.spec.ts
- packages/plugins/visitor-plugin-common/src/base-resolvers-visitor.ts
It causes `unused generic` error
> Do not create directive resolvers interface if there is no directive defined in the schema

- packages/plugins/flow/src/visitor.ts
- packages/plugins/flow/tests/flow.spec.ts
- packages/plugins/typescript-operations/tests/ts-documents.spec.ts
- packages/plugins/typescript/src/visitor.ts
- packages/plugins/typescript/tests/typescript.spec.ts
- packages/plugins/visitor-plugin-common/src/base-types-visitor.ts
- packages/plugins/visitor-plugin-common/src/base-visitor.ts
- packages/plugins/visitor-plugin-common/src/utils.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/1508
> Fix for missing descriptions

- packages/plugins/flow-resolvers/src/visitor.ts
- packages/plugins/flow-resolvers/tests/flow-resolvers.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/1404
> Fix for flow-resolvers scalar config

- packages/plugins/typescript-operations/tests/ts-documents.spec.ts
Hi @dotansimha !
I've created a failing test case for a possible bug when selecting fields of a union of types sharing common interface. This behavior is expected and supported by `apollo` so I think it's a valid bug.
Thank you for the library!
> Add test case for typescript union

- packages/plugins/typescript-resolvers/package.json
- packages/plugins/typescript-resolvers/tests/ts-resolvers.spec.ts
- yarn.lock
> Add tests for #1453

- dev-test/star-wars/types.avoidOptionals.ts
- dev-test/star-wars/types.d.ts
- dev-test/star-wars/types.immutableTypes.ts
- dev-test/star-wars/types.skipSchema.ts
- dev-test/star-wars/types.ts
- packages/plugins/typescript/tests/typescript.spec.ts
- packages/plugins/visitor-plugin-common/src/base-types-visitor.ts
- packages/plugins/visitor-plugin-common/src/utils.ts
> Fix missing type for method's arguments in interface

- packages/plugins/typescript-operations/src/ts-operation-variables-to-object.ts
- packages/plugins/typescript-operations/src/visitor.ts
- packages/plugins/typescript-operations/tests/ts-documents.spec.ts
- packages/plugins/visitor-plugin-common/src/variables-to-object.ts
>  Arguments should be optional when there's a default value

- packages/plugins/typescript-resolvers/src/index.ts
- packages/plugins/typescript-resolvers/tests/ts-resolvers.spec.ts
- packages/utils/config-md-generator/src/index.ts
> noSchemaStitching + warning in md config

- packages/plugins/flow/src/visitor.ts
- packages/plugins/flow/tests/flow.spec.ts
- packages/plugins/typescript-operations/tests/ts-documents.spec.ts
- packages/plugins/typescript-stencil-apollo/package.json
- packages/plugins/typescript/tests/typescript.spec.ts
- packages/plugins/visitor-plugin-common/package.json
- packages/plugins/visitor-plugin-common/src/base-types-visitor.ts
- packages/plugins/visitor-plugin-common/src/naming.ts
- packages/plugins/visitor-plugin-common/src/types.ts
- packages/plugins/visitor-plugin-common/src/utils.ts
- packages/plugins/visitor-plugin-common/tests/plugins-common.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/1569
> Fix for enum values and underscore

- packages/plugins/typescript-operations/tests/ts-documents.spec.ts
- packages/plugins/visitor-plugin-common/src/selection-set-to-object.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/1577
> Fix for fragments on type implementing multiple interfaces

- packages/plugins/typescript-operations/tests/ts-documents.spec.ts
- packages/plugins/visitor-plugin-common/src/base-documents-visitor.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/1581
> Fixes for issues with scalars

- packages/plugins/typescript/tests/typescript.spec.ts
- packages/plugins/visitor-plugin-common/src/base-types-visitor.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/1592
> Fix for type implementing interface without adding new fields

- packages/plugins/typescript-operations/tests/ts-documents.spec.ts
- packages/plugins/visitor-plugin-common/src/selection-set-to-object.ts
Fixes #1624.
I know the fix is not ideal but the test-case might be helpful for anyone that has a better fix.
> Should work with fragment on union type

- packages/plugins/flow-resolvers/src/visitor.ts
- packages/plugins/flow/src/visitor.ts
- packages/plugins/flow/tests/flow.spec.ts
- packages/plugins/typescript-react-apollo/tests/react-apollo.spec.ts
- packages/plugins/typescript/tests/typescript.spec.ts
- packages/plugins/visitor-plugin-common/package.json
- packages/plugins/visitor-plugin-common/src/client-side-base-visitor.ts
- packages/plugins/visitor-plugin-common/src/naming.ts
- packages/plugins/visitor-plugin-common/src/utils.ts
> WIP: Several Fixes

- packages/plugins/typescript-react-apollo/src/index.ts
- packages/plugins/typescript-react-apollo/src/visitor.ts
- packages/plugins/typescript-react-apollo/tests/react-apollo.spec.ts
> Make react-apollo is configurable with option `reactApolloImportFrom`

- packages/plugins/typescript-react-apollo/src/visitor.ts
- packages/plugins/typescript-react-apollo/tests/react-apollo.spec.ts
> Make variables prop required if any of argument is non-null

- packages/plugins/typescript-compatibility/src/visitor.ts
- packages/plugins/typescript-compatibility/tests/compatibility.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/1686
> Added fragments support for TypeScript Compatibility plugin

- packages/plugins/typescript/src/index.ts
- packages/plugins/typescript/tests/typescript.spec.ts
> Expose Maybe type

- packages/graphql-codegen-cli/src/config.ts
> Add --silent cli flag

- packages/plugins/typescript-compatibility/src/selection-set-to-types.ts
- packages/plugins/typescript-compatibility/tests/compatibility.spec.ts
This is meant to address https://github.com/dotansimha/graphql-code-generator/issues/1678#issuecomment-482420680 .
> Handle another TS strict mode case

- .circleci/config.yml
- .gitignore
- jest.config.js
- package.json
- packages/graphql-codegen-cli/package.json
- packages/graphql-codegen-core/package.json
- packages/plugins/flow/flow/package.json
- packages/plugins/flow/operations/package.json
- packages/plugins/flow/resolvers/package.json
- packages/plugins/java/java/package.json
- packages/plugins/java/resolvers/package.json
- packages/plugins/other/fragment-matcher/package.json
- packages/plugins/other/introspection/package.json
- packages/plugins/other/schema-ast/package.json
- packages/plugins/other/visitor-plugin-common/package.json
- packages/plugins/typescript/apollo-angular/package.json
- packages/plugins/typescript/compatibility/package.json
- packages/plugins/typescript/graphql-files-modules/package.json
- packages/plugins/typescript/mongodb/package.json
- packages/plugins/typescript/operations/package.json
- packages/plugins/typescript/react-apollo/package.json
- packages/plugins/typescript/resolvers/package.json
- packages/plugins/typescript/stencil-apollo/package.json
- packages/plugins/typescript/typescript/package.json
- yarn.lock
This PR [captures test results](https://circleci.com/docs/2.0/collect-test-data/) and publishes them to Circle. ([example build](https://circleci.com/gh/jrr/graphql-code-generator/11)).
> CI test result reporting

- packages/plugins/typescript/react-apollo/src/index.ts
- packages/plugins/typescript/react-apollo/src/visitor.ts
- packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
- packages/plugins/typescript/stencil-apollo/src/visitor.ts
> Add withMutationFn

- packages/plugins/typescript/react-apollo/src/visitor.ts
- packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
> Check if operationType is Query before making variables prop required

- packages/plugins/typescript/react-apollo/src/visitor.ts
- packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
> Set HOC alias

- packages/plugins/flow/resolvers/tests/__snapshots__/flow-resolvers.spec.ts.snap
- packages/plugins/flow/resolvers/tests/mapping.spec.ts
- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
- packages/plugins/typescript/resolvers/tests/mapping.spec.ts
- packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/1758
> Added support for ts-resolvers mappers with unions

- packages/plugins/typescript/compatibility/src/selection-set-to-types.ts
- packages/plugins/typescript/compatibility/tests/compatibility.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/1686
> Fixes for inline fragments in TypeScript compatibility plugin

- packages/plugins/other/visitor-plugin-common/src/base-visitor.ts
> [typo] Update base-visitor.ts

- .circleci/config.yml
- docs/generated-config/base-visitor.md
- docs/generated-config/typescript-react-apollo.md
- docs/generated-config/typescript-urql.md
- docs/plugins/typescript-urql.md
- website/generate-config.js
- website/i18n/en.json
- website/live-demo/package.json
- website/live-demo/src/App.js
- website/live-demo/src/examples.js
- website/live-demo/webpack.config.extend.js
- website/live-demo/webpackDevServer.config.extend.js
- website/sidebars.json
- website/yarn.lock
- yarn.lock
update lockfile
cleanup for live-demo
added urql example
update docs
> Fixes to support node 12

- packages/plugins/typescript/react-apollo/src/visitor.ts
> Import necessary imports only if they're used

- packages/plugins/typescript/react-apollo/src/visitor.ts
- packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
> Export react-apollo component props

- dev-test/githunt/types.reactApollo.hooks.tsx
- dev-test/githunt/types.reactApollo.tsx
- packages/plugins/typescript/react-apollo/src/visitor.ts
- packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
Related to https://github.com/dotansimha/graphql-code-generator/issues/1897
> Make variables optional if skip is provided

- docs/getting-started/further-reading.md
- website/sidebars.json
> Add "Further Reading" section to documentation.

- docs/generated-config/base-types-visitor.md
- packages/plugins/flow/flow/tests/flow.spec.ts
- packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts
- packages/plugins/other/visitor-plugin-common/src/declaration-kinds.ts
- packages/plugins/other/visitor-plugin-common/src/types.ts
- packages/plugins/typescript/typescript/tests/typescript.spec.ts
~Currently work in progress. Happy to get feedback on the approach.~
Ready for review.
Related #1852
> Interface Option

- packages/graphql-codegen-cli/src/init/helpers.ts
- packages/graphql-codegen-cli/src/init/questions.ts
- packages/graphql-codegen-cli/tests/init.spec.ts
- added missing introspection package
- fixes default documents path
> Fixes for `init` command

- packages/plugins/flow/resolvers/src/visitor.ts
- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
- packages/plugins/other/visitor-plugin-common/src/mappers.ts
- packages/plugins/other/visitor-plugin-common/tests/parse-mapper.spec.ts
- packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/1997
> Added support for mapper from default export

- docs/getting-started/codegen-config.md
- docs/getting-started/require-field.md
- packages/graphql-codegen-cli/src/cli.ts
- packages/graphql-codegen-cli/src/config.ts
- packages/graphql-codegen-cli/src/yml.ts
- packages/graphql-codegen-cli/tests/cli-flags.spec.ts
Also, updated the docs regarding environment variables, cli flags, and how to use `-r` flag with `dotenv` (to load environment variables before reading the yml config file)
> Added support for loading env vars before loading the yml file, and added default values

- .gitignore
- packages/plugins/flow/resolvers/tests/__snapshots__/flow-resolvers.spec.ts.snap
- packages/plugins/flow/resolvers/tests/mapping.spec.ts
- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
- packages/plugins/typescript/resolvers/tests/mapping.spec.ts
- packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
- packages/plugins/typescript/typescript/src/index.ts
> Introduce MaybePromise

- dev-test/test/codegen.yml
- dev-test/test/schema.graphql
- dev-test/test/src/ComponentA/document.generated.tsx
- dev-test/test/src/ComponentA/document.graphql
- dev-test/test/src/ComponentB/document.generated.tsx
- dev-test/test/src/ComponentB/document.graphql
- dev-test/test/src/document.generated.tsx
- dev-test/test/src/document.graphql
- dev-test/test/src/gql/__generated__/types.ts
- package.json
- packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts
- packages/plugins/other/visitor-plugin-common/src/types.ts
- packages/presets/near-operation-file/src/index.ts
- packages/presets/near-operation-file/src/utils.ts
> Fixes for near-operation-file preset

- packages/plugins/typescript/document-nodes/src/index.ts
- packages/plugins/typescript/document-nodes/tests/graphql-document-nodes.spec.ts
Hello again.
This is continuation of #2098 and this time new option `noGraphQLTag` is provided.
> typescript-document-nodes: new noGraphQLTag option

- lerna.json
- package.json
- packages/plugins/flow/flow/src/visitor.ts
- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
- packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts
- packages/plugins/other/visitor-plugin-common/src/enum-values.ts
- packages/plugins/other/visitor-plugin-common/src/types.ts
- packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
- packages/plugins/typescript/typescript/src/visitor.ts
- packages/plugins/typescript/typescript/tests/typescript.spec.ts
- website/live-demo/src/generate.ts
> [TypeScript] `enumValues` fixes

- docs/generated-config/schema-ast.md
- docs/plugins/schema-ast.md
- packages/plugins/other/schema-ast/src/index.ts
- packages/plugins/other/schema-ast/tests/schema-ast.spec.ts
- website/generate-config.js
- website/i18n/en.json
> New config option "includeDirectives" in SchemaAST plugin 

- dev-test/codegen.yml
- dev-test/githunt/types.urql.tsx
- package.json
- packages/graphql-codegen-cli/src/init/questions.ts
- packages/plugins/typescript/urql/src/visitor.ts
- packages/plugins/typescript/urql/tests/urql.spec.ts
- yarn.lock
> [urql-typescript] Fix generics for operation props

- packages/plugins/typescript/typescript/package.json
> [typescript] Add graphql 0.12.0^ as peer dependency

- packages/graphql-codegen-core/src/codegen.ts
- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
> Fix for issues with RequireFields & some more 

- packages/plugins/other/visitor-plugin-common/src/enum-values.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/2164
> [TypeScript] Fix for enumValues as string and introspection types

- docs/custom-codegen/index.md
- docs/custom-codegen/write-your-plugin.md
- docs/integrations/apollo-local-state.md
- docs/integrations/gatsby.md
- docs/plugins/typescript-compatibility.md
- docs/plugins/typescript-document-nodes.md
- docs/plugins/typescript-mongodb.md
- docs/plugins/typescript-operations.md
- docs/plugins/typescript-resolvers.md
- docs/presets/near-operation-file.md
This fixes a bunch of typos in the docs.
> Fix typos in docs

- packages/plugins/flow/resolvers/src/index.ts
- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
- packages/plugins/typescript/resolvers/src/index.ts
- packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
related: https://github.com/dotansimha/graphql-code-generator/issues/2236
> [TS-Resolvers] allow to customize ResolverTypeWrapper

- packages/plugins/other/visitor-plugin-common/src/base-documents-visitor.ts
- packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts
- packages/plugins/typescript/operations/tests/ts-documents.spec.ts
- packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
- website/i18n/en.json
Related to: https://github.com/dotansimha/graphql-code-generator/issues/2250
> Introduce `dedupeOperationSuffix` to operations plugin

- packages/plugins/typescript/typescript/src/avoid-optionals.ts
- packages/plugins/typescript/typescript/src/index.ts
- packages/plugins/typescript/typescript/src/types.ts
- packages/plugins/typescript/typescript/src/visitor.ts
- packages/plugins/typescript/typescript/tests/typescript.spec.ts
Relevant to  https://github.com/dotansimha/graphql-code-generator/issues/1885
> Avoid input optionals

- packages/plugins/flow/flow/src/visitor.ts
- packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts
- packages/plugins/other/visitor-plugin-common/src/base-visitor.ts
- packages/plugins/typescript/typescript/src/visitor.ts
- packages/plugins/typescript/typescript/tests/typescript.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/1712
> Added enumPrefix configuration

- dev-test/codegen.yml
- dev-test/star-wars/types.globallyAvailable.d.ts
- packages/plugins/other/visitor-plugin-common/src/utils.ts
- packages/plugins/typescript/operations/src/index.ts
- packages/plugins/typescript/operations/src/visitor.ts
- packages/plugins/typescript/operations/tests/ts-documents.spec.ts
- packages/plugins/typescript/typescript/src/index.ts
- packages/plugins/typescript/typescript/src/visitor.ts
- packages/plugins/typescript/typescript/tests/typescript.spec.ts
related: https://github.com/dotansimha/graphql-code-generator/issues/2165
> [TypeScript] Added support for generating output with no `export`

- docs/getting-started/documents-field.md
- docs/getting-started/schema-field.md
- packages/graphql-codegen-cli/package.json
- packages/graphql-codegen-cli/tests/generate-and-save.spec.ts
- packages/graphql-codegen-core/package.json
- packages/plugins/typescript/mongodb/package.json
- yarn.lock
Related: https://github.com/dotansimha/graphql-code-generator/issues/1698
> Upgrade graphql-toolkit and use globby for easier glob

- packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts
- packages/plugins/typescript/operations/tests/ts-documents.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/2174
> Fix for enums and preResolveTypes

- packages/plugins/typescript/compatibility/src/index.ts
- packages/plugins/typescript/compatibility/src/visitor.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/1876
> Fix issues with reactApollo and compatibility plugin

- packages/plugins/other/visitor-plugin-common/src/base-visitor.ts
- packages/plugins/other/visitor-plugin-common/src/scalars.ts
- packages/plugins/other/visitor-plugin-common/tests/scalars.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/1753
> Fixes for issues with js objects and scalars

- dev-test/star-wars/types.preResolveTypes.ts
- packages/graphql-codegen-cli/src/codegen.ts
- packages/graphql-codegen-cli/src/load.ts
- packages/utils/plugins-helpers/src/types.ts
Related: https://github.com/dotansimha/graphql-code-generator/pull/2283 #1698
> try to fix issues with exclude

- package.json
- packages/plugins/flow/flow/tests/flow.spec.ts
- packages/plugins/other/visitor-plugin-common/src/utils.ts
- packages/plugins/typescript/typescript/tests/typescript.spec.ts
- yarn.lock
> Add newline character at the first line of multiline comments

- dev-test/githunt/flow.flow.js
- dev-test/githunt/types.avoidOptionals.ts
- dev-test/githunt/types.d.ts
- dev-test/githunt/types.enumsAsTypes.ts
- dev-test/githunt/types.immutableTypes.ts
- dev-test/githunt/types.preResolveTypes.compatibility.ts
- dev-test/githunt/types.preResolveTypes.ts
- dev-test/githunt/types.reactApollo.customSuffix.tsx
- dev-test/githunt/types.reactApollo.hooks.tsx
- dev-test/githunt/types.reactApollo.preResolveTypes.tsx
- dev-test/githunt/types.reactApollo.tsx
- dev-test/githunt/types.stencilApollo.tsx
- dev-test/githunt/types.ts
- dev-test/githunt/types.urql.tsx
- packages/plugins/typescript/react-apollo/src/visitor.ts
- packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
> Remove Partial from ReactApollo HOC

- packages/plugins/typescript/react-apollo/src/visitor.ts
- packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
> Generate lazy query hooks on react-apollo plugin

- packages/graphql-codegen-cli/package.json
- packages/graphql-codegen-cli/src/load.ts
- packages/graphql-codegen-core/package.json
- packages/plugins/typescript/mongodb/package.json
- Sort documents by filepath in order to avoid incosistency coming from `globy` (https://github.com/dotansimha/graphql-code-generator/issues/2311)
- Fix issues with swallowed errors (https://github.com/dotansimha/graphql-code-generator/issues/2318)
> Some fixes

- packages/plugins/flow/resolvers/tests/__snapshots__/flow-resolvers.spec.ts.snap
- packages/plugins/flow/resolvers/tests/mapping.spec.ts
- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
- packages/plugins/typescript/resolvers/tests/mapping.spec.ts
- packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
- packages/plugins/typescript/typescript/tests/typescript.spec.ts
> Include NonNull argument as required

- packages/presets/near-operation-file/src/index.ts
Related #2365
See here;
https://codesandbox.io/s/graphql-codegen-issue-template-e7qf7
> [near-operation-file] Deduplicate fragment names

- packages/graphql-codegen-cli/src/load.ts
- packages/graphql-codegen-cli/tests/__mocks__/some-fetch.js
- packages/graphql-codegen-cli/tests/codegen.spec.ts
- packages/utils/plugins-helpers/src/types.ts
> Able to provide custom fetch implementation

- docs/plugins/typescript-resolvers.md
Thanks for merging #2376 and sorry for the typo.
> docs: fix typo

- packages/plugins/flow/operations/src/flow-selection-set-to-object.ts
- packages/plugins/other/visitor-plugin-common/src/base-documents-visitor.ts
- packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts
- packages/plugins/typescript/operations/src/ts-selection-set-to-object.ts
- packages/plugins/typescript/operations/tests/ts-documents.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/2326
> Fix issues with `preResolveTypes` and enums

- packages/plugins/flow/flow/src/visitor.ts
- packages/plugins/other/visitor-plugin-common/src/variables-to-object.ts
- packages/plugins/typescript/typescript/src/typescript-variables-to-object.ts
- packages/plugins/typescript/typescript/src/visitor.ts
- packages/plugins/typescript/typescript/tests/typescript.spec.ts
Related to 
https://github.com/dotansimha/graphql-code-generator/issues/1980#issuecomment-520491443
@dotansimha It doesn't look good for me. Could you review the code?
> Fix enums in args

- packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts
- packages/plugins/typescript/operations/tests/ts-documents.spec.ts
Adds failing test for https://github.com/dotansimha/graphql-code-generator/issues/2407
> test(typescript-operations): do not omit fragment spread nodes (Fix for #2407)

- packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts
- packages/plugins/typescript/operations/tests/ts-documents.spec.ts
> fix(visitor-plugin-common): union/interface types with same selection set field name but different type (#2436)

- packages/plugins/typescript/react-apollo/src/visitor.ts
This change hopefully breaks tests. ;-)
> [fix] hook functions don't need a ; at the end

- dev-test/githunt/types.immutableTypes.ts
- dev-test/githunt/types.reactApollo.customSuffix.tsx
- dev-test/githunt/types.reactApollo.hooks.tsx
- dev-test/githunt/types.reactApollo.preResolveTypes.tsx
- dev-test/githunt/types.reactApollo.tsx
- dev-test/star-wars/types.immutableTypes.ts
- packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts
- packages/plugins/typescript/typescript/tests/typescript.spec.ts
> Fix missing readonly for __typename with immutableTypes

- packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts
- packages/plugins/typescript/operations/tests/ts-documents.spec.ts
- packages/presets/near-operation-file/src/index.ts
- packages/presets/near-operation-file/src/utils.ts
- packages/presets/near-operation-file/tests/is-using-types.spec.ts
- packages/presets/near-operation-file/tests/near-operation-file.spec.ts
- yarn.lock
> `near-operation-file` fixes

- packages/plugins/other/visitor-plugin-common/src/utils.ts
> Fix comments escaping

- packages/presets/near-operation-file/src/index.ts
- packages/presets/near-operation-file/src/utils.ts
- packages/presets/near-operation-file/tests/is-using-types.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/2497
> Try to fix issues with missing import

- packages/presets/near-operation-file/src/utils.ts
- packages/presets/near-operation-file/tests/is-using-types.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/2497
> Try to fix issuse with fragments and types imports

- packages/plugins/flow/flow/tests/flow.spec.ts
- packages/plugins/flow/resolvers/src/flow-util-types.ts
- packages/plugins/flow/resolvers/src/index.ts
- packages/plugins/flow/resolvers/tests/__snapshots__/flow-resolvers.spec.ts.snap
- packages/plugins/flow/resolvers/tests/flow-resolvers.spec.ts
also, added tests for flow plugins
related: https://github.com/dotansimha/graphql-code-generator/issues/2507
> Fixes for flow plugins

- packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts
- packages/plugins/typescript/operations/tests/ts-documents.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/2506
> try to fix issue with inline fragments without typeCondition

- packages/graphql-codegen-core/src/codegen.ts
- packages/graphql-codegen-core/src/execute-plugin.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/2515
> Fix documents validations with near operation file

- packages/graphql-codegen-core/src/execute-plugin.ts
- packages/graphql-codegen-core/tests/execute-plugin.spec.ts
Related https://github.com/dotansimha/graphql-code-generator/issues/2565
> feat(core): add option for disabling document validation

- packages/plugins/flow/resolvers/src/index.ts
- packages/plugins/flow/resolvers/tests/__snapshots__/flow-resolvers.spec.ts.snap
- packages/plugins/flow/resolvers/tests/flow-resolvers.spec.ts
- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
- packages/plugins/typescript/resolvers/src/index.ts
- packages/plugins/typescript/resolvers/tests/federation.spec.ts
> fix: unused GraphQLScalarTypeConfig in resolvers (federation)

- packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/2548
> Try to fix issues with extensions

- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
Related https://github.com/dotansimha/graphql-code-generator/issues/2556.
> Fix `getTypeToUse` within parent resolvers type

- packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts
- packages/plugins/typescript/apollo-angular/src/index.ts
- packages/plugins/typescript/apollo-angular/src/visitor.ts
- packages/plugins/typescript/document-nodes/src/index.ts
- packages/plugins/typescript/document-nodes/src/visitor.ts
- packages/plugins/typescript/react-apollo/src/index.ts
- packages/plugins/typescript/react-apollo/src/visitor.ts
- packages/plugins/typescript/stencil-apollo/src/index.ts
- packages/plugins/typescript/stencil-apollo/src/visitor.ts
- packages/plugins/typescript/typescript/tests/typescript.spec.ts
- packages/plugins/typescript/urql/src/index.ts
- packages/plugins/typescript/urql/src/visitor.ts
- packages/presets/near-operation-file/src/index.ts
Related: https://github.com/dotansimha/graphql-code-generator/pull/2418
> Fix scalars and missing schema

- dev-test/codegen.yml
- dev-test/test-schema/resolvers-federation.ts
- packages/graphql-codegen-core/src/codegen.ts
- packages/graphql-codegen-core/src/execute-plugin.ts
@dotansimha should we care about plugin's config? Otherwise I could remove those lines https://github.com/dotansimha/graphql-code-generator/pull/2591/files#diff-001d4eb7df07b3b30562eaba70d2f29aR182-R194
> Prepare for federation on top of plugins

- packages/plugins/flow/flow/src/index.ts
- packages/plugins/flow/flow/src/visitor.ts
- packages/plugins/flow/flow/tests/__snapshots__/flow.spec.ts.snap
- packages/plugins/flow/flow/tests/flow.spec.ts
- packages/plugins/flow/operations/src/index.ts
- packages/plugins/flow/operations/src/visitor.ts
- packages/plugins/flow/operations/tests/__snapshots__/flow-documents.spec.ts.snap
- packages/plugins/flow/operations/tests/flow-documents.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/1844
> Set exact as default in flow types

- packages/plugins/flow/resolvers/src/index.ts
- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
- packages/plugins/typescript/resolvers/src/index.ts
- packages/plugins/typescript/resolvers/tests/federation.spec.ts
- packages/utils/plugins-helpers/src/federation.ts
> Adjust resolver type of __resolveReference field (federation)

- packages/plugins/flow/operations/src/visitor.ts
- packages/plugins/typescript/operations/src/visitor.ts
- packages/plugins/typescript/operations/tests/ts-documents.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/2621
> fix for enumPrefix and enums in variables

- packages/plugins/flow/operations/src/flow-selection-set-processor.ts
- packages/plugins/flow/operations/tests/flow-documents.spec.ts
> fix(flow-operations): Handle namespaced types import

- packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts
- packages/plugins/typescript/operations/tests/ts-documents.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/2683
> fix for __typename on unions

- packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts
- packages/plugins/typescript/operations/package.json
- packages/plugins/typescript/operations/tests/__snapshots__/ts-documents.spec.ts.snap
- packages/plugins/typescript/operations/tests/ts-documents.spec.ts
- website/i18n/en.json
Related: https://github.com/dotansimha/graphql-code-generator/issues/2699
> Fix issues with missing fields when using interfaces

- docs/generated-config/base-visitor.md
- packages/plugins/other/visitor-plugin-common/src/base-visitor.ts
- packages/plugins/other/visitor-plugin-common/src/naming.ts
- packages/plugins/other/visitor-plugin-common/tests/plugins-common.spec.ts
- packages/plugins/typescript/operations/package.json
- packages/plugins/typescript/operations/tests/ts-documents.spec.ts
- packages/plugins/typescript/react-apollo/src/visitor.ts
- packages/plugins/typescript/react-apollo/tests/__snapshots__/react-apollo.spec.ts.snap
- packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
- packages/utils/graphql-codegen-testing/package.json
- packages/utils/graphql-codegen-testing/src/typescript.ts
- packages/utils/graphql-codegen-testing/src/typings.d.ts
- packages/utils/graphql-codegen-testing/tsconfig.json
Related:
- https://github.com/dotansimha/graphql-code-generator/pull/2685 
- https://github.com/dotansimha/graphql-code-generator/pull/2725
> Fixes for transformUnderscore

- packages/presets/near-operation-file/src/index.ts
Related https://github.com/dotansimha/graphql-code-generator/issues/2515
> Fixes for documents validation with presets

- dev-test/generate-all.sh
- dev-test/generate-watch.sh
- packages/graphql-codegen-cli/src/config.ts
Related https://github.com/dotansimha/graphql-code-generator/issues/2722
> Fix issues with dotenv

- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
- packages/plugins/typescript/resolvers/tests/common.ts
- packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
- packages/plugins/typescript/typescript/tests/typescript.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/2679
> Fix issues with `enumPrefix`

- packages/plugins/typescript/resolvers/src/index.ts
- packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
> Support custom ResolveInfo

- docs/custom-codegen/write-your-plugin.md
There were some broken links, pointing to the correct location now
> Fix broken links from graphql-js

- packages/plugins/other/visitor-plugin-common/src/base-visitor.ts
- packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts
- packages/plugins/typescript/document-nodes/src/index.ts
- packages/plugins/typescript/document-nodes/src/visitor.ts
- packages/plugins/typescript/document-nodes/tests/graphql-document-nodes.spec.ts
- packages/plugins/typescript/react-apollo/src/visitor.ts
- packages/plugins/typescript/react-apollo/tests/__snapshots__/react-apollo.spec.ts.snap
- packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
Related:
https://github.com/dotansimha/graphql-code-generator/issues/2742
https://github.com/dotansimha/graphql-code-generator/issues/2826
> Fix issues with react-apollo and prefixes

- packages/plugins/other/visitor-plugin-common/src/mappers.ts
- packages/plugins/other/visitor-plugin-common/tests/parse-mapper.spec.ts
> Support aliases in mappers

- dev-test/codegen.yml
- dev-test/githunt/__generated__/comment-added.subscription.stencil-component.tsx
- dev-test/githunt/__generated__/comment.query.stencil-component.tsx
- dev-test/githunt/__generated__/current-user.query.stencil-component.tsx
- dev-test/githunt/__generated__/feed.query.stencil-component.tsx
- dev-test/githunt/__generated__/new-entry.mutation.stencil-component.tsx
- dev-test/githunt/__generated__/submit-comment.mutation.stencil-component.tsx
- dev-test/githunt/__generated__/vote.mutation.stencil-component.tsx
- dev-test/githunt/types.preResolveTypes.compatibility.ts
- dev-test/test-message/documents.ts
- dev-test/test-message/types.tsx
> Reproduction #2573

- packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts
- packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
> Respect escaping in generated Document

- packages/plugins/typescript/react-apollo/src/visitor.ts
- packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
> Fix React Apollo HOC signature

- packages/plugins/typescript/urql/src/visitor.ts
> Update urql visitor to support handler function

- packages/plugins/flow/flow/src/visitor.ts
- packages/plugins/flow/flow/tests/__snapshots__/flow.spec.ts.snap
- packages/plugins/flow/flow/tests/flow.spec.ts
Related: 
https://github.com/dotansimha/graphql-code-generator/pull/2795 
https://github.com/dotansimha/graphql-code-generator/issues/2772
> Fix for flow issues with exact

- packages/plugins/typescript/graphql-files-modules/src/index.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/2973
> Fixed for typescript-files-modules plugin

- packages/plugins/other/visitor-plugin-common/src/variables-to-object.ts
- packages/plugins/typescript/operations/src/visitor.ts
- packages/plugins/typescript/resolvers/src/visitor.ts
- packages/plugins/typescript/type-graphql/src/config.ts
- packages/plugins/typescript/type-graphql/src/index.ts
- packages/plugins/typescript/type-graphql/src/visitor.ts
- packages/plugins/typescript/typescript/src/config.ts
- packages/plugins/typescript/typescript/src/index.ts
- packages/plugins/typescript/typescript/src/introspection-visitor.ts
- packages/plugins/typescript/typescript/src/typescript-variables-to-object.ts
- packages/plugins/typescript/typescript/src/visitor.ts
- packages/plugins/typescript/typescript/tests/typescript.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/2976
> fix for enum values and prefix

- packages/plugins/other/visitor-plugin-common/src/selection-set-processor/pre-resolve-types.ts
- packages/plugins/typescript/operations/tests/__snapshots__/ts-documents.spec.ts.snap
- packages/plugins/typescript/operations/tests/ts-documents.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/2916
> fix enums, preResolveTypes and presets issues

- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
- packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
This PR implements `fieldContextTypes` to allow using custom context types for specific fields. https://github.com/dotansimha/graphql-code-generator/issues/3052
Usage:
```yml
generates:
./src/graphql/resolvers/types.generated.ts:
plugins:
- typescript
- typescript-resolvers
config:
fieldContextTypes:
- Query.messages#./my-file#ExternalContextType
- Message.id#CustomContextType
```
>  [typescript-resolvers] Implement custom field level contextType

- packages/plugins/typescript/apollo-angular/tests/apollo-angular.spec.ts
- packages/plugins/typescript/urql/src/visitor.ts
- packages/plugins/typescript/urql/tests/urql.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/3062
> Fix urql subscription hooks

- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
- packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts
- packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/3094
> [typescript-resolvers] Allow optional __resolveType

- packages/plugins/java/kotlin/src/visitor.ts
- packages/plugins/java/kotlin/tests/kotlin.spec.ts
Thanks for this great tool.
In data class in Kotlin, usually constructors are not needed. 
Therefore in this PR I removed constructors from generated code.
I guess nothing will affect and it will be more Kotlin like code.
If I was missing something please tell me.
Refs
https://kotlinlang.org/docs/reference/data-classes.html
> [kotlin] remove constructor method from generated code

- packages/graphql-codegen-core/src/codegen.ts
- packages/plugins/other/fragment-matcher/tests/plugin.spec.ts
> Respect existing federation directives

- packages/plugins/flow/flow/src/visitor.ts
- packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts
- packages/plugins/other/visitor-plugin-common/src/types.ts
- packages/plugins/other/visitor-plugin-common/src/utils.ts
- packages/plugins/typescript/typescript/src/visitor.ts
- packages/plugins/typescript/typescript/tests/typescript.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/3137
> Fix for enumsValues and explicit numeric value

- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
- packages/plugins/typescript/resolvers/src/index.ts
- packages/plugins/typescript/resolvers/src/visitor.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/3081
> Fix immutable types in ts resolvers

- packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts
- packages/plugins/other/visitor-plugin-common/src/enum-values.ts
- packages/plugins/other/visitor-plugin-common/src/mappers.ts
- packages/plugins/typescript/typescript/tests/typescript.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/3180
> Fix named default import in mappers

- packages/plugins/typescript/mongodb/src/index.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/3117
> Allow tsx extension in ts-mongo plugin

- packages/utils/plugins-helpers/src/helpers.ts
- packages/utils/plugins-helpers/tests/is-using-types.spec.ts
Related:
- https://github.com/dotansimha/graphql-code-generator/issues/3235 
- https://github.com/dotansimha/graphql-code-generator/issues/3217
> Fix issues with isUsingTypes and complex selection set

- packages/plugins/typescript/apollo-angular/src/index.ts
- packages/plugins/typescript/apollo-angular/src/visitor.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/3250
> fix unused imports in apollo-angular plugin

- packages/utils/plugins-helpers/src/helpers.ts
- packages/utils/plugins-helpers/tests/is-using-types.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/3248
> Fix isUsingTypes implementation in near-operation-file preset

- packages/plugins/flow/resolvers/tests/__snapshots__/flow-resolvers.spec.ts.snap
- packages/plugins/flow/resolvers/tests/mapping.spec.ts
- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
- packages/plugins/typescript/resolvers/tests/mapping.spec.ts
- packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/3264
> fixes for directive resolvers signature

- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
- packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/3257
> Fix duplicate imports when using mappers and enumValues together

- dev-test/test-schema/flow-types.flow.js
- dev-test/test-schema/resolvers-federation.ts
- dev-test/test-schema/resolvers-root.ts
- dev-test/test-schema/resolvers-types.ts
- dev-test/test-schema/typings.ts
- packages/plugins/flow/resolvers/src/index.ts
- packages/plugins/flow/resolvers/tests/__snapshots__/flow-resolvers.spec.ts.snap
- packages/plugins/flow/resolvers/tests/mapping.spec.ts
- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
- packages/plugins/typescript/resolvers/src/index.ts
- packages/plugins/typescript/resolvers/tests/federation.spec.ts
- packages/plugins/typescript/resolvers/tests/mapping.spec.ts
- packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/3254
> Added resolver signature for isTypeOf

- packages/plugins/flow/resolvers/src/index.ts
- packages/plugins/flow/resolvers/tests/__snapshots__/flow-resolvers.spec.ts.snap
- packages/plugins/flow/resolvers/tests/mapping.spec.ts
- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
- packages/plugins/typescript/resolvers/src/index.ts
- packages/plugins/typescript/resolvers/tests/federation.spec.ts
- packages/plugins/typescript/resolvers/tests/mapping.spec.ts
- packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
Related https://github.com/dotansimha/graphql-code-generator/issues/3418
> Generate type for directive args

- packages/presets/near-operation-file/src/fragment-resolver.ts
- packages/presets/near-operation-file/src/index.ts
- packages/presets/near-operation-file/tests/near-operation-file.spec.ts
Related https://github.com/dotansimha/graphql-code-generator/issues/3259
> Fix missing FragmentDoc import

- dev-test/codegen.yml
- dev-test/githunt/types.apolloAngular.sdk.ts
- dev-test/githunt/types.apolloAngular.ts
- packages/plugins/typescript/apollo-angular/src/visitor.ts
- packages/plugins/typescript/apollo-angular/tests/apollo-angular.spec.ts
> fix(apollo-angular): nested import 'apollo-angular/types'

- dev-test/codegen.yml
- dev-test/star-wars/types.refetchFn.tsx
- docs/generated-config/typescript-react-apollo.md
- packages/plugins/typescript/react-apollo/src/config.ts
- packages/plugins/typescript/react-apollo/src/visitor.ts
- packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
> Add withRefetchFn option

- packages/presets/near-operation-file/src/fragment-resolver.ts
- packages/presets/near-operation-file/src/index.ts
- packages/presets/near-operation-file/src/resolve-document-imports.ts
- packages/presets/near-operation-file/tests/near-operation-file.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/2365
> Fix dedupeOperationSuffix with presets

- docs/integrations/gatsby.md
> docs: add community Gatsby plugins

- packages/plugins/other/visitor-plugin-common/src/mappers.ts
- packages/plugins/other/visitor-plugin-common/tests/parse-mapper.spec.ts
- packages/plugins/typescript/typescript/tests/typescript.spec.ts
> mappers: dot-separated namespace

- packages/plugins/java/java/src/visitor.ts
- packages/plugins/java/java/tests/java.spec.ts
Related #3584 
if a argument in input is enum, and if the argument is not of that  enum type. Use enum.valueOfLabel to try to convert argument to that enum.
> fix(java): handle enum input when args is not enum

- dev-test/test-schema/flow-types.flow.js
- dev-test/test-schema/resolvers-federation.ts
- dev-test/test-schema/resolvers-root.ts
- dev-test/test-schema/resolvers-types.ts
- dev-test/test-schema/typings.ts
- packages/plugins/flow/resolvers/src/index.ts
- packages/plugins/flow/resolvers/tests/__snapshots__/flow-resolvers.spec.ts.snap
- packages/plugins/typescript/resolvers/src/index.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/3549
> allow return value to be promise in resolveType and isTypeOf

- packages/plugins/java/java/src/visitor.ts
- packages/plugins/java/java/tests/java.spec.ts
If `args.get("input") == null` then `(List<Map<String, Object>>) args.get("input).stream()` will throws NullPointerException since it's trying to access null.
Checking null before accessing to make sure there's no NullPointerException thrown
Related #3604
> Check null args for nullabe input type array

- packages/presets/near-operation-file/src/utils.ts
- packages/presets/near-operation-file/tests/near-operation-file.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/3066
> Fixes for issues with presets and fragments

- packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts
- packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/3612
> try to fix issues with missing fragments in docs

- packages/plugins/typescript/graphql-request/tests/graphql-request.spec.ts
- packages/presets/near-operation-file/src/fragment-resolver.ts
- packages/presets/near-operation-file/tests/near-operation-file.spec.ts
Related: 
- https://github.com/dotansimha/graphql-code-generator/issues/3525 
- https://github.com/dotansimha/graphql-code-generator/issues/3468 (maybe)
> Try to fix issues with FragmentDoc imports

- packages/plugins/flow/flow/src/visitor.ts
- packages/plugins/flow/flow/tsconfig.json
- packages/plugins/other/visitor-plugin-common/package.json
- packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts
- packages/plugins/other/visitor-plugin-common/src/enum-values.ts
- packages/plugins/other/visitor-plugin-common/src/types.ts
- packages/plugins/other/visitor-plugin-common/tests/enum-values.spec.ts
- packages/plugins/other/visitor-plugin-common/tsconfig.json
- packages/plugins/typescript/typescript/tests/typescript.spec.ts
- packages/plugins/typescript/typescript/tsconfig.json
- yarn.lock
Related: https://github.com/dotansimha/graphql-code-generator/issues/3641
> better enum values, now supports namespaces

- .prettierrc
- packages/graphql-codegen-cli/src/generate-and-save.ts
- packages/plugins/flow/flow/tests/validate-flow.ts
- packages/plugins/java/apollo-android/src/operation-visitor.ts
- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
- packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts
- packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts
- packages/utils/config-md-generator/src/index.ts
- packages/utils/graphql-codegen-testing/src/typescript.ts
Noticed the pre-commit hook when doing #3704 added some extra formatting. #3688 should probably have resulted in red CI so formatting was updated at the same time
> chore: run prettier on code base

- .github/workflows/main.yml
> Skip canary releases on Renovate PRs

- dev-test/test-schema/env.types.ts
- dev-test/test-schema/resolvers-root.ts
- dev-test/test-schema/resolvers-types.ts
- dev-test/test-schema/schema.graphql
- dev-test/test-schema/types.preResolveTypes.ts
- packages/graphql-codegen-cli/src/load.ts
- packages/graphql-codegen-cli/src/utils/try-to-build-schema.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/3249
> Fix issues with schema descriptions

- packages/graphql-codegen-cli/package.json
- packages/graphql-codegen-cli/src/utils/listr-renderer.ts
- yarn.lock
> Do not fit logs to terminal height

- .github/workflows/release.yml
so we don't need to copy&paste text, add a title, version and so on, just a list of changes.
> Github Action to create a release on GitHub

- README.md
Hey maintainer,
There were some minor grammar fixes, so I fixed them, Kindly merge my **PR** if everything looks good.
> Updated Documentation README.md

- packages/graphql-codegen-cli/src/codegen.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/3849
> Fix custom plugins and `require` extensions bug

- packages/graphql-codegen-cli/src/config.ts
- website/docs/getting-started/codegen-config.md
- website/docs/getting-started/development-workflow.md
Related: https://github.com/dotansimha/graphql-code-generator/issues/3854
> allow cli --watch flag to be a string/string[]

- packages/plugins/flow/flow/src/visitor.ts
- packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts
- packages/plugins/other/visitor-plugin-common/src/base-visitor.ts
- packages/plugins/typescript/typescript/src/config.ts
- packages/plugins/typescript/typescript/src/visitor.ts
- packages/plugins/typescript/typescript/tests/typescript.spec.ts
Related: 
- https://github.com/dotansimha/graphql-code-generator/pull/3883 
- https://github.com/dotansimha/graphql-code-generator/issues/3882
> Fixes for wrapping field with arrays

- packages/plugins/typescript/apollo-angular/src/config.ts
- packages/plugins/typescript/apollo-angular/src/visitor.ts
- packages/plugins/typescript/apollo-angular/tests/apollo-angular.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/3944
> Allow to override apollo-angular package

- package.json
- packages/graphql-codegen-cli/package.json
- packages/graphql-codegen-cli/src/config.ts
- yarn.lock
Reverts dotansimha/graphql-code-generator#3954
> Revert "Yargs"

- website/docs/plugins/typescript-resolvers.md
> Fix typescript-resolvers doc

- website/docs/getting-started/index.md
Haven't tested locally but hopefully this should fix the broken link.
> Docs: fix broken link

- packages/plugins/other/jsdoc/src/index.ts
- packages/plugins/other/jsdoc/tests/jsdoc-schema-types.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/4110
> added missing description to jsdoc plugin

- packages/plugins/typescript/urql/src/visitor.ts
> Fix invalid Urql subscription handler type

- renovate.json
> Preserve existing semver ranges

- packages/plugins/typescript/urql/src/visitor.ts
related: #4173
@dotansimha it'd be great if you or another maintainer could update the CI tests for these changes.
> Fix incorrect subscription hook type

- packages/plugins/typescript/urql/tests/urql.spec.ts
> Update useSubscription test

- packages/plugins/typescript/urql/src/visitor.ts
- packages/plugins/typescript/urql/tests/__snapshots__/urql.spec.ts.snap
- packages/plugins/typescript/urql/tests/urql.spec.ts
Related:
- https://github.com/dotansimha/graphql-code-generator/pull/4176
- https://github.com/dotansimha/graphql-code-generator/pull/4174
@Pytal
> Fixes for subscription generics in urql plugin 

- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
- Allow to customize the `Resolvers` suffix for each type resolvers `type`.
- Allow to customize the root exported `Resolvers` type name,
> Allow more type names customizations for `typescript-resolvers` plugin

- README.md
I just got tripped up by the same issue as in #3992
I thought I would be a good citizen and remove this from the docs so it doesn't confuse anyone else?
> Remove npx connand from quickstart docs

- packages/graphql-codegen-cli/src/config.ts
https://github.com/dotansimha/graphql-code-generator/issues/4346
> add -s alias for --silent flag

- website/docs/generated-config/named-operations-object.md
Fix plugin name for `named-operations-object`.
> Fix plugin name

- website/docs/getting-started/documents-field.md
> doc: Update documents-field.md (typo)

- packages/plugins/typescript/urql/src/visitor.ts
- packages/plugins/typescript/urql/tests/urql.spec.ts
Partial fixes to #3968 as per https://github.com/dotansimha/graphql-code-generator/issues/3968#issuecomment-661670683 I am not sure about prefixes.
> [urql] Respect omitOperationSuffix

- packages/plugins/flow/resolvers/tests/__snapshots__/flow-resolvers.spec.ts.snap
- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
- packages/plugins/typescript/resolvers/tests/__snapshots__/ts-resolvers.spec.ts.snap
- packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/4368
> Added missing ContextType on interface/union resolvers

- dev-test/githunt/types.vueApollo.ts
- packages/plugins/typescript/vue-apollo/src/visitor.ts
- packages/plugins/typescript/vue-apollo/tests/vue-apollo.spec.ts
Update subscription param options url
> [typescript-vue-apollo] Update Subscription options Doc

- dev-test/codegen.yml
- dev-test/githunt/typed-document-nodes.ts
- package.json
- packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts
- packages/plugins/typescript/typed-document-node/package.json
- packages/plugins/typescript/typed-document-node/src/index.ts
- packages/plugins/typescript/typed-document-node/src/visitor.ts
- yarn.lock
Related: https://github.com/dotansimha/graphql-code-generator/issues/4403
> Fixes for typed-document-node plugin

- packages/plugins/other/visitor-plugin-common/src/imports.ts
- packages/presets/near-operation-file/src/fragment-resolver.ts
- packages/presets/near-operation-file/src/index.ts
- packages/presets/near-operation-file/src/resolve-document-imports.ts
For #3695.
I'll try to find the time to go through the others I need for my own project, but it seems we might need to update most plugins and presets, which I don't have the time for. Hopefully others will just fix the ones they need themselves as we go 🙂
> feat: support type imports in `near-operation-file` preset

- dev-test/githunt/types.vueApollo.ts
- packages/plugins/typescript/vue-apollo/src/visitor.ts
- packages/plugins/typescript/vue-apollo/tests/vue-apollo.spec.ts
keep up with  https://github.com/vuejs/vue-apollo/commit/7495987fdb5b7ab6d7ea458cceadb4997ac92e5f
related #4444
> fix(vue-apollo): keep up with @vue/apollo-composable

- website/docs/getting-started/installation.md
PR just fixes some of the grammar and flow on the installations page.
> fix flow on installation's page

- packages/plugins/typescript/react-apollo/src/visitor.ts
Again for #3695. Didn't turn out too bad! Sorta weird, and maybe not correct, but these changes works at least for my work project
> feat(react-apollo): generate type imports

- dev-test/githunt/typed-document-nodes.ts
- packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts
- packages/plugins/typescript/typed-document-node/src/visitor.ts
Related: https://github.com/dotansimha/graphql-typed-document-node/issues/30
> Added fragments support in typed-document-node

- .changeset/tender-weeks-divide.md
Related: https://github.com/dotansimha/graphql-code-generator/issues/4492
> Fixes for published of visitor-plugin-common / ts-react-apollo

- .changeset/afraid-experts-sing.md
- dev-test/githunt/types.apolloAngular.sdk.ts
- dev-test/githunt/types.apolloAngular.ts
- packages/plugins/typescript/apollo-angular/src/visitor.ts
- packages/plugins/typescript/apollo-angular/tests/apollo-angular.spec.ts
> Fix Dependency Injection issue in Apollo Angular when targeting ES5

- .changeset/funny-books-sing.md
- .changeset/tall-knives-collect.md
- dev-test/githunt/types.apolloAngular.sdk.ts
- packages/plugins/typescript/apollo-angular/src/config.ts
- packages/plugins/typescript/apollo-angular/src/visitor.ts
- packages/plugins/typescript/apollo-angular/tests/apollo-angular.spec.ts
- scripts/canary-release.js
Related #4513 and kamilkisiela/apollo-angular#1383
> Support Apollo Angular 2.0 and add `serviceProvidedIn` option

- .changeset/afraid-garlics-hug.md
- dev-test/githunt/types.urql.tsx
- packages/plugins/typescript/urql/src/config.ts
- packages/plugins/typescript/urql/src/visitor.ts
- packages/plugins/typescript/urql/tests/urql.spec.ts
Continue the work by @Pytal  in: https://github.com/dotansimha/graphql-code-generator/pull/4495
Related: https://github.com/dotansimha/graphql-code-generator/issues/4494
> urql: Prefer generating React Hooks over React data components by default

- website/docs/getting-started/installation.md
- website/src/pages/index.js
Found myself reading the documentation and noticed some grammar/wording that could be fixed :)
> Fixed grammar/wording in installation.md

- .changeset/angry-carrots-boil.md
- packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts
- packages/plugins/other/visitor-plugin-common/src/utils.ts
- packages/plugins/typescript/typescript/tests/typescript.spec.ts
- patches/@changesets+cli+2.10.0.patch
Related: https://github.com/dotansimha/graphql-code-generator/issues/3137
> Fixes for numeric enum values

- .changeset/dull-games-destroy.md
- dev-test/githunt/types.vueApollo.ts
- packages/plugins/typescript/vue-apollo/src/visitor.ts
- packages/plugins/typescript/vue-apollo/tests/vue-apollo.spec.ts
> Fix useMutation options

- website/docs/getting-started/programmatic-usage.md
Just some minor language edits for the website.
> Improve language

- website/docs/plugins/typescript-vue-apollo.md
After some struggle to understand it better I opened an issue here and I wanted to share the solution with others.
https://github.com/dotansimha/graphql-code-generator/issues/4653
> Added an extra example with useResult

- .changeset/ninety-trees-wave.md
- .changeset/thin-pears-camp.md
- dev-test/githunt/types.preResolveTypes.compatibility.ts
- packages/plugins/typescript/compatibility/src/index.ts
- packages/plugins/typescript/compatibility/src/selection-set-to-types.ts
- packages/plugins/typescript/compatibility/tests/__snapshots__/compatibility.spec.ts.snap
- packages/plugins/typescript/compatibility/tests/compatibility.spec.ts
> Fixes for plugin `typescript-compatibility`

- website/docs/plugins/typescript-vue-apollo.md
Added import of missing `useResult`
> Forgot import statement

- .changeset/angry-cameras-give.md
- dev-test/test-schema/flow-types.flow.js
- dev-test/test-schema/resolvers-federation.ts
- dev-test/test-schema/resolvers-root.ts
- dev-test/test-schema/resolvers-types.ts
- dev-test/test-schema/typings.ts
- packages/plugins/flow/resolvers/src/index.ts
- packages/plugins/flow/resolvers/tests/__snapshots__/flow-resolvers.spec.ts.snap
- packages/plugins/flow/resolvers/tests/mapping.spec.ts
- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
- packages/plugins/typescript/resolvers/src/index.ts
- packages/plugins/typescript/resolvers/tests/__snapshots__/ts-resolvers.spec.ts.snap
- packages/plugins/typescript/resolvers/tests/federation.spec.ts
- packages/plugins/typescript/resolvers/tests/mapping.spec.ts
- packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/4789
> Fixed isTypeOf resolvers signature

- .changeset/plenty-stingrays-run.md
- packages/graphql-codegen-cli/package.json
- packages/graphql-codegen-cli/src/init/helpers.ts
- packages/graphql-codegen-cli/src/init/index.ts
- packages/graphql-codegen-cli/tests/init.spec.ts
- yarn.lock
Related:
- https://github.com/dotansimha/graphql-code-generator/issues/4779
- https://github.com/dotansimha/graphql-code-generator/discussions/4644
> Fix issues with init command and missing versions

- .changeset/six-worms-jam.md
- packages/plugins/typescript/urql/src/index.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/4612
> typescript-urql: fix extension validation

- .changeset/happy-apples-behave.md
- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
- packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/4687
> Fixes issues with typesSuffix and arguments type name

- .changeset/bright-toys-check.md
- packages/plugins/typescript/graphql-request/src/visitor.ts
- packages/plugins/typescript/graphql-request/tests/graphql-request.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/4748
> [typescript-graphql-request ] Integration with `importDocumentNodeExternallyFrom`

- packages/plugins/java/kotlin/src/visitor.ts
- packages/plugins/java/kotlin/tests/kotlin.spec.ts
This reverts commit b0582584a9beeedf72d416582d713d7099753906.
Fix for Issue #4820
> Revert "[kotlin] remove constructor method from generated code (#3156)"

- .changeset/polite-starfishes-exist.md
- packages/plugins/typescript/type-graphql/src/index.ts
- packages/plugins/typescript/type-graphql/src/visitor.ts
- packages/plugins/typescript/type-graphql/tests/type-graphql.spec.ts
> Fixed addition of Exact type to output

- website/docs/plugins/typescript-vue-apollo.md
Fixed some small typo's and added more examples
> Added more examples on using an options object

- .changeset/little-pillows-hunt.md
- packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts
- packages/plugins/typescript/typescript/tests/typescript.spec.ts
> Fixed unquoted numeric enum identifiers

- .changeset/young-jars-trade.md
- package.json
- packages/graphql-codegen-cli/src/config.ts
**What's the problem this PR addresses?**
I broke the tests in https://github.com/dotansimha/graphql-code-generator/pull/4983
**How did you fix it?**
Use `require.resolve` to resolve from the cwd
> fix(cli): resolve from folders correctly

- .changeset/calm-tables-add.md
- packages/plugins/other/schema-ast/src/index.ts
- packages/plugins/other/schema-ast/tests/schema-ast.spec.ts
- website/docs/generated-config/schema-ast.md
- website/docs/generated-config/typescript-apollo-angular.md
- website/static/config.schema.json
Related: https://github.com/dotansimha/graphql-code-generator/issues/4919
> feat(schema-ast): added support for sorting schemas before printing

- .changeset/wild-buttons-sparkle.md
- packages/presets/near-operation-file/tests/near-operation-file.spec.ts
- packages/utils/plugins-helpers/src/helpers.ts
related: https://github.com/dotansimha/graphql-code-generator/issues/5002
> fix(near-operation-file): fix issue with inline fragment without typeCondition

- .changeset/chilled-trees-act.md
- .changeset/nasty-dragons-turn.md
- packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts
- packages/plugins/typescript/operations/tests/__snapshots__/ts-documents.spec.ts.snap
- packages/plugins/typescript/operations/tests/ts-documents.spec.ts
Continue from: https://github.com/dotansimha/graphql-code-generator/pull/4839
All the credit goes to @benmosher and @n1ru4l , thank you so much! 
Related: https://github.com/dotansimha/graphql-code-generator/issues/4216
> remove broken isTypeOf call (always undefined in graphql-tools v6)

- .changeset/seven-kangaroos-stare.md
- packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts
- packages/plugins/typescript/typescript/src/config.ts
- packages/plugins/typescript/typescript/src/visitor.ts
- packages/plugins/typescript/typescript/tests/__snapshots__/typescript.spec.ts.snap
- packages/plugins/typescript/typescript/tests/typescript.spec.ts
- website/docs/generated-config/typescript-type-graphql.md
- website/docs/generated-config/typescript.md
- website/static/config.schema.json
> adds useImplementingTypes flag support

- website/docs/getting-started/require-field.md
I didn't understand how to use it, this documentation help to understand it.
> Improve 'dotenv' Integration documentation

- .changeset/wet-islands-promise.md
- .gitignore
- packages/plugins/java/java/src/config.ts
- packages/plugins/java/java/src/visitor.ts
- packages/plugins/java/java/tests/java.spec.ts
Hi,
I've made several changes to java plugin to, (A) make it compile, (B) use best practice.
If you have any question please feel free to contact me 😃 
Thanks!
Tzach
> java plugin changes

- .changeset/hot-trainers-fail.md
- packages/graphql-codegen-cli/src/config.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/5140
> Allow loading configuration from package.json file

- packages/presets/near-operation-file/src/index.ts
- website/docs/generated-config/near-operation-file-preset.md
this confounded me when trying to set up my config until I realized it was just a docs error
> docs: generates.ts -> generated.ts

- website/docs/plugins/typescript-mongodb.md
Fixed an invalid schema example
> docs: fix typescript-mongodb.md

- website/docs/integrations/apollo-local-state.md
Easy navigation and easy reading for others
> Fix broken url in docs

- .changeset/silly-carpets-walk.md
- packages/plugins/other/visitor-plugin-common/src/enum-values.ts
- packages/plugins/other/visitor-plugin-common/tests/enum-values.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/5360
> [typescript/flow] Escape enum values defined in GraphQLSchema correctly

- .changeset/tiny-phones-act.md
- packages/plugins/flow/flow/tests/__snapshots__/flow.spec.ts.snap
- packages/plugins/flow/resolvers/tests/__snapshots__/flow-resolvers.spec.ts.snap
- packages/plugins/other/visitor-plugin-common/src/utils.ts
Auto-generated files in my project have some trailing whitespace. This change removes them.
> Strip trailing whitespace

- .changeset/seven-papayas-sit.md
- .changeset/thirty-waves-glow.md
- packages/plugins/flow/operations/src/visitor.ts
- packages/plugins/flow/operations/tests/flow-documents.spec.ts
- packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts
- packages/plugins/typescript/operations/src/visitor.ts
- packages/plugins/typescript/operations/tests/ts-documents.spec.ts
> @skip, @include directives for objects

- .changeset/spicy-garlics-give.md
- packages/plugins/typescript/react-query/src/config.ts
- packages/plugins/typescript/react-query/src/fetcher-custom-mapper.ts
- packages/plugins/typescript/react-query/src/fetcher-fetch-hardcoded.ts
- packages/plugins/typescript/react-query/src/fetcher-fetch.ts
- packages/plugins/typescript/react-query/src/fetcher-graphql-request.ts
- packages/plugins/typescript/react-query/src/visitor.ts
- packages/plugins/typescript/react-query/tests/react-query.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/discussions/5377
> Allow to override TError type at the level of the config

- .changeset/violet-crabs-beg.md
- dev-test/githunt/flow.flow.js
- packages/plugins/flow/operations/src/index.ts
- packages/plugins/flow/operations/tests/__snapshots__/flow-documents.spec.ts.snap
> fix(flow-operation): remove irrelevant `Maybe` definition

- website/docs/getting-started/installation.md
See https://github.com/dotansimha/graphql-code-generator/issues/5450
> Clarify installation requirement

- .changeset/modern-pets-smile.md
- packages/plugins/typescript/graphql-request/src/visitor.ts
- packages/plugins/typescript/graphql-request/tests/__snapshots__/graphql-request.spec.ts.snap
I created PR(#5414) few days ago.
but it cause some type errors. (https://github.com/dotansimha/graphql-code-generator/pull/5414#issuecomment-767648010, #5459)
This PR fixes that errors.
> fix(plugin: graphql-requests): Fix type errors in auto-generated methods

- .changeset/polite-seahorses-impress.md
- packages/graphql-codegen-cli/src/load.ts
> feat(cli): pass plugin config to loaders

- packages/plugins/typescript/react-query/src/index.ts
- packages/plugins/typescript/react-query/src/visitor.ts
- packages/plugins/typescript/react-query/tests/react-query.spec.ts
Don't generate fetcher definition when there are no operations.
Related #5599 
`yarn build && yarn test`
- OS: Windows 10
- NodeJS: v14.15.5
If this is a relatively large or complex change, kick off …
> Don't generate fetcher without operations

- .changeset/fresh-ligers-look.md
- packages/plugins/typescript/graphql-request/src/visitor.ts
- packages/plugins/typescript/graphql-request/tests/__snapshots__/graphql-request.spec.ts.snap
- packages/plugins/typescript/graphql-request/tests/graphql-request.spec.ts
> Removed the unnecessary call to print in the graphql-request plugin.

- .changeset/slow-scissors-happen.md
- packages/plugins/flow/operations/tests/flow-documents.spec.ts
- packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts
- packages/plugins/typescript/operations/tests/ts-documents.spec.ts
- packages/utils/plugins-helpers/src/utils.ts
Related: #3882 
#5453 
#5326 
#5632
> Fixes for @skip directive

- packages/presets/graphql-modules/src/builder.ts
- packages/presets/graphql-modules/tests/__snapshots__/builder.spec.ts.snap
- packages/presets/graphql-modules/tests/builder.spec.ts
- packages/presets/graphql-modules/tests/test-files/modules/users/types/users.graphql
Reverts dotansimha/graphql-code-generator#5511
> Revert "Include enum resolvers in graphql-modules preset"

- website/docs/integrations/prettier.md
> add a perf note to prettier.md

- website/src/components/live-demo/LiveDemo.js
- website/src/components/live-demo/LiveDemoEditors.js
- website/src/components/ui/Loading.js
- website/src/components/ui/loading.module.css
> [deploy_website] Lazy-load Monaco editors

- .changeset/pink-kings-know.md
- packages/plugins/other/urql-introspection/CHANGELOG.md
- packages/plugins/other/urql-introspection/package.json
- packages/plugins/other/urql-introspection/src/index.ts
- packages/plugins/other/urql-introspection/tests/urql-introspection.spec.ts
- website/docs/generated-config/urql-introspection.md
Test coverage stays on a same level prior this changes
- OS: MacOS Big Sur
- `@graphql-codegen/urql-introspection`: 
- NodeJS: v14 (latest LTS)
- TypeScript: 4.2.4 (Bundled)
> Implemented useTypeImports in urql-introspection

- .changeset/strong-hornets-jog.md
- packages/plugins/typescript/graphql-request/src/visitor.ts
- packages/plugins/typescript/graphql-request/tests/__snapshots__/graphql-request.spec.ts.snap
- packages/plugins/typescript/graphql-request/tests/graphql-request.spec.ts
> fix(graphql-request): print document for rawRequest if documentMode is string

- website/package.json
- website/src/pages/index.js
Fixed the transition glitch by inserting the components within [BrowserOnly](https://docusaurus.io/docs/docusaurus-core#browseronly).
> New header - transition fix

- website/package.json
- website/src/css/custom.css
- website/src/pages/index.js
- website/src/theme/Root.js
- yarn.lock
Moved the header to Root in order to appear on all pages, marked the original Algolia search box as hidden & updated library version.
> Header fixes

- website/docusaurus.config.js
- website/package.json
- website/src/css/custom.css
Algolia Search configuration removal. Component moved to TGC.
https://github.com/the-guild-org/the-guild-components
> Algolia Config Removal

- .changeset/orange-beers-draw.md
- packages/plugins/c-sharp/c-sharp/src/visitor.ts
**According to feedbacks remove the access modifiers for properties in interfaces.**
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation**
**Yes i opened an issue, just right now.
https://github.com/dotansimha/graphql-code-generator/issues/5770**
**Ok, good things need time**
- [x ] Bug fix (non-breaking change which fixes an issue)
Adding links to sandbox or providing screenshots …
> remove access-modifiers on interfaces

- website/docs/integrations/vscode.md
- website/sidebars.js
Issue templete does not have a doc update as an option so I deleted it.
> add vscode extension integration doc

- packages/presets/near-operation-file/src/index.ts
Fix typo in near-operation-file index.ts
- OS: 
- NodeJS: 
> Fix typo in near-operation-file index.ts

- packages/presets/graphql-modules/src/config.ts
Fix typo in graphql-modules config.ts
- OS: 
- NodeJS: 
> Fix typo in graphql-modules config.ts

- .changeset/gold-ties-wonder.md
- packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts
- packages/plugins/typescript/operations/tests/ts-documents.spec.ts
- yarn.lock
Related https://github.com/dotansimha/graphql-code-generator/issues/3950
> Fix issues with missing sub-fragments when skipTypename: true

- .changeset/wet-panthers-kiss.md
- packages/plugins/other/visitor-plugin-common/src/selection-set-processor/pre-resolve-types.ts
- packages/plugins/typescript/operations/tests/ts-documents.spec.ts
Fix for array types with @skip @include directives
Related #6178
> @skip @include Arrays fix

- .changeset/stupid-cups-study.md
- packages/plugins/typescript/react-apollo/src/config.ts
- packages/plugins/typescript/react-apollo/src/visitor.ts
- packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
> feat(react-apollo): add hooksSuffix option

- packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts
Just fixing a small typo in a comment: colleting -> collecting
It has not been tested.
> chore: Fix a tiny typo

- website/docs/plugins/typescript-vue-apollo.md
I spent quite some time trying to figure out how to use the plugins TypedDocumentNode and vue-apollo together. Only after finding https://the-guild.dev/blog/typed-document-node, I realized that the latter is no longer needed when using TypedDocumentNode, and that this plugin is the "recommended"/modern version.
Thus, I've added a small note to the documentation pointing others in this direction.
Please describe the …
> Add pointer to TypedDocumentNode plugin in vue plugin

- .changeset/dry-nails-return.md
- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
Related: https://github.com/dotansimha/graphql-code-generator/discussions/6183#discussioncomment-995071
> Allow multiple `{T}` instances in defaultMapper

- .changeset/clean-scissors-happen.md
- packages/presets/near-operation-file/src/fragment-resolver.ts
- packages/presets/near-operation-file/src/utils.ts
- packages/presets/near-operation-file/tests/near-operation-file.spec.ts
- yarn.lock
> 6245 missing fragment imports fix

- .changeset/violet-pens-juggle.md
- packages/presets/near-operation-file/src/fragment-resolver.ts
- packages/presets/near-operation-file/tests/near-operation-file.spec.ts
- yarn.lock
> 6245 further edge cases fix

- .changeset/quiet-horses-grin.md
- packages/graphql-codegen-cli/package.json
- yarn.lock
Related: https://github.com/dotansimha/graphql-code-generator/issues/6374
> Fix for loaders issues with new GraphQL-Tools version

- website/docs/integrations/apollo-local-state.md
Readme to update generating local-state code
> Generating local state queries

- packages/graphql-codegen-cli/src/plugins.ts
- packages/graphql-codegen-cli/src/presets.ts
Given that the changes are fairly small I didn't open an issue; I believe seeing the proposed changes may be easier to understand. There are currently two small fixes I encountered while developing a third-party tool using this project. I've put a comment under each one if you wish to discuss them separately.
Made the changes in the graphql-codegen code within my project, and things worked instead of crashing.
- n/a I have commented my code, particularly in hard-to-understand areas
- n/a I have made corresponding changes to the documentation
- n/a Any dependent changes have been merged and published in downstream modules
> Fixes relative custom imports & empty plugins

- .changeset/quick-owls-call.md
- packages/plugins/typescript/apollo-client-helpers/src/index.ts
- packages/plugins/typescript/apollo-client-helpers/tests/__snapshots__/apollo-client-helpers.spec.ts.snap
- website/docs/plugins/typescript-apollo-client-helpers.md
Strengthen the `TypePolicies` type protections by narrowing allowed keys to know types.
Define and export `StrictTypedTypePolicies`
Export backwards-compatible union of `StrictTypedTypePolicies` and original very-loose `TypePolicies`
Update documentation example to use `StrictTypedTypePolicies`
Related #6318
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. …
> feat(apollo-client-helpers): export StrictTypedTypePolicies

- .changeset/ten-toes-impress.md
- packages/graphql-codegen-cli/src/graphql-config.ts
Follow-up of https://github.com/dotansimha/graphql-code-generator/pull/6494, by applying the changes not only to how schema files are loaded but also documents.
Related #6449.
- OS: 
- NodeJS: 
If …
> fix: do not alter the indentation of documents

- .changeset/tasty-steaks-prove.md
- packages/utils/plugins-helpers/src/resolve-external-module-and-fn.ts
- packages/utils/plugins-helpers/tests/fixtures/externalModuleFn.js
- packages/utils/plugins-helpers/tests/resolve-external-module-and-fn.spec.ts
Related #6553 
No screenshots. There is a [sandbox](https://codesandbox.io/s/empty-rain-hzgdf?file=/package.json) for the reproduction of the problem in the issue. There are tests that verify the fix.
Added a test and verified it failed before the fix with yarn test. Fixed the issue. Verified the test now passes with yarn test.
- OS: Linux 5.11.0-27-generic 29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
(Unchecked checklist items don't apply)
Note: Some tests fail locally before and after my changes.
> Fix cannot find module

- .changeset/early-roses-flash.md
- package.json
- packages/plugins/other/visitor-plugin-common/package.json
- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
- packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts
- packages/plugins/other/visitor-plugin-common/src/optimize-operations.ts
- packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts
- packages/plugins/other/visitor-plugin-common/src/utils.ts
- packages/utils/plugins-helpers/src/federation.ts
- yarn.lock
Related https://github.com/dotansimha/graphql-code-generator/issues/6542
> fix(plugin-helpers): remove unnecessary import

- .changeset/poor-lemons-doubt.md
- packages/plugins/typescript/typescript/src/config.ts
- packages/plugins/typescript/typescript/src/visitor.ts
- packages/plugins/typescript/typescript/tests/typescript.spec.ts
Related #6061
- n/a Bug fix (non-breaking change which fixes an issue)
- n/a Breaking change (fix or feature that would cause existing functionality to not work as expected)
- OS: 
- NodeJS: 
> Support future-proof enums as enums

- .changeset/light-boats-study.md
- packages/plugins/typescript/generic-sdk/src/visitor.ts
- packages/plugins/typescript/generic-sdk/tests/generic-sdk.spec.ts
Closes https://github.com/dotansimha/graphql-code-generator/issues/6551
> fix(generic-sdk): helpful error message for unnamed operations

- .changeset/clean-beds-dance.md
- packages/plugins/typescript/react-query/src/config.ts
- packages/plugins/typescript/react-query/src/fetcher-fetch-hardcoded.ts
- packages/plugins/typescript/react-query/tests/__snapshots__/react-query.spec.ts.snap
- packages/plugins/typescript/react-query/tests/react-query.spec.ts
Closes https://github.com/dotansimha/graphql-code-generator/issues/5449
Closes https://github.com/dotansimha/graphql-code-generator/pull/6408
See .changeset/clean-beds-dance.md for a description of this change
@paolotiu , @dankreminov, @jonathanstanley please provide feedback :)
> change fetchParams configuration option from object to string

- .changeset/green-icons-sip.md
- packages/plugins/typescript/gql-tag-operations/src/index.ts
- packages/presets/gql-tag-operations/tests/gql-tag-operations.spec.ts
> fix: follow "useTypeImports" configuration

- .changeset/plenty-jeans-knock.md
- packages/utils/plugins-helpers/package.json
otherwise we get this one:
```
$ graphql-codegen --config codegen.yml
/home/capaj/work-repos/authier-repos/authier/node_modules/@graphql-codegen/plugin-helpers/index.js:502
const getCachedDocumentNodeFromSchema = utils.memoize1(utils.getDocumentNodeFromSchema);
^
TypeError: utils.memoize1 is not a function
at Object.<anonymous> (/home/capaj/work-repos/authier-repos/authier/node_modules/@graphql-codegen/plugin-helpers/index.js:502:47)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require …
```
> Fix wrong dep semver range of graphql tools/utils

- website/docs/presets/gql-tag-operations.md
> docs: link to dev-test examples and adjust wordings

- packages/plugins/typescript/typescript/src/config.ts
See issue: https://github.com/dotansimha/graphql-code-generator/issues/6993
> Fix default of wrapFieldDefinitions

- .changeset/violet-planes-change.md
> chore: add changeset for visitor-plugin-common

- website/docs-templates/graphql-modules-preset.md
- website/docs/custom-codegen/contributing.md
- website/docs/custom-codegen/using-visitor.md
- website/docs/getting-started/index.md
- website/docs/integrations/gatsby.md
- website/docs/migration/from-0-18.md
* Updates to the documentation to fix various typos
> docs: fix various typos

- website/routes.ts
- fix typo in Sidebar's `Integrations`
- `GastbyJS` -> `GatsbyJS`
current version
> docs: fix typo in routes - GatsbyJS -> GatsbyJS

- website/docs/integrations/gatsby.md
- website/routes.ts
Fixing typos for "Gatsby" & updating the name to the correct usage.
> chore: Update Gatsby brand on website

- .changeset/great-radios-explode.md
- dev-test/githunt/types.urql.tsx
- packages/plugins/typescript/urql/src/visitor.ts
- packages/plugins/typescript/urql/tests/__snapshots__/urql.spec.ts.snap
- packages/plugins/typescript/urql/tests/urql.spec.ts
Related #7163 
- OS: Linux 5.13.19-2-MANJARO 
- NodeJS: v12.22.7
> [typescript-urql] Improve query hooks arg types

- .changeset/replace-dead-link.md
- website/docs/config-reference/codegen-config.md
Modify dead link for #7431 
Related #7431 
- OS: 
- NodeJS: 
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what …
> (fix:website) modify dead link in the docs

- website/docs/config-reference/schema-field.md
This PR adds an example of loading an API URL from a TypeScript file. 
Thanks to @n1ru4l for pointing me in the right direction.
> Loading API URL from TypeScript file example

- .changeset/pretty-planets-occur.md
- packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts
- packages/plugins/typescript/operations/tests/ts-documents.spec.ts
Resolves https://github.com/dotansimha/graphql-code-generator/pull/6442#issuecomment-1042586953
> fix: inlineFragmentTypes config option

- website/src/pages/plugins/[name].tsx
> docs: add meta tags to plugin hub

- website/docs/getting-started/installation.md
> docs(installation): fix typo with resources

- .changeset/new-weeks-turn.md
- packages/utils/plugins-helpers/src/types.ts
- website/docs/integrations/prettier.md
- website/next.config.js
- website/public/config.schema.json
reported on crisp.
we really need some kind of route lockfile and route integrity check within the guild-docs. (https://github.com/the-guild-org/the-guild-docs/issues/504, https://github.com/the-guild-org/the-guild-docs/issues/505)
> fix: broken links

- website/docs-templates/relay-operation-optimizer.md
Related #7594
Click link
Doc updates
> docs(relay-operation-optimizer): Fix URL

- .changeset/weak-radios-join.md
- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
- packages/plugins/other/visitor-plugin-common/tests/create-resolvers-fields.spec.ts
Fixes https://github.com/dotansimha/graphql-code-generator/issues/7562
> fix(resolvers): fix conflict between `typesPrefix: true` and `enumPrefix: false`

- .changeset/brown-rockets-tan.md
- packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
- packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
- website/public/config.schema.json
This PR add the `directiveContextExtender` 
Related #7505 
I've locally tested this changes with `yarn test`
I've add a new test to check if my contributions is working properly.
- OS: MacOS 12.1 (Apple Silicon)
- NodeJS: v16.13.2
> [typescript-resolvers] Add directiveContextExtender option

- website/docs-templates/typed-document-node.md
Includes video for `typed-document-node`
For Monday's WTF episode.
> docs(typed-document-node): add wtf video

- .changeset/perfect-mails-repair.md
- packages/graphql-cli-codegen-plugin/package.json
- packages/graphql-codegen-cli/package.json
- packages/graphql-codegen-cli/src/init/helpers.ts
- yarn.lock
fix security alert regarding package `got`
related: #7990 
ran `yarn test`
- OS: macOS
- NodeJS: 18 (should retain compatibility back to node 12, however)
> Upgrade latest version

- .changeset/eleven-buckets-explode.md
- dev-test/githunt/__generated__/comment.query.stencil-component.tsx
- dev-test/githunt/__generated__/feed-entry.fragment.stencil-component.tsx
- dev-test/githunt/__generated__/feed.query.stencil-component.tsx
- dev-test/githunt/__generated__/submit-comment.mutation.stencil-component.tsx
- dev-test/gql-tag-operations-masking-star-wars/gql/index.ts
- dev-test/gql-tag-operations-masking/gql/index.ts
- dev-test/gql-tag-operations-urql/gql/gql.d.ts
- dev-test/gql-tag-operations/gql/index.ts
- dev-test/star-wars/__generated__/CreateReviewForEpisode.tsx
- dev-test/star-wars/__generated__/HeroAndFriendsNames.tsx
- dev-test/star-wars/__generated__/HeroAppearsIn.tsx
- dev-test/star-wars/__generated__/HeroDetails.tsx
- dev-test/star-wars/__generated__/HeroDetailsFragment.tsx
- dev-test/star-wars/__generated__/HeroDetailsWithFragment.tsx
- dev-test/star-wars/__generated__/HeroName.tsx
- dev-test/star-wars/__generated__/HeroNameConditional.tsx
- dev-test/star-wars/__generated__/HeroParentTypeDependentField.tsx
- dev-test/star-wars/__generated__/HeroTypeDependentAliasedField.tsx
- dev-test/star-wars/__generated__/HumanFields.tsx
- dev-test/star-wars/__generated__/HumanWithNullWeight.tsx
- dev-test/star-wars/__generated__/TwoHeroes.tsx
- packages/plugins/other/visitor-plugin-common/src/imports.ts
- packages/plugins/typescript/gql-tag-operations/src/index.ts
- packages/plugins/typescript/oclif/src/visitor.ts
- packages/plugins/typescript/resolvers/tests/mapping.spec.ts
- packages/presets/gql-tag-operations/src/index.ts
- packages/presets/gql-tag-operations/tests/gql-tag-operations.spec.ts
- packages/presets/graphql-modules/tests/builder.spec.ts
- packages/presets/near-operation-file/tests/near-operation-file.spec.ts
Reverts dotansimha/graphql-code-generator#8034
> Revert "feat: attach .js extension to all relative/absolute file imports/exports"

- .changeset/real-toes-dance.md
- packages/graphql-codegen-cli/src/codegen.ts
- packages/graphql-codegen-cli/src/config.ts
- packages/graphql-codegen-cli/src/utils/debugging.ts
- packages/utils/plugins-helpers/src/types.ts
- website/src/pages/docs/config-reference/codegen-config.mdx
> feat(cli): `--verbose` and `--debug` flags

- .changeset/four-emus-care.md
- examples/programmatic-typescript/package.json
- packages/graphql-codegen-cli/package.json
- yarn.lock
Fixes https://github.com/dotansimha/graphql-code-generator/issues/6174
> chore(deps): update `@graphql-tools/graphql-file-loader` to `7.5.0`

- website/src/pages/docs/config-reference/codegen-config.mdx
- website/src/pages/docs/integrations/prettier.mdx
cf https://github.com/dotansimha/graphql-code-generator/issues/2872#issuecomment-1203701337
> doc(prettier): add notice for usage of dry-run mode with Prettier

- website/src/pages/docs/config-reference/multiproject-config.mdx
> fix: typo on docs

- website/src/pages/docs/getting-started/esm-typescript-usage.mdx
> depency > dependency

- website/src/pages/docs/guides/graphql-server-apollo-yoga.mdx
> update yoga / apollo server title

- website/package.json
- yarn.lock
Fixes issue with search results:
> fix(website): bump to `@guild-docs/algolia@0.2.1` to support new docs

- .github/workflows/algolia-integrity.yml
- .github/workflows/algolia-publish.yml
- .github/workflows/main.yml
- .github/workflows/website-integrity.yml
- package.json
> ci: use shared setup and lint actions

- .changeset/breezy-points-nail.md
- packages/plugins/typescript/generic-sdk/src/visitor.ts
- packages/plugins/typescript/generic-sdk/tests/__snapshots__/generic-sdk.spec.ts.snap
> fix(generic-sdk): explicitly define the return type of each method to satisfy TS type check

- website/src/pages/plugins/presets/gql-tag-operations-preset.mdx
Thanks, @benjie, for the heads-up! 🦅
> doc(preset/gql-tag-operations): avoid generic import path alias

- .changeset/heavy-cooks-move.md
- packages/presets/gql-tag-operations/src/babel.ts
Related #8206 
Bug fix (non-breaking change which fixes an issue)
Tested this change in the repro provided in the issue.
we should figure out integration test strategy for different bundlers 🤔
> fix: babel plugin for vite

- .changeset/@graphql-codegen_cli-8289-dependencies.md
- .changeset/shaggy-moons-exist.md
- packages/graphql-codegen-cli/package.json
Closes https://github.com/dotansimha/graphql-code-generator/issues/8212
Related:
- https://github.com/kamilkisiela/graphql-config/releases/tag/v4.3.4
- https://github.com/dotansimha/graphql-code-generator/issues/8212
- https://github.com/kamilkisiela/graphql-config/pull/1103
- https://github.com/kamilkisiela/graphql-config/issues/1113
> fix: issue for loading typescript config

- website/src/pages/docs/getting-started/development-workflow.mdx
- website/src/pages/docs/getting-started/esm-typescript-usage.mdx
Related #8318
I didn't run tests because I only add symbols into sample texts on the website.
> website: Add several symbols into some samples to fix typo

- website/src/pages/docs/advanced/how-does-it-work.mdx
- website/src/pages/docs/getting-started/index.mdx
Closes https://github.com/dotansimha/graphql-code-generator/pull/8351
> docs: callout

- website/src/pages/docs/getting-started/esm-typescript-usage.mdx
> fix: typos in copy

- website/src/pages/docs/getting-started/index.mdx
(I'm sorry for creating PR without issue, but this is a small minor fix.)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your …
> docs: minor fix in getting-started

- website/src/pages/plugins/presets/graphql-modules-preset.mdx
> docs: minor fix for graphql-modules-preset.mdx

- website/package.json
- website/theme.config.tsx
- yarn.lock
fixes https://github.com/dotansimha/graphql-code-generator/issues/8425
> use defineConfig in components

- .changeset/@graphql-codegen_cli-8441-dependencies.md
- .changeset/twenty-donuts-flash.md
- dev-test/codegen.ts
- examples/front-end/advanced/babel-optimized/package.json
- examples/front-end/advanced/babel-optimized/yarn.lock
- examples/front-end/react/apollo-client/package.json
- examples/front-end/react/apollo-client/yarn.lock
- examples/front-end/react/graphql-request/package.json
- examples/front-end/react/graphql-request/yarn.lock
- examples/front-end/react/swr/package.json
- examples/front-end/react/swr/yarn.lock
- examples/front-end/react/tanstack-react-query/package.json
- examples/front-end/react/tanstack-react-query/yarn.lock
- examples/front-end/react/urql/package.json
- examples/front-end/react/urql/yarn.lock
- examples/front-end/vue/apollo-composable/package.json
- examples/front-end/vue/apollo-composable/yarn.lock
- examples/front-end/vue/urql/package.json
- examples/front-end/vue/urql/yarn.lock
- examples/front-end/vue/villus/package.json
- examples/front-end/vue/villus/yarn.lock
- packages/graphql-codegen-cli/package.json
- packages/graphql-codegen-cli/src/config.ts
- scripts/examples-front-end-upgrade-codegen.js
- website/src/pages/docs/getting-started/installation.mdx
- website/src/pages/docs/guides/react-vue.mdx
- yarn.lock
> fix(cli): revert to cosmiconfig-typescript-loader

- .changeset/gentle-waves-grab.md
- packages/presets/client/src/index.ts
- website/src/pages/docs/guides/react-vue.mdx
https://github.com/dotansimha/graphql-code-generator/issues/8435
> feat(preset/client): allow the use of essential `config` options

- .changeset/famous-grapes-compare.md
- packages/presets/client/src/index.ts
cf: https://github.com/dotansimha/graphql-code-generator/pull/8455#discussion_r989223267
> fix(preset/client): typo in config mapping

- .changeset/moody-windows-type.md
- dev-test/codegen.ts
- packages/presets/client/src/index.ts
- packages/presets/client/src/isOutputFolder.ts
- packages/presets/client/src/process-sources.ts
- packages/presets/client/tests/client-preset.spec.ts
> feat(client-preset): print warning on skipped anonymous operation

- .changeset/fair-mugs-reflect.md
- packages/presets/client/src/index.ts
cf: https://github.com/dotansimha/graphql-code-generator/issues/8296#issuecomment-1289566183
> fix(client-preset): allow non-typescript plugins

- website/src/pages/docs/guides/react-vue.mdx
Related https://github.com/dotansimha/graphql-code-generator/issues/8601
> doc(client-preset): `pnpm` specific installation instructions

- .github/ISSUE_TEMPLATE/feature_request.yml
> fix unique id error for GH issues

- website/src/pages/docs/guides/react-vue.mdx
> Grammar fixes

- .changeset/real-ties-cross.md
- dev-test/gql-tag-operations-masking-star-wars/gql/gql.ts
- dev-test/gql-tag-operations-masking/gql/gql.ts
- dev-test/gql-tag-operations/gql/gql.ts
- dev-test/gql-tag-operations/graphql/gql.ts
- packages/plugins/typescript/gql-tag-operations/src/index.ts
- packages/presets/client/tests/client-preset.spec.ts
- packages/presets/gql-tag-operations/tests/gql-tag-operations.spec.ts
[Related issue](https://github.com/dotansimha/graphql-code-generator/issues/8762)
- Bug fix (non-breaking change which fixes an issue)
> change the client-preset generated template.

- .changeset/soft-pumpkins-smile.md
- dev-test/gql-tag-operations-masking-star-wars/gql/gql.ts
- dev-test/gql-tag-operations-masking/gql/gql.ts
- dev-test/gql-tag-operations/gql/gql.ts
- dev-test/gql-tag-operations/graphql/gql.ts
- packages/plugins/typescript/gql-tag-operations/src/index.ts
- packages/presets/client/src/fragment-masking-plugin.ts
- packages/presets/client/src/index.ts
- packages/presets/client/tests/client-preset.spec.ts
- packages/presets/gql-tag-operations/src/fragment-masking-plugin.ts
- packages/presets/gql-tag-operations/tests/gql-tag-operations.spec.ts
Fixing some linting issues in generated output. See details in issue.
#8795 
These are just linting fixes. I updated the relevant tests so that they pass.
> Linting fixes

- packages/plugins/typescript/operations/tests/__snapshots__/ts-documents.spec.ts.snap
- packages/plugins/typescript/operations/tests/ts-documents.spec.ts
- website/next.config.mjs
Attempting to repro https://github.com/dotansimha/graphql-code-generator/issues/8793 but seems like in `operations` plugin as we expect it to be
> test: selecting typename should not return optional

- website/src/pages/docs/guides/flutter-freezed.mdx
Explained the various blocks and Patterns that could be used to configure them
> docs: :memo: updated flutter-freezed plugin guide

- examples/persisted-documents/README.md
- examples/persisted-documents/babel.config.js
- examples/persisted-documents/codegen.ts
- examples/persisted-documents/jest.config.js
- examples/persisted-documents/package.json
- examples/persisted-documents/src/gql/fragment-masking.ts
- examples/persisted-documents/src/gql/gql.ts
- examples/persisted-documents/src/gql/graphql.ts
- examples/persisted-documents/src/gql/index.ts
- examples/persisted-documents/src/gql/persisted-documents.json
- examples/persisted-documents/src/main.ts
- examples/persisted-documents/src/yoga.spec.ts
- examples/persisted-documents/src/yoga.ts
- examples/persisted-documents/tsconfig.json
- examples/typescript-esm/src/gql/gql.ts
- examples/typescript-esm/src/gql/graphql.ts
- examples/yoga-tests/README.md
- website/src/components/file-tree.tsx
- website/src/pages/plugins/presets/preset-client.mdx
- yarn.lock
> docs: add example for persisted documents

- scripts/fix-bin.js
> ignore symlink that already exist

- .github/workflows/release.yml
- .github/workflows/rust.yml
- packages/presets/swc-plugin/README.md
- website/src/pages/plugins/presets/preset-client.mdx
Made the rust plugin flow to be triggered manually making and added documentation on release flow.
> rust plugin ci and docs update

- examples/typescript-graphql-request/package.json
- yarn.lock
Reverts dotansimha/graphql-code-generator#9090
> Revert "fix(deps): update dependency graphql-request to v5.2.0"

- examples/react/apollo-client/package.json
- examples/react/graphql-request/package.json
- examples/react/tanstack-react-query/package.json
- examples/react/urql/package.json
- examples/vue/apollo-composable/package.json
- examples/vue/urql/package.json
- examples/vue/villus/package.json
- yarn.lock
Reverts dotansimha/graphql-code-generator#9067
> Revert "chore(deps): update dependency cypress to v12.7.0"

- .vscode/launch.json
Could be helpful.
- OS:
- NodeJS:
> Add Code debugger setup

- website/src/pages/docs/guides/graphql-server-apollo-yoga.mdx
On this page, there is a snippet of code that allows an individual to start the yoga service.
https://the-guild.dev/graphql/codegen/docs/guides/graphql-server-apollo-yoga
However, the snippet has invalid javascript, highlighted in red, below.
[](https://github.com/dotansimha/graphql-code-generator/issues/9126)
- OS:
- NodeJS:
> docs: Correct guide example server code

- packages/presets/swc-plugin/Cargo.lock
- packages/presets/swc-plugin/Cargo.toml
- website/src/pages/plugins/presets/preset-client.mdx
> fix: downgrade swc_core and update docs to acknowledge swc as an experimental feature

- website/src/pages/docs/config-reference/schema-field.mdx
We get this quesiton time to time so worth documenting.
> docs: handleAsSDL option

- website/src/pages/docs/config-reference/codegen-config.mdx
Related https://github.com/dotansimha/graphql-code-generator/issues/9154
- OS:
- NodeJS:
> Mention jiti loader in codegen config docs

- website/src/pages/docs/guides/graphql-server-apollo-yoga-with-server-preset.mdx
> fix schema path in docs

- packages/presets/swc-plugin/README.md
Update swc-plugin README.md next.js snippet example to use correct npm package name of `@graphql-codegen/client-preset-swc-plugin`.
README.md change.
> docs: swc-plugin next.js example

- website/src/pages/plugins/typescript/_meta.json
Signed-off-by: TuvalSimha <tuval.simha@gmail.com>
**Test …
> Website/plugin: Fix `nhost` tag

- packages/presets/swc-plugin/Cargo.lock
- packages/presets/swc-plugin/Cargo.toml
- Update swc_core in order to support the upcoming Next.js
- https://github.com/vercel/next.js/pull/48098
- https://swc.rs/docs/plugin/selecting-swc-core#v0750
Related https://github.com/dotansimha/graphql-code-generator/issues/9326
**Test …
> Update swc_core to v0.75

- .changeset/dull-coats-drop.md
- examples/react/apollo-client-swc-plugin/package.json
- examples/react/nextjs-swr/package.json
- packages/presets/swc-plugin/Cargo.lock
- packages/presets/swc-plugin/Cargo.toml
- packages/presets/swc-plugin/package.json
- yarn.lock
https://swc.rs/docs/plugin/selecting-swc-core#v0750
> Update swc_core to v0.75 (#9335)

- .changeset/khaki-dolphins-pump.md
- packages/utils/plugins-helpers/src/types.ts
- website/public/config.schema.json
Related https://github.com/dotansimha/graphql-code-generator/issues/9309
- OS:
- NodeJS:
> Add missing handleAsSDL property to UrlSchemaOptions type

- packages/presets/client/tests/client-preset.spec.ts
Tests on CI are currently broken because there was a new test added which was created before merging `defer`.  
- OS:
- …
> Update new client-preset test

- examples/vue/urql/src/main.ts
- website/src/pages/docs/guides/react-vue.mdx
I'm seeing some issues that's blocking CI/CD:
- a doc file failing prettier check
- new version of `@urql/vue` breaking e2e test. It looks like it's from this PR: https://github.com/dotansimha/graphql-code-generator/pull/9255
This PR fixes the above
> Fix CI/CD issues

- packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts
There is a small error in optimizeDocumentNode docs. This PR fixes it.
> docs: fix optimizeDocumentNode docs error

- .changeset/old-jokes-doubt.md
- packages/graphql-codegen-cli/package.json
- yarn.lock
Fix update yaml dependency to fix vulnerability.
Related to https://github.com/dotansimha/graphql-code-generator/issues/9341
- OS:
- NodeJS:
If this is a relatively large or complex change, kick off …
> deps: yaml v2

- packages/plugins/typescript/typescript/src/config.ts
> Fix docs typo

- .changeset/early-rice-brush.md
- website/src/pages/docs/guides/react-vue.mdx
Docs were missing a few packages that need to be installed
> docs: add missing packages to install

- website/src/pages/docs/config-reference/codegen-config.mdx
Sorry if this is too trivial, just sending a small english typo update.
- OS:
- NodeJS:
If this is a relatively large or complex change, kick off the discussion by explaining why you …
> Removed typo in codegen-config.mdx

- website/package.json
- website/public/config.schema.json
- website/src/pages/plugins/typescript/typescript-msw.mdx
Update documentation for major version on `@graphql-codegen/typescript-msw`
Related dotansimha/graphql-code-generator-community#594
Documentation update
> docs: update msw documentation

- website/src/pages/docs/config-reference/codegen-config.mdx
Document the noSilentErrors option. Doc string taken from https://github.com/ardatan/graphql-tools/blob/master/packages/loaders/code-file/src/index.ts#L33
Related https://github.com/dotansimha/graphql-code-generator/issues/9172
Documentation
n/a
n/a
> docs(codegen-config): document the noSilentErrors option

- website/src/pages/docs/custom-codegen/contributing.mdx
> Website: Fix 404 paths in docs

- website/src/pages/docs/getting-started/index.mdx
Think this was meant to be singular, not plural
Very simple grammar fix
Not sure this merits a whole issue?
- OS:
- NodeJS:
If this is a relatively large or complex change, kick off …
> Simple grammar fix

- README.md
as per our discussion in slack
> docs: add "Created by The Guild" logo to the readme

- website/src/components/index-page.tsx
- website/src/pages/docs/getting-started/index.mdx
- website/src/pages/docs/getting-started/installation.mdx
- website/src/pages/docs/guides/_meta.ts
- website/src/pages/docs/guides/react-vue.mdx
Some edits and link changes of headlines and the landing page.
> docs: improvements

- .github/ISSUE_TEMPLATE/feature_request.yml
The final question is a duplicate of the first. I've updated it to something a little bit better, but am still not happy with it and I'm not 100% on the intent. Just wanted to take a step toward an improvement.
> Improve duplicate question for on feature request template

- website/src/pages/docs/guides/vanilla-typescript.mdx
> docs: fix code example vanilla-typescript.mdx

- .changeset/shy-berries-shop.md
- dev-test/gql-tag-operations-masking/gql/graphql.ts
- dev-test/gql-tag-operations-urql/gql/graphql.ts
- dev-test/gql-tag-operations/gql/graphql.ts
- dev-test/gql-tag-operations/graphql/graphql.ts
- examples/persisted-documents-string-mode/src/gql/graphql.ts
- examples/persisted-documents/src/gql/graphql.ts
- examples/react/apollo-client-defer/src/gql/graphql.ts
- examples/react/apollo-client-swc-plugin/src/gql/graphql.ts
- examples/react/apollo-client/src/gql/graphql.ts
- examples/react/http-executor/src/gql/graphql.ts
- examples/react/nextjs-swr/gql/graphql.ts
- examples/react/tanstack-react-query/src/gql/graphql.ts
- examples/react/urql/src/gql/graphql.ts
- examples/typescript-esm/src/gql/graphql.ts
- examples/typescript-graphql-request/src/gql/graphql.ts
- examples/vite/vite-react-cts/src/gql/graphql.ts
- examples/vite/vite-react-mts/src/gql/graphql.ts
- examples/vite/vite-react-ts/src/gql/graphql.ts
- examples/vue/apollo-composable/src/gql/graphql.ts
- examples/vue/urql/src/gql/graphql.ts
- examples/vue/villus/src/gql/graphql.ts
- examples/yoga-tests/src/gql/graphql.ts
- packages/presets/client/src/index.ts
- packages/presets/client/tests/client-preset.spec.ts
Reverts dotansimha/graphql-code-generator#10073
Related: https://github.com/dotansimha/graphql-code-generator/issues/10167
> Revert "feat: reduce code output of client preset"

- packages/utils/plugins-helpers/src/types.ts
Fixes two minor typos in some JSDoc.
> Fix typos in documentation

- .eslintrc.cjs
- .vscode/settings.json
- packages/graphql-codegen-cli/src/cli.ts
- packages/graphql-codegen-cli/src/graphql-config.ts
- packages/graphql-codegen-cli/src/utils/watcher.ts
- packages/graphql-codegen-cli/tests/__mocks__/some-fetch.js
- packages/graphql-codegen-cli/tests/custom-loaders/custom-documents-loader.js
- packages/graphql-codegen-cli/tests/custom-loaders/custom-schema-loader-with-context.js
- packages/graphql-codegen-cli/tests/custom-loaders/custom-schema-loader.js
- packages/graphql-codegen-cli/tests/init.spec.ts
- packages/plugins/other/schema-ast/tests/schema-ast.spec.ts
- packages/plugins/other/visitor-plugin-common/src/types.ts
- packages/plugins/other/visitor-plugin-common/src/variables-to-object.ts
- packages/plugins/typescript/operations/tests/ts-documents.spec.ts
- packages/plugins/typescript/typescript/src/typescript-variables-to-object.ts
- packages/utils/graphql-codegen-testing/src/index.ts
This PR fixes lint step on `master` because of ESLint errors (image below shows the start of the ESLint errors)
When I try checking it locally, we had about 80 errors, probably because we updated the rules recently? 
This PR fixes or ignore these rules to make the linting CI step green.
> Fix ESLint issues

- website/package.json
- website/tailwind.config.ts
- yarn.lock
Quick fix to the navigation confusion we overlooked before.
I clicked the link.
> Bump Components to have a /docs link in nav instead of Sign up

- website/theme.config.tsx
We link to the new blog. Single line change.
> Update the Blog link to go to Hive blog

- dev-test/modules/blog/generated.ts
- dev-test/modules/common/generated.ts
- dev-test/modules/dotanions/generated.ts
- dev-test/modules/users/generated.ts
- packages/presets/graphql-modules/src/index.ts
- packages/presets/graphql-modules/tests/integration.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/pull/10314
There were some dev tests that needed updating, so this PR updates them to unblock CI.
> Fix failing CI dev-tests
