dotansimha/graphql-code-generator

package.json
I don't believe `optionalDependency` is necessary. It installs `@types/graphql` which apparently conflicts with `graphql` typings causing issues like so:
```
$ tsc -p .
...
node_modules/@types/graphql/index.d.ts(126,9): error TS2484: Export declaration conflicts with exported declaration of 'IntrospectionNonNullTypeRef'
```
=> chore(dependencies): Removes unnecessary optional @types/graphql dependency

src/engine/templates.ts
Currently when trying to run the multi-file typescript setup the user gets the following error:
```
(node:94403) UnhandledPromiseRejectionWarning: Unhandled promise rejection 
(rejection id: 1): 
Error: Template file /home/<user>/generators/type....index.handlebars does not exist
```
This issue is because the generator path wasn't being resolved as the config.js path was.
=> Fix error in template file resolutions

src/engine/codegen.ts
I'm not actually sure this is the best way to go about doing this. Maybe the logic should've went in the handleType method? Regardless, this gets the desired result. 
By the way, I think some of these methods really should be broken down to be more testable.
=> Fixes #111: Prevent primitives from being output like other models

packages/graphql-codegen-compiler/src/handlebars-extensions.ts
Now `ifDirective` is executed with it's parent context along with the directive value
=> Fix helpers context

CHANGELOG.md, dev-test/config/gql-gen.json, packages/graphql-codegen-cli/README.md, packages/graphql-codegen-cli/src/cli.ts, packages/graphql-codegen-cli/tests/cli.spec.ts, packages/graphql-codegen-compiler/package.json, packages/graphql-codegen-compiler/src/compile.ts, packages/graphql-codegen-compiler/src/generate-multiple-files.ts, packages/graphql-codegen-compiler/src/generate-single-file.ts, packages/graphql-codegen-compiler/tests/multiple.spec.ts, packages/graphql-codegen-compiler/tests/single.spec.ts, packages/graphql-codegen-compiler/yarn.lock, packages/graphql-codegen-generators/src/types.ts, packages/graphql-codegen-generators/src/typescript-single-file/template.handlebars
- change cli from `projectConfig` to be `config`
- use gql-gen not only in project generation
- expose `config` as part of the root context of the template
- export `currentTime` as part of the root context of the template
- added `generated in...` to ts single file template
Related to:
https://github.com/dotansimha/graphql-code-generator/issues/148
Usage example is `gql-gen.json`:
https://github.com/dotansimha/graphql-code-generator/blob/f54696ebf550a25ef8b70f376d9ff030653aface/dev-test/config/gql-gen.json
And then it's available as part of the template context:
https://github.com/dotansimha/graphql-code-generator/blob/f54696ebf550a25ef8b70f376d9ff030653aface/packages/graphql-codegen-generators/src/typescript-single-file/template.handlebars
=> Added generator-specific config in `gql-gen.json`

packages/graphql-codegen-compiler/tests/multiple.spec.ts, packages/graphql-codegen-compiler/tests/single.spec.ts, packages/graphql-codegen-generators/src/typescript-multi-file/enum.handlebars, packages/graphql-codegen-generators/src/typescript-single-file/schema.handlebars
Recent versions of Typescript allow for string-values based enumerations. This allows enums that looks like this: 
```ts
enum Color {
RED='red',
GREEN='green',
BLUE='blue',
}
```
The benefit of this in client code is that you can reference enumeration values as symbols instead of just relying on raw string values.
e.g. 
```ts
const color: Color  = 'red'
// becomes
const color = Color.RED
```
=> Update enumeration handling to emit Typescript string-backed enums

dev-test/test-schema/schema-ast.js, dev-test/test-schema/schema-formats.js, dev-test/test-schema/schema-json.js, dev-test/test-schema/schema-object.js, dev-test/test-schema/schema-text.js, packages/graphql-codegen-cli/src/loaders/schema-from-export.ts, packages/graphql-codegen-cli/tests/cli.spec.ts, packages/graphql-codegen-core/src/schema/schema-to-template-context.ts
This is a PR to be able to accept more formats for the `--export` flag. It will now accept all of these formats:
1. GraphQLSchema object
2. Text (the GraphQL schema language textual format)
3. AST (the GraphQL schema language textual format parsed into an AST)
4. Introspection JSON (result returned by introspection query)
The PR adds tests for all of the above cases.
In order for the tests to work there can only be one instance of the `graphql` package imported or the `instanceof` checks [here](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-core/src/schema/schema-to-template-context.ts#L61) will fail. They will fail even if the exact same version of the `graphql` package is imported by all packages. In order for the `instanceof` operator to work, …
=> Accept more formats for the --export flag

packages/graphql-codegen-cli/src/cli.ts
This MR is fixing export (`--export`) short alias as it's not as shown in project readme (`-e`), but `-u` what is used by `--url`.
export himself seems to be working nicely.
=> CLI: fix export short alias

packages/graphql-codegen-cli/src/loaders/templates-scanner.ts, packages/graphql-codegen-compiler/src/compile.ts, packages/graphql-codegen-compiler/src/generate-multiple-files.ts, packages/graphql-codegen-compiler/src/handlebars-extensions.ts, packages/graphql-codegen-generators/CUSTOM_TEMPLATES.md
Address #209, as well as:
* preserve directory structure to `--out` 
* make `ts.{ schema, documents }.handlebars` work without a prefix
(e.g. `ts.schema.handlebars` => `schema.ts`)
* automatically `registerPartial` custom templates without breaking normal partial registration (`registerPartial(filename.split('.').reverse()[1], template)`)
* mark comments safe to avoid url escaping
* fixes some links in the docs and add relevant docs for the included changes
=> Output custom template output to --out

packages/graphql-codegen-cli/tests/__snapshots__/document-finder.spec.ts.snap, packages/graphql-codegen-cli/tests/document-finder.spec.ts
So it turns out that tests for document-finder that were simply checking for the existence of some text were not sufficient. Instead, I've added snapshot testing so every small change in the output matters. Then I've manually tweaked the snapshot to a form that will pass through the parser.
There is some sort of breaking change in 0.8.19 (works in 0.8.18) which includes brackets in the output while those are not part of `gql` literal string and parsing fails afterward.
```graphql
query GPlayerList {
allPlayers {
id
tier
name
}
}
) # this bracket should not be here
```
I am not strong with regexp, so looking at the actual code, I am not sure how to fix this. However, at least now there is failing test.
=> Use snapshots for tests

packages/graphql-codegen-cli/tests/cli.spec.ts, packages/templates/typescript/README.md, packages/templates/typescript/src/config.ts, packages/templates/typescript/src/helpers/get-field-resolver-name.ts, packages/templates/typescript/src/helpers/get-field-resolver.ts, packages/templates/typescript/src/helpers/get-type.ts, packages/templates/typescript/src/resolver.handlebars, packages/templates/typescript/src/schema.handlebars, packages/templates/typescript/src/utils/capitalize.ts, packages/templates/typescript/src/utils/get-result-type.ts, packages/templates/typescript/tests/custom-matchers.ts, packages/templates/typescript/tests/typescript.spec.ts, yarn.lock
Closes #319
I changed a bit how `expect().toBeSimilarStringTo` works, it was comparing a template from start to end now it checks if a template contains a part we're looking for.
Example: https://github.com/kamilkisiela/gql-gen-with-resolvers
@dotansimha
=> typescript: generate types for resolvers

packages/templates/typescript/package.json
It won't compile as a stand-alone package if it isn't here.
It complains about missing types.
The same thing as #390
=> add graphql to typescript template dependencies

dev-test/generate-all.sh, dev-test/githunt/types.reactApollo.ts, packages/templates/typescript-react-apollo/.gitignore, packages/templates/typescript-react-apollo/.npmignore, packages/templates/typescript-react-apollo/.npmrc, packages/templates/typescript-react-apollo/README.md, packages/templates/typescript-react-apollo/package.json, packages/templates/typescript-react-apollo/src/components.handlebars, packages/templates/typescript-react-apollo/src/config.ts, packages/templates/typescript-react-apollo/src/index.ts, packages/templates/typescript-react-apollo/src/polyfills.d.ts, packages/templates/typescript-react-apollo/tests/components.spec.ts, packages/templates/typescript-react-apollo/tests/custom-matchers.ts, packages/templates/typescript-react-apollo/tests/files/schema.json, packages/templates/typescript-react-apollo/tsconfig.json, yarn.lock
This template generates React Apollo components with TypeScript typings.
This template is extended version of TypeScript template, so the configuration is same with `graphql-codegen-typescript-template`.
- Example Input
```graphql
query Test {
feed {
id
commentCount
repository {
full_name
html_url
owner {
avatar_url
}
}
}
}
```
- Example Usage
```tsx
<Test.Component query={...} variables={...}>
...
</Test.Component>
```
=> Add TypeScript React Apollo Template

dev-test/githunt/types.avoidOptionals.ts, dev-test/githunt/types.d.ts, dev-test/githunt/types.immutableTypes.ts, dev-test/githunt/types.noNamespaces.ts, dev-test/githunt/types.reactApollo.ts, dev-test/githunt/types.ts, dev-test/star-wars/ts-multiple/heroparenttypedependentfield.query.ts, dev-test/star-wars/types.avoidOptionals.ts, dev-test/star-wars/types.d.ts, dev-test/star-wars/types.immutableTypes.ts, dev-test/star-wars/types.noNamespaces.ts, dev-test/star-wars/types.skipSchema.ts, dev-test/star-wars/types.ts, dev-test/test-schema/typings.avoidOptionals.ts, dev-test/test-schema/typings.immutableTypes.ts, dev-test/test-schema/typings.ts, packages/graphql-codegen-compiler/src/flatten-types.ts, packages/graphql-codegen-core/src/schema/resolve-type-indicators.ts, packages/graphql-codegen-core/src/schema/resolve-type.ts, packages/graphql-codegen-core/src/schema/transform-fields.ts, packages/graphql-codegen-core/src/schema/transform-interface.ts, packages/graphql-codegen-core/src/schema/transform-object.ts, packages/graphql-codegen-core/src/types.ts, packages/templates/typescript/src/helpers/get-field-resolver.ts, packages/templates/typescript/src/resolver.handlebars, packages/templates/typescript/src/schema.handlebars, packages/templates/typescript/src/utils/get-result-type.ts, packages/templates/typescript/tests/resolvers.spec.ts, packages/templates/typescript/tests/typescript.spec.ts
If end user decide to put something there it should be able to do it
Fixes #462 
Fixes #466
https://github.com/dotansimha/graphql-code-generator/issues/153#issuecomment-410647014
https://github.com/dotansimha/graphql-code-generator/pull/444#discussion_r207878190
=> Parent of resolver should always be any; Use Resolver or SubscriptionResolver directly on field

packages/templates/typescript/src/schema.handlebars, packages/templates/typescript/tests/typescript.spec.ts
The template doesn't currently Pascal case union types; this PR updates the schema handlebar to fix this.
=> Make types pascal cased

packages/templates/typescript/src/template.handlebars, packages/templates/typescript/tests/typescript.spec.ts
=> Avoid escaping `prepend` lines (dotansimha/graphql-code-generator#484)

packages/templates/typescript-apollo-angular/.gitignore, packages/templates/typescript-apollo-angular/.npmignore, packages/templates/typescript-apollo-angular/.npmrc, packages/templates/typescript-apollo-angular/README.md, packages/templates/typescript-apollo-angular/package.json, packages/templates/typescript-apollo-angular/src/components.handlebars, packages/templates/typescript-apollo-angular/src/config.ts, packages/templates/typescript-apollo-angular/src/helpers/gql.ts, packages/templates/typescript-apollo-angular/src/index.ts, packages/templates/typescript-apollo-angular/src/polyfills.d.ts, packages/templates/typescript-apollo-angular/tests/components.spec.ts, packages/templates/typescript-apollo-angular/tests/custom-matchers.ts, packages/templates/typescript-apollo-angular/tests/files/schema.json, packages/templates/typescript-apollo-angular/tsconfig.json
Uses https://github.com/apollographql/apollo-angular/pull/622
- `noGraphQLTag` flag to use parsed object as a document (turned off by default, uses `graphql-tag`)
An example to play with:
https://codesandbox.io/s/github/kamilkisiela/apollo-angular-code-generator
Repository:
https://github.com/kamilkisiela/apollo-angular-code-generator
=> Introduce a template for apollo-angular

dev-test/test-schema/schema-with-imports.graphql, packages/graphql-codegen-cli/package.json, packages/graphql-codegen-cli/src/loaders/schema/schema-from-typedefs.ts, packages/graphql-codegen-cli/tests/cli.spec.ts, packages/graphql-codegen-cli/tests/schema-from-typedefs.spec.ts, packages/graphql-codegen-cli/tests/test-files/schema-dir/query.graphql, yarn.lock
[GraphQL Yoga](https://github.com/prismagraphql/graphql-yoga) uses [`graphql-import`](https://github.com/prismagraphql/graphql-import) that allows for using the following syntax: 
```graphql
type A {
first: String
second: Float
b: B
}
```
This PR adds support for that syntax.
Thanks for this amazing package @dotansimha 👍
=> Support for the "# import" syntax

packages/graphql-codegen-cli/src/codegen.ts, packages/graphql-codegen-cli/src/loaders/documents/document-loader.ts
Hi! PR #513 was a WIP but got merged :) Here is a fix for the error that arises when loading documents sources without a gql tag. I also filtered out the validation rule `NoUnusedFragments` because as of now it seems that we don't compile the template literals which will not include external fragments declared in other variables
=> Fix validating queries against schema bug

packages/graphql-codegen-cli/src/codegen.ts, packages/graphql-codegen-compiler/src/generate-multiple-files.ts, packages/graphql-codegen-compiler/src/generate-single-file.ts, packages/templates/typescript/src/helpers/is-primitive-type.ts, packages/templates/typescript/src/utils/get-result-type.ts, packages/templates/typescript/tests/resolvers.spec.ts
CLI dismisses `primitives` and `flattenTypes` option in `gql-gen.json`.
This PR fixes this issue and also refactors by using `primitives` everywhere instead of `primitivesMap`.
Fixes #543
=> [cli] fix handling gql-gen config

packages/graphql-codegen-cli/src/loaders/schema/introspection-from-url.ts
Fix for #556 
Not sure where things were left in the discussion, but so far I haven't found any explanation for the `replace` call that removes `locations`, and as things stand I'm unable to use this library. Furthermore, neither of the other `introspection-from-` files seem to have a similar transformation.
=> Restore `locations` field in introspection query

packages/graphql-codegen-cli/src/codegen.ts, packages/scripts/codegen-templates-scripts/webpack.config.js, packages/templates/typescript-mongodb/tests/ts-mongo.spec.ts
`mergeSchemas` from `graphql-tools` removes directives because it's based on AST, so it broke the MongoDB template because the directives were stripped.
We prefer to use `@graphql-modules/epoxy` for it ;)
=> Fix for schema merging 

packages/graphql-codegen-cli/src/loaders/documents/document-loader.ts, packages/graphql-codegen-cli/tests/load-documents-sources.spec.ts, packages/graphql-codegen-cli/tests/test-documents/my-fragment.ts, packages/graphql-codegen-cli/tests/test-documents/query-with-my-fragment.ts
This is a quickfix for #624 to allow users to continue working. 
It will simply ignore errors with message "Unknown fragment". This way we can still get the filename of every other error.  I think only the case with misspelled fragment names in spreads where the fragment is imported from another file will be not be validated with this fix.
The proper fix would be to actually resolve all the fragments.
=> Proposed quickfix for unknown fragment

README.md
I was having trouble when trying to use the programmatic approach shown in the readme, and I had to go into the type files to see what is accepted by `CLIOptions`.
Changes:
- I believe `url` is no longer used in favor of `schema`
- I added `args` to the example as the blob used in the CLI examples wasn't immediately clear as to how to use it
- Even though it isn't specific to this module, I added `async` in the case that a reader isn't yet familiar with async/await. This will remove the error of using `await` outside of an `async` function.
=> fix programmatic usage section of readme

packages/templates/README.md
The link in the readme was linking incorrectly :)
=> fix(docs): fix link in templates readme

packages/graphql-codegen-cli/src/codegen.ts
Hello! While debugging gql-gen with a new template I was building, I found that some log messages were displaying empty strings instead of the values they were supposed to display. I fixed it locally in order to understand what was going on.
Please, consider if it could be appropriate to be merged upstream.
=> Fix some logging messages not properly displaying the expected information

packages/graphql-codegen-cli/src/loaders/schema/schema-from-typedefs.ts
I get a ton of warnings like this due to using a lot of graphql interfaces. This warning doesn't apply here because we don't deal with resolvers. This patch turns it off.
```
Type "Node" is missing a "resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
```
=> suppress warnings from apollo-tools when making schema from typedefs

packages/graphql-codegen-cli/src/loaders/documents/document-loader.ts, packages/graphql-codegen-cli/tests/load-documents-sources.spec.ts, packages/graphql-codegen-cli/tests/test-documents/invalid-directive.graphql
To support client-side only directives, such as `@client`.
=> ignore invalid directive error during validation

packages/graphql-codegen-cli/src/codegen.ts
This PR adds optional CLI flag `--shallow-error` useful for `watch` mode. 
At the moment codegen will terminate the watch process if the error will be found on schema validation and the developer needs to restart watcher if he made a mistake in the schema or some query/mutation.
With `--shallow-error` flag process will output the error but also, will keep watcher alive giving an ability to fix a mistake without restarting the process.
=> Added CLI flag to shallow error on schema validation

packages/graphql-codegen-cli/src/utils/watcher.ts
Running `gql-gen -w` would result in the following crash.
```
error: graphql_codegen_core_1.getLogger(...).warning is not a function
```
This issue is from this line: 
https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-cli/src/utils/watcher.ts#L36
The warning I was getting was an Access denied error, which won't happen for everyone, which might be why this is kinda a hard issue to find. Simple fix though!
=> Fix getLogger(...).warning is not a function

README.md, dev-test/generate-all.sh, dev-test/githunt/graphql-declared-modules.d.ts, packages/graphql-codegen-cli/src/codegen.ts, packages/graphql-codegen-cli/src/loaders/documents/document-loader.ts, packages/graphql-codegen-cli/src/loaders/documents/validate-documents.ts, packages/graphql-codegen-cli/tests/load-documents-sources.spec.ts, packages/graphql-codegen-compiler/src/build-files-array.ts, packages/graphql-codegen-compiler/src/compile.ts, packages/graphql-codegen-compiler/src/generate-multiple-files.ts, packages/graphql-codegen-compiler/src/generate-single-file.ts, packages/graphql-codegen-core/src/index.ts, packages/graphql-codegen-core/src/operations/transform-document.ts, packages/graphql-codegen-core/src/schema/transform-fields.ts, packages/graphql-codegen-core/src/types.ts, packages/graphql-codegen-core/tests/transform-document.spec.ts, packages/scripts/codegen-templates-scripts/cli/codegen-templates-scripts-init.js, packages/templates/graphql-files-typescript-modules/.gitignore, packages/templates/graphql-files-typescript-modules/.npmignore, packages/templates/graphql-files-typescript-modules/README.md, packages/templates/graphql-files-typescript-modules/package.json, packages/templates/graphql-files-typescript-modules/src/config.ts, packages/templates/graphql-files-typescript-modules/src/index.ts, packages/templates/graphql-files-typescript-modules/src/polyfills.d.ts, packages/templates/graphql-files-typescript-modules/src/template.handlebars, packages/templates/graphql-files-typescript-modules/tsconfig.json
The goal is to generate something like that:
Given a file `./src/my-query.graphql`, it will generate:
```
declare module './src/my-query.graphql' {
const doc: DocumentNode;
export default doc;
}
```
And support all use cases of [`graphql-tag/loader`](https://github.com/apollographql/graphql-tag#webpack-preprocessing-with-graphql-tagloader), to make sure that imports from `.graphql` files on client-side are strongly-typed now
Tasks:
=> [New Template] Generate `module` definition for `.graphql` files

packages/templates/apollo-angular/tests/components.spec.ts, packages/templates/typescript-react-apollo/src/components.handlebars, packages/templates/typescript-react-apollo/src/helpers/generate-fragments.ts, packages/templates/typescript-react-apollo/src/helpers/to-fragment-name.ts, packages/templates/typescript-react-apollo/tests/components.spec.ts
I used `FragmentDoc` suffix for fragments and left `Document` for other operations.
I don't think there's a person uses those fragments directly but if so this is a breaking change.
Fixes #702
=> Fix fragment/document conflict in React template

dev-test/test-schema/resolvers-types.ts, packages/templates/typescript-resolvers/src/config.ts, packages/templates/typescript-resolvers/src/helpers/parent-type.ts, packages/templates/typescript-resolvers/src/resolver.handlebars, packages/templates/typescript-resolvers/tests/resolvers.spec.ts
Uses `never` on root types
Otherwise uses parent's type as default
=> resolvers: generic type for parent

packages/templates/typescript-mongodb/package.json, packages/templates/typescript-mongodb/src/helpers/entity-fields.ts, packages/templates/typescript-resolvers/package.json, packages/templates/typescript-resolvers/src/after-schema.handlebars, packages/templates/typescript-resolvers/src/before-schema.handlebars, packages/templates/typescript-resolvers/src/config.ts, packages/templates/typescript-resolvers/src/helpers/field-type.ts, packages/templates/typescript-resolvers/src/helpers/import-mappers.ts, packages/templates/typescript-resolvers/src/helpers/mappers.ts, packages/templates/typescript-resolvers/src/helpers/parent-type.ts, packages/templates/typescript-resolvers/src/resolver.handlebars, packages/templates/typescript-resolvers/tests/resolvers.spec.ts, packages/templates/typescript/src/helpers/get-type.ts, packages/templates/typescript/src/index.ts, packages/templates/typescript/src/utils/get-result-type.ts
```js
{
mappers: {
User: './interfaces#UserParent',
Post: 'string' // or even 'Post'
}
}
```
I think tests show exactly what we want to achieve.
=> Mappers (in typescript-resolvers template)

packages/graphql-codegen-cli/src/utils/prettier.ts
It was a little surprising when my team started experimenting with prettier and our generated typefiles changed. It would be nice to have some way to disable prettier, and rather than add another config option, I thought we could just use the existing `.prettierignore` file that prettier CLI supports.
This assumes that `.prettierignore` is in the current directory when executing gql-gen, but that's the same behavior as the prettier CLI, so it seemed OK to me.
I adapted this from Gitlab: https://gitlab.com/gitlab-org/gitlab-ce/blob/master/scripts/frontend/prettier.js#L90
=> Obey .prettierignore file

dev-test/test-schema/resolvers-types.ts, packages/templates/typescript-resolvers/README.md, packages/templates/typescript-resolvers/src/before-schema.handlebars, packages/templates/typescript-resolvers/tests/resolvers.spec.ts
Explicitly to match this use:
https://github.com/graphql-boilerplates/typescript-graphql-server/blob/master/advanced/src/resolvers/Subscription.ts#L6
which is here defined to return a promise:
https://github.com/graphql-boilerplates/typescript-graphql-server/blob/master/advanced/src/generated/prisma.ts#L32
=> Allow subscription resolver to return a promise

packages/templates/INPUT_TYPE_PROJECT.md
Links to `codegen-templates-scripts` were incorrectly `handlebars-templates-scripts`.
Also, a link to an external repo was pointing to a file that has since been deleted.
=> Fix documentation links

packages/plugins/typescript-resolvers/src/context.ts, packages/plugins/typescript-resolvers/src/index.ts, packages/plugins/typescript-resolvers/src/mappers.ts, packages/plugins/typescript-resolvers/src/parent-type.ts, packages/plugins/typescript-resolvers/src/resolver.handlebars, packages/plugins/typescript-resolvers/src/root.handlebars, packages/plugins/typescript-resolvers/tests/typescript-resolvers.spec.ts, yarn.lock
`never` is hard to work with when you mock things...
`{}` as default context makes sense because with `any` we won't get any ts warnings, it's more strict (breaking).
`{}` for empty arguments also makes sense since GraphQL provides an empty object when there's no arguments.
=> V2: importable context type. {} as default context and also instead of every `never`

packages/plugins/typescript-server/src/root.handlebars, packages/plugins/typescript-server/tests/typescript-server.spec.ts
When using the interfacePrefix config option along with graphql unions, the generated code is not valid typescript that looks like:
```typescript
export interface GqlQuery {
getSomething: GqlMyUnion;
}
export type MyUnion = OneType | AnotherType;
```
=> Add interface prefix to unions type definitions

packages/graphql-codegen-cli/src/loaders/documents/documents-from-glob.ts, packages/graphql-codegen-cli/src/utils/document-finder.ts, packages/graphql-codegen-cli/tests/codegen.spec.ts, packages/graphql-codegen-cli/tests/document-finder.spec.ts, packages/graphql-codegen-cli/tests/test-documents/ts-features-with-query.ts
Because loading documents fails on some typescript features if we use `gqlPluck.fromCodeString`
After https://github.com/DAB0mB/graphql-tag-pluck/pull/8 gets fixed we can switch back to use code as a string.
=> Make graphqlTagPluck to extract documents from files

packages/plugins/flow/src/variables-to-object.ts, packages/plugins/flow/src/visitor.ts, packages/plugins/flow/tests/flow.spec.ts
**The problem:**
Transforming the snippet below with the `typesPrefix` flag generates wrong flow type for the `input` type. Notice how the `TMutationFooArgs.input` is referencing `Input` instead of `TInput`.
```GraphQL
input Input {
name: String
}
type Mutation {
foo(id: String, input: Input): String
}
```
```js
export type TInput = {
name: ?string,
};
export type TMutation = {
foo: ?string,
};
export type TMutationFooArgs = {
id?: ?string,
input?: ?Input
};
```
This PR fixes this bug by using the `_convertName` function in `OperationVariablesToObject`.
I have also added a test to cover this bug.
=> Fix mutation arguments transforms in flow plugin

packages/plugins/flow-resolvers/src/visitor.ts, packages/plugins/flow-resolvers/tests/flow-resolvers.spec.ts, packages/plugins/flow/src/visitor.ts
The visitors in flow-resovlers plugin weren't implementing the `convertName` method of the `BasicFlowVisitor` interface. Fixed that.
There was also a bug in `OperationVariablesToObject`:
When `typeof variable.type === 'string'` `variable.type` won't match the proper key from `DEFAULT_SCALARS` (it would be `string` instead of `String` or `number` instead of `Int`).
This happened only on directives parsing, in all other cases `typeof variable.type === 'object'`.
Fixed this by adding "mapped" default scalars `string, number, boolean` to `DEFAULT_SCALARS`.
This fixes the currently (master at https://github.com/dotansimha/graphql-code-generator/commit/7e3df340ff525f91e49d7ae349f0f1c982791b7f) broken tests in `flow-resolvers`. All tests in the monorepo should be green after merging.
=> Fix directive arguments transforms in flow-resolvers plugin

packages/graphql-codegen-cli/src/load.ts, packages/graphql-codegen-cli/src/loaders/schema/schema-from-string.ts, packages/graphql-codegen-cli/tests/schema-from-string.spec.ts
`isValidPath` says that pretty much any string is a valid path... So I decided to check whether it's a glob path or has an alphanumeric extension.
=> Make sure it can load a schema as a string

packages/plugins/flow-resolvers/src/index.ts, packages/plugins/flow-resolvers/src/visitor.ts, packages/plugins/flow-resolvers/tests/flow-resolvers.spec.ts
=> Flow plugin improvements  

packages/plugins/flow-resolvers/src/index.ts, packages/plugins/flow-resolvers/tests/flow-resolvers.spec.ts
Both `GraphQLResolveInfo` and `GraphQLScalarTypeConfig` are types in `graphql` package flow import and should be imported via `import { type ... }` or flow lints will complain.
This pull request fixes this behaviour. I've intentionally put `type` specificator to both of them, in case we will need import some real entry from `graphql` package once.
=> [Flow Resolvers] fix type imports

packages/plugins/flow/src/visitor.ts, packages/plugins/flow/tests/flow.spec.ts
As @adelsz mentioned in #1142 it is [normal behavior](https://facebook.github.io/graphql/June2018/#sec-Null-Value) not to provide value at all for field value. This update brings generated types in sync with specification allowing both "missing" value and specifying null
=> Allow non-null fields to be missing for types (see #1142)

packages/plugins/typescript-resolvers/src/import-mappers.ts, packages/plugins/typescript-resolvers/tests/typescript-resolvers.spec.ts
Apologies if the tests fail, I couldn't get them passing locally.
This fixes an issue with mappers using nested data. E.g. in my application I want to use `Team#Team.Model` because I have an `index.ts` that does `import * as Team from './team'; export { Team }`.
=> Import variable from mapper, not entire identifier

docs/plugins/typescript-resolvers.md, packages/plugins/typescript-resolvers/src/helpers.ts, packages/plugins/typescript-resolvers/src/index.ts, packages/plugins/typescript-resolvers/tests/typescript-resolvers.spec.ts
With this PR, i propose a `fieldResolverNamePrefix` option for `typescript-resolvers` plugin, in order to avoid potential conflicts in name generation while using `noNamespace` option too.
I hope this implementation meets your code style & architecture, feel free to tell me if not.
See #1064 for use case.
I've added test & docs, however i'm not sure how to test it locally in my project. If you could suggest me how to link properly my modified version to my existing `package.json` (should I use `yarn link`? or maybe point `graphql-codegen-typescript-resolvers` to my github repo?) I'd be glad to test it more.
=> [typescript-resolvers] Add Field Resolver name prefix

docs/plugins/typescript-common.md, packages/plugins/typescript-common/src/enum.handlebars, packages/plugins/typescript-common/src/helpers.ts, packages/plugins/typescript-common/src/index.ts, packages/plugins/typescript-common/tests/typescript-common.spec.ts
After logging #1134 I realized that it would be very useful to me to import existing enums in my codebase instead of generating new ones with custom, but similar values.  (See #678 for some problems with that approach.)
This PR allows specifying a string like `path/to/enums#MyCustomEnum` as the value for an enum definition in the config, which will then import the enum instead of generating another.  In order to still map to internal values (with Apollo or otherwise) a `AValueMap` type is also generated which assists in doing so.
```graphql
enum A {
ONE
TWO
}
```
```yaml
generates:
path/to/generated.ts:
plugins:
- typescript-common
config:
enums:
A: path/to/enums#MyCustomEnum
```
```ts
// path/to/generated.ts
import { MyCustomEnum as A } from "path/to/enums";
export type AValueMap = { …
```
=> Support for reusing (importing) enums

packages/plugins/typescript-resolvers/src/index.ts, packages/plugins/typescript-resolvers/src/resolver.handlebars, packages/plugins/typescript-resolvers/src/root.handlebars, packages/plugins/typescript-resolvers/tests/typescript-resolvers.spec.ts
I want my resolvers to be type-safe, this will make it a little extra work to write them out completely but at least it won't fail at runtime. FWIW, I have a way that would work to automatically reduce the types when the property is of the correct type for GraphQL to automatically use as a resolver (example below, could be tidied up and easily generated based on the import).
```ts
interface Bar {
test: string
another: number
}
interface Foo <T> {
test: T extends Record<'test', string>
? never
: () => string
}
export type KnownKeys<T> = ({ [K in keyof T]-?: T[K] extends never ? never : K })[keyof T];
export type Strip<T> = Pick<T, KnownKeys<T>>;
const foo: Strip<Foo<Bar>> = {}
```
Edit: What is the existing reasoning for having all the properties be optional?
Edit 2: Working in the …
=> Support `strict` code output

packages/plugins/typescript-common/src/enum.handlebars, packages/plugins/typescript-common/tests/typescript-common.spec.ts, packages/plugins/typescript-resolvers/tests/typescript-resolvers.spec.ts
Related: #1193 
Given:
```graphql
enum CIState { ... }
```
Output:
```ts
// types.ts
export enum CiState {
NONE = "NONE",
IN_DEVELOPMENT = "IN_DEVELOPMENT",
IN_USE = "IN_USE",
IN_REMOVAL = "IN_REMOVAL",
REMOVED = "REMOVED"
}
export type Desired = {
// ...
state: Maybe<CiState>;
};
```
=> Enum names should match

packages/plugins/typescript-resolvers/src/root.handlebars
the resolve-type template does not produce a generic interface, so applying a generic to these in #1130 causes a compile error
https://github.com/dotansimha/graphql-code-generator/blob/498958e7a0ad3fc3b8f863db667dc0d5e2bdc73a/packages/plugins/typescript-resolvers/src/resolve-type.handlebars#L5-L7
=> [typescript-resolvers] do not apply generic to interfaces and unions

packages/plugins/typescript-client/tests/typescript-client.spec.ts, packages/plugins/typescript-common/src/helpers.ts, packages/plugins/typescript-common/tests/typescript-common.spec.ts
=> fix: same behaviour when generating nullable types with/without noNamespaces

packages/plugins/typescript-resolvers/src/helpers.ts, packages/plugins/typescript-resolvers/src/resolve-type.handlebars, packages/plugins/typescript-resolvers/src/resolver.handlebars, packages/plugins/typescript-resolvers/src/root.handlebars, packages/plugins/typescript-resolvers/tests/typescript-resolvers.spec.ts
Hi, this Pr just rename `Context` to `TContext` so that way if we want to specify our custom context, we can still name it `Context` instead of `MyContext`
=> Rename Context to TContext

packages/plugins/typescript-resolvers/src/import-mappers.ts, packages/plugins/typescript-resolvers/src/root.handlebars, packages/plugins/typescript-resolvers/tests/typescript-resolvers.spec.ts
Currently the mappers does not generate import statement for interfaces. This PR fixes it.
For example take a look at added test case.
The interfaces are good if you want to extend some other interface and use it as Type...
=> Add import for interfaces mappings

packages/plugins/flow-documents/package.json, packages/plugins/flow-documents/src/index.ts, packages/plugins/flow-documents/src/selection-set-to-object.ts, packages/plugins/flow-documents/src/visitor.ts, packages/plugins/flow-documents/tests/flow-documents.spec.ts, packages/plugins/flow-resolvers/src/index.ts, packages/plugins/flow-resolvers/src/visitor.ts, packages/plugins/flow/src/index.ts, packages/plugins/flow/src/utils.ts, packages/plugins/flow/src/visitor.ts, packages/plugins/flow/tests/flow.spec.ts
we've missed 2 flow features https://flow.org/en/docs/types/objects/#toc-exact-object-types and https://flow.org/en/docs/types/utilities/#toc-readonly. this PR adds the support of both based on new `config` settings called `useFlowExctObjects` and `useFlowReadOnlyTypes`.
extend your `codegen.yml`:
```
generates:
<path to your output file>:
plugins:
- flow
config:
useFlowExactObjects: true
useFlowReadOnlyTypes: true
```
instead of:
```
interface MyInterface {
foo: String
bar: String!
}
```
you'll get:
```
interface MyInterface {|
foo: String
bar: String!
|}
```
instead of:
```
interface MyInterface {
foo: String
bar: String!
}
```
you'll get:
```
interface MyInterface {
+foo: String
+bar: String!
}
```
instead of:
```
export type CurrentUserQuery = { me: ?($Pick<User, { id: * }> & …
```
=> Add flow output options for exact objects and read only types

docs/plugins/typescript-react-apollo.md, packages/plugins/typescript-react-apollo/src/helpers.ts, packages/plugins/typescript-react-apollo/src/index.ts, packages/plugins/typescript-react-apollo/src/root.handlebars, packages/plugins/typescript-react-apollo/tests/react-apollo.spec.ts
Since `useSubscription` is [merged and released](https://github.com/trojanowski/react-apollo-hooks/pull/37), there is no need for a specific import.
It's also for consideration if `withSubscriptionHooks` is necessary. I don't feel that Subscriptions needs any special treatment really.
=> Remove subscription hook import

docs/plugins/flow.md
this is a follow up of https://github.com/dotansimha/graphql-code-generator/pull/1317 and just adding missing documentation. just let me know if i have to update anything else.
=> updated docs after adding `useFlowExactObject` and `useFlowReadOnlyTypes`

packages/plugins/typescript-resolvers/src/root.handlebars, packages/plugins/typescript-resolvers/tests/typescript-resolvers.spec.ts
=> Add index signature to IResolvers and IDirectiveResolvers

dev-test/githunt/types.noNamespaces.ts, dev-test/githunt/types.reactApollo.noNamespaces.tsx, dev-test/githunt/types.reactApollo.tsx, dev-test/test-message/types.reactApollo.noNamespaces.tsx, dev-test/test-message/types.stencilApollo.noNamespaces.tsx, dev-test/test-mongodb/types.ts, dev-test/test-schema/resolvers-root.ts, dev-test/test-schema/resolvers-types.ts, dev-test/test-schema/typings.ts, packages/plugins/typescript-client/tests/typescript-client.spec.ts, packages/utils/plugins-helpers/src/flatten-types.ts
=> Duplicated type when fields are named the same as operation types

packages/graphql-codegen-core/src/operations/build-selection-set.ts, packages/graphql-codegen-core/src/utils/get-field-def.ts, packages/plugins/typescript-client/src/root.handlebars, packages/plugins/typescript-client/tests/typescript-client.spec.ts
Fixesss (@dotansimha ~~related~~) https://github.com/dotansimha/graphql-code-generator/issues/643#issuecomment-428464025 and https://github.com/dotansimha/graphql-code-generator/issues/643#issue-363140248
=> typescript-client: Include __typename in fragments and metadata fields

dev-test/test-schema/resolvers-root.ts, packages/plugins/typescript-resolvers/src/root.handlebars, packages/plugins/typescript-resolvers/tests/typescript-resolvers.spec.ts
- Make `IResolvers` and `IDirectiveResolvers` are extendable with generic resolvers instead of restricting new resolvers by `never`.
=> Fix IResolvers index signature

packages/plugins/flow/src/utils.ts, packages/plugins/flow/tests/flow.spec.ts
just fixing a bug which occurred after introducing `useFlowReadOnlyTypes` on handling Enums.
```
export const MyEnumValues = Object.freeze({
+A: 'A',
+B: 'B',
+C: 'C'
});
```
```
export const MyEnumValues = Object.freeze({
A: 'A',
B: 'B',
C: 'C'
});
```
=> FIX: fixed bug with useFlowReadOnlyTypes on Enums

docs/getting-started/development-workflow.md
=> Fix typo in docs (Getting Started / Development Workflow)

dev-test/test-schema/resolvers-root.ts, dev-test/test-schema/resolvers-types.ts, dev-test/test-schema/typings.ts, packages/plugins/typescript-resolvers/src/index.ts
Make sure we use prefixed generic types in there so they won't colide with types imported by user.
Related #1393
=> Support schema stitching in typescript-resolvers

docs/custom-codegen/using-handlebars.md
Handlebars npm package is called `handlebars` not `Handlebars`
=> Fix docs / update using-handlebars.md

packages/plugins/fragment-matcher/package.json
Use commonjs build for `main`, es build for `module`
Fixes #1502
=> Fix `main` field in fragment-matcher package.json

packages/graphql-codegen-cli/src/init/questions.ts
We didn't validate the answer so even an empty answer was allowed
=> Make sure user selects a target in init command

docs/migration/from-0-18.md
When I tried to follow the instructions in the migration guide, I saw the following errors:
```
Couldn't find any versions for "@graphql-codegen/typescript" that matches "0.18.0"
? Please choose a version of "@graphql-codegen/typescript" from this list: 1.0.2
Couldn't find any versions for "@graphql-codegen/typescript-operations" that matches "0.18.0"
? Please choose a version of "@graphql-codegen/typescript-operations" from this list: 1.0.2
```
Thank you for creating such a great tool!
=> Switch plugins to 1.0.0 versions

packages/plugins/typescript-react-apollo/src/visitor.ts, packages/plugins/visitor-plugin-common/src/client-side-base-visitor.ts
Definitions like Document, HOC, hooks, and Component shouldn't have
typesPrefix added to their generated names.
Related #1550
=> Removes typesPrefix from non-type definitions

docs/getting-started/programmatic-usage.md
- convert schema to `DocumentNode` as required by `codegen`
- I also noticed that the `typescript` plugin also currently does not use the `outputFile` option to write the output to the file system.
=> Update programatic usage in docs

packages/plugins/typescript-react-apollo/tests/react-apollo.spec.ts, packages/plugins/typescript/tests/typescript.spec.ts, packages/plugins/visitor-plugin-common/src/base-types-visitor.ts, packages/plugins/visitor-plugin-common/src/client-side-base-visitor.ts
This is in addition to #1551, and removes the configured typesPrefix from Enum values.
e.g. Instead of having `IColors.IRED`, it would be `IColors.RED`
=> Remove typesPrefix from Enum values

packages/plugins/typescript-resolvers/tests/ts-resolvers.spec.ts, packages/plugins/visitor-plugin-common/src/base-resolvers-visitor.ts
```patch
-__resolveType: TypeResolveFn<'CccFoo' | 'CccBar', ParentType, Context>
+__resolveType: TypeResolveFn<'CCCFoo' | 'CCCBar', ParentType, Context>
```
=> Should not convert type names in unions

packages/utils/config-md-generator/src/index.ts
This fixes generated markdown docs
=> Include warning in tag definitions

docs/plugins/typescript.md
The `add` was missing in the yarn installation command making it invalid.
=> [docs] Add missing `add` in yarn command

packages/plugins/flow-resolvers/src/index.ts, packages/plugins/flow-resolvers/src/visitor.ts, packages/plugins/flow-resolvers/tests/flow-resolvers.spec.ts, packages/plugins/flow-resolvers/tests/mapping.spec.ts, packages/plugins/typescript-resolvers/src/index.ts, packages/plugins/typescript-resolvers/tests/common.ts, packages/plugins/typescript-resolvers/tests/mapping.spec.ts, packages/plugins/typescript-resolvers/tests/ts-resolvers.spec.ts, packages/plugins/typescript/tests/validate.ts, packages/plugins/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/visitor-plugin-common/src/utils.ts
This PR will resolve the following issues related to resolvers packages:
=> Improve Resolvers plugins

docs/getting-started/programmatic-usage.md
Just a typo in the last code snippet
=> Fix typo in programmatic-usage.md

packages/plugins/typescript-react-apollo/src/index.ts
I noticed a typo when reading [the documentation of typescript-react-apollo](https://graphql-code-generator.com/docs/plugins/typescript-react-apollo).
=> Fix typo in @example comment

packages/plugins/typescript-resolvers/tests/ts-resolvers.spec.ts, packages/plugins/visitor-plugin-common/src/base-resolvers-visitor.ts
Before this change, the generated code would have included:
```
__resolveType: TypeResolveFn<, ParentType, Context>
```
which would fail to parse due to the missing type parameter
=> Gracefully handle an interface with no known implementors

packages/plugins/flow-resolvers/src/index.ts
The reason for that is that most Flow users will want to use the verbose version of array notation, according to https://github.com/gajus/eslint-plugin-flowtype/blob/master/.README/rules/array-style-simple-type.md
This change will also keep consistency with other plugins (i.e. `flow`) which generate `?Array<sometype>` (cf. https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/flow/src/flow-variables-to-object.ts#L25)
=> Set SubscriptionResolver type to full array type.

packages/plugins/visitor-plugin-common/src/base-resolvers-visitor.ts
This PR makes sure that the omit logic is not applied when a mapper is specified for a graphql interface.
related #1670
P.s. is it possible to run the tests for a single package, instead of the whole suite? Preferably also without having to run `yarn build`.
=> do not apply omit to interface when mapper is configured

packages/plugins/flow-resolvers/tests/mapping.spec.ts, packages/plugins/typescript-resolvers/tests/mapping.spec.ts, packages/plugins/visitor-plugin-common/src/base-resolvers-visitor.ts
=> Allow to use {T} in mappers

dev-test/test-schema/resolvers-root.ts, dev-test/test-schema/resolvers-types.ts, dev-test/test-schema/typings.ts, docs/plugins/typescript-resolvers.md, packages/plugins/flow-resolvers/tests/flow-resolvers.spec.ts, packages/plugins/flow-resolvers/tests/mapping.spec.ts, packages/plugins/typescript-resolvers/tests/mapping.spec.ts, packages/plugins/typescript-resolvers/tests/ts-resolvers.spec.ts, packages/plugins/visitor-plugin-common/src/base-resolvers-visitor.ts
when having a context interface name `Context`, it didn't work because the generic parameter was referring to itself. By naming it `ContextType` it's less common, and thus the change of having clash is smaller.
fixes #1681
=> change generic parameter name of context type to prevent clash

packages/plugins/flow-resolvers/src/index.ts, packages/plugins/flow-resolvers/tests/__snapshots__/flow-resolvers.spec.ts.snap, packages/plugins/flow-resolvers/tests/flow-resolvers.spec.ts
Fixes https://github.com/dotansimha/graphql-code-generator/issues/1725.
- As discussed, the resolvers arguments shouldn't be optional. 
- There was also no test coverage for these type definitions so I added a snapshot test which covers them as well as the existing "string comparison" tests (removed since they were made obsolete by the snapshot test).
=> fix(flow-resolvers): non optional arguments in resolvers

docs/getting-started/index.md
https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-cli/src/generate-and-save.ts#L11
This exported method must have been moved from core to cli without updating the docs?
=> docs(getting-started): import generate from cli not core

docs/getting-started/index.md
The docs referenced a method from the incorrect package. `generate` is available in `@graphql-codegen/cli` and `codegen` is available in `@graphql-codegen/core`. From the usage in the code that followed, it seems `generate` is the intended method.
=> Update import statement in getting-started docs

packages/plugins/other/visitor-plugin-common/src/base-visitor.ts, packages/plugins/other/visitor-plugin-common/src/naming.ts, packages/plugins/other/visitor-plugin-common/src/types.ts, packages/plugins/other/visitor-plugin-common/tests/plugins-common.spec.ts
Added the field transformUnderscore to the namingConvention object to make it possible to override the default behavior to preserve Underscores. Without this it is not possible to fully customize the naming convention for the generated types, only the individual parts between underscores.
I was not sure if this is the best place for the configuration. Let me know if I should change it.
=> Added transformUnderscore configuration to namingConvention

packages/plugins/typescript/react-apollo/src/index.ts, packages/plugins/typescript/react-apollo/src/visitor.ts, packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
Small fix in docs. Also update to import ReactApollo when `withMutationFn` is enabled but ReactApollo features are disabled.
=> Docs fix and import React Apollo when withMutationFn is configured

packages/graphql-codegen-cli/src/generate-and-save.ts
This PR addresses issue: https://github.com/dotansimha/graphql-code-generator/issues/1806.
Following the recommendations from, this PR removes the use of the `NODE_TLS_REJECT_UNAUTHORIZED` environment variable: https://nodejs.org/api/cli.html#cli_node_tls_reject_unauthorized_value
> If value equals '0', certificate validation is disabled for TLS connections. This makes TLS, and HTTPS by extension, insecure. *The use of this environment variable is strongly discouraged.*
=> Remove use of NODE_TLS_REJECT_UNAUTHORIZED env var.

packages/plugins/typescript/urql/.gitignore, packages/plugins/typescript/urql/.npmignore, packages/plugins/typescript/urql/package.json, packages/plugins/typescript/urql/src/index.ts, packages/plugins/typescript/urql/src/visitor.ts, packages/plugins/typescript/urql/tests/urql.spec.ts, packages/plugins/typescript/urql/tsconfig.json
I mainly just copied the react-apollo plugin and rewrote the generated code to use the urql API, which differs from the `react-apollo` and `react-apollo-hooks` a bit.
Closes #1575
=> Urql support

docs/plugins/add.md
clarify the importance of order of plugins In the add plugin docs
=> docs: clarify the importance of order of plugins

packages/plugins/typescript/react-apollo/src/index.ts, packages/plugins/typescript/react-apollo/src/visitor.ts, packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
This PR addresses the following issue: #1834 
The default suffix is `Component`. It should be possible to specify the desired suffix (string) via `customSuffix` property in plugin config in `codegen.yml`.
I only made changes to the `typescript-react-apollo` plugin.
=> Make suffix of generated React Apollo components customizable

packages/plugins/typescript/urql/src/visitor.ts, packages/plugins/typescript/urql/tests/urql.spec.ts
These would throw an error saying "Required field `query` not provided".  Need to omit that.
=> Fix urql typescript types

packages/plugins/typescript/graphql-files-modules/src/index.ts, packages/plugins/typescript/graphql-files-modules/tests/graphql-files-modules.spec.ts
This change would allow specifying a `customModulePathPrefix` when using the `typescript-graphql-files-modules` plugin to generate typings for GraphQL files.
Consider the following project structure:
```
/src
/api
/user-service
queries.graphql
mutations.graphql
schema.graphql
fragments.graphql
/message-service
queries.graphql
mutations.graphql
schema.graphql
fragments.graphql
index.ts
codegen.yml
```
Currently all files generated using the plugin have the following format. The generic module definition glob makes type discovery with intellisense difficult.
```typescript
module "*/FILE_NAME.graphql" { ... }
```
With the changes in place, using the following config would allow for a more specific module definition path.
```yaml
generates: ./src/api/user-service/queries.d.ts
schema: …
```
=> Allow specifying customModulePathPrefix with typescript-graphql-files-modules plugin

packages/presets/near-operation-file/src/index.ts, packages/presets/near-operation-file/src/utils.ts, packages/presets/near-operation-file/tests/near-operation-file.spec.ts
Fixes #1892 (backslashes being used in generated imports on Windows) and also problem with a nested file import where the import would be missing slash after "current directory" dot (`.nested/types` instead of `./nested/types`).
I've used a regex to replace backslashes with slashes. Let me know if you want me to use a library like https://www.npmjs.com/package/normalize-path or https://www.npmjs.com/package/slash instead.
=> Fix relative imports generation in `near-operation-file` preset

docs/plugins/add.md, packages/plugins/other/add/src/index.ts
Add functionality to add plugin so that it is possible to select which output section the text should end up in.
This supports such use cases such as wrapping the output in a namespace, etc.
=> Update add plugin with output section selection

packages/plugins/typescript/react-apollo/src/visitor.ts
Implements the solution as suggested by @dotansimha in https://github.com/dotansimha/graphql-code-generator/issues/1863#issuecomment-496586940
It checks whether `hooksImportFrom` is set to `@apollo/react-hooks`, if so, it outputs the signature that `@apollo/react-hooks` expects, otherwise it defaults to the signature that is compatible with `react-apollo-hooks`.
One quick thing to mention, I tested this change rather quickly by manually editing the visitor in my node_modules, let me know if somethings not right!
=> Fix QueryHookOptions for @apollo/react-hooks

website/live-demo/package.json
I think this should fix https://github.com/dotansimha/graphql-code-generator/issues/1959
Just based on the fact that when I tried to run this package locally, it wouldn't run without this dependency
=> Update the live demo to include the missing stencil apollo dependency

packages/plugins/typescript/operations/src/ts-operation-variables-to-object.ts, packages/plugins/typescript/operations/tests/ts-documents.spec.ts, packages/plugins/typescript/typescript/src/typescript-variables-to-object.ts, packages/plugins/typescript/typescript/tests/typescript.spec.ts
Related #1934
`typescript-operations` generates false types for operation variables width default values.
Example:
```graphql
query foo($var: String = "test") {
foo(var: $var)
}
```
**Generated Types:**
```typescript
export type FooQueryVariables = {
var: Maybe<Scalars['String']>
};
```
**Expected Types:**
```diff
export type FooQueryVariables = {
-  var: Maybe<Scalars['String']>
+  var?: Maybe<Scalars['String']>
};
```
More details can be found in https://github.com/dotansimha/graphql-code-generator/issues/1934
=> fix(typescript-operations): wrong type for variable with default value ( #1934)

docs/custom-codegen/write-your-plugin.md
In the description just above you state that documents is an array of type `{ filePath: string, content: DocumentNode }` but then in the subsequent example `definitions` is accessed directly instead of first via `content`.
=> Incorrect example in write-your-plugin

packages/graphql-codegen-cli/src/codegen.ts
When using `near-operation-file` where the configuration doesn't point to a file, prettier was invoked incorrectly
For example, with this:
```yml
./packages/app/src:
preset: near-operation-file
```
The filename passed to prettier was `./packages/app/src` and not the actual generated file name
=> Use the proper output filename when invoking prettier

packages/graphql-codegen-cli/src/utils/watcher.ts
This is a fairly naive attempt at fixing watch mode while using a preset.
The problem stems from the key of the configuration using the preset pointing to a folder, and in the end being ignored by chokidar.
The easy fix would be to just leave out any `generates` configuration that uses a prefix, but I've tried to make it do the right thing, by combining the key (assuming it's a path) with the configured extension (if one exists)
For config
```yml
some/folder:
preset: near-operation-file
presetConfig:
extension: .generated.tsx
```
You should end up with an ignore of `some/folder/**/*.generated.tsx`
Related #2069
=> Fix watch mode when using presets

packages/graphql-codegen-cli/src/codegen.ts, packages/graphql-codegen-core/src/codegen.ts, packages/graphql-codegen-core/src/execute-plugin.ts, packages/presets/near-operation-file/src/index.ts, packages/utils/plugins-helpers/src/types.ts
Each plugin being executed was generating an AST of the schema over and over again, which was especially painful when using `near-operations-file`.
With this change the AST is built early, and only rebuilt in situations where it isn't passed to the plugin for whatever reason, or a plugin changes the schema.
In my project it decreased execution time from 10s to 4s (250%)
Before
After
There's probably still more that could be done, but this takes care of the worst bits
Addresses the performance issues mentioned on #2069
=> Improve performance by not building schema AST over and over

packages/plugins/typescript/react-apollo/src/index.ts
property should be after comment to recognize correctly.
NO CHANGE FOR FUNCTIONALITY
=> Fix: incorrect comment position

packages/plugins/other/schema-ast/src/index.ts
By setting the comment descriptions to false, comments in the `.graphql` files will also be included in introspection after code generation.
Currently (with the default `true`), comments are not included in introspection.
=> Set comment descriptions to false by default

packages/plugins/other/visitor-plugin-common/src/utils.ts
Closes the same issue as https://github.com/dotansimha/graphql-code-generator/pull/1166 that's re-appeared in the refactor.
=> Strip all extraneous type import characters

packages/plugins/typescript/react-apollo/src/index.ts, packages/plugins/typescript/react-apollo/src/visitor.ts
"reactApolloVersion" to specify version
of "react-apollo", as exported type names
are changed @ v3
=> feat(typescript-react-apollo): new option `reactApolloVersion`

docs/getting-started/codegen-config.md, packages/graphql-codegen-cli/src/codegen.ts, packages/utils/plugins-helpers/src/types.ts
See https://github.com/dotansimha/graphql-code-generator/pull/2073#issuecomment-506531049
=> Add config option for disabling output formatting

packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts, packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/2080
=> Try to fix fragments with `noGraphQlTag`

dev-test/codegen.yml, dev-test/githunt/types.preResolveTypes.compatibility.ts, dev-test/githunt/types.preResolveTypes.ts, dev-test/githunt/types.reactApollo.preResolveTypes.tsx, dev-test/star-wars/types.preResolveTypes.ts, packages/plugins/flow/operations/src/flow-selection-set-to-object.ts, packages/plugins/flow/operations/src/visitor.ts, packages/plugins/other/visitor-plugin-common/src/base-documents-visitor.ts, packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts, packages/plugins/typescript/compatibility/src/index.ts, packages/plugins/typescript/compatibility/src/selection-set-to-types.ts, packages/plugins/typescript/compatibility/src/visitor.ts, packages/plugins/typescript/operations/src/ts-selection-set-to-object.ts, packages/plugins/typescript/operations/src/visitor.ts, packages/plugins/typescript/operations/tests/ts-documents.spec.ts, website/live-demo/src/examples.ts, website/live-demo/src/generate.ts
A solution for: https://github.com/dotansimha/graphql-code-generator/issues/1904 
It still requires `typescript` as a dependency, but now `typescript-operations` can use `preResolveTypes: true` in order to generate `field: string` instead of `field: Pick<BaseType, 'field'>`.
Required `typescript-compatibility` minor changes because of the needs to eliminate `Maybe` when building the intermediate types.
=> Try to pre-resolve types in order to avoid `Pick`

packages/plugins/typescript/typescript/tests/typescript.spec.ts
This adds a failing test for issue #1954 with a minimal reproduction of duplicate type names being generated. I tried fixing this, but am not sure where in the codebase the fix should go.
@dotansimha would you mind tackling this?
=> Add failing test for duplicate names

packages/graphql-codegen-cli/src/codegen.ts, packages/graphql-codegen-cli/src/utils/try-to-build-schema.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/2108
=> Allow codegen to skip schema building when it's not possible

docs/getting-started/programmatic-usage.md
Fix incorrect URL in the docs for programmatic usage example in the live demo source.
=> Update programmatic-usage.md: Fix incorrect URL

packages/plugins/flow/resolvers/src/flow-util-types.ts, packages/plugins/flow/resolvers/src/index.ts, packages/plugins/flow/resolvers/src/visitor.ts, packages/plugins/flow/resolvers/tests/flow-resolvers.spec.ts, packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/other/visitor-plugin-common/src/utils.ts, packages/plugins/typescript/resolvers/src/index.ts, packages/plugins/typescript/resolvers/src/visitor.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
When args field has default value, we generate by default the `Args` type with optional and `Maybe`, because `typescript-operations` uses it to set the variables/arguments - and if it has a default value - then it's fine that it's optional.
But, for `typescript-resolvers`, we need to override this behaviour because we would like to tell the backend developers that this field will have a value (because it has a default).
Related: https://github.com/dotansimha/graphql-code-generator/issues/2064
=> Fixes for resolvers plugins: override optional declaration of args types

packages/graphql-codegen-cli/src/utils/watcher.ts
The use of `import path from 'path'` was incorrectly compiled to commonjs as `path_1.default.join`
=> Fix import causing issues when compiled to commonjs

dev-test/githunt/types.reactApollo.hooks.tsx, packages/plugins/typescript/react-apollo/src/visitor.ts, packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
=> [typescript-react-apollo] Generate HookResult type

packages/presets/near-operation-file/src/utils.ts, packages/presets/near-operation-file/tests/near-operation-file.spec.ts
This is a suggestion to fix the issue mentioned in https://github.com/dotansimha/graphql-code-generator/issues/2069#issuecomment-509346480
When a query only contains a fragment spread:
```graphql
query {
user {
...UserFragment
}
}
```
as opposed to
```graphql
query {
user {
id
...UserFragment
}
}
```
The import of the main types file, i.e. `import * as Types from '../types'` was not included.
=> Fixes issue where base types file is not referenced

packages/presets/near-operation-file/src/index.ts, packages/presets/near-operation-file/tests/near-operation-file.spec.ts
Right now if you have multiple fragments with the same name, it will not fail, and you may end up with the wrong fragment being used.
Ideally I would prefer that it figured out using the correct fragment based on the imports in the source file, however that could be pretty complicated.
For now, this will at least prevent you from having duplicate fragment names.
=> Guard against duplicate fragment names in near-operations-file

packages/plugins/typescript/react-apollo/src/visitor.ts, packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
This PR addresses the following issue: #2160 
When custom operation result type name is specified by `operationResultSuffix` config option, React Apollo HOC props are generated with a wrong operation type name. This PR fixes the way HOC props are generated.
Expected example (with `operationResultSuffix` set to `Response`): 
```javascript
export type BooksProps<TChildProps = {}> = Partial<
ReactApollo.DataProps<BooksQueryResponse, BooksQueryVariables>
> &
TChildProps;
```
=> Fix HOC data props with custom type names

packages/plugins/typescript/urql/src/visitor.ts, packages/plugins/typescript/urql/tests/urql.spec.ts
First of all, thank you for making a great tool.
Here is simple patch for add variables type to useMutation hooks so to be specified type instead of `object`
```ts
export declare const useMutation: <T = any, V = object>(query: string | DocumentNode) => [UseMutationState<T>, (variables?: V | undefined) => Promise<OperationResult<T>>];
```
=> Add variables type parameter to Urql.useMutation hook

packages/plugins/typescript/react-apollo/src/index.ts, packages/plugins/typescript/react-apollo/src/visitor.ts, packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
This PR adds `withResultType` and `withMutationOptionsType` for the `typescript-react-apollo` plugin:
- `withResultType` option generates typed `QueryResult`, `MutationResult` and `SubscriptionResult` depending on the operation
- `withMutationOptionsType` option generates typed `MutationOptions` for mutations only
Related: https://github.com/dotansimha/graphql-code-generator/issues/2144
=> [typescript-react-apollo] Add withResultType and withMutationOptionsType options

packages/graphql-codegen-cli/src/utils/debugging.ts
I don't want to receive codegen logs, but when I set the value DEBUG to undefined it affects the whole project
=> process.env.DEBUG

docs/plugins/typescript-react-apollo.md, docs/plugins/typescript-stencil-apollo.md
This fixes a couple links to the typescript plugin page that currently result in a 404.
=> Fix links to @graphql-codegen/typescript

packages/plugins/typescript/typescript/src/visitor.ts, packages/plugins/typescript/typescript/tests/typescript.spec.ts
Related #2206.
It works but I'm not sure if the approach is correct. Maybe there should be `getEnumsExports` method in `BaseTypesVisitor` (to complement `getEnumsImports`)?
=> Fix external enums to be re-exported from the generated file

packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts
Currently, when calling `visit` with a visitor extending the `BaseTypesVisitor` in the `@graphql-codegen/visitor-plugin-common` package, the compiler throws a wobbly because the types do not match. Example:
```ts
import { visit } from 'graphql'
const visitorResult = visit(astNode, { leave: visitor })
```
If it matters, the full error at `{ leave: visitor }` is this:
```
Argument of type '{ leave: Visitor<PluginConfig, ParsedConfig>; }' is not assignable to parameter of type 'Visitor<ASTKindToNode, ASTNode>'.
Type '{ leave: Visitor<PluginConfig, ParsedConfig>; }' is not assignable to type 'EnterLeave<VisitFn<ASTNode, ASTNode> | { Name?: VisitFn<ASTNode, NameNode> | undefined; Document?: VisitFn<ASTNode, DocumentNode> | undefined; OperationDefinition?: VisitFn<ASTNode, …
```
=> Minor type changes for visitor-plugin-common

packages/graphql-codegen-core/src/codegen.ts, packages/presets/near-operation-file/src/index.ts, packages/presets/near-operation-file/tests/near-operation-file.spec.ts, packages/utils/plugins-helpers/src/types.ts
related: https://github.com/dotansimha/graphql-code-generator/issues/2143
=> allow duplicate operations when near-operation-file is used

dev-test/githunt/types.reactApollo.customSuffix.tsx, dev-test/githunt/types.reactApollo.hooks.tsx, dev-test/githunt/types.reactApollo.preResolveTypes.tsx, dev-test/githunt/types.reactApollo.tsx, packages/plugins/typescript/react-apollo/src/visitor.ts, packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
- Hardcoded true or false does not allow for variables of type boolean to be passed into the skip property. This resolves the type error for boolean variables used.
Resolves bug introduced from https://github.com/dotansimha/graphql-code-generator/pull/1926
=> Allow for skip to be a boolean type

packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts, packages/plugins/other/visitor-plugin-common/src/types.ts, packages/plugins/other/visitor-plugin-common/src/utils.ts, packages/plugins/typescript/type-graphql/.gitignore, packages/plugins/typescript/type-graphql/.npmignore, packages/plugins/typescript/type-graphql/package.json, packages/plugins/typescript/type-graphql/src/index.ts, packages/plugins/typescript/type-graphql/src/visitor.ts, packages/plugins/typescript/type-graphql/tests/type-graphql.spec.ts, packages/plugins/typescript/type-graphql/tsconfig.json, packages/plugins/typescript/typescript/src/index.ts, packages/plugins/typescript/typescript/src/visitor.ts
This is a plugin that generates type-graphql types, loosely based on the typescript plugin. See PR #2173 for more details.
=> Add typescript type graphql plugin

packages/plugins/flow/operations/tests/flow-documents.spec.ts, packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts, packages/plugins/typescript/compatibility/tests/compatibility.spec.ts, packages/plugins/typescript/operations/src/ts-selection-set-to-object.ts, packages/plugins/typescript/operations/tests/ts-documents.spec.ts
- Changes the tests for union/interfaces according to #2240 and #2200
- Fixes code generation
**TODO:**
=> fix(typescript/flow-operations): generate correct union/interface type definitions

packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts, packages/plugins/typescript/operations/tests/ts-documents.spec.ts
Follow up to #2248
```graphql
query field {
field {
... on Error {
__typename
message
}
... on ComplexError {
additionalInfo
}
... on FieldResultSuccess {
someValue
}
}
}
```
should generate
```ts
export type FieldQuery = (
{ __typename?: 'Query' }
& { field: (
{ __typename: 'Error1' }
& Pick<Error1, 'message'>
) | (
{ __typename: 'Error2' }
& Pick<Error2, 'message'>
) | (
{ __typename: 'ComplexError' }
& Pick<ComplexError, 'message' | 'additionalInfo'>
) | (
{ __typename?: 'FieldResultSuccess' }
& Pick<FieldResultSuccess, 'someValue'>
) }
);
```
=> fix(visitor-plugin-common): __typename field selection on union

packages/plugins/typescript/react-apollo/src/visitor.ts, packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
This PR adds support for importing document node from an external file for hooks i.e. `useQuery`, `useLazyQuery`, `useMutation`, `useSubscription`. 
The current implementation only works with `withComponent` config. As the result, hook document nodes are not used correctly. This can be seen here: https://codesandbox.io/s/gcg-15-experiments-c8l15 (Look for `src/GetProject.operation.generated.tsx`)
=> [typescript-react-apollo] Add support for importing document node from external file for hooks and HOCs

packages/plugins/typescript/react-apollo/src/visitor.ts, packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
Right now react hook's names are not being deduped even if the option `dedupeOperationSuffix` is enabled. This PR fixes it.
=> fix: properly dedupe react hooks names

docs/plugins/typescript-resolvers.md
Thanks for the awesome work on graphql-codegen!
Added just a short hint in the docs on how to use generated resolvers directly since I had to do some substantial digging to find that bit of information. If you don't find that useful or it's already in the docs and I just missed it then feel free to close the PR.
=> docs: hint how to use generated resolvers directly

packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts, packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
Normally, fragments are turned into document nodes so we can include them in the operations document nodes they are used in. In the case of `documentMode = 'external'`, the operation document nodes are created externally and imported into the generated files. Therefore, there's no need to print fragment variables in the generated file anymore
This problem can be seen in this sandbox: https://codesandbox.io/s/gcg-15-experiments-c8l15. There are fragments in `webpack/GetProject_Status.fragment.graphql` and `webpack/CreateProject.operation.graphql`, and these will be converted into variables with suffix `FragmentDoc` in generated files (Note that we are not even importing the `graphql-tag` module).
This PR ensures that no fragments are generated when `external` mode is used. 
NOTE: I'm …
=> [typescript-react-apollo] Fix problem with unnecessary fragment imports for external mode

packages/plugins/typescript/type-graphql/src/index.ts, packages/plugins/typescript/type-graphql/src/visitor.ts, packages/plugins/typescript/type-graphql/tests/type-graphql.spec.ts
I'm looking to generate interface type objects with type-graphql so that I can implement them while simultaneously extending another type
I just threw this together, it might not be the best way to achieve this though.
=> feat(type-graphql): allow overriding decorators

dev-test/codegen.yml, dev-test/githunt/__generated__/comment-added.subscription.stencil-component.tsx, dev-test/githunt/__generated__/comment.query.stencil-component.tsx, dev-test/githunt/__generated__/comments-page-comment.fragment.stencil-component.tsx, dev-test/githunt/__generated__/current-user.query.stencil-component.tsx, dev-test/githunt/__generated__/feed-entry.fragment.stencil-component.tsx, dev-test/githunt/__generated__/feed.query.stencil-component.tsx, dev-test/githunt/__generated__/new-entry.mutation.stencil-component.tsx, dev-test/githunt/__generated__/repo-info.fragment.stencil-component.tsx, dev-test/githunt/__generated__/submit-comment.mutation.stencil-component.tsx, dev-test/githunt/__generated__/vote-buttons.fragment.stencil-component.tsx, dev-test/githunt/__generated__/vote.mutation.stencil-component.tsx, packages/presets/near-operation-file/src/index.ts, packages/presets/near-operation-file/src/utils.ts, packages/presets/near-operation-file/tests/near-operation-file.spec.ts
I was wondering if there was a way we could create a `sub-folder` to save all our code-generated files instead of just appending them into the same folder, and I stumbled across #2287  issue / comment by @RIP21.
And since I had a bit of free time, I made a PR for it
- A added a new [optional option `folder`](https://github.com/dotansimha/graphql-code-generator/compare/master...fforres:fforres/near_operation_file?expand=1#diff-1736635a0ac8752e8ba3cc2ee5c3e5c2R65) to the `near-operation-file` config
- It sets a relative sub-folder where to save the files generated by the code-generator.
Once thing I didn't know how to (Or what does the project use them for) is the files under `dev-test`. 
I did modified the `./dev-test/githunt` option under `dev-test/codegen.yml` option to test the plugin …
=> Add sub-folder param to near-operation-file

packages/plugins/typescript/react-apollo/src/visitor.ts, packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
- The use of the same name for an HOC operation and its alias (i.e. `withCreateAppointment`) causes a shadowed variable problem when trying to call the alias function from props and requires an additional alias to be assigned under the `name` property of an operation like below:
```
export default withCreateAppointment({
name: 'createAppointment',
})(MyComponent);
```
- This PR changes HOC aliases to the camel-cased version of their operation name to make them usable as intended
=> Make GraphQL operation alias unique from HOC name

packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts, packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
Currently, in external mode, we are importing nodes even for files without operations i.e. files with just fragments. This behaviour can be seen here: https://codesandbox.io/s/gcg-16-experiments-c8l15 in `src/webpack/GetProject_Id.fragment.generated.tsx`
This PR adds a check to make sure we don't import operations unnecessarily
=> [typescript-react-apollo] Fix external mode to avoid importing operations in files that don't have operations

packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts, packages/plugins/typescript/type-graphql/src/visitor.ts, packages/plugins/typescript/type-graphql/tests/type-graphql.spec.ts
I have added support for TypeGraphQL `InputType`s and `ArgsType`s to the @graphql-codegen/typescript-type-graphql plugin, as requested in #2177.
=> Added support for TypeGraphQL Input- and ArgTypes

dev-test/githunt/types.reactApollo.hooks.tsx, packages/plugins/typescript/react-apollo/src/visitor.ts, packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
Related to #2133 & #2309  
As title, add missing result type for lazy query hooks
e.g. dev-test/githunt/types.reactApollo.hooks.tsx
```diff
export function useCommentQuery(baseOptions?: ApolloReactHooks.QueryHookOptions<CommentQuery, CommentQueryVariables>) {
return ApolloReactHooks.useQuery<CommentQuery, CommentQueryVariables>(CommentDocument, baseOptions);
}
export function useCommentLazyQuery(baseOptions?: ApolloReactHooks.LazyQueryHookOptions<CommentQuery, CommentQueryVariables>) {
return ApolloReactHooks.useLazyQuery<CommentQuery, CommentQueryVariables>(CommentDocument, baseOptions);
}
export type CommentQueryHookResult = ReturnType<typeof useCommentQuery>;
+ export type CommentLazyQueryHookResult = ReturnType<typeof useCommentLazyQuery>;
```
=> [typescript-react-apollo] Add missing lazy query hooks result type

docs/custom-codegen/write-your-plugin.md
This points the URL to DocumentNode and GraphQLSchema API to the correct URL. They moved the types to graphql-js repo.
I checked and didn't see if there's any guideline for prefixing commits or PR titles so I hope this works :D
=> update doc to use correct url for graphql.js types

packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts, packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
:wave: 
I have trouble when using graphql-codegen with CRA.
I tried to use `importDocumentNodeExternallyFrom: near-operation-file` with in-source-code documents becuase I don't wanna separate document file(`.graphql`) from component code.
in my config:
```yaml
documents:
- src/**/*.{ts,tsx}
- '!src/**/*.generated.{ts,tsx}'
generates
./src/generated/types.ts:
plugins:
- typescript
- typescript-resolvers
./src/:
preset: near-operation-file
presetConfig:
extension: .generated.tsx
baseTypesPath: generated/types.ts
plugins:
- typescript-operations
- typescript-react-apollo
config:
gqlImport: graphql.macro#gql
documentMode: external
importDocumentNodeExternallyFrom: near-operation-file
reactApolloVersion: 3
withComponent: false
withHOC: false
withHooks: true
```
But I got an error: `An import …
=> Fix importDocumentNodeExternallyFrom on CRA TypeScript

packages/plugins/flow/operations/tests/flow-documents.spec.ts, packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts, packages/plugins/typescript/operations/tests/ts-documents.spec.ts
This fixes the issue occurring in #2489
=> fix(visitor-plugin-common): also include empty selection set types/generate valid type output

packages/plugins/other/visitor-plugin-common/src/federation.ts, packages/plugins/typescript/resolvers/tests/federation.spec.ts, packages/utils/graphql-codegen-testing/src/index.ts
These properties should only actually be stripped when there is no `__resolveReference` present. Since there's no way to know if `__resolveReference` is set, we have to assume it is.
[closes #2530]
=> fix: do not strip properties from federation resolvers parents

packages/plugins/flow/flow/src/visitor.ts, packages/plugins/flow/flow/tests/flow.spec.ts, packages/plugins/flow/operations/src/flow-selection-set-processor.ts, packages/plugins/flow/operations/tests/flow-documents.spec.ts, packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts, packages/plugins/other/visitor-plugin-common/src/selection-set-processor/base.ts, packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts
Based on @matikrk's awesome PR: https://github.com/dotansimha/graphql-code-generator/pull/2569 
I changed the implementation a bit in order to match the new selection set transformer, now the base library doesn't know about Flow, but allow if to override some parts of it's behaviour (related to rendering). 
So each plugin now provides it's whole logic to the transformer, without the need for `isFlow`. 
Thank you @matikrk!
=> Improve Flow types using spread operator

packages/plugins/java/common/src/scalars.ts, packages/plugins/java/kotlin/.gitignore, packages/plugins/java/kotlin/.npmignore, packages/plugins/java/kotlin/package.json, packages/plugins/java/kotlin/src/index.ts, packages/plugins/java/kotlin/src/visitor.ts, packages/plugins/java/kotlin/tests/kotlin.spec.ts, packages/plugins/java/kotlin/tsconfig.json
Kotlin Generator based / as a copy of the Java Generator.
When generating Kotlin code, there were significant differences, so I built a new generator and did not make the Java Generator switchable.
BTW: Thanks for this great project 🤗
=> Kotlin code generator

packages/graphql-codegen-cli/src/utils/listr-renderer.ts
Hey hey 👋🏼, first of all, I want to say I love `graphql-code-generator`, I have been using it a lot lately and it has made my life so much easier 😅I want to help improve it so here is my little contribution, hope you consider it 🤞🏼
**The problem I had:**
I was working on one of my projects when I decided to add the `typescript-react-apollo` plugin. It keept throwing an error (`Plugin "typescript-react-apollo" validation failed:`), which is kind of undescriptive.
After digging into the code I figured out the problem but also realized that there are details to the errors that are not being displayed. Especially in my case, it would have really helped me out.
**My solution**
Display the details of the errors and make it easier for the user to debug their program.
The `listr-renderer.ts` now …
=> Make errors thrown more descriptive

packages/graphql-codegen-cli/src/init/plugins.ts, packages/graphql-codegen-cli/src/init/questions.ts, packages/graphql-codegen-cli/src/init/types.ts, packages/graphql-codegen-cli/tests/init.spec.ts
Hey hey, another one from me 👋🏼
**The problem I had:**
When running `yarn graphql-codegen init`, you are prompted with a question: "Where to write the output:", with the default value thats always "src/generated/graphql.ts". A problem occurs if you have for example chosen `flow` plugin that requires its extension to be `.js` or the `react-apollo` plugin that requires its extension to be `.jsx`. 
**My solution:**
The default value should be inferred from the plugins you have selected. There is also an inferred hierarchy of the extensions.
For example: If you have multiple plugins selected and one of them requires `.tsx`, no matter what other plugins requires, `.tsx` will be the suggested default.
If you have multiple plugins selected and one of them requires `.ts` and no other requires …
=> Custom output default value based on the selected plugins

docs/generated-config/flow-operations.md, docs/generated-config/flow.md, docs/generated-config/typescript-react-apollo.md, docs/generated-config/typescript-stencil-apollo.md
Another one, kind of connected to #2689, I feel like extensions of output files in the docs should by corresponding to the plugins used.
Especially in the case of `apollo-react` where using a `.ts` output file throws an error.
Also, in the case of `flow` plugins, if you are using `flow` then you are probably not using `typescript` and the extension should be just `.js`.
Another small one I fixed, the last `yml` code snippet in the `react-apollo` plugin docs was wrongly formated, here is how it looked:
=> Update extensions in the docs

dev-test/.env, dev-test/codegen.yml, dev-test/generate-all.sh, dev-test/generate-watch.sh, dev-test/test-schema/env.types.ts, packages/graphql-codegen-cli/package.json, yarn.lock
@dotansimha - was `graphql-codegen -r dotenv/config` working back then (#1757) or `dotenv/config` should be loaded before `graphql-codegen`?
=> Use dotenv in examples

packages/plugins/typescript/react-apollo/src/index.ts, packages/plugins/typescript/react-apollo/src/visitor.ts, packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
A configuration option to disable docblocks was requested in PR: https://github.com/dotansimha/graphql-code-generator/pull/2572#issuecomment-539019085
- Added addDocBlocks config option
- Added a test that covers the config option
Are docs autogenerated from the **[docblocks](https://github.com/dotansimha/graphql-code-generator/pull/2717/files#diff-28a8359a9001055804c02e58d2430315R177)** (insert Xzibit meme) or are they required to be added somewhere else?
CC: @levrik does this suit your needs?
=> Added `addDocBlocks` configuration option

packages/plugins/typescript/type-graphql/src/visitor.ts, packages/plugins/typescript/type-graphql/tests/type-graphql.spec.ts
Hello, I did come across a problem that when I provided a custom scalar, it would try and find the type in the graphql-type package. This type did of course not exist and it would define it as any in the code generated graphql file.
So I thought it would be nice to have custom scalar support in the plugin :)
```
generate({
overwrite: true,
schema: `http://${minikubeIP.trim()}/micro-service/graphql`,
documents: 'src/queries/micro-service/**/*.graphql',
generates: {
'src/generated/micro-service-graphql.ts': {
plugins: [{ [TYPESCRIPT_TYPE_GRAPHQL_PLUGIN]: { scalars: { DateTime: "Date" } } }, TYPESCRIPT_OPERATIONS_PLUGIN]
},
'src/generated/micro-service-graphql-modules.d.ts': {
plugins: [TYPESCRIPT_GRAPHQL_FILES_MODULES_PLUGIN]
},
'src/generated/micro-service.graphql': {
plugins: …
```
=> Added support for custom scalars

docs/getting-started/index.md
This fixes a typo in the Getting started part of the documentation.
=> Correct a typo in docs/getting-started

packages/graphql-codegen-cli/src/utils/try-to-build-schema.ts
commentDescriptions: Provide true to use preceding comments as the description, eg "# comment"
=> feat(typescript): support preceding comments

docs/getting-started/index.md
In the [Using in runtime](https://graphql-code-generator.com/docs/getting-started/#using-in-runtime) section, the `generates` file points to a directory and hence throws:
`Error: EISDIR: illegal operation on a directory`
It gets fixed by providing the file name.
=> add filename to target file

packages/plugins/other/fragment-matcher/src/index.ts, packages/plugins/other/fragment-matcher/tests/plugin.spec.ts
Apollo announced Client version 3. It is in beta right now. The configuration for the fragment matcher has been changed. 
The new configuration can be found [here](https://www.apollographql.com/docs/react/v3.0-beta/data/fragments/#defining-possibletypes-manually)
This pull request aims to make fragment-matcher plugin compatible with the new Apollo Client v3.
=> make fragment-matcher compatible with Apollo Client 3

packages/plugins/typescript/stencil-apollo/src/visitor.ts, packages/plugins/typescript/stencil-apollo/tests/stencil-apollo.spec.ts
Fixes #2848 .
This PR adds query variables for the `typescript-stencil-apollo` plugin. Basically it just involved changing the generated template and adding `variables= { this.variables }` to the used `<apollo-query>` StencilJS component.
It has the drawback, that it does so for **all** queries, regardless whether they actually **have** _any_ variables or not - but this will work anyway, because `typescript-operations` will generate a _"proper"_ _empty_ QueryVariables type (actually `{}`) and queries will still work.
Therefore I had to change the old test case.
I would make the variables stuff generation _optional_, but I did not find an easy way on **how** to get to know about **whether** the passed schema contains any variables at all in the `StencilApolloVisitor`.
Docs are still off a …
=> Add query variables to stencil apollo plugin

docs/getting-started/codegen-config.md, docs/getting-started/config-field.md, docs/getting-started/documents-field.md, docs/getting-started/require-field.md, docs/getting-started/schema-field.md
This fixes typos, improves wording, fixes links, and fixes formatting in configuration-related pages of the Getting Started docs.
=> Fix typos and improve wording in Getting Started docs

packages/presets/near-operation-file/src/index.ts, packages/presets/near-operation-file/tests/near-operation-file.spec.ts
Users can specify non-absolute `baseTypesPath` by adding `~` in the beginning of the given path.
Related #2912
=> [near-operation-file] Allow non-absolute paths in baseTypes

packages/plugins/other/visitor-plugin-common/src/utils.ts
Now it's impossible to fix `**/` multiline comment ending to be them linted correctly
=> Fix closing of multiline comment blocks

packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/other/visitor-plugin-common/src/utils.ts, packages/plugins/typescript/resolvers/tests/mapping.spec.ts
The previous PR https://github.com/dotansimha/graphql-code-generator/pull/2957 added the import definition in the mapper description, but doesn't actually use it when generating code. This fixes it.
Fixes https://github.com/dotansimha/graphql-code-generator/issues/2932
=> Use generated import definitions when writing typescript mappers

packages/plugins/typescript/apollo-angular/src/index.ts, packages/plugins/typescript/apollo-angular/src/visitor.ts, packages/plugins/typescript/apollo-angular/tests/apollo-angular.spec.ts
I've based this implementation on the `graphql-request` plugin, collecting all operations and creating a wrapper class with that data.
Open to feedback on how to improve the code or the tests. 
Related: #3005 .
=> Add SDK service that exposes all generated services in Apollo Angular plugin

packages/plugins/java/kotlin/src/visitor.ts, packages/plugins/java/kotlin/tests/kotlin.spec.ts
As I looked into code generation logic for TypeScript it seems that `ID` is mapped to `string`.
However in Kotlin it was mapped to `Any` so I changed to `String`.
Thanks.
=> [kotlin] Map ID to String instead of Any

packages/graphql-codegen-cli/src/init/helpers.ts
There currently exists a small but annoying issue in CLI when bootstrapping a new project with `graphql-codegen init`. Instead of reading the version from CLI `package.json`, `writePackage` function reads it from the project package.json, assigning the wrong version to the plugins selected during ineracrtive init process.
To reproduce you can create a new empty project and init codegen there:
```sh
mkdir test-codegen-cli && cd test-codegen-cli
npm init -y
npm i -s graphql  && npm i -D @graphql-codegen/cli
npx graphql-codegen init
```
You'll notice that selected plugins are added to package.json with the version of the project (1.0.0) , instead of the installed version of the CLI (1.9.1 at the moment of creating this issue)
Seems like the dist structure was changed at some point, but the …
=> Fix relative path to package.json in CLI init command

packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts, packages/plugins/typescript/typescript/src/visitor.ts, packages/plugins/typescript/typescript/tests/typescript.spec.ts
related: https://github.com/dotansimha/graphql-code-generator/issues/3102
=> Fix declarationKind=class syntax errors

packages/presets/near-operation-file/package.json, packages/presets/near-operation-file/src/fragment-resolver.ts, packages/presets/near-operation-file/src/index.ts, packages/presets/near-operation-file/src/resolve-document-imports.ts, packages/presets/near-operation-file/src/utils.ts, packages/utils/plugins-helpers/src/types.ts
I've refactored `near-operation-file` to extract the fragment resolution logic into `fragment-resolver.ts` and the main document processing logic into `resolve-document-imports.ts`, which is then re-exported as `resolveDocumentImports` for use by other preset builders, thus satisfying #3091.
This cuts the main plugin logic down to the following, aside from prep and post processing:
```typescript
function resolveImportPath(baseOutputDir: string, relativeOutputPath: string, sourcePath: string) {
const shouldAbsolute = !sourcePath.startsWith('~');
if (shouldAbsolute) {
const absGeneratedFilePath = resolve(baseDir, relativeOutputPath);
const absImportFilePath = resolve(baseDir, sourcePath);
return resolveRelativeImport(absGeneratedFilePath, absImportFilePath);
} else {
return …
```
=> Language agnostic near-operation-file preset helpers

packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts, packages/plugins/typescript/operations/tests/__snapshots__/ts-documents.spec.ts.snap, packages/plugins/typescript/operations/tests/ts-documents.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/3064
Codegen should let `graphql.js` handle validations, and ignore when it finds an invalid field (because inline fragments are allowed everywhere...)
=> Fixes for fields existences checks for selection set

packages/plugins/typescript/apollo-angular/src/index.ts, packages/plugins/typescript/apollo-angular/src/visitor.ts
There are currently 2 issues with generating apollo-angular operations with documentMode = external
1) It throws an exception in `ClientSideBaseVisitor` when it attempts to access `documents.length` because `ApolloAngularVisitor` is missing the `document` parameter when calling the parent constructor.
2) The document variable name is missing `Operations.` namespace which is defined by external mode.
This PR solves both issues.
For the second issue, it borrows from react's plugin implementation of the method `_getDocumentNodeVariable`
Finally, thanks for all the great work.
=> Fix apollo angular external mode

packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/other/visitor-plugin-common/src/mappers.ts, packages/plugins/other/visitor-plugin-common/tests/parse-mapper.spec.ts
this option allows you to add a suffix to all imported types to prevent name clashes with graphql types.
Followup of my comment here: https://github.com/dotansimha/graphql-code-generator/issues/2932#issuecomment-582862732
=> Add mapperTypeSuffix option

packages/plugins/flow/resolvers/src/visitor.ts, packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
The motivation behind this change is lined out in more detail in dotansimha/graphql-code-generator#3322. The basic problem is that `RequireFields` includes provisions to make non-required arguments optional (via `?:` mapping) but this wrapper type only gets applied when there is at least one required argument in the list.
However, argument lists with all-optional arguments must have the optional mapping applied as well. If not, they end up including only `null` but not `undefined` in their types which can lead to subtle runtime errors.
Related #3322
=> fix: include undefined as type for all-optional argument lists

docs/generated-config/base-documents-visitor.md, docs/generated-config/client-side-base-visitor.md, packages/plugins/other/visitor-plugin-common/src/base-documents-visitor.ts, packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts, packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts, packages/plugins/typescript/operations/tests/ts-documents.spec.ts, packages/plugins/typescript/react-apollo/src/visitor.ts, packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts, packages/plugins/typescript/vue-apollo/src/visitor.ts, packages/plugins/typescript/vue-apollo/tests/vue-apollo.spec.ts
Set this configuration to `true` if you wish to disable auto add suffix of operation name, like `Query`, `Mutation`, `Subscription`, `Fragment`.
----
This option is a companion of `dedupeOperationSuffix`. So code was modified where was used this option.
=> feat: add option `omitOperationSuffix`

docs/plugins/typescript-resolvers.md
Getting Started contains `-D` flag, same should be done by the plugins guides.
=> Add "-D" installation flag

packages/graphql-codegen-cli/src/generate-and-save.ts, packages/graphql-codegen-cli/src/utils/file-system.ts
Code is quite simple:
- ONLY in `watch` mode:
- it remembers files from build to `previouslyGeneratedFilenames` array
- for next builds it tries to find files in `previouslyGeneratedFilenames` which are not generated in the current build - such files are `stale`
- if `overwrite: true` then `stale` files will be deleted.
I tested locally and it works perfectly. 
But I don't find a proper way how to write test cases for Jest. I didn't find any test for watch mode.
=> feat: in watch mode remove stale files from the previous build

packages/plugins/other/fragment-matcher/src/index.ts, packages/plugins/other/fragment-matcher/tests/plugin.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/3464
=> [fragment-matcher] Allow string/number to be specific as apolloClientVersion

packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/typescript/resolvers/src/config.ts, packages/plugins/typescript/resolvers/src/index.ts, packages/plugins/typescript/resolvers/src/visitor.ts, packages/plugins/typescript/resolvers/tests/federation.spec.ts, packages/plugins/typescript/typescript/src/config.ts, packages/plugins/typescript/typescript/src/index.ts, packages/plugins/typescript/typescript/src/visitor.ts, packages/plugins/typescript/typescript/tests/typescript.spec.ts
Adds the optional (disabled by default) `FieldWrapper` type for wrapping field definitions on objects and interfaces (but _not_ input types).
In addition to returning a value of the actual type for a field, objects can also return Promises to that type or functions that do the same. It is currently not possible to achieve that by reconfiguring the code generator.
This adds the ability to wrap field definitions in a `FieldWrapper`, which defaults to `FieldWrapper<T> = T`, thus not changing behavior in any way. To get the above-described behavior, a user would need to set `fieldWrapperValue` to `T | Promise<T> | (() => T | Promise<T>)` or something similar in addition to enabling field wrapping by setting `wrapFieldDefinitions` to `true`.
That may be overkill, but I wanted to avoid altering …
=> feat: allow field definitions to be wrapped

packages/graphql-codegen-cli/tests/codegen.spec.ts, packages/plugins/flow/flow/src/visitor.ts, packages/plugins/flow/flow/tests/__snapshots__/flow.spec.ts.snap, packages/plugins/flow/flow/tests/flow.spec.ts, packages/plugins/flow/operations/src/visitor.ts, packages/plugins/flow/operations/tests/flow-documents.spec.ts, packages/plugins/flow/resolvers/src/visitor.ts, packages/plugins/flow/resolvers/tests/__snapshots__/flow-resolvers.spec.ts.snap, packages/plugins/flow/resolvers/tests/mapping.spec.ts, packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts, packages/plugins/other/visitor-plugin-common/src/base-visitor.ts, packages/plugins/other/visitor-plugin-common/src/variables-to-object.ts, packages/plugins/typescript/generic-sdk/tests/__snapshots__/generic-sdk.spec.ts.snap, packages/plugins/typescript/graphql-request/tests/__snapshots__/graphql-request.spec.ts.snap, packages/plugins/typescript/operations/src/visitor.ts, packages/plugins/typescript/operations/tests/__snapshots__/ts-documents.spec.ts.snap, packages/plugins/typescript/operations/tests/ts-documents.spec.ts, packages/plugins/typescript/react-apollo/tests/__snapshots__/react-apollo.spec.ts.snap, packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts, packages/plugins/typescript/resolvers/src/visitor.ts, packages/plugins/typescript/resolvers/tests/mapping.spec.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts, packages/plugins/typescript/typescript/src/typescript-variables-to-object.ts, packages/plugins/typescript/typescript/src/visitor.ts, packages/plugins/typescript/typescript/tests/typescript.spec.ts
related: #3102  #3183 
If declarationKind is `class`, `interface`, `type` in `typescript`, and `class`, `interface` in `flow`, the punctuation should be semicolon(;), not comma(,).
=> Fix declarationKind=interface, type syntax errors

packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts, packages/plugins/other/visitor-plugin-common/src/enum-values.ts, packages/plugins/other/visitor-plugin-common/src/mappers.ts, packages/plugins/other/visitor-plugin-common/src/types.ts, packages/plugins/typescript/resolvers/tests/mapping.spec.ts, packages/plugins/typescript/typescript/tests/typescript.spec.ts
Related #3466
Produces:
```typescript
import DatabaseMyOtherType, { MyType as DatabaseMyType } from './my-type';
```
It also fixes a bug where named imports weren't even produced if there was a default import of the same module...
I cleaned up a bit the parseMappers logic so later on it will be easier to introduce the new syntax.
=> mappers: put default import next to named identifiers

docs/generated-config/base-visitor.md, packages/plugins/other/visitor-plugin-common/src/base-visitor.ts
related: #3237 
```yaml
config:
scalars:
DateTime: Date
JSON: { [key: string]: any }
```
This config file makes TS type definition file like this.
```typescript
export type Scalars = {
ID: string;
String: string;
Boolean: boolean;
Int: number;
Float: number;
JSON: {"[ key: string ]":"any"};
};
```
So it should be changed into this code.
```yaml
config:
scalars:
DateTime: Date
JSON: "{ [key: string]: any }"
```
```typescript
export type Scalars = {
ID: string;
String: string;
Boolean: boolean;
Int: number;
Float: number;
JSON: { [key: string]: any };
};
```
=> docs: fix config example in base-visitor.md (scalars - JSON)

packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts
These config options are [declared in ClientSideBasePluginConfig](https://github.com/dotansimha/graphql-code-generator/blob/v1.12.2/packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts#L72-L73) but not being used. Looks like a typo to use the document prefix/suffix.
=> Use fragment prefix/suffix in client side base visitor

packages/plugins/typescript/apollo-angular/src/config.ts, packages/plugins/typescript/apollo-angular/src/visitor.ts, packages/plugins/typescript/apollo-angular/tests/apollo-angular.spec.ts
This PR allows users to specify a naming scheme for operations other than the currently hard-coded suffix of `GQL` that is applied to everything and may not be suitable for every team/application.
We are currently using the changes in this PR* as a custom version of this plugin but we would love to get official support for this, and hope that this can offer some value to other users.
*_bar making `GQL` the default suffix, which was added to the PR so there are no breaking changes_
=> [Plugin][typescript-apollo-angular]: Add configurable suffixes for operations

dev-test/test-schema/resolvers-federation.ts, dev-test/test-schema/resolvers-root.ts, dev-test/test-schema/resolvers-types.ts, dev-test/test-schema/typings.ts, docs/generated-config/typescript-resolvers.md, packages/plugins/typescript/resolvers/src/config.ts, packages/plugins/typescript/resolvers/src/index.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
Allows the ability to fully customise the `ResolverFn` type.
You can provide your custom ResolverFn instead of the default one.
Most of the time, this is not needed, and `customResolveInfo` is enough to modify the `info`.
One reason for this can be to make it compatible with other libraries in which the resolver functions are different than the rest, and for example the `info` type depends on the `TParent`.
One example of this kind of libraries is Postgraphile, in which `info`'s type is:
```typescript
info: GraphQLResolveInfo & {
graphile: GraphileHelpers<TParent>;
}
```
=> [typescript-resolvers] `customResolverFn` option

docs/generated-config/typescript.md, packages/plugins/typescript/typescript/src/config.ts, packages/plugins/typescript/typescript/src/visitor.ts, packages/plugins/typescript/typescript/tests/typescript.spec.ts
TypeScript 3.4 introduces a new construct for literal values called const assertions. Its syntax is a type assertion with const in place of the type name (e.g. `{} as const`)
Example:
```
// Type '{ readonly text: "hello" }'
let z = { text: "hello" } as const;
```
Read more about `const assertions`  in:
- [Typescript release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html)
- [Pull Request](https://github.com/Microsoft/TypeScript/pull/29510)
This PR add parameter `enumAsConst` for generate enum like object literals
```
enum MyEnum {
A_B_C
X_Y_Z
_TEST
My_Value
}
```
output
```
export const MyEnum = {
ABC: 'A_B_C',
XYZ: 'X_Y_Z',
Test: '_TEST',
MyValue: 'My_Value'
} as const;
export type MyEnum = typeof MyEnum[keyof typeof MyEnum];
```
enum as const …
=> [Typescript] enum as const: add support const assertions from TypeScript 3.4

packages/plugins/other/visitor-plugin-common/src/mappers.ts, packages/plugins/other/visitor-plugin-common/tests/parse-mapper.spec.ts
Suffix was only applied in regular imports (`file#Identifier`), not when there was an alias or a default import. 
With this PR we only skip adding the suffix to namespaces and internal types (reuse of generated types).
=> fix(mappers): suffix

packages/plugins/java/java/src/visitor.ts, packages/plugins/java/java/tests/java.spec.ts
`Enum.valueOfLabel` accept a String as parameter. `args.get("input")` return type `Object` thus, can not be passed to `Enum.valueOfLabel`. It has to explicitly casted to String before passing to the function.
Related #3616
=> fix(java): Cast args to String for valueOfLabel

packages/plugins/flow/operations/src/visitor.ts, packages/plugins/other/visitor-plugin-common/src/base-documents-visitor.ts, packages/plugins/other/visitor-plugin-common/src/base-visitor.ts, packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts, packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts, packages/plugins/other/visitor-plugin-common/src/types.ts, packages/plugins/typescript/operations/src/visitor.ts, packages/plugins/typescript/react-apollo-offix/src/visitor.ts, packages/presets/near-operation-file/src/fragment-resolver.ts, packages/presets/near-operation-file/src/index.ts, packages/presets/near-operation-file/src/resolve-document-imports.ts
In v1.13.0, there's an issue where the fragment imports generated by `near-file-operation` preset do not match the fragment spreads generated in `client-side-base-visitor`.
This is due to the fact that the logic used in the preset and the plugin does not match.
This PR is an attempt to unify the logic for generating fragment names, fragment variables names (fragment doc) and general operation naming.
=> Fixed issue with fragment names when using near-operation-file + dedupeOperationSuffix

docs/generated-config/typescript-graphql-request.md, docs/plugins/typescript-graphql-request.md, docs/plugins/typescript-oclif.md
This adds the `rawRequest` option to the `typescript-graphql-request` plugin documentation.
=> Add rawRequest to graphql-request plugin documentation

packages/plugins/typescript/document-nodes/src/index.ts, packages/plugins/typescript/document-nodes/src/visitor.ts
Fixes `TypeError: Cannot read property 'length' of undefined` when using `importDocumentNodeExternallyFrom: near-operation-file`.
=> Pass documents to document node visitor

docs/generated-config/typescript-operations.md, docs/generated-config/typescript.md, packages/plugins/other/visitor-plugin-common/src/avoid-optionals.ts, packages/plugins/other/visitor-plugin-common/src/index.ts, packages/plugins/other/visitor-plugin-common/src/types.ts, packages/plugins/typescript/operations/src/config.ts, packages/plugins/typescript/operations/src/visitor.ts, packages/plugins/typescript/type-graphql/src/visitor.ts, packages/plugins/typescript/typescript/src/config.ts, packages/plugins/typescript/typescript/src/index.ts, packages/plugins/typescript/typescript/src/types.ts, packages/plugins/typescript/typescript/src/visitor.ts
v1.13.1 changed the behaviour of optional fields.
All nullable fields are now optional `?` including fields inside queries and fragments.
I found that a bit confusing knowing that if a field is requested as part of a query or fragment, then the GraphQL engine will always return the field, and if it's a nullable field, then its value could be null but still present.
Adding `avoidOptionals: true` to `typescript-operations` plugin doesn't work because that also makes all the nullable properties of query and mutation variables non-optional, which is not the desired behaviour.
I've managed to fix it by introducing a new `field` flag to `avoidOptionals` config which specifically makes field values (those returned by queries and fragments) non-optional.
This works because …
=> Added 'field' flag to avoidOptionals

packages/plugins/typescript/graphql-request/src/visitor.ts, packages/plugins/typescript/graphql-request/tests/__snapshots__/graphql-request.spec.ts.snap
Useful when passing an sdk instance around
=> feat(typescript-graphql-request): export Sdk type

packages/plugins/typescript/generic-sdk/src/visitor.ts, packages/plugins/typescript/generic-sdk/tests/__snapshots__/generic-sdk.spec.ts.snap
Like #3704 but for the generic sdk
=> feat(typescript-generic-sdk): export `Sdk` type

dev-test/githunt/types.preResolveTypes.compatibility.ts, packages/plugins/typescript/compatibility/src/selection-set-to-types.ts, packages/plugins/typescript/compatibility/tests/__snapshots__/compatibility.spec.ts.snap, packages/plugins/typescript/compatibility/tests/compatibility.spec.ts
We encountered some codegen issues in the `typescript-compatibility` plugin pertaining to multiple fragment spreads.
The primary problem can be illustrated through this simple example:
```graphql
fragment FullUser on User {
id
...UserInfo
...UserFriends
}
```
This fragment will generate the following namespace:
```typescript
export namespace FullUser {
export type Fragment = UserFriendsFragment; // This is wrong. It omits the fields from UserInfoFragment
// ...
}
```
Effectively, when you have more than one named fragment spread, the type of the last fragment will become the type of the containing fragment.
Fixing this issue took me down a bit of a rabbit hole, because I had to work to intuit the purpose of the `Kind.FRAGMENT_SPREAD` case in the code generator. Ultimately, I discovered …
=> Fix edge cases from multiple fragment spreads in `typescript-compatibility` plugin

.github/workflows/main.yml, dev-test/generate-all.sh, dev-test/generate-watch.sh, dev-test/init.sh, package.json
This PR moves script for generating examples from shell to npm scripts. 
It's not so easy to run a shell script on windows, but since it is a one-liner, can be safely moved into `package.json`
This will help people with no shell to contribute to the project
=> Simplify generate examples script

dev-test/githunt/types.reactApollo.customSuffix.tsx, dev-test/githunt/types.reactApollo.hooks.tsx, dev-test/githunt/types.reactApollo.preResolveTypes.tsx, dev-test/githunt/types.reactApollo.tsx, dev-test/star-wars/__generated__/CreateReviewForEpisode.tsx, dev-test/star-wars/__generated__/HeroAndFriendsNames.tsx, dev-test/star-wars/__generated__/HeroAppearsIn.tsx, dev-test/star-wars/__generated__/HeroDetails.tsx, dev-test/star-wars/__generated__/HeroDetailsWithFragment.tsx, dev-test/star-wars/__generated__/HeroName.tsx, dev-test/star-wars/__generated__/HeroNameConditional.tsx, dev-test/star-wars/__generated__/HeroParentTypeDependentField.tsx, dev-test/star-wars/__generated__/HeroTypeDependentAliasedField.tsx, dev-test/star-wars/__generated__/HumanWithNullWeight.tsx, dev-test/star-wars/__generated__/TwoHeroes.tsx, dev-test/star-wars/types.refetchFn.tsx, packages/plugins/typescript/react-apollo/package.json, packages/plugins/typescript/react-apollo/src/visitor.ts, packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
Fixes issue described in https://github.com/dotansimha/graphql-code-generator/issues/2192
=> Additional type argument to allow custom config.name for react-apollo HOCs

README.md
We should run 'graphql-codegen init' command by yarn or npx, otherwise, we get an error like this:
"command not found: graphql-codegen"
=> Run init command by yarn

website/docs/getting-started/index.md
The CLI is installed with `yarn add -D @graphql-codegen/cli`. Since it's not global, `graphql-codegen init` will fail with a "command not found" error. A few lines down, it's suggested to not install it globally, so we need a different solution.
I added [npx](https://www.npmjs.com/package/npx) in front since that will execute the CLI in `node_modules/.bin`.
=> docs(README): fix init command

packages/plugins/java/java/src/visitor.ts, packages/plugins/java/java/tests/java.spec.ts, packages/plugins/java/resolvers/src/visitor.ts, packages/plugins/java/resolvers/tests/java-resolvers.spec.ts, packages/plugins/other/visitor-plugin-common/src/utils.ts
related #3929 
For scalars that have not been configured with class mapping, the default behavior is to set it to `any` which works for typescript but in java default type should be `Object`.
I have updated the function `buildScalars` to accept another parameter : defaultScalarType. It's set to `any` by default, but for java, it's set to `Object`. It's likely that other package also need to be updated.
=> Fix: set java default class for scalar to Object

dev-test/codegen.yml, dev-test/githunt/types.preResolveTypes.onlyOperationTypes.ts, dev-test/star-wars/types.preResolveTypes.onlyOperationTypes.ts, dev-test/test-schema/types.preResolveTypes.onlyOperationTypes.ts, packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts, packages/plugins/typescript/typescript/src/config.ts, packages/plugins/typescript/typescript/src/visitor.ts
This is a new config option `onlyOperationTypes` intended to generate only types for operations (enums, scalars, etc..., https://github.com/dotansimha/graphql-code-generator/issues/3475#issuecomment-597020849 may be related)
Non-operation types are incorrect to use for the client-side. You can't get a value of the type if you don't have an operation for that. But since non-operation types are not marked, my coworkers accidentally using them all the time. That option will get rid of that
When using `preResolveTypes` you probably don't need all base types, so now you can skip them and significantly reduce the size of types file. For example, in `dev-test/star-wars` 384 lines dropped to 183 with `preResolveTypes` + `onlyOperationTypes` …
=> New option `onlyOperationTypes` for typescript and flow

packages/plugins/typescript/typescript/src/config.ts, packages/plugins/typescript/typescript/src/visitor.ts, packages/plugins/typescript/typescript/tests/typescript.spec.ts
`relay` users usually use [noFutureProofEnums option](https://github.com/facebook/relay/blob/da7ed10312e6f10743e646ce2e3027059fd40d73/packages/relay-compiler/bin/RelayCompilerBin.js#L101) in their projects. Although It's clear that this is not something hard to accomplish without this pull request, with a utility type like this:
`type FutureProofEnums<T> = T | '%future added value'`
I thought it would be cool to have an option to support it. For now, `futureProofEnums` works only when `enumsAsTypes` is `true`. Because it looks weird if you add `%future added value` to an `enum`.
Also:
- Moved the  `|` sign from the end of the lines, to the first to be more like prettier format.
- Refactor 2 lines of code
=> feat: futureProofEnums option

packages/plugins/java/java/src/visitor.ts, packages/plugins/java/java/tests/java.spec.ts
The crux of the problem I'm trying to solve is the following: consider a schema that includes a type like 
```
input MyEntityInput {
```
In this case, the current codegen will generate a Java class called MyEntityInputInput.java. I'd like to update this to simply generate MyEntityInput.java. I've updated the code to check whether the input type from the schema ends with "Input" and omit adding the "Input" suffix if it does.
The big use case here is when we're using graphql for CRUD operations. If that's the case, then it's very likely that the read operations will necessitate a schema that includes
```
type MyEntity {
```
but that means that we'd want to include the following for writes:
```
input MyEntityInput {
```
The one thing I'm hesitant about with my change is backwards …
=> Update Java plugin: Omit extra 'Input' suffix from an input's class name if the input type's name ends in Input

dev-test/githunt/flow.flow.js, packages/plugins/flow/operations/src/flow-selection-set-processor.ts, packages/plugins/flow/operations/src/visitor.ts, packages/plugins/flow/operations/tests/flow-documents.spec.ts
Related https://github.com/dotansimha/graphql-code-generator/pull/3639
Fix for https://github.com/dotansimha/graphql-code-generator/pull/3639#issuecomment-619090429
This PR makes all nullable fields to be optional in flow.
Currently there is an inconsistency between the top-level types and the query types.
example: https://github.com/dotansimha/graphql-code-generator/blob/master/dev-test/githunt/flow.flow.js
```js
// top-level types
export type Repository = {|
__typename?: 'Repository',
name: $ElementType<Scalars, 'String'>,
full_name: $ElementType<Scalars, 'String'>,
// description is optional field
description?: ?$ElementType<Scalars, 'String'>,
html_url: $ElementType<Scalars, 'String'>,
stargazers_count: $ElementType<Scalars, 'Int'>,
open_issues_count?: ?$ElementType<Scalars, 'Int'>, …
```
=> Fix optional types in queries [flow]

dev-test/star-wars/types.preResolveTypes.onlyOperationTypes.ts, packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts
This is a quick fix for https://github.com/dotansimha/graphql-code-generator/pull/3760 
Some input types are missing and this is critical
This is a hotfix and should be reverted after that issue goes https://github.com/dotansimha/graphql-code-generator/issues/3958
=> [onlyOperationTypes] missing input types

packages/plugins/flow/resolvers/src/visitor.ts, packages/plugins/flow/resolvers/tests/__snapshots__/flow-resolvers.spec.ts.snap, packages/plugins/flow/resolvers/tests/mapping.spec.ts, packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/typescript/resolvers/src/visitor.ts, packages/plugins/typescript/resolvers/tests/federation.spec.ts, packages/plugins/typescript/resolvers/tests/mapping.spec.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
This is a followup to https://github.com/dotansimha/graphql-code-generator/issues/3486 for typescript-resolvers . 
I chose not to implement declarationKind because it would have required a heavier refactoring (because of the `useIndexSignature` option), but I made the plugin use the `getPunctuation` function so that semicolons are now correctly used.
=> Fix punctuation in typescript-resolvers

packages/plugins/java/java/src/visitor.ts, packages/plugins/java/java/tests/java.spec.ts, packages/plugins/java/kotlin/src/visitor.ts, packages/plugins/java/kotlin/tests/kotlin.spec.ts
Fix for the #3998 
BREAKING: 
- I've changed `ID` default scalar's type for the `Kotlin` language from `String` to `Any` — it was done to achieve consistency with the `Java` language: it uses `Object` type (not `java.lang.String` as it was in `Kotlin`)
Except this breaking change above, I hadn't change previously written tests, so there should not be any regression.
=> Fix #3998: Fix nested input suffix reduplication

packages/plugins/other/fragment-matcher/src/index.ts, packages/plugins/other/fragment-matcher/tests/plugin.spec.ts, website/docs/generated-config/fragment-matcher.md
This is my first time contributing to this repo, so apologies in advance if I need to change something – please just let me know what needs changing, and I'll be happy to do it. 
I was using the fragment matcher for a project that didn't use Apollo Client at all. I was doing some custom logic on objects based on if it inherited from a particular interface. The fragment matcher was really useful – I was storing typenames, so I could just check `fragmentMatcher.possibleTypes.[INTERFACE].includes(object.__typename)`, and it worked like a charm.
But, there wasn't any typescript support, since the `possibleTypes` property had a generic `{ [key: string]: string[] }` type. So, this pull request add more explicit types. Specifically – it just defined the type by the content actually created. I …
=> Add useExplicitTyping to fragment matcher config

website/docs/plugins/index.md
Couldn't check if working in website, as `yarn start` gives me some errors `Module not found: Can't resolve '@graphql-codegen/add' in '/.../graphql-code-generator/website/src/components/live-demo'`, not sure how to fix this.
Just took last plugin docs as example.
=> Add apollo-typed-documents to plugin docs

packages/plugins/java/kotlin/src/config.ts, packages/plugins/java/kotlin/src/visitor.ts, packages/plugins/java/kotlin/tests/kotlin.spec.ts, website/docs/generated-config/kotlin.md
Added generation of Kotlin data classes for object types. Probably connected with the https://github.com/dotansimha/graphql-code-generator/issues/3484, but this is only for Kotlin and not Java.
=> feat: add generation of kotlin classes for types

packages/graphql-codegen-cli/src/utils/watcher.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/3560
=> fix(cli): watch mode not updating nested files content because of `require.cache`

packages/plugins/flow/flow/tests/__snapshots__/flow.spec.ts.snap, packages/plugins/flow/flow/tests/flow.spec.ts, packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts, packages/plugins/typescript/generic-sdk/tests/__snapshots__/generic-sdk.spec.ts.snap, packages/plugins/typescript/graphql-request/tests/__snapshots__/graphql-request.spec.ts.snap, packages/plugins/typescript/operations/tests/__snapshots__/ts-documents.spec.ts.snap
if `config.immutableTypes` is false generated code contains an extra space before __typename:
Expected result:
```ts
export type MyType = {
__typename?: 'Entry';
/** Information about the repository from GitHub */
repository: Repository;
}
```
Actual result:
```ts
export type MyType = {
__typename?: 'Entry';
/** Information about the repository from GitHub */
repository: Repository;
}
```
This PR removes the extra space.
=> Fix __typename indentation if immutableTypes is false

packages/plugins/other/time/src/index.ts, website/docs/generated-config/time.md
This PR fixes the following small issues:
- Change default message to "Generated on", which is better English
- when passing config as an object, `format` should not be required.
=> fix(time): config and default message

packages/plugins/other/jsdoc/src/index.ts, packages/plugins/other/jsdoc/tests/jsdoc-schema-types.spec.ts
Solves #4108 
Transforms InputTypes into valid JSDoc types.
**GraphQL**
```graphql
input FooInput {
foo: Int!
}
```
**JSDoc**
```js
/**
* @typedef {Object} FooInput
* @property {number} foo
*/
```
=> Fix #4108: JSDoc transform InputTypes

website/docs/plugins/typescript-urql.md
Instead of the `HOC`:ish name, a `use`-prefixed function is generated
=> Docs: Correct hook usage in typescript-urql

packages/plugins/typescript/operations/src/index.ts
I don't think there is much to explain, #3990 explains it pretty well. `typescript-operations` is writing fragments multiple times to the out file.
I've filtered the output string, and not the objects before it because that resulted in other errors.
This small fix, works quite nice.
---
related #3990
=> fix: don't write duplicate fragments to output

dev-test/githunt/__generated__/comment.query.stencil-component.tsx, dev-test/githunt/comment.query.graphql, dev-test/githunt/graphql-declared-modules.d.ts, packages/graphql-codegen-core/src/codegen.ts, packages/plugins/typescript/named-operations-object/src/index.ts, packages/plugins/typescript/operations/src/index.ts
Instead of deduplicating the generated output, this PR does the same thing before code generation step.
https://github.com/dotansimha/graphql-code-generator/pull/4134
=> Deduplicate definitions before code generation

dev-test/test-schema/resolvers-federation.ts, dev-test/test-schema/resolvers-root.ts, dev-test/test-schema/resolvers-types.ts, dev-test/test-schema/typings.ts, packages/plugins/typescript/resolvers/src/index.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
Since GraphQL Tools v6; `fragment` is replaced by `selectionSet` in stitching resolvers.
https://www.graphql-tools.com/docs/schema-stitching#resolvers
So this PR allows to use new schema stitching API.
=> Support new schema stitching

packages/plugins/typescript/typescript/src/config.ts, packages/plugins/typescript/typescript/src/visitor.ts, packages/plugins/typescript/typescript/tests/typescript.spec.ts
=> Adding option for numeric typescript enums

packages/plugins/other/jsdoc/src/index.ts, packages/plugins/other/jsdoc/tests/jsdoc-schema-types.spec.ts, website/docs/plugins/jsdoc.md
#3223 introduced enums that were typed like readonly objects. Which is sort of true when applying it to the context of a value instead of the context of just types. Which the jsdoc plugin currently only is. For enum "variables" there is an actual `@enum` type. Which will be used once generating implementations is introduced. For now a union of strings is the correct application here.
=> JSDoc: Fixed incorrect enum type generation

packages/presets/near-operation-file/src/index.ts, website/docs/generated-config/near-operation-file.md
Refs #3109. Currently the actual key is `baseTypesPath` so this is just a docs fix.
=> Fix incorrectly renamed config key

.github/workflows/website.yml, packages/plugins/other/visitor-plugin-common/src/imports.ts
Related #3990
I had a look into issue #3990 as I was experiencing the same symptoms, the fix proposed in [this comment](https://github.com/dotansimha/graphql-code-generator/issues/3990#issuecomment-636192237) did not work for me as the imports are generated in the `visitor-plugin-common` package.
In my case it seemed like duplicate fragment identifiers were only generated sometimes, for example I would get something like the below in my generated files (unfortunately it's an internal codebase that I'm not able to share - I believe [this comment](https://github.com/dotansimha/graphql-code-generator/issues/3990#issuecomment-639345782) references a codebase that can reproduce the bug):
```ts
import {
aFieldsFragment, // used multiple times in the queries, single import
bFieldsFragment, // …
```
=> Fix duplicate indentifiers in import statements

packages/plugins/other/jsdoc/src/index.ts, packages/plugins/other/jsdoc/tests/jsdoc-schema-types.spec.ts
This PR adds support for the `@deprecated` directive by appending a textual warning to the `@property` of a `@typedef`. Sadly JSDoc does not allow you to use the actual `@deprecated` annotation on properties but only on symbols. Would have been cool to have added actual IDE warnings and compiler warnings... ah well 🤷‍♂️
=> JSDoc - Added support for @deprecated directive

packages/plugins/flow/resolvers/src/visitor.ts, packages/plugins/flow/resolvers/tests/flow-resolvers.spec.ts, packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/other/visitor-plugin-common/src/types.ts, packages/plugins/typescript/resolvers/src/visitor.ts, packages/plugins/typescript/resolvers/tests/common.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts, website/docs/plugins/flow-resolvers.md, website/docs/plugins/typescript-resolvers.md, website/static/config.schema.json
Related: https://github.com/dotansimha/graphql-code-generator/issues/3985
TODO:
=> feature(typescript-resolvers): make enum resolvers work with external enums and internal values mapping

website/docs/getting-started/installation.md
The "copy to clipboard" functionality is great, but it's picking up the `$`'s. I think it's pretty self explanatory that the commands are for the command line without the `$`'s there. This seems easier than trimming the string in the clipboard utility.
=> Remove faux prompt because it gets copied to the clipboard

packages/plugins/c-sharp/c-sharp-operations/src/visitor.ts
Fixes the suffix bug as described in #4221 
Comparison was against Pascal Cased operation type string while operation type is always camel case, regardless of the operation type's "alias".
=> Fix operation name suffix

website/docs/plugins/c-sharp-operations.md
Had some hard time figuring out for which GraphQL library it generates the C# code for. The author [mentioned](https://github.com/dotansimha/graphql-code-generator/pull/3726) GraphQL.Net which seems to be the wrong one. Then tried GraphQL for .NET, also the wrong one. 
Finally figured out that it requires [GraphQL.Client](https://www.nuget.org/packages/GraphQL.Client/). Would really be useful if there is a reference to that library in the docs. Not sure if example codes are allowed, added it anyway, helpful for starters.
=> Info about required C# library + example code

packages/plugins/other/jsdoc/src/index.ts, packages/plugins/other/jsdoc/tests/jsdoc-document-types.spec.ts, packages/plugins/other/jsdoc/tests/jsdoc-schema-types.spec.ts
This plugin does not yet support operations as output, however when your documents contain operations it breaks the output by casting an object to string. Resulting in a `[object Object]` in the output. Which could turn out to be trouble when ran with a bundler. This PR removes that behaviour and makes it so that the plugin no-op's when encountering a operation or fragment.
=> JSDoc: Removed incorrect results for documents containing operations

packages/plugins/c-sharp/c-sharp/src/common/c-sharp-declaration-block.ts, packages/plugins/c-sharp/c-sharp/src/common/common.ts, packages/plugins/c-sharp/c-sharp/src/common/field-types.ts, packages/plugins/c-sharp/c-sharp/src/common/scalars.ts, packages/plugins/c-sharp/c-sharp/src/common/utils.ts, packages/plugins/c-sharp/c-sharp/src/index.ts, packages/plugins/c-sharp/c-sharp/src/visitor.ts, packages/plugins/c-sharp/c-sharp/test/c-sharp.spec.ts
Solves #4214. 
Additionally added some more improvements:
- Nullable value types
- Initial value support
- Class and field documentation in summary block
- Deprecated fields have DeprecatedAttribute
- Required input fields have JsonRequiredAttribute
- Generic implementation to compose input object
- Code in namespace indented and wrapped
There's one incompatibility though: the generated C# method `getInputObject` is renamed to `GetInputObject` just to follow the general C# naming convention. If breaking compatibility is a no-go to you, it can be reverted.
=> C# plugin improvements

packages/plugins/c-sharp/c-sharp-operations/src/config.ts, packages/plugins/c-sharp/c-sharp-operations/src/index.ts, packages/plugins/c-sharp/c-sharp-operations/src/visitor.ts, packages/plugins/c-sharp/c-sharp-operations/test/c-sharp-operations.spec.ts, packages/plugins/c-sharp/c-sharp/src/config.ts, packages/plugins/c-sharp/c-sharp/src/visitor.ts, packages/plugins/c-sharp/c-sharp/test/c-sharp.spec.ts
Improvements in the C# operations part including:
- Bug solving: operation different casing (#4260)
- Support for custom namespace
- DocumentMode.graphQLTag unsupported, fall back to documentNode
- Removed unused serviceName config item
Also added unit tests for C# operations.
Note: this is based on branch "c-sharp-reserved-keywords" so when that branch is merged to master (#4250) I may need to rebase this one. Let me know if you want me to do this.
=> C sharp operations improvements

packages/plugins/typescript/generic-sdk/src/config.ts, packages/plugins/typescript/generic-sdk/src/index.ts, packages/plugins/typescript/generic-sdk/src/visitor.ts, packages/plugins/typescript/generic-sdk/tests/__snapshots__/generic-sdk.spec.ts.snap, packages/plugins/typescript/generic-sdk/tests/generic-sdk.spec.ts
Allow the use of Observables on subscription operations for Generic SDK
```
config:
usingObservableFrom: "import Observable from 'zen-observable';"
OR
usingObservableFrom: "import { Observable } from 'rxjs';"
documents: '../**/document.graphql'
generates:
./index.ts:
schema: '../**/schema.graphql'
plugins:
- typescript
- typescript-operations
- typescript-generic-sdk
```
Generates a method that returns an Observable instead of a Promise.
```
...
import Observable from 'zen-observable';
OR
import { Observable } from 'rxjs';
...
export function getSdk<C>(requester: Requester<C>) {
return {
...
onX(variables?: OnXVariables, options?: C): Observable<OnXSubscription> {
return requester<OnXSubscription, OnXVariables>(OnXDocument, variables, options);
}
};
}
```
When this config is enabled, the …
=> feat: allow use of Observables on subscriptions with generic-sdk

dev-test/githunt/flow.flow.js, packages/plugins/flow/operations/src/index.ts, packages/plugins/flow/operations/tests/__snapshots__/flow-documents.spec.ts.snap, packages/plugins/flow/operations/tests/flow-documents.spec.ts, packages/plugins/other/visitor-plugin-common/src/optimize-operations.ts
This fixes a bug where fragment types are not generated when `flattenGeneratedTypes` config is provided for flow operations.
=> Fix bug with flow-operations codegeneration and flattenGeneratedTypes config

packages/plugins/other/visitor-plugin-common/src/utils.ts
I am using `DeclarationBlock` to [generate a function](https://github.com/Zhouzi/graphql-codegen-factories/blob/ae48ff276e586b9421c8b2725f5ad79a70ca7cfa/src/FactoriesVisitor.ts#L141-L159) but it currently adds a semicolon after blocks with that kind. It generates:
```js
function foo() {
};
```
Instead of:
```js
function foo() {
}
```
Here's a real example of the output: https://github.com/Zhouzi/graphql-codegen-factories/blob/ae48ff276e586b9421c8b2725f5ad79a70ca7cfa/__tests__/types.ts#L75-L87
This PR adds "function" to the list of kinds that should not be followed with a semicolon.
=> Fix DeclarationBlock to omit the semicolon for functions

website/docs/plugins/typescript-apollo-next.md, website/sidebars.js
Add new plugin doc based on https://github.com/dotansimha/graphql-code-generator/discussions/4301
I can move the plugin to your repo if you prefer
=> feat(plugin): add doc for ts-apollo-next-ssr

packages/graphql-codegen-cli/src/hooks.ts, packages/utils/plugins-helpers/src/types.ts
This adds the ability to use hook functions instead of only run
executabels as hooks.
This option could only be used if integrating graphql-codegenerator
directly from nodejs.
Related #4219
=> feat: allow hooks to be functions if used from node

packages/presets/near-operation-file/src/fragment-resolver.ts, packages/presets/near-operation-file/src/index.ts, packages/presets/near-operation-file/src/resolve-document-imports.ts
The current implementation causes the preset sometimes to add unused fragment imports when `importAllFragmentsFrom` is set. This PR fixes that by changing the timing of the import override (at the moment, it's doing that while building the fragments map, this PR changes it to be done after building all the graph and imports, and it's just acts as override without effecting behaviour).
=> [near-operation-files] More fixes for `importAllFragmentsFrom`

packages/plugins/typescript/resolvers/src/config.ts, packages/plugins/typescript/resolvers/src/visitor.ts, packages/plugins/typescript/resolvers/tests/__snapshots__/ts-resolvers.spec.ts.snap, packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
The purpose of this new configuration flag (`allowParentTypeOverride`) is to allow less strict resolvers signature. Setting this to `true` will change the generated code to use the generic `ParentType = MyType` instead of `ParentType extends MyType = MyType`. Changing this will allow developers to have a bridge type that overrides the value they use for parent value (`type MyModifiedResolvers = TypeResolvers<ContextType, { customValue: string }>`.
=> Added `allowParentTypeOverride` to `typescript-resolvers` plugin

dev-test/setup.js, jest.project.js, package.json, packages/plugins/typescript/apollo-angular/tests/apollo-angular.spec.ts
In regards to issue #4437 I've made two fixes to the angular tests: (i) awaiting all validateTypeScript calls as to not hide failures and (ii) fixing the test that was (silently) failing by updating its gql mutation/subscription to fit the actual schema.
Other than that, this PR also includes a setup file for jest which makes sure the execution fails if there's an unhandledRejection so that they may not stay hidden.
=> Fixing Issue #4437 - Failing tests for unhandledRejection

website/docs/getting-started/index.md
The website mistakenly refers to "our" GitHub repo as "your" GitHub repo.
=> Fix typo in website

packages/plugins/typescript/mongodb/src/visitor.ts, packages/plugins/typescript/mongodb/tests/typescript-mongo.spec.ts
```gql
name: String @column @map(path: "fullName")
```
output before: 
```js
fullName: Maybe<string>
```
fixed output
```js
fullName?: Maybe<string>
```
=> Fix plugin Typescript mongoDB: generate optional type for @map 

packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts, packages/plugins/other/visitor-plugin-common/src/base-visitor.ts, packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts, packages/plugins/typescript/graphql-request/src/visitor.ts, packages/plugins/typescript/graphql-request/tests/__snapshots__/graphql-request.spec.ts.snap, packages/plugins/typescript/graphql-request/tests/graphql-request.spec.ts, packages/plugins/typescript/resolvers/src/index.ts, packages/plugins/typescript/resolvers/tests/mapping.spec.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
Very rough start on #3695. Not sure how you want to handle this. I'll probably just do the ones we need at work (which means Apollo TS), but it should be fine to expand as we go?
(is there some watch mode I can run that builds as we go? right now I do a full `yarn build` every time I change something, which seems suboptimal)
=> feat: support type imports

packages/plugins/typescript/resolvers/src/index.ts
Another one for #3695. For my own use case I _believe_ I'm just missing `react-apollo`. However, I'm not sure when it's safe to do `import type` and when not to there - help would be appreciated 🙂 This is however enough for the stuff we have server side 🎉
=> feat(typescript-resolvers): use `import type` when importing from graphql

dev-test/githunt/typed-document-nodes.ts, packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts, packages/plugins/other/visitor-plugin-common/src/types.ts, packages/plugins/typescript/typed-document-node/src/visitor.ts
The new(ish?) typed-document-node plugin includes an unused import of the default DocumentNode from ClientSideBaseVisitor. One issue with this is it triggers ESLint's no-unused-vars rule.
This PR moves the custom DocumentNode import to the base class with added customisability similar to the `gql` import (e.g. it should now be possible to use [graphql-typed](https://www.npmjs.com/package/graphql-typed) should you wish) and removes the unused import.
=> fix: do not import the unused DocumentNode for typed-document-node

packages/plugins/typescript/generic-sdk/src/visitor.ts
For #3695. Last one I personally need for server side stuff, probably still missing from other plugins/presets.
=> chore(generic-sdk): use import type

packages/graphql-codegen-cli/src/codegen.ts, packages/graphql-codegen-cli/src/config.ts, packages/graphql-codegen-cli/tests/codegen.spec.ts, packages/graphql-codegen-cli/tests/custom-loaders/custom-schema-loader-with-context.js, packages/graphql-codegen-cli/tests/custom-plugins/context.js, packages/graphql-codegen-core/src/codegen.ts, packages/graphql-codegen-core/src/execute-plugin.ts, packages/utils/plugins-helpers/src/types.ts, website/docs/getting-started/documents-field.md, website/docs/getting-started/schema-field.md
This exposes a `pluginContext` object that's accessible to plugins, presets and custom loaders. This provides a way to pass arbitrary data from custom loaders (and presets) to plugins.
=> Add context to plugins and custom loaders

packages/plugins/typescript/operations/src/config.ts, packages/plugins/typescript/operations/src/index.ts, packages/plugins/typescript/operations/tests/ts-documents.spec.ts
This PR is relative to this issue https://github.com/dotansimha/graphql-code-generator/issues/3949
It allows you to add operation name to output file.
=> Add operation export name

.changeset/odd-dancers-pump.md, packages/plugins/typescript/react-apollo/src/visitor.ts
Otherwise output is
```ts
import type * as Apollo from '@apollo/client';
import * as Apollo from '@apollo/client';
```
Which both complains about duplicate identifiers and using type import as value
=> fix: apollo v3 should not use type import

.changeset/clever-nails-agree.md, packages/plugins/typescript/react-apollo/src/visitor.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/4515
=> typescript-react-apollo: prevent adding gql alias when documentMode is external

.changeset/rotten-steaks-nail.md, .changeset/wet-news-juggle.md, dev-test/githunt/typed-document-nodes.ts, packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts, packages/plugins/typescript/typed-document-node/src/index.ts, packages/plugins/typescript/typed-document-node/src/visitor.ts
Related: https://github.com/dotansimha/graphql-code-generator/discussions/4512
=> [typed-document-node] allow `documentMode: graphqlTag`

.changeset/many-owls-bathe.md, packages/plugins/c-sharp/c-sharp-operations/src/visitor.ts, packages/plugins/c-sharp/c-sharp-operations/test/c-sharp-operations.spec.ts
If a double quotes for a constant string are used in a graphql
query these are escaped in c-sharp code as `"""` in the
verbatim string, but in a verbatim string the escape sequence
for a `"` is `""`.
Change-type: patch
Signed-off-by: Andreas Fitzek <andreas.fitzek@gmail.com>
=> 🐛: double quotes gql queries are not correctly escaped in c-sharp operations plugin

website/docs/getting-started/documents-field.md
With the suggested glob here, this error can occur:
> graphql-codegen --config codegen.yml
✔ Parse configuration
❯ Generate outputs
❯ Generate src/generated/types.ts
✔ Load GraphQL schemas
✖ Load GraphQL documents
→ Cannot read property 'buildError' of undefined
Generate
Found 1 error
✖ src/generated/types.ts
TypeError: Cannot read property 'buildError' of undefined
at Scope.checkBlockScopedCollisions (node_modules/@graphql-tools/graphql-tag-pluck/node_modules/@babel/traverse/lib/scope/index
.js:421:22)
I was able to trace this back through some issues to an error in babel caused by attempting to process type files containing module decelerations. 
Using an updated glob pattern: "src/**/!(*.d).{ts,tsx}" avoids that.
=> Correcting typescript glob to avoid 'buildError' of undefined

packages/plugins/typescript/graphql-request/package.json
There is a typo of `peerDependenxcies` and `graphql-tag` is needed to use `@graphql-codegen/typescript-graphql-request`.
=> fix: @graphql-codegen/typescript-graphql-request peerDependencies of graphql-tag 

.changeset/sour-vans-repeat.md, packages/plugins/other/jsdoc/src/index.ts, packages/plugins/other/jsdoc/tests/jsdoc-schema-types.spec.ts
Turns out that you are not supposed to add an `@description` annotation under an `@typedef` annotation or it will end being invalid
=> fix(jsdoc): Correctly placed description in typedef

packages/plugins/typescript/graphql-request/src/visitor.ts
was 
```typescript
this._additionalImports.push(`${typeImport} { GraphQLError } from 'graphql-request/dist/src/types';`);
```
new 
```typescript
this._additionalImports.push(`${typeImport} { GraphQLError } from 'graphql-request/dist/types';`);
```
=> [bug fix] typescript/graphql-request plugin wrong types import fix

packages/plugins/typescript/resolvers/tests/federation.spec.ts, packages/utils/plugins-helpers/src/federation.ts
This PR seeks to fix the issue raised in https://github.com/dotansimha/graphql-code-generator/issues/4493
This updates the `transformParentType` function to only transform parent types if one of their fields contains an @external directive, or if the field is named `__resolveReference`. This essentially translates to whether the type extends a type defined in a remote schema, or whether the type is a base type.
The objective is to target only the resolvers that the gateway will call from the `_entities` query in a federated schema. The gateway only guarantees that fields from the `@key` or `@requires` directives will be supplied in the parent type, so we limit the parent type to only contain these fields. If the parent type is a base type, however, then its field resolvers (other than …
=> fix(resolvers/federation): only transform federated parent types when they contain @external directive

.changeset/breezy-clocks-ring.md, packages/presets/near-operation-file/src/resolve-document-imports.ts
This PR makes errors coming from presets more readable, and with more details, by wrapping it with `DetailedError`.
=> Better errors in presets

.changeset/eight-eyes-type.md, .changeset/nine-cameras-agree.md, packages/plugins/c-sharp/c-sharp-operations/package.json, packages/plugins/c-sharp/c-sharp/src/index.ts, packages/plugins/c-sharp/c-sharp/src/visitor.ts, packages/plugins/c-sharp/common/c-sharp-declaration-block.ts, packages/plugins/c-sharp/common/utils.ts
While preparing another change I noticed some code in the c-sharp plugin that seems to be a left over from a fork. This PR removes this code.
This PR also fixes the package description of the c-sharp-operations package.
=> Remove unused code in c-sharp plugins

.changeset/modern-emus-allow.md, packages/plugins/flow/operations/src/flow-selection-set-processor.ts, packages/plugins/flow/operations/src/visitor.ts, packages/plugins/flow/operations/tests/__snapshots__/flow-documents.spec.ts.snap, packages/plugins/flow/operations/tests/flow-documents.spec.ts
When generating flow operations, the `useFlowReadOnlyTypes:true` flag was not working when `preResolveTypes:true`. This diff updates the `FlowDocumentsVisitor` logic to insert the read-only modifier when formatting the name field so that it's consistent across processors. It also updates the `wrapArray` logic to use `$ReadOnlyArray` when `useFlowReadOnlyTypes:true`.
Output from live demo:
**schema.graphql**
<pre lang="graphql">
scalar Date
schema {
query: Query
}
type Query {
user(id: ID!): User
allUsers: [User]
}
enum Role {
USER,
ADMIN,
}
interface Node {
id: ID!
}
type User implements Node {
id: ID!
username: String!
email: String!
role: Role!
friends: [Friend!]!
}
type Friend implements Node {
id: ID!
name: String!
}
</pre>
**operation.graphql**
<pre lang="graphql">
query …
=> Update read-only flow type generation to be compatible with both FlowWithPickSelectionSetProcessor and PreResolveTypesProcessor

website/docs/getting-started/documents-field.md
Hi! Looks like [graphql-toolkit](https://github.com/ardatan/graphql-toolkit/) is deprecated now, so this PR updates link to correct default gql tags list.
Thanks!
=> docs: fix link to default gql tag list

.changeset/late-spoons-vanish.md, packages/plugins/other/visitor-plugin-common/src/base-visitor.ts, packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts, packages/plugins/other/visitor-plugin-common/src/naming.ts, packages/plugins/typescript/operations/tests/ts-documents.spec.ts, packages/plugins/typescript/react-apollo-offix/src/visitor.ts, packages/plugins/typescript/react-apollo/src/visitor.ts, packages/plugins/typescript/urql/src/visitor.ts
Previously, `ClientSideBaseVisitor#OperationDefinition` aborted eagerly if the node name was not set, since the `getName` function invoked from `BaseVisitor#getOperationSuffix` did not correctly handle scenarios where the node name was unset. This caused the `typed-document-node` plugin not to be able to generate a `DocumentNode` export for unnamed queries.
Related dotansimha/graphql-typed-document-node#40
=> Improve support for unnamed queries

.changeset/yellow-apes-cover.md, packages/graphql-codegen-cli/src/codegen.ts, packages/graphql-codegen-cli/src/presets.ts
**What's the problem this PR addresses?**
`@graphql-codegen/cli` is trying to require user provided packages from itself making it rely on hoisting which does not guarantee that the packages are placed in an accessible location and when using PnP the resolution is rejected because `@graphql-codegen/cli` doesn't declare them.
Fixes https://github.com/yarnpkg/berry/issues/1599#issuecomment-686629356 cc @xenoterracide
**How did you fix it?**
Use `createRequire` to resolve packages relative to the user config
=> fix(cli): import relative to user config

.changeset/wet-trainers-reply.md, packages/utils/plugins-helpers/src/types.ts
Hello, I believe this is typed incorrectly?
This change allows me to pass hooks like:
```ts
{
hooks: {
afterAllFileWrite: ['prettier --write'],
},
}
```
instead of:
```ts
{
hooks: {
afterStart: [],
beforeDone: [],
onWatchTriggered: [],
onError: [],
afterOneFileWrite: [],
afterAllFileWrite: ['prettier --write'],
beforeOneFileWrite: [],
beforeAllFileWrite: [],
},
}
```
Thanks! Love you :)
=> Allow passing partial hooks when generating programatically.

.changeset/tender-steaks-do.md, packages/plugins/typescript/typescript/src/visitor.ts, packages/plugins/typescript/typescript/tests/typescript.spec.ts
Related #4273
Similar to #2018, but for inputs. The fixes didn't apply to inputs because input don't use the argument transformer. Maybe it should be the real fix, but that will impact all plugins and I don't know the codebase enough to try it!
=> Typescript: Make non nullable input field with default value optional

packages/plugins/typescript/graphql-files-modules/src/index.ts
I recently started migrating from `@apollo/client` to `react-query`, and instead of using a package like `graphql-request`, I am planning to simply use a `fetch` wrapper similar to this: https://github.com/tannerlinsley/react-query/discussions/301#discussioncomment-74886
For that, I would like to generate types for named exports from my `.gql` files. The plugin
`@graphql-codegen/typescript-graphql-files-modules` almost makes it possible, but it can only output `DocumentNode` types. I added a config option, to make it possible to use strings as types.
The feature can be expanded/generalized if there is demand for it. I am open for discussion.
Here is a link where I try to explain the problem a bit better:
https://stackoverflow.com/questions/64050929/named-export-multiple-graphql-operation-f …
=> Make export types configurable in typescript-graphql-files-modules

.changeset/twenty-dingos-remain.md, packages/graphql-codegen-cli/src/plugins.ts, packages/graphql-codegen-cli/src/presets.ts, packages/graphql-codegen-cli/tests/cli-flags.spec.ts
**What's the problem this PR addresses?**
When the CLI is trying to require dependencies dynamically it checks for module not found errors by scanning the error message to see if a package is missing, instead of checking the error code.
Related https://github.com/dotansimha/graphql-code-generator/issues/4766
**How did you fix it?**
Check `code !== 'MODULE_NOT_FOUND'` instead of searching the error message
=> fix(cli): handle missing dependencies correctly

.changeset/funny-bikes-switch.md, packages/graphql-codegen-cli/src/utils/watcher.ts, packages/utils/plugins-helpers/src/types.ts, website/docs/getting-started/development-workflow.md
ref: #4815 
- Change usePolling default from `true` to `false`
- Add `watchPolling` config file option to configure polling
Let me know if there's a better option for the config option or if it should be dropped in favor of a cli flag.
=> Add watch polling configuration

.changeset/rotten-flies-sort.md, packages/graphql-codegen-cli/src/codegen.ts
This PR will make use of `fs.statSync` instead of `path.extname` when creating the custom `require` function. The issue with the previous version is discussed in #4859. But to summarize the previous version creates issues when the folder the script is running from has a name ending with something that might be mistaken for a file extension – for example `mysite.com` (`path.extname('mysite.com') === '.com'`).
One could argue if we even need to do the check since `makeDefaultLoader` is always passed `context.cwd` which I guess is always a directory? We could probably just do with `from = path.join(from, '__fake.js')`. Please let me know if you think I should remove the check completely.
Related #4859
=> Use stat instead of extname when creating require

.changeset/lemon-owls-marry.md, packages/plugins/typescript/typescript/src/visitor.ts, packages/plugins/typescript/typescript/tests/typescript.spec.ts
Related #4870. Bug manifested not only when `enumAsConst` was `true`, but whenever any of the values in `enumValues` was falsy, i.e. `0` or `''`.
=> Fixed reading of enumValues from config

website/docs/generated-config/import-types.md
The current example is incorrect, the PR fixes that.
(Sorry about the EOL change creeping in, but that's odd that it wasn't there in the first place, as most sane editors always add it. Don't you want to enforce it? And perhaps adopt `.editorconfig`?)
=> docs: fix typo in import-types example

website/docs/getting-started/documents-field.md
The extra \` is apparently a leftover.
=> docs: fix typo in `documents` field chapter

.changeset/slimy-forks-work.md, packages/presets/import-types/src/index.ts, packages/presets/import-types/tests/types-import.spec.ts
This PR adds support for the `useTypeImports` config when using the `types-import` preset.
=> feat(types-import): support useTypeImports

.changeset/fluffy-snakes-vanish.md, packages/plugins/typescript/vue-apollo/src/index.ts
Allowing the vue-apollo plugin to write to .tsx files means that piglovesyou/graphql-let will work out of the box with the the `typescript-vue-apollo` plugin.
Without it writing to a `.tsx` file throws this error: **Plugin "vue-apollo" requires extension to be ".ts"!**
=> Allow the vue-apollo plugin to write code to .tsx files

.changeset/nasty-squids-press.md, packages/plugins/typescript/type-graphql/src/config.ts, packages/plugins/typescript/type-graphql/src/visitor.ts, packages/plugins/typescript/type-graphql/tests/type-graphql.spec.ts
Related #4831. New `decorateTypes` config option can now be used to specify types that should be decorated.
=> Types that must be TypeGraphQL decorated can now be specified

.changeset/moody-pots-move.md, packages/plugins/typescript/type-graphql/src/visitor.ts, packages/plugins/typescript/type-graphql/tests/type-graphql.spec.ts
This merge requests is an improvement over #4181 and fixes #4663. In GraphQL arrays, there are several nullable types:
- Items in the array may be null, (`[String]!`)
- The array itself may be null, (`[String!]`)
- Both the array and items in the array may be null (`[String]`)
- Neither the array nor the items in it may be null (`[String!]!]`)
So far, `@graphql-codegen/typescript-type-graphql` did not support either of the cases where the items in the array can be null. This led to uncompilable code, which #4181 attempted to fix. However, there were two problems with this merge request:
- It only fixed fields definitions, but not input value definitions, leaving the bug in #4663
- It removes the compilation error, but actually outputs the incorrect, non-nullable item type
TypeGraphQL …
=> Fixed decorators for non-nullable type-graphql array types

.changeset/brown-eels-chew.md, packages/graphql-codegen-cli/src/codegen.ts, packages/graphql-codegen-cli/src/config.ts, packages/graphql-codegen-cli/src/utils/listr-renderer.ts, packages/utils/plugins-helpers/src/types.ts
When watching multiple processes in parallel, the output from the graphql-cli can be quite verbose. This PR allows the --errors-only flag to be passed to the cli which suppresses all other output. 
There are some things that might be questionable: for example the nested ternary, even though I think in this case it's actually quite clear to understand. However I'm happy for any feedback, since I'm quite new to the open source world.
=> Add errors-only flag to graphql-codegen-cli

website/docs/generated-config/near-operation-file.md
I was configurating `graphql-codegen` for a monorepo project and I needed an absolute types path, but the docs didn't specify anything about using absolute paths, for example, for node_modules reference, and I found while looking at the source code about this undocumented feature
https://github.com/dotansimha/graphql-code-generator/blob/master/packages/presets/near-operation-file/src/index.ts#L148
=> as is types path for near-operation-file docs

.changeset/fair-spoons-drum.md, dev-test/githunt/flow.flow.js, packages/plugins/flow/flow/src/index.ts, packages/plugins/flow/operations/src/index.ts, packages/plugins/flow/operations/tests/flow-documents.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/4911
`// @flow` declaration is removed from [flow operations](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/flow/operations/src/index.ts#L38) since [flow plugin](https://github.com/dotansimha/graphql-code-generator/blob/c0f7e16f2e9ddaab61421643da7e4851cadccf97/packages/plugins/flow/flow/src/index.ts#L10) already prepends this to the final output.
Not sure if this affects other part of the lib though.
=> Remove extra `// @flow` declaration from flow operations

.changeset/neat-lemons-drive.md, dev-test/githunt/types.vueApollo.ts, packages/plugins/typescript/vue-apollo/src/visitor.ts, packages/plugins/typescript/vue-apollo/tests/vue-apollo.spec.ts
This PR consists of 3 commits, explained below.
Related #5006
A test has been added to cover this.
Not using undefined for variables generic fixes the following issue:
`Type 'undefined' does not satisfy the constraint 'Record<string, any>'`
Not using undefined for variables parameter fixes the following issue:
`Argument of type 'undefined' is not assignable to parameter of type 'VariablesParameter<Exact<{ [key: string]: never; }>>'`
Tests have been updated accordingly.
* Remove newlines before and after the first argument in the example code.
* Add `@param variables` where applicable.
=> Improve typescript vue apollo plugin

.changeset/sweet-avocados-unite.md, packages/graphql-codegen-cli/src/config.ts
**What's the problem this PR addresses?**
The CLI is requiring modules passed through the `-r` flag from itself and not the users project.
Related https://github.com/dotansimha/graphql-code-generator/issues/4947
**How did you fix it?**
Resolve all modules provided to the `-r` flag relative to the CWD
=> fix(cli): resolve modules provided through the -r flags relative to the cwd

.changeset/four-ants-lick.md, packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts, packages/plugins/typescript/apollo-angular/package.json, packages/plugins/typescript/apollo-angular/src/visitor.ts, packages/plugins/typescript/apollo-angular/tests/apollo-angular.spec.ts, website/docs/generated-config/typescript-apollo-angular.md
This is a work in progress. I'm trying to get my types, operations, and angular services to all be in separate files (with angular generated in a separate lib within my project). I couldn't get this working without these code changes. #4719 is related, but more was required.
If there is a better way, great. If not and this works then I'll complete the tests and whatever is needed for the change.
Example codegen.yml
```yml
schema: "schema.graphql"
generates:
lib/generated/src/lib/types.ts:
plugins:
- "typescript"
libs/generated/src/lib/:
preset: near-operation-file
documents: "libs/generated/**/*.graphql"
config:
documentMode: graphQLTag
presetConfig:
baseTypesPath: types.ts
plugins:
- "typescript-operations"
- "typed-document-node"
libs/generated-angular/src/lib/graphql-services.ts: …
```
=> modify apollo angular visitor to allow external operation definitions related to #4719

.changeset/empty-dragons-teach.md, packages/plugins/typescript/vue-apollo/src/visitor.ts, packages/plugins/typescript/vue-apollo/tests/vue-apollo.spec.ts
related #5014 
omitOperationSuffix was not respected because of dedupeOperationSuffix
@packages/plugins/typescript/vue-apollo/src/visitor.ts:133
=> fix(vue-apollo): regression, respect omitOperationSuffix even with dedupeOperationSuffix enabled

.changeset/hot-pants-vanish.md, packages/plugins/flow/operations/src/index.ts, packages/plugins/flow/operations/src/visitor.ts
Related: #4944
The typescript visitors already do this — but looks like the flow implementations were missed out.
=> Fixes #4944, fragment import statement generation for flow

.changeset/olive-owls-chew.md, packages/plugins/typescript/typed-document-node/src/index.ts, packages/plugins/typescript/typed-document-node/tests/typed-document-node.spec.ts
Realted: https://github.com/dotansimha/graphql-code-generator/issues/4989
=> fix(typed-document-node): avoid printing imports when there are no operations

.changeset/early-gorillas-wave.md, .changeset/green-turkeys-develop.md, dev-test/githunt/types.reactApollo.customSuffix.tsx, dev-test/githunt/types.reactApollo.hooks.tsx, dev-test/githunt/types.reactApollo.preResolveTypes.tsx, dev-test/githunt/types.reactApollo.tsx, dev-test/githunt/types.reactApollo.v2.tsx, dev-test/star-wars/__generated__/CreateReviewForEpisode.tsx, dev-test/star-wars/__generated__/HeroNameConditional.tsx, dev-test/star-wars/types.refetchFn.tsx, dev-test/test-message/types.tsx, packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts, packages/plugins/typescript/react-apollo/src/visitor.ts, packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
related: https://github.com/dotansimha/graphql-code-generator/issues/4964
=> typescript-react-apollo: Improved type safety for generated React hooks, by making sure that variables exists when required

.changeset/purple-bikes-call.md, .changeset/shaggy-brooms-enjoy.md, packages/plugins/other/visitor-plugin-common/src/base-documents-visitor.ts, packages/plugins/typescript/operations/tests/ts-documents.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/5001
=> [typescript-operations] Fix issues with incorrect naming when typesSuffix is used

.changeset/dirty-flowers-check.md, dev-test/githunt/types.reactApollo.customSuffix.tsx, dev-test/githunt/types.reactApollo.hooks.tsx, dev-test/githunt/types.reactApollo.preResolveTypes.tsx, dev-test/githunt/types.reactApollo.tsx, dev-test/githunt/types.reactApollo.v2.tsx, dev-test/star-wars/__generated__/CreateReviewForEpisode.tsx, dev-test/star-wars/types.refetchFn.tsx, dev-test/test-message/types.tsx, packages/plugins/typescript/react-apollo/src/visitor.ts, packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/5045
=> [typescript-react-apollo] prevent baseOptions from being required when Mutation is used

website/docs/getting-started/codegen-config.md
`errorsOnly` config option (introduced in https://github.com/dotansimha/graphql-code-generator/pull/4931) should be described in the docs.
This PR also fixes https://github.com/dotansimha/graphql-code-generator/issues/4849.
=> docs: add `errorsOnly` config option to docs

.changeset/sour-wolves-sleep.md, packages/plugins/typescript/vue-apollo/src/visitor.ts, packages/plugins/typescript/vue-apollo/tests/vue-apollo.spec.ts
Related #5070 
A test has been added to cover this.
=> fix(vue-apollo): Use empty object as default value to variables parameter instead of question mark when variables of query is all optional

.changeset/chilled-cows-fry.md, .changeset/short-monkeys-return.md, packages/plugins/other/visitor-plugin-common/src/avoid-optionals.ts, packages/plugins/other/visitor-plugin-common/src/types.ts, packages/plugins/typescript/operations/src/config.ts, packages/plugins/typescript/type-graphql/src/visitor.ts, packages/plugins/typescript/typescript/src/config.ts, packages/plugins/typescript/typescript/src/typescript-variables-to-object.ts, packages/plugins/typescript/typescript/src/visitor.ts, packages/plugins/typescript/typescript/tests/typescript.spec.ts
This PR adds a `defaultValue` flag to the `avoidOptionals` configuration in all plugins. The behavior is as follows:
- Upon turning on the flag, all defaulted fields (in `input`s or arguments) will strictly obey the type of that field.
- e.g. `input TestInput { test: String! = "test" }` will transpile to `type TestInput { test: Scalars['String'] }`.
- For `input`s, if the `inputValue` flag in `avoidOptionals` is on, then `defaultValue` is not necessary.
- For arguments, if the `objectValue` is `true`, then `defaultValue` is ignored. (to keep with current behavior)
Related #5112
=> feat(typescript): adds a `defaultValue` flag to all `avoidOptionals` configs

.changeset/chatty-buttons-greet.md, packages/graphql-codegen-cli/package.json, packages/graphql-codegen-cli/src/config.ts
This PR allows users to use `<<` syntax (see [here](https://yaml.org/type/merge.html)) for use in configuration files since `<<` as a key has no conflict for this package or its dependents.
=> feat(graphql-codegen-cli): adds YAML `merge` (`<<`) syntax for configuration files

.changeset/loud-clouds-lick.md, packages/graphql-codegen-cli/src/plugins.ts, packages/graphql-codegen-cli/src/presets.ts
When the referenced plugin/preset throws a `MODULE_NOT_FOUND` error within itself, `@graphql-codegen/cli` mistakenly assumes the plugin/preset itself wasn't found, resulting in a very misleading error message.
This shouldn't happen when using external packages as plugins/presets, but I hit this issue when using a local file, within which I had forgotten to install a dependency - in my case, `ramda`.
=> Fixes mistaken MODULE_NOT_FOUND error for missing dependency

.changeset/wild-paws-type.md, packages/graphql-codegen-cli/src/hooks.ts
If a hook is a single function, it is filtered out here, but arrays for
functions would be kept.
=> fix: hooks can be functions and need to be normalized

.changeset/happy-kids-walk.md, packages/plugins/typescript/typed-document-node/src/config.ts, packages/plugins/typescript/typed-document-node/src/index.ts
I wanted to completely flatten fragments.
=> Enable flattening typed document nodes

website/docs/generated-config/typescript-type-graphql.md
fix plugin name so that we can generating `type-graphql` codes.
=> docs: fix typescript-type-graphql plugin name

.changeset/twelve-papayas-scream.md, packages/plugins/typescript/apollo-client-helpers/src/index.ts, packages/plugins/typescript/apollo-client-helpers/tests/__snapshots__/apollo-client-helpers.spec.ts.snap
Adds the merge field ([see API](https://www.apollographql.com/docs/react/caching/cache-field-behavior/#fieldpolicy-api-reference)) for generated TypePolicies.
We could also, instead, use something like `Omit<FieldPolicy, "fields" | "keyFields"> & { fields?: ..., keyFields?: ... }>`, that way, when Apollo adds other fields, we still only override the ones that we type specifically.
wdyt?
=> feat(apollo-client-helpers): Add TypePolicies merge field

.changeset/pretty-zoos-listen.md, dev-test/githunt/types.react-query.ts, package.json, packages/plugins/typescript/react-query/src/config.ts, packages/plugins/typescript/react-query/src/fetcher-custom-mapper.ts, packages/plugins/typescript/react-query/src/fetcher-fetch-hardcoded.ts, packages/plugins/typescript/react-query/src/fetcher-fetch.ts, packages/plugins/typescript/react-query/src/fetcher-graphql-request.ts, packages/plugins/typescript/react-query/src/visitor.ts, packages/plugins/typescript/react-query/tests/__snapshots__/react-query.spec.ts.snap, packages/plugins/typescript/react-query/tests/react-query.spec.ts, yarn.lock
Related #5271
Description:
* Upgraded react-query to v3
* Modified generated useQuery hooks to allow passing in of data type to be used with [query data selectors](https://react-query.tanstack.com/guides/migrating-to-react-query-3#query-data-selectors)
* Reworked the mutations so that variables are passed in at mutate time and not at instantiation
Example new useQuery hook
```js
export const useListPostsQuery = <TData = ListPostsQuery, TError = unknown,>(
variables: ListPostsQueryVariables,
options?: UseQueryOptions<ListPostsQuery, TError, TData>
) =>
useQuery<ListPostsQuery, TError, TData>(
["ListPosts", variables],
fetcher<ListPostsQuery, ListPostsQueryVariables>(
ListPostsDocument,
variables
),
options
);
```
Example new useMutation hook
```js
export const useCreatePostMutation = …
```
=> feat: Adding support for react-query v3

.changeset/popular-icons-tap.md, packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts, packages/plugins/other/visitor-plugin-common/src/enum-values.ts, packages/plugins/other/visitor-plugin-common/tests/enum-values.spec.ts
By default, `enumValues` is taken from `GraphQLSchema` but this doesn't work well with client side stuff because client side libraries doesn't expect the value from the server side. I think this functionality is already problematic. We should never use server-side values for client-side stuff.
Anyway, this PR adds an option `ignoreEnumValuesFromSchema` which is false by default, and users can disable it to fix this. For example, I'll use this on Mesh.
=> feat(visitor-plugin-common): add ignoreEnumValuesFromSchema to ignore enum values from GraphQLSchema

website/src/css/custom.css
Overwrites docusaurus' admonition color and keeps it white for both `dark` and `light` modes.
Fixes #5308.
_Light mode:_
_Dark mode:_
=> fix(style): docusaurus admonition dark mode color (#5310) [deploy_website]

.changeset/swift-rules-do.md, packages/plugins/typescript/graphql-request/src/visitor.ts, packages/plugins/typescript/graphql-request/tests/__snapshots__/graphql-request.spec.ts.snap
`GraphQLClient`'s `request` method accepts `Dom.RequestInit['headers']` parameter (it is same as `HeadersInit`).
but auto-generated methods accept `Headers` parameter only.
so I can not pass an object to that methods.
I fixed it.
=> fix(plugin: graphql-requests): Fix argument types in auto-generated methods

website/docs/generated-config/typescript-operations.md
I'm not sure if the intention was to link somewhere else.
=> docs: remove back tick from description

.changeset/spotty-flowers-rush.md, packages/plugins/typescript/react-query/src/config.ts, packages/plugins/typescript/react-query/src/fetcher-fetch-hardcoded.ts, packages/plugins/typescript/react-query/src/fetcher-fetch.ts, packages/plugins/typescript/react-query/src/fetcher-graphql-request.ts, packages/plugins/typescript/react-query/src/variables-generator.ts, packages/plugins/typescript/react-query/src/visitor.ts, packages/plugins/typescript/react-query/tests/react-query.spec.ts
As suggested in https://github.com/dotansimha/graphql-code-generator/issues/5334
for each `useTestQuery` you'll get an ```useTestQuery.getKey = (variables: TestQueryVariables) => ['test', variables];```
This option can be turned on by setting `exposeQueryKeys: true` in config
=> Expose query keys for react-query (#5334)

.changeset/ninety-teachers-protect.md, packages/plugins/typescript/apollo-angular/src/config.ts, packages/plugins/typescript/apollo-angular/src/visitor.ts, packages/plugins/typescript/apollo-angular/tests/apollo-angular.spec.ts
Due to PR #4508 feature will overwrite the params for the constructor of the basic Query service to makes injected service lose.
Add the `additionalDI ` and config to add custom dependency injections
For the case see https://github.com/dotansimha/graphql-code-generator/issues/4366#issuecomment-759314958
=> [Angular] Add additionalDI config for add custom dependency injections

.changeset/four-pots-suffer.md, .changeset/smooth-tools-trade.md, packages/plugins/typescript/graphql-request/package.json
I had graphql-request 3.3.0 installed and the types weren't working out. I had to look at the changelog to figure out what version of graphql-request I needed.
=> declare a peer dependency on graphql-request

.changeset/tidy-candles-press.md, packages/plugins/other/visitor-plugin-common/src/enum-values.ts, packages/plugins/other/visitor-plugin-common/tests/enum-values.spec.ts
See #5432
See also https://github.com/cometkim/gatsby-plugin-typegen/issues/143
=> fix type error on parsing enums

.changeset/wicked-onions-complain.md, packages/plugins/typescript/react-query/src/config.ts, packages/plugins/typescript/react-query/src/fetcher-custom-mapper.ts, packages/plugins/typescript/react-query/src/visitor.ts, packages/plugins/typescript/react-query/tests/__snapshots__/react-query.spec.ts.snap, packages/plugins/typescript/react-query/tests/react-query.spec.ts, website/docs/plugins/typescript-react-query.md
Currently the generated hooks use the custom fetcher in the following way:
query hooks: They invoke the fetcher inline. I.e you could **use react hooks in your fetcher**
mutation hooks: They create a lambda function that will invoke your fetcher at a later time, when react query performs your mutation. i.e you cannot use react hooks in your fetcher.
**Wait, why would you want to use react hooks in your fetcher?**
My usecase is rather simple: I have to inject some headers and the fetch url at runtime. So in order to not pass them to the queries and mutations everywhere in the code, I could keep them in a `ReactContext` and retrieve them through `useContext` in the fetcher.
**The solution**
This PR extends the `fetcher` option and allows one to pass an object with the following interface: …
=> [React Query] Allow the custom fetcher to lazily receive mutation variables

website/docs/getting-started/require-field.md
This extends the documentation on `dotenv` and adds a reminder that sensitive keys may be output into the generated code.
=> Documentation: Provide a dotenv example

.changeset/new-beans-obey.md, packages/plugins/c-sharp/c-sharp-operations/src/config.ts, packages/plugins/c-sharp/c-sharp-operations/src/index.ts, packages/plugins/c-sharp/c-sharp-operations/src/visitor.ts, packages/plugins/c-sharp/c-sharp-operations/test/c-sharp-operations.spec.ts
Hi! Thank you for the great library.
I'd like to generate C# operation code.
Currently, there are no class definitions for the request/response parameter. So we need to define parameter classes by ourselves.
This p-r provides the option to generate the request/response parameters for operations so that we can execute typesafe query/mutation/subscription operations without defining parameter classes by ourselves.
I attached a diff below, from the example in https://graphql-code-generator.com/
Thank you for reviewing.
```
--- a/codegen.yml
+++ b/codegen.yml
generates:
Operations.cs:
plugins:
-      - c-sharp-operations
+      - c-sharp-operations:
+          typesafeOperation: true
```
```
--- a/Operations.cs
+++ b/Operations.cs
@@ -1,3 +1,7 @@
+using Newtonsoft.Json;
+using GraphQL;
+using …
```
=> typesafe c-sharp operations

.changeset/four-pillows-explain.md, packages/plugins/c-sharp/c-sharp/package.json, packages/plugins/c-sharp/c-sharp/src/config.ts, packages/plugins/c-sharp/c-sharp/src/visitor.ts, packages/plugins/c-sharp/c-sharp/test/c-sharp.spec.ts, packages/plugins/c-sharp/common/c-sharp-declaration-block.ts, packages/plugins/c-sharp/common/keywords.ts, yarn.lock
Add an `emitRecords: true` to config, and it will spit out the immutable syntax (init-only) for c# 9 records, e.g. `record MyType(int Age, string Name) : <interfacelist>` etc. Note that the fields/parameters are PascalCased, as they should be in this case since they are exposed as properties.
```yaml
schema:
- ./types.graphql
- ./units.graphql
generates:
./src/types.cs:
plugins:
- c-sharp
config:
namespaceName: MyNamespace.Types
emitRecords: true
scalars:
ISO8601DateTime: DateTime
```
~~Oh, and I squeaked in a fix for enforcing Pascal Case on C# public properties too. EDIT: which broke tests expecting lower case property names, oops. Will fix tomorrow.~~
input:
```graphql
type Account {
id: ID!
login: String!
lastLogin: ISO8601DateTime
locations: [Location!]
disabled: Boolean!
}
``` …
=> allow csharp plugin to emit c# 9 record types instead of classes

dev-test/githunt/types.reactApollo.customSuffix.tsx, dev-test/githunt/types.reactApollo.hooks.tsx, dev-test/githunt/types.reactApollo.preResolveTypes.tsx, dev-test/githunt/types.reactApollo.tsx, dev-test/githunt/types.reactApollo.v2.tsx, dev-test/star-wars/__generated__/CreateReviewForEpisode.tsx, dev-test/star-wars/__generated__/HeroAndFriendsNames.tsx, dev-test/star-wars/__generated__/HeroAppearsIn.tsx, dev-test/star-wars/__generated__/HeroDetails.tsx, dev-test/star-wars/__generated__/HeroDetailsWithFragment.tsx, dev-test/star-wars/__generated__/HeroName.tsx, dev-test/star-wars/__generated__/HeroNameConditional.tsx, dev-test/star-wars/__generated__/HeroParentTypeDependentField.tsx, dev-test/star-wars/__generated__/HeroTypeDependentAliasedField.tsx, dev-test/star-wars/__generated__/HumanWithNullWeight.tsx, dev-test/star-wars/__generated__/TwoHeroes.tsx, dev-test/star-wars/types.refetchFn.tsx, dev-test/test-message/types.tsx, packages/plugins/typescript/react-apollo/src/config.ts, packages/plugins/typescript/react-apollo/src/visitor.ts, packages/plugins/typescript/react-apollo/tests/__snapshots__/react-apollo.spec.ts.snap, packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
Hi 👋! 
With my team made an adaptation to be able to pass a context name to the generator this helps us to have multiple apollo connections and generate ready-to-use queries pointing to their context.
We follow the recommendation of Dmitri Farkov made in issues [#5433](https://github.com/dotansimha/graphql-code-generator/issues/5433)
Works correctly by passing: 
`generates:
config:
defaultBaseOptions: {
context: { clientName: "yourClientName" },
}
`
=> Add baseOptions customization for typescript-react-apollo

.github/workflows/website.yml, algolia/config.json, packages/presets/graphql-modules/src/utils.ts, patches/@docsearch+react+3.0.0-alpha.32.patch, website/README.md, website/docusaurus.config.js
@Urigo @ardatan Only a very small change is needed to be made to enable multi-search on the client side. 
Have added the client side changes to this PR which works across multiple Guild websites.
In addition to it, I have also added a README to the website folder to document running the website locally
**NOTE:** [The indexer](https://github.com/tvvignesh/algolia-docsearch-indexer) has to be run manually or on schedule after setting it up in a server for updating the search results in  the index as the docs on the relevant websites are changed.
=> Added support for multi-search

.changeset/heavy-gifts-ring.md, packages/plugins/typescript/react-query/src/fetcher-graphql-request.ts, packages/plugins/typescript/react-query/tests/react-query.spec.ts
Add support for useTypeImports when using fetcher: graphql-request.
Related https://github.com/dotansimha/graphql-code-generator/issues/5478
`yarn build && yarn test`
- OS: macOS 10.15.7
- NodeJS: …
=> Add support for useTypeImports when using fetcher: graphql-request

website/docs/getting-started/codegen-config.md
Adds `generates.preset` documentation to highlight some of the presets available such as near-operation-file.
When I was setting up for the first pass it wasn't clear to me that all the documents no matter where in the repo would just end up in a single file.
We might want to look into adding a step in the cli tool to offer presets as an option. Not sure how that would work though.
=> Add generates.preset

.changeset/pretty-bananas-destroy.md, packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/5648
=> Allow to generate only __resolveType for interfaces resolvers

algolia/config.json
I missed adding https://graphql-code-generator.com/ and its sitemap to the config for scraping. Adding it now.
=> Added codegen to the list of websites to be scraped

.changeset/heavy-peaches-arrive.md, packages/graphql-codegen-cli/package.json, packages/plugins/c-sharp/c-sharp-operations/package.json, packages/plugins/c-sharp/c-sharp/package.json, packages/plugins/java/apollo-android/package.json, packages/plugins/other/visitor-plugin-common/package.json, packages/plugins/typescript/apollo-angular/package.json, packages/plugins/typescript/apollo-client-helpers/package.json, packages/plugins/typescript/compatibility/package.json, packages/plugins/typescript/named-operations-object/package.json, packages/plugins/typescript/react-apollo-offix/package.json, packages/plugins/typescript/react-apollo/package.json, packages/plugins/typescript/react-query/package.json, packages/plugins/typescript/stencil-apollo/package.json, packages/plugins/typescript/typed-document-node/package.json, packages/plugins/typescript/urql/package.json, packages/plugins/typescript/vue-apollo/package.json, packages/presets/graphql-modules/package.json, packages/utils/plugins-helpers/src/resolve-external-module-and-fn.ts, yarn.lock
Related https://github.com/dotansimha/graphql-code-generator/issues/3256#issuecomment-799338073 and https://github.com/btxtiger/change-case-all/issues/2
=> fix(naming-convention): revert and pin change-case-all dependency back to 1.0.12 for workaround #3256

.changeset/chilly-donuts-breathe.md, packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts, packages/plugins/other/visitor-plugin-common/src/utils.ts
There is type error on run `graphql-mesh generate-sdk`.
```
TypeError: Cannot read property 'length' of undefined
at hasConditionalDirectives (/Users/tim/Workspace/tmp/graphql-mesh-test/node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:479:20)
```
The line 479:
I think we shouldn't trust TypeScript that much :/
=> fix(visitor-plugin-common): guards possible runtime type error

.changeset/wild-rules-press.md, packages/plugins/c-sharp/c-sharp-operations/src/visitor.ts, packages/plugins/c-sharp/c-sharp/src/visitor.ts, packages/plugins/java/java/src/visitor.ts, packages/plugins/java/kotlin/src/visitor.ts, packages/plugins/java/resolvers/src/visitor.ts, packages/plugins/other/visitor-plugin-common/src/base-documents-visitor.ts, packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts, packages/plugins/other/visitor-plugin-common/src/base-visitor.ts, packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts, packages/plugins/other/visitor-plugin-common/src/utils.ts, packages/plugins/typescript/compatibility/src/visitor.ts, packages/plugins/typescript/mongodb/src/visitor.ts, packages/plugins/typescript/typescript/tests/typescript.spec.ts, packages/presets/near-operation-file/src/fragment-resolver.ts
Allows defining the scalar type to use for unknown scalars, instead of `any`.
Additionally, allows setting a config value `strictScalars: true`, which will result in the generator throwing an error if it encounters a scalar that wasn't defined in the `scalars` config field.
Related #5274
N/A
Added unit tests.
I chose to create a new wrapper method for `buildScalars` and keep the changes minimal. The reason for the new method is to ensure that there are no breaking changes. I wasn't sure if `buildScalars` is exported and used by other external plugins.
=> feat: configuration of default scalar type

.changeset/witty-toes-cross.md, packages/plugins/typescript/react-query/src/config.ts, packages/plugins/typescript/react-query/src/visitor.ts, packages/plugins/typescript/react-query/tests/react-query.spec.ts
Adding an option to expose document from hook. See https://github.com/dotansimha/graphql-code-generator/issues/5862
Added tests
=> feat(react-query): expose document for hooks

.changeset/warm-candles-teach.md, packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts, packages/plugins/typescript/typescript/src/config.ts, packages/plugins/typescript/typescript/src/visitor.ts, packages/plugins/typescript/typescript/tests/typescript.spec.ts
Fixes regression introduced in: #3938, fixes feature requested in: #5227  and #4614 (issue can be discussed ether in these issues, or here).
The change made in issue #3938 changed how `fieldWrapper` worked, so that it is no longer possible to wrap an entire array using `FieldWrapper`, rather the values INSIDE the array are wrapped.
@nebbles summed this up well in #5227:
When adding to config:
wrapFieldDefinitions: true
fieldWrapperValue: T | Promise<T> | (() => T) | (() => Promise<T>)
Then I'd expect this wrapper to be applied to the Type of the field
A type like this:
images: Array<GqlImageData>;
Should turn into: 
images: FieldWrapper<Array<GqlImageData>>;
However as mentioned, the above change (#3938) means that Arrays cannot be given a custom wrapper. The result of using the config …
=> Add `entireFieldWrapperValue` configuration option, to wrap arrays.

.changeset/thirty-nails-wash.md, packages/utils/plugins-helpers/src/types.ts
As highlighted in the issue, using the cli programmatically should not cause a type error when implementing a single hook.
Related #5904 
N/A
Static analysis is sufficient. Hooks are normalized in runtime code and the normalization process is tested.
=> fix: make lifecycle hooks definition a partial

.changeset/orange-bugs-impress.md, packages/plugins/typescript/graphql-request/src/visitor.ts, packages/plugins/typescript/graphql-request/tests/__snapshots__/graphql-request.spec.ts.snap, packages/plugins/typescript/graphql-request/tests/graphql-request.spec.ts
Pass operation name to middleware function (#5807)
Add ability to modify request headers from middleware function (#5883)
=> feat(typescript-graphql-request): Add enchancements to request middleware function (#5883, #5807)

.changeset/sharp-cherries-yell.md, packages/plugins/other/urql-introspection/src/index.ts, packages/plugins/other/urql-introspection/tests/urql-introspection.spec.ts
Added tests and implemented fix for a bug where `includeScalars` and similar options were not respected
Related #6052 
Added tests to test suite
- OS: 
- NodeJS:
=> Fixed `include` functionality in `urql-introspection`

website/docs/getting-started/naming-convention.md
This moves naming convention docs to a separate section and documents how to use third party modules and custom naming functions
Related #6040 
- [ x ] Documentation change
This has not been tested
- OS: 
- NodeJS:
=> docs: document custom naming-convention

.changeset/serious-seas-judge.md, packages/plugins/c-sharp/c-sharp-operations/test/c-sharp-operations.spec.ts, packages/plugins/c-sharp/c-sharp/test/c-sharp.spec.ts, packages/plugins/c-sharp/common/scalars.ts
The graphql  type "Float" corresponds to the C# type "double". But it was incorrectly translated to "float" before (which also is a valid C# type, but not the right one).
Related #5815
I used graphql-codegen cli to generate a .cs-file before and after my changes to verify that graphql  type "Float" is now correctly translated to C# type "double".
=> fix(c-sharp): Use `double` instead of `float` 

.changeset/shaggy-bees-drum.md, packages/plugins/typescript/react-apollo/src/visitor.ts, packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
Implement a fix for #6001, `typescript-react-apollo` should use `typesSuffix` on type names but not on operation names.
Related #6001
=> test(typescript-react-apollo): Implement fix for #6001

.changeset/flat-tables-clap.md, packages/plugins/typescript/react-apollo/src/visitor.ts
As described in the linked issue. When using a combination of the `near-operations-file` preset, only generating hooks, and using a custom apollo hooks import, the "common" import is generated like this:
```ts
import * as Apollo from '@apollo/client';
```
While it is expected to be generated like this, since only types are used from the import:
```ts
import type * as Apollo from '@apollo/client';
```
In combination with the tsconfig setting `importsNotUsedAsValues: true` this causes errors.
This fix is a pretty naive approach, that may only fix this specific scenario, but the change should be pretty harmless overall.
Fixes #5633
Checked it against our code base
While this should probably have a test associated, to prevent regression. I'm not familiar enough with this code base to write a …
=> Fix missing use of type import when using custom apollo hooks import

.changeset/silent-beers-act.md, dev-test/githunt/types.urql.tsx, packages/plugins/typescript/urql-graphcache/src/index.ts, packages/plugins/typescript/urql-graphcache/tests/__snapshots__/urql.spec.ts.snap
This brings the types up to speed, urql defaults variables to an empty object.
- OS:  Windows 10
- `@graphql-codegen/...`: urql-graphcache
- NodeJS: 14.15.0
=> (urql-graphcache) - default to empty object just like urql itself does

.changeset/tasty-ravens-doubt.md, packages/plugins/c-sharp/c-sharp/test/c-sharp.spec.ts, packages/plugins/c-sharp/common/scalars.ts, packages/plugins/c-sharp/common/utils.ts
This code causes issues with nullability of value types. Task #5859 
```
export function isValueType(type: string): boolean {
// Limitation: only checks the list of known built in value types
// Eg .NET types and struct types won't be detected correctly
return csharpValueTypes.includes(type);
}
```
I do not eliminate that limitation completly:
```
// Limitation: only checks the list of known built in value types
// Eg .NET types and struct types won't be detected correctly
```
But with this fix - generator more or less usable in C# projects. It is quite major blocker - if code does not support DateTime nullability.
In general DateTime - is not language primitive like ```int, bool, float``` but it is built-in value type. For CRL - there is no much difference in DateTime and Int32 (int is …
=> Consider DateTime as builtin C# value type

packages/plugins/other/visitor-plugin-common/src/base-visitor.ts
Fixes typo in the `dedupeFragments` config option documentation.
Fixes #6163
- OS: 
- NodeJS: 
=> Fix typo in base-visitor.ts

.changeset/rotten-pets-notice.md, packages/presets/near-operation-file/src/fragment-resolver.ts, packages/presets/near-operation-file/src/index.ts, packages/presets/near-operation-file/src/resolve-document-imports.ts, packages/presets/near-operation-file/src/utils.ts, packages/presets/near-operation-file/tests/near-operation-file.spec.ts
Fix missing imports on dedupeFragments with near-operation-file
Related #6217
=> Fix missing imports on dedupeFragments with near-operation-file

.changeset/swift-fishes-draw.md, packages/plugins/other/visitor-plugin-common/src/base-visitor.ts, packages/plugins/typescript/typescript/src/config.ts, packages/plugins/typescript/typescript/src/visitor.ts, packages/plugins/typescript/typescript/tests/typescript.spec.ts
Sometimes you already have const strings returned from your Database layer. Having to map them to the corresponding GraphQL Enum type can be an annoying task.
Often we simply cast them instead of doing a more error-prone mapping using a mapper function based on switch statements (e.g. `moodTags: (record) => record.moodTags as Array<AudioAnalysisV6MoodTags>,`). However, doing so can cause unnoticed bugs when one of the taxonomies changes.
WIth TypeScript literal types we can now map TypeScript enum types to literal union types easily.
```ts
enum AEnum {
A = "A"
B = "B"
C = "C"
}
type ValuesOfA = `${AEnum}` // "A" | "B" | "C"
const value1: ValuesOfA = "A" // ok
const value2: AEnum = "A" // error, we can only assign AEnum.A :/
```
Related # (none) …
=> feat: allow returning string literal types for resolvers returning enum values

.changeset/witty-donkeys-remember.md, dev-test/githunt/types.urql.tsx, packages/plugins/typescript/urql-graphcache/src/constants.ts, packages/plugins/typescript/urql-graphcache/src/index.ts, packages/plugins/typescript/urql-graphcache/tests/__snapshots__/urql.spec.ts.snap
This PR adds schema property which is missing in GraphqlCacheConfig.
Related #6228 
=> fixed missing schema property in urql GraphCacheConfig

website/docs/getting-started/programmatic-usage.md
The documentation for programmatic usage doesn't work for typescript/node as is. I think both keys I added should be marked optional and the code should reflect that, but this is the fix to get it working in the first place. I'd love to look into making this work. Path isn't available globally by default in my setup, but I think that's a general issue, so that should be imported too.
#6263
OS: macOS Big Sur 11.4
"@graphql-codegen/cli": "1.21.6",
"@graphql-codegen/introspection": "1.18.2",
"@graphql-codegen/typescript": "1.22.4",
NodeJS: v15.14.0
N/A, but the issue I linked gives some additional info
=> Update programmatic-usage.md (#6264) [deploy_website]

website/docs/custom-codegen/contributing.md
There is no such word as `filee` and the sentence makes sense with just `file` , so I assume it's a typo.
- n/a Bug fix (non-breaking change which fixes an issue)
- n/a New feature (non-breaking change which adds functionality)
- n/a Breaking change (fix or feature that would cause existing functionality to not work as expected)
https://www.graphql-code-generator.com/docs/custom-codegen/contributing
1. Start website
```
yarn workspace @graphql-codegen/website run start
```
2. Visit http://localhost:3000/docs/custom-codegen/contributing
- n/a I have commented my code, particularly in hard-to-understand areas
- n/a I have added tests that prove my fix is effective or that my feature works
- n/a New and existing unit tests pass locally with my changes
- n/a Any dependent changes have been …
=> Fix a typo in custom-codegen contributing.md file

.changeset/gold-pans-sneeze.md, dev-test/modules/types.ts, dev-test/test-schema/resolvers-federation.ts, dev-test/test-schema/resolvers-root.ts, dev-test/test-schema/resolvers-types.ts, dev-test/test-schema/typings.ts, packages/plugins/typescript/resolvers/src/index.ts, packages/plugins/typescript/resolvers/tests/__snapshots__/ts-resolvers.spec.ts.snap, packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
Added a new type of StitichingResolver without the `selectionSet` field to its union.
Related https://github.com/dotansimha/graphql-code-generator/issues/6243
None 
=> Add a type of stitching resolver without selectionSet

.changeset/loud-toys-draw.md, packages/graphql-codegen-cli/src/codegen.ts, packages/presets/near-operation-file/src/index.ts, packages/utils/plugins-helpers/src/helpers.ts
I think it is totally legit for a preset to not require any additional plugins, having them required can be confusing. Instead the presets should throw if plugins are mandatory
=> fix: make plugins optional for preset

.changeset/yellow-eggs-lie.md, packages/plugins/typescript/typed-document-node/src/config.ts, packages/plugins/typescript/typed-document-node/src/visitor.ts, packages/plugins/typescript/typed-document-node/tests/typed-document-node.spec.ts
Added automatic appending __typename field to typed-document-node plugin by config parameter
In our project(based on NextJS) we use apollo client for graphql layer. As you know apollo automatically adds __typename to query in runtime.
Such functionality is performance overhead for us, and we want to move __typename adding to generation time.
Unit test + in our project localy
=> Add generation of __typename for typed-document-node plugin

.changeset/eighty-starfishes-drum.md, packages/plugins/c-sharp/c-sharp/src/config.ts, packages/plugins/c-sharp/c-sharp/src/json-attributes.ts, packages/plugins/c-sharp/c-sharp/src/visitor.ts, packages/plugins/c-sharp/c-sharp/test/c-sharp.spec.ts
The test was made using different sample schemas added to `dev-test/codegen.yml` with different arguments given to the plugin.
- OS: Windows
- `@graphql-codegen/cli` (locally built)
- `@graphql-codegen/c-sharp` (locally built)
- NodeJS: 14.16.1
Related #6340
Related #6341
=> Implement additional configuration for C# plugin related to JSON attributes, remove redundant dependency on `GraphQL` namespace

.changeset/metal-students-pump.md, packages/plugins/java/java/src/visitor.ts, packages/plugins/java/java/tests/java.spec.ts
change `valueOfLabel` to `valueOf` for `enum` since `valueOfLabel` is no longer generated.
Related #6320 (issue)
- OS: 
- NodeJS: 
If this is a relatively large or complex change, kick off the …
=> change valueOfLabel to valueOf for enum, fix #6320

.changeset/ninety-months-deny.md, packages/plugins/typescript/react-query/src/config.ts, packages/plugins/typescript/react-query/src/fetcher-custom-mapper.ts, packages/plugins/typescript/react-query/src/fetcher-fetch-hardcoded.ts, packages/plugins/typescript/react-query/src/fetcher-fetch.ts, packages/plugins/typescript/react-query/src/fetcher-graphql-request.ts, packages/plugins/typescript/react-query/src/fetcher.ts, packages/plugins/typescript/react-query/src/visitor.ts, packages/plugins/typescript/react-query/tests/react-query.spec.ts
This pull request adds an option to export each query's fetcher.
#5526
- OS: Ubuntu-20.04 (WSL2)
=> Expose fetcher (with `exposeFetcher` config) in `typescript-react-query` plugin 

.changeset/healthy-walls-provide.md, packages/plugins/typescript/react-query/src/visitor.ts, packages/plugins/typescript/react-query/tests/react-query.spec.ts
This PR gets the `typescript-react-query` plugin to respect the `dedupeOperationSuffix` parameter when generating hook names.
Related #6368.
https://codesandbox.io/s/react-query-operation-suffix-deduping-bug-repro-c8r58
- OS: macOS 11.5.1
- `@graphql-codegen/typescript-react-query`: 1.3.5
- NodeJS: 14.16.1
I more or less just copied and modified a bunch of code from `typescript-react-apollo` for this (both in the plugin itself and the corresponding test suite).  It might or might not be the best possible implementation for the `typescript-react-query` plugin, but it does make it work in the way the …
=> react-query: dedupe operation names in hook names

.changeset/lovely-needles-pretend.md, .vscode/settings.json, examples/programmatic-typescript/package.json, examples/programmatic-typescript/src/index.ts, packages/graphql-codegen-cli/src/codegen.ts, packages/graphql-codegen-core/src/codegen.ts, packages/plugins/c-sharp/c-sharp-operations/src/index.ts, packages/plugins/c-sharp/c-sharp-operations/src/visitor.ts, packages/plugins/c-sharp/c-sharp/src/index.ts, packages/plugins/flow/flow/src/index.ts, packages/plugins/flow/resolvers/src/index.ts, packages/plugins/java/java/src/index.ts, packages/plugins/java/kotlin/src/index.ts, packages/plugins/java/resolvers/src/index.ts, packages/plugins/other/jsdoc/src/index.ts, packages/plugins/other/schema-ast/src/index.ts, packages/plugins/typescript/mongodb/src/index.ts, packages/plugins/typescript/resolvers/src/index.ts, packages/plugins/typescript/type-graphql/src/index.ts, packages/presets/near-operation-file/tests/near-operation-file.spec.ts, packages/utils/plugins-helpers/src/federation.ts, packages/utils/plugins-helpers/src/getCachedDocumentNodeFromSchema.ts, packages/utils/plugins-helpers/src/index.ts, website/docs/custom-codegen/using-visitor.md
Use utility functions such as `getDocumentNodeFromSchema`(in favor of `parse(printSchema(` chain), `mapSchema`, `astFromObjectType`(instead of `parse(printType` chain) and etc. from `@graphql-tools/utils` if possible.
Implement `getCachedDocumentNodeFromSchema` instead of multiple calls of `printSchemaWithDirectives`, `printSchema` and `parse` which probably increases the performance(removes the duplicate workload on large schemas).
=> enhance(plugins): use getDocumentNodeFromSchema and other utilities from @graphql-tools/utils

packages/plugins/typescript/react-query/src/config.ts
React Query's config options `exposeDocument` and `exposeQueryStrings` documentation examples aren't rendering as code blocks.
The `exposeFetcher` documentation example uses `@exampleMarkdown` to render as a code block.
Related #6475
Existing `exposeDocument` and `exposeQueryStrings` examples vs `exposeFetcher` which uses `@exampleMarkdown`.
=> chore(react-query): use `@exampleMarkdown` for config examples

.changeset/nine-kiwis-remain.md, packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts, packages/presets/near-operation-file/tests/fixtures/issue-6520.ts, packages/presets/near-operation-file/tests/near-operation-file.spec.ts
This prevents ClientSideBaseVisitor.getImports from generating an import for a fragment declared in the same file it's outputting to.  This type of import is a TypeScript compilation error (and is also not necessary, since the const is declared later on in the file).
Related #6520 
https://codesandbox.io/s/stoic-minsky-0l3bg
I added a test case in the near-operation-files-preset suite labeled with issue number #6520.  It initially failed (reproducing this behavior) and now passes with my fix.
- OS: macOS 11.5.1
- `@graphql-codegen/cli`: 2.1.1
- `@graphql-codegen/near-operation-file-preset`: 2.1.0
- `@graphql-codegen/typescript`: 2.1.0
- `@graphql-codegen/typescript-graphql-request`: 4.1.0
- …
=> Don't generate import statements for fragments declared in the same file

.changeset/shiny-eels-smell.md, packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts, packages/presets/near-operation-file/tests/fixtures/issue-6546-fragments.ts, packages/presets/near-operation-file/tests/fixtures/issue-6546-queries.ts, packages/presets/near-operation-file/tests/near-operation-file.spec.ts
This fixes the duplicate imports for the same identifier bug outlined in #6546.  To do so, it extends `getImports` to track what identifiers it has already imported and not import the same one twice.  It also eliminates empty import statements that might result from this deduplication.
Related #6546 
https://codesandbox.io/s/proud-bird-jx23b
I added a test case in the near-operation-files-preset suite labeled with issue number #6546.  It initially failed (reproducing this behavior) and now passes with my fix.
- OS: macOS 11.5.1
- `@graphql-codegen/cli`: 2.1.1
- `@graphql-codegen/near-operation-file-preset`: 2.1.1
- `@graphql-codegen/typescript`: 2.1.1
- `@graphql-codegen/typescript-graphql-request`: 4.1.1
- …
=> Fix double imports

.changeset/flat-spoons-fail.md, packages/presets/graphql-modules/src/utils.ts, packages/presets/graphql-modules/tests/integration.spec.ts, packages/presets/graphql-modules/tests/test-files/modules/users/types/ext_user.graphql
For now, I just added the test failing... Now I need to code the fix.
In one module if you declare a type and extend the type (in another file of the same module), codegen will generate 2 times the same type and will generate an invalid file.
Related https://github.com/dotansimha/graphql-code-generator/issues/6534
- With a Unit test
=> fix: module-duplicate-type

website/docs/getting-started/codegen-config.md
This is a small PR removing an extra backtick character from the [codegen.yml](https://www.graphql-code-generator.com/docs/getting-started/codegen-config) documentation page.
=> docs(codegen-config): remove extra backtick

.changeset/lovely-ways-live.md, packages/plugins/other/jsdoc/src/index.ts, packages/plugins/other/jsdoc/tests/jsdoc-schema-types.spec.ts
See my existing issue for what's up. In short: schema and directives cause the JSDocs plugin to output `[object Object]`, which is kind of annoying. Adding a `DirectiveDefinition` and `SchemaDefinition` which returns `null` solves this problem since the expected behaviour is to not write anything out.
This _does not_ affect directives that are used. If a field is marked `@deprecated(reason: ...)` then that reason will be output as per normal. It just avoids trying to write the definition of the directive to the file.
Related #6505 
Code sandbox is available here: https://codesandbox.io/s/nifty-euclid-o963o?file=/schema.graphql
1. Include an unused directive in the schema. Nothing extra is printed out, the file looks like it should.
2. Include a …
=> [jsdocs] Handle directive & schema definitions

.changeset/early-starfishes-check.md, packages/plugins/other/visitor-plugin-common/src/utils.ts, packages/plugins/typescript/operations/tests/ts-documents.spec.ts
The follow valid fragment definitions (which merge a fragment spread with an inline fragment) cause an error.
```graphql
fragment Post on Post {
id
comments {
... on TextComment {
text
}
}
}
fragment PostPlus on Post {
...Post
comments {
id
}
}
```
Error is thrown from this line: https://github.com/dotansimha/graphql-code-generator/blob/a910a79892e88222ec8594e59c50e440eb3d800a/packages/plugins/other/visitor-plugin-common/src/utils.ts
Closes #6409
Closes #6410
Added a failing test, added the fix.
=> [typescript-operations] fix merging inline fragment and fragment spread

.changeset/seven-ladybugs-beg.md, packages/plugins/typescript/urql-graphcache/src/index.ts, packages/plugins/typescript/urql-graphcache/tests/__snapshots__/urql.spec.ts.snap, packages/plugins/typescript/urql-graphcache/tests/urql.spec.ts
This PR gets the typescript-urql-graphcache plugin to respect the typesPrefix and typesSuffix options when generating type names.
Related #6544.
None.
- OS: macOS 11.5.1
- @graphql-codegen/typescript-urql-graphcache: 2.1.1
- NodeJS: v16.6.2
None.
=> [typescript-urql-graphcache] add support for typesPrefix and typesSuffix options

.changeset/quick-shoes-visit.md, packages/plugins/c-sharp/c-sharp-operations/src/visitor.ts, packages/plugins/c-sharp/c-sharp-operations/test/c-sharp-operations.spec.ts, packages/plugins/c-sharp/c-sharp/src/visitor.ts, packages/plugins/c-sharp/common/keywords.ts
This adds logic to the `c-sharp-operations` plugin to add a `@` prefix to properties whose names collide with reserved C# keywords.  This logic already existed in the `c-sharp` plugin, and it was simply missing from the `c-sharp-operations` plugin.
For example:
```cs
public string @operator { get; set; }
```
Related #5556
This also adds `System` as an import because `DateTime` is a very common type that would need to be used in the resulting C# code.
I created GraphQL schemas that contain properties whose names collide with reserved keywords in C#, such as `private`. Added relevant automated tests.
I moved `convertSafeName()` to the common `packages/plugins/c-sharp/common/keywords.ts` file, since it's shared functionality between the two C# plugins.
=> [c-sharp-operations] Use ampersand prefix for C# keyword name collisions

.changeset/weak-plums-reflect.md, packages/plugins/flow/resolvers/tests/__snapshots__/flow-resolvers.spec.ts.snap, packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/typescript/resolvers/src/config.ts, packages/plugins/typescript/resolvers/src/index.ts, packages/plugins/typescript/resolvers/tests/__snapshots__/ts-resolvers.spec.ts.snap, packages/plugins/typescript/resolvers/tests/common.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
This can be handy for automatically having the correct type when using directives for authorization as it allows providing a custom context, without having to manually type it.
=> map directive on FIELD_DEFINITION to custom field resolver type

.changeset/ninety-insects-kick.md, dev-test/githunt/types.react-query.ts, packages/plugins/typescript/react-query/src/fetcher-custom-mapper.ts, packages/plugins/typescript/react-query/src/fetcher-fetch-hardcoded.ts, packages/plugins/typescript/react-query/src/fetcher-fetch.ts, packages/plugins/typescript/react-query/src/fetcher-graphql-request.ts, packages/plugins/typescript/react-query/src/variables-generator.ts, packages/plugins/typescript/react-query/tests/__snapshots__/react-query.spec.ts.snap, packages/plugins/typescript/react-query/tests/react-query.spec.ts
Related #6496 by modifying `generateQueryKey` to not include `undefined` variables.
This can be a breaking change if you rely on the undefined entry in the query key. I would consider the previous behavior a bug though.
I have tested it in a private project, where I applied the listed changes via patch-package.
=> [typescript-react-query] Remove undefined variables from query key

.changeset/tame-items-film.md, packages/plugins/typescript/typescript/src/visitor.ts, packages/plugins/typescript/typescript/tests/typescript.spec.ts
Related: https://github.com/dotansimha/graphql-code-generator/issues/6532
=> Apply missing namingConvention when numericEnums is used

.changeset/stupid-actors-kneel.md, packages/plugins/typescript/react-query/src/fetcher-graphql-request.ts, packages/plugins/typescript/react-query/tests/__snapshots__/react-query.spec.ts.snap, packages/plugins/typescript/react-query/tests/react-query.spec.ts
With `graphql-request` it's possible to pass in `headers` on a per request basis. With the current implementation, this can not be achieved with `@graphql-codegen/typescript-react-query`. This PR adds an optional parameter `headers` to the hook and fetcher.
- OS: macOS
- NodeJS:
=> [typescript-react-query] Allow passing `headers` to `graphql-request`

.changeset/heavy-tables-float.md, .changeset/quick-candles-suffer.md, examples/programmatic-typescript/package.json, packages/graphql-codegen-cli/package.json, packages/graphql-codegen-cli/tests/codegen.spec.ts, packages/plugins/other/schema-ast/src/index.ts, packages/plugins/other/schema-ast/tests/schema-ast.spec.ts, yarn.lock
Use graphql.lexicographicSortSchema in transformSchemaAST depending on the parameter - sort
Bumps GraphQL Tools package that handles schema definitions correctly
Related #6624 
- Bug fix (non-breaking change which fixes an issue)
- OS: macOS Catalina version: 0.15.7
- `@graphql-codegen/typescript`: "2.2.0"
=> Bump GraphQL Tools for Schema Sorting and the fix for the schema definition handling

.changeset/tiny-lions-laugh.md, packages/plugins/flow/resolvers/tests/__snapshots__/flow-resolvers.spec.ts.snap, packages/plugins/flow/resolvers/tests/mapping.spec.ts, packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/typescript/resolvers/tests/__snapshots__/ts-resolvers.spec.ts.snap, packages/plugins/typescript/resolvers/tests/mapping.spec.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
Fix indentation of DirectiveArgs
Related #6652 
I ran the tests and updated the snapshots accordingly.
- OS: MacOS
- `@graphql-codegen/...`: `master`
- NodeJS: 14
-
=> fix: proper indentation of DirectiveArgs

.changeset/unlucky-bears-march.md, packages/plugins/typescript/react-query/src/fetcher-fetch.ts, packages/plugins/typescript/react-query/tests/__snapshots__/react-query.spec.ts.snap, packages/plugins/typescript/react-query/tests/react-query.spec.ts
Provide fix, so that dataSource is required param in situations where user have not provided custom endpoint because fetch must get it from somewhere.
#6633
- OS: Linux
- `@graphql-codegen/...`: latest
- NodeJS: 14
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what …
=> fix: fix dataSource not beign required in fetcher

.changeset/small-knives-yawn.md, packages/plugins/typescript/urql/src/visitor.ts, packages/plugins/typescript/urql/tests/urql.spec.ts
This fixes the  typescript-urql plugin ignores documentMode importDocumentNodeExternallyFrom and importOperationTypesFrom settings
I've used the code from https://github.com/dotansimha/graphql-code-generator/pull/4765 as a basis to add this
Related #6650
Bug fix (non-breaking change which fixes an issue)
the issue is shown in the following sandbox also linked in issue #6650
https://codesandbox.io/s/confident-dream-l0sd5?file=/urql.ts 
Ran unit tests
=> modify urql visitor to allow external operation definitions

.changeset/smooth-otters-compare.md, packages/plugins/typescript/gql-tag-operations/src/index.ts, packages/presets/gql-tag-operations/tests/fixtures/duplicate-operation.ts, packages/presets/gql-tag-operations/tests/gql-tag-operations.spec.ts
@n1ru4l 
While using the preset I encountered that if the same query appears twice, the operation is duplicated and the preset emits invalid TypeScript.
=> fix: prevent duplicate operations

website/docs/custom-codegen/extend-schema.md
There is a typo on the website https://www.graphql-code-generator.com/docs/custom-codegen/extend-schema
- n/a Bug fix (non-breaking change which fixes an issue)
- n/a New feature (non-breaking change which adds functionality)
- n/a Breaking change (fix or feature that would cause existing functionality to not work as expected)
- n/a I have commented my code, particularly in hard-to-understand areas
- n/a My changes generate no new warnings
- n/a I have added tests that prove my fix is effective or that my feature works
- n/a Any dependent changes have been merged and published in downstream modules
=> Fix typo in extend schema documentation

.changeset/six-eagles-agree.md, packages/plugins/typescript/resolvers/src/config.ts, packages/plugins/typescript/resolvers/src/index.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts, website/static/config.schema.json
Adds a config property called, makeResolverTypeCallable, which removes the resolverWithResolve type from the resolver union when set to true
Related https://github.com/dotansimha/graphql-code-generator/issues/6310
None
- OS: MacOS
- NodeJS: v16
=> Add new config property that removes ResolverWithResolve from the Resolver union

.changeset/poor-seas-swim.md, packages/plugins/typescript/graphql-request/src/config.ts, packages/plugins/typescript/graphql-request/src/visitor.ts, packages/plugins/typescript/graphql-request/tests/__snapshots__/graphql-request.spec.ts.snap, packages/plugins/typescript/graphql-request/tests/graphql-request.spec.ts
This introduces a new configuration for the `graphql-request` plugin for
typescript. It allows to use `unknown` (or a custom type) instead of
`any` for the `extensions` parameter without breaking changes.
Related #6966 
No jest tests has been added for this. The change is trivial, but if you want me to add a test, just say it.
=> Allow customization for extensions type

.changeset/six-icons-sneeze.md, packages/plugins/typescript/urql-graphcache/src/constants.ts, packages/plugins/typescript/urql-graphcache/src/index.ts, packages/plugins/typescript/urql-graphcache/tests/urql.spec.ts
Related #6912 
See #6912 for sandbox example of the issue.
- Locally linked the modified `@graphql-codegen/typescript-urql-graphcache` into my [test project](https://github.com/rossng/repro-gql-codegen-urql).
- Added a test to `typescript-urql-graphcache` which tests for the presence of correctly-worded imports when `useTypeImports` is enabled.
- OS: macOS Monterey
- …
=> Respect `useTypeImports` config in `typescript-urql-graphcache` plugin

.changeset/tame-cups-fetch.md, dev-test/star-wars/types.refetchFn.tsx, packages/plugins/typescript/react-apollo/src/visitor.ts, packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts
This eliminates a potential source of bugs: the current definition
always generates variables as optional, whereas they should be
required if the variables contain non-null arguments.
Follow up to https://github.com/dotansimha/graphql-code-generator/issues/3478 and https://github.com/dotansimha/graphql-code-generator/pull/3479
I added an automated test to ensure the proper code is generated.
- ~[ ] I have made corresponding changes to the documentation~ No need for any config changes, this will simply uncover some bugs
- ~[ ] Any dependent changes have been merged and published in downstream modules~ no dependencies
=> Require non-null variables in react-apollo refetchFn

.changeset/warm-buttons-vanish.md, packages/plugins/typescript/urql-graphcache/src/index.ts, packages/plugins/typescript/urql-graphcache/tests/__snapshots__/urql.spec.ts.snap, packages/plugins/typescript/urql-graphcache/tests/urql.spec.ts
This PR fixes a bug in the urql-graphcache plugin where if the mutationType name in the schema was anything other than `mutation` the generated `GraphCacheOptimisticUpdaters` would have incorrect types.
Related https://github.com/dotansimha/graphql-code-generator/issues/6560
=> Dynamically Name Optimistic Mutation

.changeset/mighty-tools-repair.md, packages/plugins/typescript/urql/src/visitor.ts, packages/plugins/typescript/urql/tests/__snapshots__/urql.spec.ts.snap, packages/plugins/typescript/urql/tests/urql.spec.ts
Pull request #6651 had an issue where the import operation name "Operations." would be also prefixed to the Urql type import.
Expected
```js
export function useTestQuery(options: Omit<Urql.UseQueryArgs<Operations.TestQueryVariables>, 'query'> = {}) {
return Urql.useQuery<Operations.TestQuery>({ query: Operations.TestDocument, ...options });
};
```
Issue:
```js
export function useTestQuery(options: Omit<Urql.UseOperations.QueryArgs<Operations.TestQueryVariables>, 'query'> = {}) {
return Urql.useOperations.Query<Operations.TestQuery>({ query: Operations.TestDocument, ...options });
};
```
#6651 
I've updated the tests to check explicitly for this case, and I've also added a snapshot test which will help prevent this in the …
=> Fix Urql imports being prefixed with operation import name

.changeset/khaki-masks-whisper.md, packages/plugins/other/schema-ast/src/index.ts, packages/plugins/other/schema-ast/tests/schema-ast.spec.ts, packages/plugins/typescript/type-graphql/src/index.ts, packages/plugins/typescript/typescript/src/index.ts, website/static/config.schema.json
Related #6900
Adds `includeIntrospection` option to schema-ast plugin.
This is useful when Relay code needs to reference an enum type, e.g.
```js
import { graphql, useLazyLoadQuery } from 'react-relay';
import type { UserFeaturesDebugQuery } from '@/__generated__/UserFeaturesDebugQuery.graphql';
import type { UserFeature } from '@/types/api';
type UserFeaturesDebugProps = {
currentFeatures: readonly UserFeature[];
};
export const UserFeaturesDebug = ({
currentFeatures,
}: UserFeaturesDebugProps) => {
const introspection = useLazyLoadQuery<UserFeaturesDebugQuery>(
graphql`
query UserFeaturesDebugQuery {
__type(name: "UserFeature") {
name
enumValues(includeDeprecated: true) {
name
deprecationReason
description
}
}
}
`,
{}
);
const flags = [...(introspection.__type?.enumValues ?? …
```
=> feat: add includeIntrospection option to schema-ast

.changeset/calm-cherries-visit.md, babel.config.js, packages/graphql-codegen-cli/src/config.ts
Tests might be added later but I don't think it is necessary now because it is internal already.
=> feat(cli): export loadCodegenConfig to load codegen configuration files

.changeset/mighty-worms-camp.md, packages/graphql-codegen-cli/src/config.ts
sorry about deleting the template, but it seemed superflous for this trivial change
=> export generateSearchPlaces

.changeset/wicked-bees-rest.md, packages/plugins/typescript/generic-sdk/src/config.ts, packages/plugins/typescript/generic-sdk/src/visitor.ts, packages/plugins/typescript/generic-sdk/tests/__snapshots__/generic-sdk.spec.ts.snap, packages/plugins/typescript/generic-sdk/tests/generic-sdk.spec.ts
Adding a `rawRequest: boolean` config option to the typescript-generic-sdk. This allows the requestor to return `data` and `errors` on the top level.
https://github.com/dotansimha/graphql-code-generator/issues/6854
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings
- [ x ] I have added tests that prove my fix is effective or that my feature works
- [ x ] New and existing …
=> Adding 'rawRequest' config option to typescript-generic-sdk

.changeset/funny-vans-collect.md, packages/plugins/typescript/graphql-request/src/visitor.ts, packages/plugins/typescript/graphql-request/tests/__snapshots__/graphql-request.spec.ts.snap, packages/plugins/typescript/graphql-request/tests/graphql-request.spec.ts
`print` shouldn't be imported as type, as it's a function that's used when supporting `useTypeImports` & `rawRequest` and `documentMode` is not a `string`.
Related #7058
https://codesandbox.io/s/aged-bird-qfoju?file=/types.ts:1556-1604
This is the same test as `Should support rawRequest when documentMode = "documentNode"`, but with the extra config of `useTypeImports` set to `true`
- OS: macOS 11.2.3
- `@graphql-codegen/typescript-graphql-request`: `^4.3.1`
- NodeJS: v16.5.0
- [N/A] I have commented my code, particularly in hard-to-understand areas
- [N/A] I have made corresponding changes to the documentation
=> fix(graphql-request): don't import `print` as type when supporting `useTypeImports` & `rawRequest` and `documentMode` is not a `string`

.changeset/pretty-frogs-leave.md, packages/plugins/typescript/react-query/src/config.ts, packages/plugins/typescript/react-query/src/fetcher-fetch-hardcoded.ts, packages/plugins/typescript/react-query/tests/__snapshots__/react-query.spec.ts.snap, packages/plugins/typescript/react-query/tests/react-query.spec.ts
This PR adds a test case `React-Query › fetcher: hardcoded-fetch › Should generate query correctly with fetch config and fetchParams object` into spec `packages/plugins/typescript/react-query/tests/react-query.spec.ts` for the config parameter `fetchParams` as requested in issue https://github.com/dotansimha/graphql-code-generator/issues/6794#issuecomment-968057226. 
In case the `fetchParams` parameter was set via a YAML config, it does contain an Object instead of a String. However, the Typescript type definition in [config.ts](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/typescript/react-query/src/config.ts#L3) expects a String and doesn't handle the case if an Object was passed via YAML. It is valid to define the parameters as Object according to …
=> issue 6794: add stage 2 failing test case

.changeset/clever-ads-tell.md
Added `patch` changeset for GraphQL16 version bump for packages that were left out in https://github.com/dotansimha/graphql-code-generator/commit/97ddb487ae2d4f54eca9974c960b78c078a2982e#diff-0162fb12b66d02773262d9cb1ea902dbe2f6c3b429593b772c2fa5d3e8293caf
Related #7003 & #7109
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant …
=> Add patch GraphQL 16 changeset for packages that were left out

.changeset/four-humans-rescue.md, packages/plugins/typescript/react-query/src/variables-generator.ts, packages/plugins/typescript/react-query/tests/react-query.spec.ts
react-query plugin
Found a little bug after testing new `exposeMutationKeys` option: it adds unnecessary bracket. This PR provides fix and test case for it.
Related PR https://github.com/dotansimha/graphql-code-generator/pull/6863
Related issue #6724 
- OS: macOS Big Sur 11.2.3 (20D91)
- NodeJS: v12.22.6
=> fix(react-query): exposeMutationKey adds unnecessary bracket

.changeset/real-pugs-leave.md, packages/plugins/typescript/mongodb/src/visitor.ts, packages/plugins/typescript/mongodb/tests/typescript-mongo.spec.ts, website/docs-templates/typescript-mongodb.md
* Change ObjectID import to ObjectId, due to ObjectID is deprecated
in mongodb v4.1
Changes ObjectID import from mongodb to ObjectId instead.
Related #6830
- [X ] Bug fix (non-breaking change which fixes an issue)
- OS: linux
- `@graphql-codegen/typescript-mongodb`: 2.1.4
- NodeJS: 14.17.4
- mongodb: 4.1.3
=> Change ObjectID import to ObjectId

website/src/lib/plugins.ts
The RTK-Query plugin was missing the `react` tag, so this adds it. I hope I am not missing another place where I have to add it.
=> docs: add react tag to rtk-query plugin

.changeset/orange-keys-guess.md, .gitattributes, packages/presets/gql-tag-operations/src/process-sources.ts, packages/presets/gql-tag-operations/tests/fixtures/crlf-operation.ts, packages/presets/gql-tag-operations/tests/gql-tag-operations.spec.ts
Related #7362 
`gql-tag-operations` generates invalid types on Windows, causing compile-time error when attempting to launch the application.
Source file is read by `@graphql/tools` using `fs.promises.readFile`, which means that the linebreaks are read as-is and the result will be different depending on the OS: it will contain LF (`\n`) on Linux/MacOS and CRLF (`\r\n`) on Windows.
In most scenarios that would be OK. However, `gql-tag-operations` is using the resulting string as a TypeScript type. Which means that the string will be compared against a template literal, for example:
```typescript
`
query a {
a
}
` === '\n query a {\n    a\n  }\n '
```
According to [clause 12.8.6.2 of ECMAScript Language Specification](https://tc39.es/ecma262/#sec-static-semantics-trv), when comparing …
=> fix: gql-tag-operations generates invalid types on Windows #7362

.changeset/light-rockets-design.md, packages/plugins/typescript/rtk-query/src/visitor.ts, packages/plugins/typescript/rtk-query/tests/__snapshots__/rtk-query.spec.ts.snap, packages/plugins/typescript/rtk-query/tests/rtk-query.spec.ts
does not export an attempt to inject the rtk query api for graphql fragment files
https://github.com/dotansimha/graphql-code-generator/issues/7278
repro of issue: https://github.com/hkasemir/gql-codegen-issue
- OS: Mac OS Big Sur (11.2.3)
- `@graphql-codegen/typescript-rtk-query`: 2.2.1
- NodeJS: 17.2.0
=> fix(rtk query): bad api export in fragment generated files [issue #7278]

.changeset/yellow-walls-refuse.md, packages/plugins/typescript/react-query/src/config.ts, packages/plugins/typescript/react-query/src/variables-generator.ts, packages/plugins/typescript/react-query/src/visitor.ts, packages/plugins/typescript/react-query/tests/react-query.spec.ts
This adds support for a `getKey` function on generated infinite queries when using the `react-query` plugin. Currently, the `getKey` function is only available on regular queries. By adding a `getKey` function to infinite queries as well, it will allow safer and more useful invalidations for people who rely on the generated infinite queries.
Related #7365
An additional test was added that verifies the `getKey` function is added to infinite queries as well as to regular queries. See the test `exposeQueryKeys: true, addInfiniteQuery: true`
=> React-query: `getKey` on infinite queries

.changeset/early-carrots-exist.md, packages/plugins/typescript/react-query/src/fetcher-custom-mapper.ts, packages/plugins/typescript/react-query/tests/react-query.spec.ts, website/docs-templates/typescript-react-query.md
Add a new `options?: HeadersInit` property on the `useQuery.fetcher` function.
Most of the time, fetchers can have more information than the `query` & the `variables`.
For example, the GraphQL Request fetcher can receive [`requestHeaders`](https://github.com/prisma-labs/graphql-request/blob/12c2e8d387bf2b4f467335babd2989f0a1d33f53/src/types.ts#L75).
Adding this PR would allow the `prefetchQuery` to be used like this : 
```typescript
queryClient.prefetchQuery(
useCoursesByUserQuery.getKey(variables),
useCoursesByUserQuery.fetcher(variables, options), // `Ex: { Authorization: "Bearer xxx" }`
);
```
https://github.com/dotansimha/graphql-code-generator/issues/7370
Using the same sets of current tests.
I just updated …
=> [React-Query]: Add `options` to exposed fetcher

.changeset/breezy-llamas-chew.md, packages/plugins/typescript/urql/package.json, packages/plugins/typescript/urql/src/visitor.ts, packages/plugins/typescript/urql/tests/urql.spec.ts
This PR fixes the `dedupeOperationSuffix` option for hooks generated by `typescript-urql`.
Related #7384
Reproduction sandbox: https://codesandbox.io/s/loving-lalande-hs196
Unit test added to verify deduping of operation suffix.
=> fix(typescript-urql): respect dedupeOperationSuffix in hooks

.changeset/hungry-crabs-agree.md, dev-test/githunt/types.vueApollo.ts, packages/plugins/typescript/vue-apollo/src/visitor.ts, packages/plugins/typescript/vue-apollo/tests/vue-apollo.spec.ts
Support `useLazyQuery` for vue-apollo plugin
Related #5258
- OS: macOS 11.6.1
- `@graphql-codegen/...`: e1285609a9cb08a8f15e75254ca8fc7d1684d4ad
- NodeJS: v17.0.1
=> feat: useLazyQuery for vue-apollo plugin

.changeset/fluffy-pumpkins-build.md, packages/plugins/other/visitor-plugin-common/src/avoid-optionals.ts, packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/other/visitor-plugin-common/src/types.ts, packages/plugins/typescript/resolvers/src/visitor.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts, packages/plugins/typescript/typescript/tests/typescript.spec.ts
Fix https://github.com/dotansimha/graphql-code-generator/issues/7005.
Possibly broken in #5112.
Failing test diff:
```diff
-   users?: Resolver<Array<ResolversTypes['User']>, ParentType, ContextType, RequireFields<QueryUsersArgs, 'filter'>>;
-   ping?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
+   users: Resolver<Array<ResolversTypes['User']>, ParentType, ContextType, RequireFields<QueryUsersArgs, 'filter'>>;
+   ping: Resolver<ResolversTypes['String'], ParentType, ContextType>;
+ };
```
- OS: 
- NodeJS: 
If this is a relatively large or complex change, …
=> fix(typescript-resolvers): Fix optional resolver types

.changeset/witty-carrots-clap.md, packages/graphql-codegen-cli/src/codegen.ts, packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
------
On a 4sec total build project:
**Before**
**After**
=> Performance work: resolvers plugins, documents loading

.changeset/famous-bikes-punch.md, packages/graphql-codegen-cli/src/codegen.ts, packages/graphql-codegen-cli/src/utils/cli-error.ts, packages/graphql-codegen-cli/tests/codegen.spec.ts
All syntax errors in referenced `*.graphql` files resulted in the CLI displaying the generic error message:
> Something went wrong
Investigation found that that the error details were captured by `listr` but were not printed to the CLI. This change checks for aggregate errors, and include them in the CLI error output.
Related #5064
Tested by running against valid and invalid .graphql files, to ensure the error details were printed out as follows:
```
Something went wrong
Failed to load schema for "path/to/output-types.ts"
Failed to load schema from path/a.graphql,path/b.graphql:
Syntax Error: Expected ":", found Name "credentialSetup".
GraphQLError: Syntax Error: …
```
=> #5064 Display detailed errors from CLI

.changeset/empty-phones-laugh.md, packages/plugins/typescript/graphql-request/package.json
v4 of `graphql-request` has `graphql@16` in their peer range.
N/A
N/A
N/A
N/A
=> fix(graphql-request): allow v4 as peer dependency

.changeset/pink-mugs-cover.md, packages/plugins/java/java/src/visitor.ts, packages/plugins/java/java/tests/java.spec.ts
* Adds a failing test for generated Java enum list args
* Fixes the issue by returning the enums if args contain an Iterable<String> instead of Iterable<Enum>
Related #7002
Can be found in the linked issue.
Tested through the added unit test and in a project that has query arguments which contain a list of enum options.
- OS: Debian 10
- `@graphql-codegen/java`: 
- NodeJS: 12.22.7
=> Fix validation of enum list args for Java

.changeset/serious-houses-repeat.md, packages/plugins/typescript/react-query/src/fetcher-custom-mapper.ts, packages/plugins/typescript/react-query/src/fetcher-graphql-request.ts, packages/plugins/typescript/react-query/tests/react-query.spec.ts
Fixes https://github.com/dotansimha/graphql-code-generator/issues/7444
=> fix(react-query): avoid unused `RequestInit` import when fetcher is not exposed

.changeset/sweet-poets-begin.md, packages/plugins/typescript/react-query/src/fetcher-custom-mapper.ts, packages/plugins/typescript/react-query/tests/react-query.spec.ts
Fixes https://github.com/dotansimha/graphql-code-generator/issues/7444#issuecomment-1034370768
=> fix(plugins/react-query): remove useless `RequestInit` import for custom fetcher

website/docs-templates/typescript-react-apollo.md
This adds the video https://graphql.wtf/episodes/29-apollo-client-3-with-graphql-code-generator to the `typescript-react-apollo` plugin page.
=> docs(react-apollo): add graphql wtf video

.changeset/yellow-sloths-check.md, packages/plugins/typescript/apollo-angular/src/config.ts, packages/plugins/typescript/apollo-angular/src/visitor.ts
TypeScript 4.3 added a new feature to explicitly mark class override. It can be enabled with the `noImplicitOverride` compiler option.
This PR adds the `override` modifier so that generated angular classes don't fail the compilation when this flag is on.
Related #7038 
Can't go much lighter than this PR :)
=> Add override modifier in apollo-angular to abide by noImplicitOverride compiler options

renovate.json
Uses the newly created shared renovate config: https://github.com/the-guild-org/shared-config/blob/main/renovate.json
This The Guild preset configures:
- extend `config:base`
- automerges unless major
- add `dependencies` label to PR
- group all non-major updates into a single PR
- Higher priority to `@the-guild/*` and `@guild-docs/*` package (website related)
Any other suggestion?
=> chore(renovate): use a shared preset

.changeset/twenty-boats-pull.md, packages/graphql-codegen-cli/src/presets.ts
Developing presets locally fails without this change. 
The change is similar to what is already being done in `getPluginByName`
Config:
```yaml
schema: "https://api.spacex.land/graphql"
generates:
generated/src:
preset: dist/my-preset.js
```
Error on generate:
```
Unable to find preset matching 'dist/my-preset.js'
Install one of the following packages:
- @graphql-codegen/dist/my-preset.js
- @graphql-codegen/dist/my-preset.js-preset
- dist/my-preset.js
Error: Unable to find preset matching dist/my-preset.js
at getPresetByName (/Users/staffordwilliams/git/graphql-code-generator/packages/graphql-codegen-cli/dist/bin.js:405:11)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async /Users/staffordwilliams/git/graphql-code-generator/packages/graphql-codegen-cli/dist/bin.js …
```
=> Preset: resolve absolute path

.changeset/moody-elephants-hope.md, packages/plugins/flow/resolvers/src/index.ts, packages/plugins/flow/resolvers/src/visitor.ts, packages/plugins/flow/resolvers/tests/__snapshots__/flow-resolvers.spec.ts.snap, packages/plugins/flow/resolvers/tests/flow-resolvers.spec.ts
This change corrects tests and fixes the issue of the `flow-resolver` plugin not adding the correct imports to the generated file.
Related #5322 
Bug fix (non-breaking change which fixes an issue)
For now, just unit tests in `packages/plugins/flow/resolvers/tests/flow-resolvers.spec.ts` - these were incorrect, so have been corrected.
- OS: MacOS 12
- NodeJS: 14
=> Fix: Flow Plugin not defining some types in generated file

.changeset/fresh-islands-own.md, packages/plugins/java/kotlin/src/config.ts, packages/plugins/java/kotlin/src/visitor.ts, packages/plugins/java/kotlin/tests/kotlin.spec.ts
Related #7631
Added an `omitJvmStatic` option to Kotlin plugin, so that its output can be used in Kotlin Multiplatform Project.
Included a unit test with the PR.
=> add omitJvmStatic to Kotlin plugin

.changeset/brave-lies-yell.md, packages/presets/near-operation-file/src/resolve-document-imports.ts, packages/presets/near-operation-file/tests/near-operation-file.spec.ts
This fixes the issue near-operation-file-preset does not import root type when a fragment spread a fragment without any fields.
Related #7547 
| after | before |
|--|--|
| ![image](https://user-images.githubusercontent.com/1481277/156628846-115b98a6-94e0-43e0-aaef-d735a19423f7.png) | ![image](https://user-images.githubusercontent.com/1481277/156628889-fe23db7b-feaf-4a0c-8b60-3c89a5c1e90d.png) |
=> [near-operation-file-preset] Importing root types when a fragment spread a fragment without any field

.changeset/soft-colts-matter.md, packages/plugins/typescript/resolvers/src/index.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
This fixes #7566 wich creates typescript errors on generated file when using `directiveResolverMappings` with external type (details and example in issue).
I used the example given in the issue and could generate the expected output. Tested in a production project and it works perfectly.
👆 I might need some help on the tests
=> Fix #7566 external resolver name export for directiveResolverMappings

.changeset/brave-apricots-yawn.md, packages/plugins/typescript/apollo-angular/src/visitor.ts, packages/plugins/typescript/apollo-angular/tests/apollo-angular.spec.ts
PR #7322 adds the option `addExplicitOverride` with the `override` modifier to the `document` property.
When making use of the config option `namedClient` like so:
```yaml
config:
namedClient: 'customName'
```
This ends up in a `client` property that doesn't have the required `override` modifier. 
Related #7548
I added a jest test for `addExplicitOverride` since it was missing and I added the `customName` check in there as well.
None.
=> Fix addExplicitOverride for custom namedClient

.changeset/rotten-coins-flow.md, .changeset/wet-tomatoes-suffer.md, dev-test/githunt/types.react-query.ts, packages/plugins/typescript/react-query/src/fetcher-custom-mapper.ts, packages/plugins/typescript/react-query/src/fetcher-fetch-hardcoded.ts, packages/plugins/typescript/react-query/src/fetcher-fetch.ts, packages/plugins/typescript/react-query/src/fetcher-graphql-request.ts, packages/plugins/typescript/react-query/src/visitor.ts, packages/plugins/typescript/react-query/tests/react-query.spec.ts
corrects behavior so that `typescript-react-query` respects `useTypeImports` flag
fixes #7666 main issue
fixes #7661 the graphql-request fetcher portion
tests all pass.  added test to [prove functionality](https://github.com/dotansimha/graphql-code-generator/blob/6cdb68b9123dccc80009b2af9ac66bb7de961cd9/packages/plugins/typescript/react-query/tests/react-query.spec.ts#L528).
n/a
=> React-query: useTypeImports

.changeset/chatty-colts-peel.md, packages/plugins/typescript/graphql-request/src/visitor.ts, packages/plugins/typescript/graphql-request/tests/__snapshots__/graphql-request.spec.ts.snap
The errors property from the return type has been removed, because it is never
returned by `graphql-request`. Instead, failed requests throw a `ClientError`.
Also, data is no longer optional, because it always exists for successful responses.
Related #7592
Existing snapshots have been updated.
=> fix: fix rawRequest return type

.changeset/loud-grapes-reflect.md, dev-test/githunt/types.urql.tsx, packages/plugins/typescript/urql-graphcache/src/index.ts, packages/plugins/typescript/urql-graphcache/tests/__snapshots__/urql.spec.ts.snap
This preserves the following graphql types:
* `UNION_TYPE_DEFINITION`
* `INPUT_OBJECT_TYPE_DEFINITION`
* `OBJECT_TYPE_DEFINITION`
when generating graphql typescript types using `typescript-urql-graphcache`
Related https://github.com/dotansimha/graphql-code-generator/issues/7447
This has been tested in my own [repo](https://github.com/AndysonDK/syncbase)
=> update WithTypename to preserve original graphql type

.changeset/two-dolphins-deliver.md, dev-test/codegen.yml, dev-test/gql-tag-operations-masking-star-wars/gql/fragment-masking.ts, dev-test/gql-tag-operations-masking-star-wars/gql/gql.ts, dev-test/gql-tag-operations-masking-star-wars/gql/graphql.ts, dev-test/gql-tag-operations-masking-star-wars/gql/index.ts, dev-test/gql-tag-operations-masking-star-wars/schema.json, dev-test/gql-tag-operations-masking-star-wars/src/index.tsx, packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts, packages/plugins/typescript/operations/tests/ts-documents.spec.ts, packages/presets/gql-tag-operations/tests/fixtures/union-fragment.ts
Related #7811 
`useFragment` for union was giving a type error because `$fragmentName` was not set to fragment subtypes when `inlineFragmenType: mask` was set.
- https://codesandbox.io/s/gql-tag-operations-preset-fragment-masking-union-bug-2trm1w?file=/fixed.tsx:362-507
- https://codesandbox.io/s/gql-tag-operations-preset-fragment-masking-union-bug-2trm1w?file=/__generated__fixed__/graphql.ts:1923-2609
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
=> fix(typescript-operations): Generate ` $fragmentName` for fragment subtypes for fragment masking

.changeset/fifty-students-fail.md, packages/plugins/typescript/operations/src/visitor.ts, packages/presets/near-operation-file/tests/fixtures/issue-7798-child.ts, packages/presets/near-operation-file/tests/fixtures/issue-7798-parent.ts, packages/presets/near-operation-file/tests/near-operation-file.spec.ts
Fix bug of #7798 
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] Any dependent changes have been merged and published in downstream modules~~
=> fix(typescript-operations): Import type definitions of dependent fragments when `inlineFragmentType` is `mask`

website/docs/guides/react.mdx
In order to be able to import the following:
```typescript
import { postsQueryDocument } from "./graphql/generated"
```
one needs to name the query in the `.graphql` file accordingly. Following the guide (and therefore not doing so) can lead to confusion as the generated document will just be called `Document` instead of `postsQueryDocument`, leading to various issues and headaches.
Related # none
- OS: …
=> Name example query in React guide

website/docs/getting-started/installation.mdx
I also wanted to fix this, which errors (there is no `graphql-codegen` script—you have to do `npx graphql-codegen init`), but I don't see where `<PackageRun>` is defined?
=> Fix typo in docs

.changeset/wicked-geckos-do.md, packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts, packages/plugins/other/visitor-plugin-common/src/utils.ts, packages/plugins/typescript/type-graphql/src/visitor.ts, packages/plugins/typescript/typescript/src/visitor.ts, packages/plugins/typescript/typescript/tests/typescript.spec.ts
Support for the `@oneOf` directive on input object types.
Things to consider:
- Should we make this available behind a flag?
`@onOf` is still in the RFC stage and the behavior could change slightly. Should we, therefore, make this opt-in?
____
References:
- https://github.com/graphql/graphql-js/pull/3513#issuecomment-1137703851
- https://github.com/graphql/graphql-spec/pull/825
=> feat: support generating correct types for `@oneOf` input types

.changeset/long-mice-cross.md, packages/plugins/typescript/urql-graphcache/src/index.ts, packages/plugins/typescript/urql-graphcache/tests/__snapshots__/urql.spec.ts.snap, packages/plugins/typescript/urql-graphcache/tests/urql.spec.ts
The `typescript-urql-graphcache` plugin causes a typescript error in the generated type file for the type `GraphCacheOptimisticUpdaters` if the schema has no mutations.
Related Issue: https://github.com/dotansimha/graphql-code-generator/issues/7910
- Bug fix (non-breaking change which fixes an issue)
- A test has a schema with no GraphQL mutations to cover this edge case
=> URQL GraphCache creates type error when there are no mutations

.changeset/afraid-clocks-ring.md, packages/graphql-codegen-cli/package.json, packages/graphql-codegen-cli/src/init/helpers.ts, yarn.lock
Reverts dotansimha/graphql-code-generator#7991
Upgrading `latest-version` to `6.0.0` broke the CLI, let's find another way to fix https://github.com/dotansimha/graphql-code-generator/issues/7990
=> Revert recent `latest-version` upgrade due to ESM issues

.changeset/early-pots-leave.md, packages/graphql-codegen-cli/src/utils/cli-error.ts, packages/graphql-codegen-cli/src/utils/is-browser.ts
not sure why we need the browser or node check. This isn't really meant for browsers and to make it work for browser we need to refactor many things.
=> refactor: remove unnecessary browser check

.changeset/spotty-waves-whisper.md, packages/plugins/other/visitor-plugin-common/src/enum-values.ts, packages/plugins/typescript/typescript/tests/typescript.spec.ts
Enums with falsy values were getting generated incorrectly when using enumsAsTypes. The cause was truthyness check on the value before creating the value map.
I've removed the truthy check so instead it only checks if `value !== name`.
I considered adding a `typeof value !== "undefined"` but as far as I'm aware, value is never undefined. For enums without a value map, then the value is the same as the name.
Related #7898
[CodeSandbox](https://codesandbox.io/s/intelligent-dubinsky-5rerq2) demonstrating problem
A test has been added in this PR
- OS: Linux
- NodeJS: v16.15.0
```
"@graphql-codegen/core": "2.5.1",
"@graphql-codegen/typescript": "2.4.11",
"graphql": "16.5.0"
```
=> fix: ensure falsy enum values are still mapped

.changeset/pink-tips-grin.md, packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
On the [plugin documentation page](https://www.graphql-code-generator.com/plugins/typescript-resolvers) I noticed that `rootValueType` and `directiveContextTypes` were swapped around.
=> docs: Swapping rootValueType with directiveContextTypes for correctness

.changeset/large-poets-yell.md, packages/plugins/typescript/type-graphql/src/visitor.ts, packages/plugins/typescript/type-graphql/tests/type-graphql.spec.ts
When using typescript-type-graphql, the optional fields from an input are not optional
Related #8001 
- [x ] Bug fix (non-breaking change which fixes an issue)
- OS: [Linux]
- NodeJS: [16.15.1]
- graphql version: [15.3.0]
- @graphql-codegen/cli version(s): [ 2.6.2]
- @graphql-codegen/typescript-type-graphql version(s): [ 2.2.14]
=> fix optional input type fields for graphql-input

.changeset/fuzzy-bears-speak.md, packages/plugins/typescript/graphql-request/src/visitor.ts, packages/plugins/typescript/graphql-request/tests/graphql-request.spec.ts
This adds support for `importOperationTypesFrom` config option for the `typescript-graphql-request` plugin.
Related #7114.
The documentation already mentions this config option for the plugin but the plugin ignores it.
I reran the codegen configuration in #7114 and verified that it correctly adds the type prefix.
- ~I have commented my code, particularly in hard-to-understand areas~
- ~I have made corresponding changes to the documentation~
- ~I have added tests that prove my fix is effective or that my feature works~
-  ~Any dependent changes have been merged and published in downstream modules~
=> Honor importOperationTypesFrom in graphql-request generator

.changeset/purple-eyes-fix.md, packages/utils/plugins-helpers/src/oldVisit.ts
Fix the compiler error:
```
node_modules/@graphql-codegen/plugin-helpers/oldVisit.d.ts:5:75 - error TS2339: Property 'enter' does not exist on type '{ readonly enter?: ASTVisitFn<NameNode> | undefined; readonly leave: ASTReducerFn<NameNode, unknown>; } | { readonly enter?: ASTVisitFn<DocumentNode> | undefined; readonly leave: ASTReducerFn<...>; } | ... 41 more ... | undefined'.
5     enter?: Partial<Record<keyof NewVisitor, NewVisitor[keyof NewVisitor]['enter']>>;
~~~~~~~
node_modules/@graphql-codegen/plugin-helpers/oldVisit.d.ts:6:75 - error TS2339: Property 'leave' does not exist on type '{ readonly enter?: ASTVisitFn<NameNode> | undefined; readonly leave: ASTReducerFn<NameNode, unknown>; } | { readonly enter?: ASTVisitFn<DocumentNode> | undefined; readonly leave: ASTReducerFn<...>; } | …
```
=> Fix TS type error on strictNullChecks: true

.changeset/shiny-cameras-reply.md, dev-test/githunt/types.urql.tsx, packages/plugins/typescript/urql-graphcache/src/index.ts, packages/plugins/typescript/urql-graphcache/tests/__snapshots__/urql.spec.ts.snap
This issue was detected in https://github.com/FormidableLabs/urql/issues/2502 which seems to link to https://github.com/dotansimha/graphql-code-generator/pull/7681 the change there looks good but introduces a subtile difference, we remove the `?` which was appended after the property-key. This PR adds onto that change by adding `Partial<>` which should have the same affect as what we were doing with `{ [K in Exclude<keyof T, '__typename'>]?: T[K] }`.
Fixes https://github.com/FormidableLabs/urql/issues/2502
Creating a testable scenario 😅 
Did a quick test in the `dev-test/githunt/urql.types` that looked like:
```ts
const config: GraphCacheConfig = {
optimistic: {
submitComment: (vars) => ({
__typename: 'Comment',
repoName: …
```
=> Avoid enforcing return/get the complete object

.changeset/serious-doors-lick.md, packages/graphql-codegen-cli/package.json, yarn.lock
`tslib` is used in generated code. In the monorepo it doesn't crash since it uses the one we have in `monorepo` but we should provide this part of package.
Related #8075 
Or should we just put this as a peer-dep 🤔
=> chore: add tslib as dep

website/src/pages/docs/advanced/profiler.mdx, website/src/pages/docs/config-reference/codegen-config.mdx, website/src/pages/docs/getting-started/installation.mdx, website/src/pages/plugins/typescript/typescript-oclif.mdx
Based on my research when we try to use `npx graphql-codegen` it resolves to this old package https://www.npmjs.com/package/graphql-codegen and the alias that seems to work is `graphql-code-generator`
Related #8074 
=> docs: use graphql-code-generator in npx example

package.json, yarn.lock
I think Node.js 18.6.0 changed something in the fs module (or even introduced a bug) because previously bob build never failed when running two tsc processes in parallel. 🤔 
Anyways, upgrading bob to 3.0.1 solves this issue as it runs tsc for esm and commonjs in sequence.
=> chore: upgrade bob to the latest version

.changeset/smooth-beans-fetch.md, packages/graphql-codegen-cli/src/cli.ts
I did a local repro for #7546 that reported duplicated error messages from CLI output.
When watcher is enabled, duplicated error messages don't show because we properly handle promise fail callback:
https://github.com/dotansimha/graphql-code-generator/blob/f2ecf73ff858e091901c7f40df9b00fd8a3a5560/packages/graphql-codegen-cli/src/utils/watcher.ts#L70-L71
The duplicated came from the main `try/catch` that unnecessarily rethrow the error returned by `generate()`.
=> fix(cli): prevent duplicated error messages on fail (without watcher)

package.json, yarn.lock
When reviewing and testing https://github.com/dotansimha/graphql-code-generator/pull/7988, I realized that we don't use `globby` directly, `@graphql-tools/*` do.
=> chore(deps): drop unused `globby` dependency

.changeset/spotty-cherries-drop.md, dev-test/githunt/types.urql.tsx, packages/plugins/typescript/urql/src/visitor.ts, packages/plugins/typescript/urql/tests/__snapshots__/urql.spec.ts.snap, packages/plugins/typescript/urql/tests/urql.spec.ts
Add missing generic type. No dependencies and all information for this is already present, just not wired up.
Related #7976
N/A
The change is very simple and can be verified by looking at the one line of code which was changed in conjunction with the type signature [of useQuery here](https://github.com/FormidableLabs/urql/blob/main/packages/react-urql/src/hooks/useQuery.ts#L49).
- `@graphql-codegen/typescript-urql` version: 3.5.12
=> Add useQuery argument generic type

.changeset/curly-clocks-warn.md, packages/graphql-codegen-cli/src/cli.ts
When I run `yarn graphql-codegen init`, it just print some options and is ended immediately. So I add `await` operator to prevent it from early returning.
Related #8162 
`yarn graphql-codegen init`
I haven't tested this. But if it is needed tell me how I can test.
=> fix(cli): prevent early returning on init cmd

.changeset/smart-islands-fetch.md, packages/plugins/other/visitor-plugin-common/src/base-visitor.ts, packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts
After https://github.com/dotansimha/graphql-code-generator/pull/8077 every fragment import was with `.js` extension and option wouldn't work. 
Related #8186
- OS:
- NodeJS:
If this is a relatively …
=> Fix emitLegacyCommonJSImports to being passed

.changeset/rotten-lemons-wash.md, packages/graphql-codegen-cli/src/codegen.ts, packages/graphql-codegen-cli/src/load.ts, packages/graphql-codegen-cli/tests/codegen.spec.ts
Fixes regression introduced in https://github.com/dotansimha/graphql-code-generator/issues/7546
=> fix(ci): regression on error output

.changeset/twelve-insects-invite.md, packages/plugins/typescript/generic-sdk/src/visitor.ts, packages/plugins/typescript/generic-sdk/tests/__snapshots__/generic-sdk.spec.ts.snap, packages/plugins/typescript/generic-sdk/tests/generic-sdk.spec.ts
- Respect GraphQL Live Queries like Subscriptions and use the stream return types (`AsyncIterable` or `Observable`).
- Previously if there was no `usingObservableFrom` set in the configuration, the plugin was using `Promise` as subscriptions' return type, and this is wrong. Now it uses `AsyncIterable` in this case.
=> feat(generic-sdk): respect live queries & use AsyncIterable if possible

packages/graphql-codegen-cli/src/config.ts
This is just a typo fix in the help menu
=> Fix typo in help options

packages/plugins/other/visitor-plugin-common/tests/parse-mapper.spec.ts
This adds an additional test to how mapper strings are parsed 
Related #8050
Adds new unit test
N/A - ran `yarn test-and-build`
- OS:
- `@graphql-codegen/visitor-plugin-common`:2.12.1
- NodeJS: v18.7.0
As discussed with @n1ru4l  - this just adds an extra test to prevent regression on using custom generics inside mappers, because it felt to me like I was hacking codegen.
=> chore(parse-mapper): Add extra test for using a custom generic mapper

packages/plugins/typescript/type-graphql/src/config.ts, website/public/config.schema.json
The definition in `packages/plugins/typescript/type-graphql/src/config.ts` was incorrectly specifying `@type: string[]` in the docs, which was overriding the derived type used by the `typescript-schema-generator`:
> Note that we needed to use @TJS-type instead of just @type because of an [issue with the typescript compiler](https://github.com/Microsoft/TypeScript/issues/13498). ([source](https://www.npmjs.com/package/typescript-json-schema))
Related #8209
In our project's `codegen.yml`:
Valid: …
=> Fix json schema for TypeGraphQLPluginConfig

.changeset/twenty-beds-boil.md, package.json, packages/plugins/typescript/urql-graphcache/package.json, packages/plugins/typescript/urql-svelte-operations-store/package.json, website/src/pages/docs/getting-started/development-workflow.mdx, yarn.lock
We have bumped our major, for types the biggest change is our new variables type https://github.com/FormidableLabs/urql/pull/2607
Related https://github.com/dotansimha/graphql-code-generator/issues/8276
Seeing is we see issues like https://github.com/FormidableLabs/urql/issues/2668 or https://github.com/FormidableLabs/urql/issues/2639 as well 😅 
Have left this in in case we see issues in the tests 😅 but should be good unless the new variables type includes issues, we have tested it on our side and it didn't but it still could
Ran locally on our application
=> upgrade to the new urql major

website/src/pages/docs/advanced/how-does-it-work.mdx
As discussed with @n1ru4l, GraphQL Code Generator requires fragments and operations to have unique names, otherwise it will throw an error. Stating this requirement feels sensible.
=> Operations and fragments must be uniquely named

.changeset/sweet-comics-scream.md, packages/plugins/typescript/graphql-request/src/visitor.ts, packages/plugins/typescript/graphql-request/tests/__snapshots__/graphql-request.spec.ts.snap, packages/plugins/typescript/graphql-request/tests/graphql-request.spec.ts
This PR fixes a bug where the graphql-request plugin would not add a .js extension the `graphql-request/dist/types.dom` path in the generated SDK when using `emitLegacyCommonJSImports: false`. This would cause Typescript to error when using the `module: nodenext` compiler option.
```
path/to/generated-file.ts:2:22 - error TS2307: Cannot find module 'graphql-request/dist/types.dom' or its corresponding type declarations.
2 import * as Dom from 'graphql-request/dist/types.dom';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Related #8022 (issue) and #8235 (stale PR)
None
I've tested on a local project and can attest that Typescript with `module: nodenext` compiles code generated by this branch, but does not successfully compile code without these changes.
Otherwise the tests provide coverage for this …
=> graphql-request: support emitLegacyCommonJSImports: false

.changeset/six-readers-hunt.md, packages/graphql-codegen-cli/src/codegen.ts, packages/utils/plugins-helpers/package.json, packages/utils/plugins-helpers/src/types.ts, yarn.lock
Fixes https://github.com/dotansimha/graphql-code-generator/issues/8307
=> fix(cli): support ApolloEngine loader in TypeScript config

.changeset/violet-sloths-sparkle.md, packages/graphql-codegen-cli/src/hooks.ts
Related to https://github.com/dotansimha/graphql-code-generator/issues/8382
=> fix(cli): properly print error that occurred during hook execution

website/src/category-to-packages.mjs, website/src/lib/plugins.ts, website/src/pages/plugins/typescript/_meta.json, website/src/pages/plugins/typescript/typescript-mock-data.mdx
Add [graphql-codegen-typescript-mock-data](https://github.com/ardeois/graphql-codegen-typescript-mock-data) in plugins page. It's a plugin for building mock data based on the schema. Very useful in unit test to avoid manually creating your mocks.
It's not very popular yet, but the plugin is already used by multiple users and I'm maintaining it for now
I'm considering moving this project to your repo so you can own it, but this will be done later.
Note I didn't create any issue as it's a documentation PR only, but let me know if you prefer me to create an issue
=> doc: add graphql-codegen-typescript-mock-data plugin in doc

.changeset/@graphql-codegen_cli-8452-dependencies.md, .changeset/modern-rabbits-rescue.md, packages/graphql-codegen-cli/package.json, packages/graphql-codegen-cli/src/config.ts, yarn.lock
conflict with graphql-config also using `TypeScriptLoader()`, causing a double `ts-node` register.
#8437
=> TS config file loading issue

.changeset/beige-buckets-sleep.md, packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts
#7978 added `.js` extensions all over the place. But this one seems wrong. In a typescript project, it will for example generate
`import * as Operations from './UserSelection.gql.js';` resulting in a bunch of errors because the files aren't there (they are `.ts` files)
#8370 #8331
=> Remove extension from operations file import

.changeset/gold-mirrors-refuse.md, packages/presets/client/src/index.ts, website/src/pages/docs/guides/react-vue.mdx
Related #8471
Confirmed locally that it resolves #8471
- OS: all
- NodeJS: v14, v16
- `graphql` version: 16.6.0
- `@graphql-codegen/cli`: 2.13.6
=> feat(preset/client): allow use of enumsAsType config option

.changeset/nine-shrimps-beam.md, packages/presets/graphql-modules/src/builder.ts, packages/presets/graphql-modules/src/index.ts, packages/presets/graphql-modules/tests/builder.spec.ts, packages/presets/graphql-modules/tests/integration.spec.ts
This PR take the `config.useTypeImports` into account for the `graphql-modules` plugin.
Related [KitQL issue](https://github.com/jycouet/kitql/issues/234)
=> :sparkles: NEW: handle global config.useTypeImports in graphql-modules

.changeset/dry-pianos-grab.md, dev-test/gql-tag-operations-masking-star-wars/gql/fragment-masking.ts, dev-test/gql-tag-operations-masking-star-wars/gql/graphql.ts, dev-test/gql-tag-operations-masking/gql/fragment-masking.ts, dev-test/gql-tag-operations-masking/gql/graphql.ts, dev-test/gql-tag-operations/graphql/fragment-masking.ts, dev-test/gql-tag-operations/graphql/graphql.ts, packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts, packages/plugins/typescript/operations/tests/ts-documents.spec.ts, packages/presets/client/src/fragment-masking-plugin.ts, packages/presets/client/tests/client-preset.spec.ts, packages/presets/gql-tag-operations/src/fragment-masking-plugin.ts, packages/presets/gql-tag-operations/tests/gql-tag-operations.spec.ts
Fixes https://github.com/dotansimha/graphql-code-generator/issues/8440
=> fix(typescript): Fragment masking ` $fragmentName` and ` $fragmentRefs` are optional

.changeset/sweet-nails-tie.md, dev-test/githunt/types.react-query.ts, packages/plugins/typescript/react-query/src/fetcher-custom-mapper.ts, packages/plugins/typescript/react-query/src/fetcher-fetch-hardcoded.ts, packages/plugins/typescript/react-query/src/fetcher-fetch.ts, packages/plugins/typescript/react-query/src/fetcher-graphql-request.ts, packages/plugins/typescript/react-query/tests/__snapshots__/react-query.spec.ts.snap, packages/plugins/typescript/react-query/tests/react-query.spec.ts
In the typescript-react-query plugin, there are `useInfinite${operationName}Query` hooks. These require a `pageParamKey` to be specified in order for the hook to fetch the next page in paginated queries. Previously, this param was defined as a private param with a preceding '_' and was left unused in the call to the fetcher.
I dropped the private underscore prefix `pageParamKey` and updated the fetcher call so that the `metaData.pageParam` is passed to the `pageParamKey` variable. This allows pagination function properly.
Related #7549 
N/A
Can be tested with:
```
$ yarn build …
```
=> fixes issue #7549

.changeset/eighty-trees-confess.md, packages/plugins/typescript/typescript/src/index.ts
This PR handles instances where the namedType is undefined and prevents it from being passed to the `isIntrospectionType` function which would result in a crash as outlined in  #8389
I've ran and ensured that the existing tests pass
- Operating System: `Linux`
- Node Version:     `v14.19.1`
- Package Manager:  `yarn@1.22.19`
=> fix: handle undefined namedType for introspection

.changeset/@graphql-codegen_cli-8535-dependencies.md, .changeset/loud-feet-brush.md, packages/graphql-codegen-cli/package.json, yarn.lock
`DEBUG=1` now prints some profiling info on files loading:
=> feat(cli): upgrade `@graphql-tools/load` to get benefits of debug info on file loading

.changeset/dirty-beans-shave.md, packages/presets/client/src/index.ts
Forward the `dedupeFragments` config option to plugins.
Related #8103
I ran the fork on my project and fragments were successfully deduped.
=> fix(client-preset): forward dedupeFragments option

.changeset/@graphql-codegen_testing-8556-dependencies.md, .changeset/config.json, .changeset/metal-ravens-juggle.md, packages/plugins/flow/resolvers/tests/flow-resolvers.spec.ts, packages/plugins/flow/resolvers/tests/mapping.spec.ts, packages/plugins/typescript/resolvers/tests/mapping.spec.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts, packages/utils/graphql-codegen-testing/package.json, packages/utils/graphql-codegen-testing/src/index.ts, packages/utils/graphql-codegen-testing/src/mock-graphql-server.ts, packages/utils/graphql-codegen-testing/src/resolvers-common.ts, yarn.lock
Required for migration of community plugins to https://github.com/dotansimha/graphql-code-generator-community
=> feat(testing): update `@graphql-codegen/testing` package + include common resolvers testing helpers and fixtures

.changeset/@graphql-codegen_core-8606-dependencies.md, .changeset/twenty-dots-pump.md, packages/graphql-codegen-core/package.json, yarn.lock
Fix https://github.com/dotansimha/graphql-code-generator/issues/8570
=> fix(core): fix validations on fragments/operations naming conflicts

.changeset/afraid-maps-complain.md, packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts, packages/plugins/typescript/typescript/tests/typescript.spec.ts
On #8024 it was suggested to remove support for `declarationKind` all together.
Since this is a breaking change and probably won't happen soon and things are currently broken if using a `declarationKind` other than `type`, I would like to propose hard-coding `@oneOf` declarations to `type`, regardless of the configured `declarationKind` as `type` is the only one working.
Fixes #7938
=> Fix @oneOf support broken with declaration kind other than type

website/src/pages/docs/guides/react-vue.mdx
the install guide for react/vue has a reference to yarn in the npm section.
this is a super minor change so I skipped making an issue.
=> correct npm package install on documentation page

packages/presets/client/src/index.ts
According to https://the-guild.dev/graphql/codegen/docs/guides/react-vue the preset name is `client` not `front-end`
=> fix docs for client-preset

.changeset/thick-ravens-try.md, dev-test/gql-tag-operations-masking-star-wars/gql/gql.ts, dev-test/gql-tag-operations-masking/gql/gql.ts, dev-test/gql-tag-operations-urql/gql/gql.d.ts, dev-test/gql-tag-operations/gql/gql.ts, dev-test/gql-tag-operations/graphql/gql.ts, packages/plugins/typescript/gql-tag-operations/src/index.ts, packages/presets/client/tests/client-preset.spec.ts, packages/presets/gql-tag-operations/tests/gql-tag-operations.spec.ts
Related #8632
It adds some jsdoc comments to support devs when using the `client-preset`:
In case the generated types are out of sync it provides a hint to regenerate them:
It explains why the babel-plugin should be used for production:
Unfortunately I couldn't update the snapshots on my machine.  
Jest showed the following error:
`Jest: Couldn't locate all inline snapshots. `
=> improve autogenerated jsdocs

.changeset/odd-files-train.md, packages/graphql-codegen-cli/package.json, packages/graphql-codegen-cli/src/generate-and-save.ts, packages/graphql-codegen-cli/src/utils/file-system.ts, packages/graphql-codegen-cli/tests/generate-and-save.spec.ts
`graphql-codegen-cli/src/generate-and-save.ts` has more filesystem than neccessary:
1.  Checking for existence before reading. (from the [official nodejs docs](https://nodejs.org/docs/latest-v14.x/api/fs.html#fs_fs_exists_path_callback)):
> Using fs.exists() to check for the existence of a file before calling fs.open(), fs.readFile() or fs.writeFile() is not recommended.
2. After reading the file from disk and generating the hash, the hash is not stored.  
So if the `previousHash` matches the `currentHash` the file will be read again from disk.
3. `mkdirp` is now [built into node](https://nodejs.org/docs/latest-v14.x/api/fs.html#fs_fspromises_mkdir_path_options)
This PR improves all three cases and in addition fixes a bug where `input.cwd` is not passed to `mkdirp`.
All unit tests + …
=> improve generation performance

.changeset/short-buses-share.md, packages/graphql-codegen-cli/src/codegen.ts
Too many generics that TS didn't really complain :/ 
related #8635
=> fix: bad concurrency config

.changeset/funny-keys-sin.md, dev-test/gql-tag-operations/graphql/fragment-masking.ts, packages/presets/client/src/fragment-masking-plugin.ts, packages/presets/client/tests/client-preset.spec.ts, website/src/category-to-packages.mjs, website/src/lib/plugins.ts, website/src/pages/docs/guides/react-vue.mdx, website/src/pages/plugins/presets/_meta.json, website/src/pages/plugins/presets/preset-client.mdx
=> `client-preset`: Plugin page with advanced doc on Fragment Masking + testing helper

.changeset/silent-singers-cover.md, packages/graphql-codegen-cli/src/config.ts
This PR simply averts from using a top level variable for the `TypeScriptLoader` to prevent the unnecessary early registration of `ts-node`
Related #8588
=> fix: top level ts-node registration bug

.changeset/warm-trainers-shout.md, packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts, packages/plugins/typescript/operations/tests/__snapshots__/ts-documents.spec.ts.snap, packages/plugins/typescript/operations/tests/ts-documents.spec.ts
Related https://github.com/dotansimha/graphql-code-generator/issues/7364 and https://github.com/dotansimha/graphql-code-generator/pull/6874
Here's a screenshot of how the test fails without the bugfix:
- I created a new unit test in ts-documents.spec.ts that fails before the fix and succeeds afterwards.
- I plan on testing this on a codebase with a large schema. I'll update this comment when I have verified it works on our codebase.
This is just https://github.com/dotansimha/graphql-code-generator/pull/6874 with a unit test to show what has been fixed 😅 @mvestergaard did all the hard work here
The important features of the schema and query used in the test are:
- The `snake` field returns a `SnakeResult` and all the child fields are within a …
=> Fix issue where selection set flattening uses the wrong parent type

.changeset/@graphql-codegen_cli-8673-dependencies.md, .changeset/twenty-buttons-search.md, packages/graphql-codegen-cli/package.json, yarn.lock
I couldn't find any usage here and `yarn` didn't complain if this was `peerDep` for something. So I think its safe to remove it?
=> chore: remove unused dep ansi-escapes

.changeset/plenty-bottles-prove.md, packages/graphql-codegen-cli/src/hooks.ts, packages/utils/plugins-helpers/src/types.ts
I would like to prepare a PR for #8643.  
Right now the life cycle hooks are using generics and reducers which kind of blocks an easy implementation.
Therefore I removed the reducer and the generic type.
Related #8643
=> improve life cycle hooks typings

.changeset/perfect-dolphins-fix.md, packages/graphql-codegen-cli/src/hooks.ts
For an easier review https://github.com/dotansimha/graphql-code-generator/pull/8652 was split into two PRs.
This is the second part of #8652. It's a small refactoring to replace an entire reducer with 3 lines of code.
<s>Please wait with a review after #8652 was merged and this PR was rebased on top of master.</s>
=> refactoring: remove hooks reducer

.changeset/perfect-mails-allow.md, packages/presets/client/src/index.ts, packages/presets/client/tests/client-preset.spec.ts
Adding the ability to pass through `nonOptionalTypename` to the underlying codegen. This is useful for our team as we use Apollo client in our front end which requires __typename on all queries. By having optional typenames by default we are unable to discriminate unions without extra type checking on types.
https://github.com/dotansimha/graphql-code-generator/issues/8558#issuecomment-1339621125
This is merely passing an extra config to `typescript` and `typescript-operations`
- run codegen without `nonOptionalTypename` in …
=> add nonOptionalTypename config

.changeset/violet-tools-fetch.md, packages/utils/plugins-helpers/src/types.ts
Reflects https://the-guild.dev/graphql/tools/docs/api/interfaces/graphql_tag_pluck_src.GraphQLTagPluckOptions#globalgqlidentifiername in TS types
=> Add globalGqlIdentifierName to the types

.changeset/silver-peaches-itch.md, packages/presets/client/src/index.ts
allow missing possible option avoidOptionals to forwarded configs
Allows optional typescript option to be added to configs.
#8562
- OS:
- NodeJS:
=> add typescript avoidOptionals to forwarded configs

.changeset/loud-crews-itch.md, packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts, packages/plugins/typescript/typescript/tests/typescript.spec.ts
This PR slightly modifies TypeScript code-generation to use idiomatic ES6-style imports (where possible) when importing custom `enumValues`.  
Currently, the following config:
```ts
{ enumValues: { MyEnum: './my-file#MyCustomEnum' } }
```
will produce
```ts
import { MyCustomEnum } from './my-file';
import MyEnum = MyCustomEnum;
export { MyEnum };
```
The namespace import (on the second line above) is a fairly unusual bit of TypeScript syntax.  Some third-party parsers (such as Babel) have difficulty parsing it.  In this scenario, the namespace import is also entirely unnecessary, as we can specify our alias in the original import statement.  
---
After this PR, the output becomes:
```ts
import { MyCustomEnum as MyEnum } from './my-file';
export { MyEnum };
```
This output should be …
=> avoid namespace imports for enums

.changeset/big-mice-switch.md, packages/utils/plugins-helpers/src/types.ts
fix incorrect type.
Related #8579 
=> fix: gqlMagicComment type

.changeset/@graphql-codegen_client-preset-8757-dependencies.md, .changeset/lemon-zebras-hunt.md, .changeset/tasty-adults-doubt.md, packages/plugins/other/visitor-plugin-common/package.json, packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts, packages/presets/client/package.json, packages/presets/client/src/index.ts, packages/presets/client/src/persisted-documents.ts, packages/presets/client/tests/client-preset.spec.ts, website/src/pages/docs/guides/react-vue.mdx, yarn.lock
Closes https://github.com/dotansimha/graphql-code-generator/issues/8756
Closes https://github.com/dotansimha/graphql-code-generator/issues/8822
This implementation is very ugly IMHO, but I could not see a different way in how things are structured right now. 🥲
=> feat: add support for metadata and persisted operations in client preset

.changeset/lemon-zebras-hunt.md, packages/presets/client/src/index.ts, packages/presets/client/tests/client-preset.spec.ts
let's merge this before the next release. I actually wanted to name these persisted documents but ended up writing persisted operations lol. Since we did not release persisted documents, we can still rename them.
=> fix: use consistent naming convention

.changeset/famous-pumas-travel.md, packages/graphql-codegen-cli/package.json
Upgrade `codefileloader` version to fix bug
Related #8780
error example: https://stackblitz.com/edit/github-vffocy?file=src%2F__gql__%2Fgql.ts,src%2FApp.tsx,codegen.ts.
fix example: https://stackblitz.com/edit/github-vffocy-ba7ruw?embed=1&file=README.md
- OS:
- NodeJS:
If this is a relatively large or complex change, kick off …
=> fix: update CodeFileLoader to fix overwrite bug #8780

packages/plugins/typescript/typescript/src/config.ts
IDK why exactly this fixes the output, but it works.
=> docs(plugins/typescript): exampleMarkdown indentation

website/src/pages/docs/guides/graphql-server-apollo-yoga.mdx
Updates step 2 of [the guide](https://the-guild.dev/graphql/codegen/docs/guides/graphql-server-apollo-yoga) to include `@graphql-codegen/cli` as a dependency to install, as it's required for steps 3 (Configure the plugin) & 4 (Run the codegen)
=> docs: codegen dependencies

.changeset/nasty-eggs-rule.md, dev-test/gql-tag-operations/graphql/gql.ts, examples/persisted-documents/src/gql/gql.ts, examples/react/apollo-client/src/gql/gql.ts, examples/react/babel-optimized/src/gql/gql.ts, examples/react/graphql-request/src/gql/gql.ts, examples/react/nextjs-swr/gql/gql.ts, examples/react/tanstack-react-query/src/gql/gql.ts, examples/react/urql/src/gql/gql.ts, examples/typescript-esm/src/gql/gql.ts, examples/typescript-graphql-request/src/gql/gql.ts, examples/vue/apollo-composable/src/gql/gql.ts, examples/vue/urql/src/gql/gql.ts, examples/vue/villus/src/gql/gql.ts, examples/yoga-tests/src/gql/gql.ts, packages/plugins/typescript/gql-tag-operations/src/index.ts, packages/presets/client/tests/client-preset.spec.ts
I noticed that the example generated wasn't using `gqlTagName`, and therefore the example said `gql`, but the recent version switched to `graphql`, and it got me confused for a second. I believe we probably want to leverage `gqlTagName` for the example and the other places already relying on it.
See updated snapshots and examples.
=> fix: use `gqlTagName` in the autogenerated example

packages/presets/swc-plugin/Cargo.lock, packages/presets/swc-plugin/Cargo.toml, packages/presets/swc-plugin/src/tests.rs
Fix for updating swc_core. Related [fix(deps): update rust crate swc_core to 0.59.*](https://github.com/dotansimha/graphql-code-generator/pull/9023)
=> Update swc_core for swc-plugin

website/src/pages/plugins/presets/preset-client.mdx
I fixed a few words while reading the `preset-client`'s documentation.
Additionally, I noticed that it wasn't explaining how to grab a Fragment's type from the definition itself so we don't have to "guess" the name of the generated fragment with `ResultOf<typeof FragmentName>`.
Executed the documentation locally.
=> docs: improve `preset-client` docs

packages/presets/swc-plugin/package.json
I tried to build the SWC plugin, but I noticed that the wasm file wasn't in the `package.json`'s files array. Besides, the `build-wasm` command copied the file to the wrong place. This fixes it 😄
=> Fix swc-plugin package.json

.prettierignore
I noticed that Prettier was executed on `build` folders of generated examples, e.g.: `examples/react/apollo-client/build`.
We don't need to run Prettier on the generated builds from generated examples, especially since they are ignored by git.
=> chore: add `build/` to `.prettierignore`

website/src/pages/docs/guides/graphql-server-apollo-yoga-with-server-preset.mdx
This PR updates the server preset guide with new v0.3.0 mapper behaviours:
- automatically create missing field resolvers
- automatically create incompatible field resolvers
=> Update server preset guide with 0.3.0 mapper behaviour

website/src/pages/docs/guides/react-vue.mdx, website/src/pages/plugins/presets/preset-client.mdx
I've noticed that the config API section about `client-preset` was outdated, the following options were missing: `strictScalars`, `defaultScalars`, `dedupeFragments`, `nonOptionalTypename`, and `avoidOptionals`.
Additionally, options were linked to `/plugins/typescript/typescript#config-api-reference` rather than the specific config option. I've updated all of them to link to the specific anchor.
See the screenshot above.
=> chore(docs): update `client` preset config API

.changeset/quick-carpets-teach.md, packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts, packages/plugins/other/visitor-plugin-common/tests/client-side-base-visitor.spec.ts
These changes skip removing `.js` extensions from import paths when the `emitLegacyCommonJSImports` option is set to `false`
#8894 
Added unit test to simulate the input parameters and configuration options. Verify with 
```sh
yarn test  packages/plugins/other/visitor-plugin-common/tests/client-side-base-visitor.spec.ts 
```
OS: macOS
NodeJS: 18.13.0
graphql version: 16.6.0
@graphql-codegen/visitor-plugin-common version(s): 2.13.1
=> Preserve .js extension when importDocumentNodeExternallyFrom and emitLegacyCommonJSImports is false

.github/workflows/release.yml
#9039 I made it such that we have to trigger CI to publish the rust plugin. So we no longer need to run this automatically
=> ci: remove auto ci job to publish rust

.changeset/beige-guests-cheer.md, packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/typescript/resolvers/tests/mapping.spec.ts
=> Custom mappers w. placeholder will apply omit

packages/presets/client/tests/client-preset.spec.ts, packages/presets/client/tests/fixtures/reused-fragment.ts
I was looking into [an issue with duplicated fragments](https://github.com/dotansimha/graphql-code-generator/issues/8670) and found out it was fixed in [a recent PR](https://github.com/dotansimha/graphql-code-generator/pull/8971) by always inlining fragments. So this PR only adds a test case to ensure that it works as expected (I followed @saihaj's repros mentioned in the issue).
However, should we revisit the inlining part? It causes [issues with huge files being generated](https://github.com/dotansimha/graphql-code-generator/pull/8971#issuecomment-1451997425).
Related https://github.com/dotansimha/graphql-code-generator/issues/8670
=> Add a test case to ensure deduplicated fragments

.changeset/brave-papayas-shout.md, packages/graphql-codegen-cli/src/utils/watcher.ts, packages/utils/plugins-helpers/src/types.ts
This PR allows each `generates` config to declare additional file pattern to watch using `watchPattern`.
- OS: MacOS
- `@graphql-codegen/cli`: `3.3.0-alpha-20230311001721-c93af8a64`
- NodeJS: 18
=> [cli] Add watchPattern to generates config

.changeset/clean-files-begin.md, packages/plugins/typescript/typescript/src/visitor.ts, packages/plugins/typescript/typescript/tests/typescript.spec.ts
Properly escape enum identifiers when enumsAsConst is used
Related #9149 
Tested change locally using a basic enum like
```
enum SomeType {
_401K
Other
}
```
- OS: macOS
=> fix: add makeValidEnumIdentifier for enumsAsConst

website/src/pages/docs/guides/graphql-server-apollo-yoga-with-server-preset.mdx
This PR updates the server with preset guide with `defineConfig` available in server preset v0.4.
Blocked by https://github.com/eddeee888/graphql-code-generator-plugins/pull/92
| Description | Screenshot |
| -- | -- |
| `codegen.ts` | ![Screenshot 2023-04-07 at 9 56 57 am](https://user-images.githubusercontent.com/33769523/230514478-fae348e6-e21c-4ff9-9535-ffd554c7ad3c.png) |
| `codegen.yml` |  ![Screenshot 2023-04-07 at 9 57 03 am](https://user-images.githubusercontent.com/33769523/230514463-20004c76-f5f3-49bb-951a-541c1c465867.png) |
=> [website-docs] Update server with preset guide for v0.4 usage

.changeset/big-bottles-bow.md, packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts, packages/plugins/other/visitor-plugin-common/src/utils.ts, packages/plugins/other/visitor-plugin-common/tests/client-side-base-visitor.spec.ts, packages/plugins/other/visitor-plugin-common/tests/utils.spec.ts
Fixes a regression issue introduced by a recent change which removes fragment imports entirely.
Related #9293
I cloned [this minimal reproduction](https://stackblitz.com/edit/graphql-codegen-fragment-issue?file=src/user.query.ts) from the related issue and ran it with the changes.
As part of the change I've added 3 one line array utility functions, which make the change code much cleaner and easier to understand.
=> Fix fragment imports for near-operation-file with graphQLTag

.changeset/tough-bags-hunt.md, packages/graphql-codegen-cli/src/init/questions.ts, packages/graphql-codegen-cli/tests/__snapshots__/init.spec.ts.snap
we were missing `/` in the default output path, so updating that so it is not broken.
Related #9157
=> fix: output directory for init command

packages/presets/client/src/babel.ts
Disclaimer: it's a very very very small improvement.
In order to prepare a talk on TypeScript performance, I was playing with random repositories trying to find some interesting stuff. So there was one hot spot in this repo — in the `babel.ts` file:
I passed an options type to generic `declare` to remove the hot spot.
It may not be a significant difference, but it's something.
Before:
After — check time got better:
=> Pass options type to declare function in babel preset

website/src/pages/plugins/presets/preset-client.mdx
I noticed some highlights on `client-preset` were a little bit off, let's fix this.
Documentation / Website.
| Before | After |
| - | - |
| <img width="849" alt="Screenshot 2023-04-24 at 9 12 27 AM" src="https://user-images.githubusercontent.com/7189823/234008050-0ef85269-2325-496f-baee-40413e41362f.png"> | <img width="843" alt="Screenshot 2023-04-24 at 9 13 42 AM" src="https://user-images.githubusercontent.com/7189823/234008234-a582eeac-75e6-44b8-9a70-ae3038d55ac1.png"> |
| <img width="851" alt="Screenshot 2023-04-24 at 9 12 36 AM" src="https://user-images.githubusercontent.com/7189823/234008048-43c6e036-7793-4961-8d6c-f6fa60f2daba.png"> | <img width="846" alt="Screenshot 2023-04-24 at 9 13 51 AM" src="https://user-images.githubusercontent.com/7189823/234008232-a18d351f-be83-425a-bcce-f38 …
=> docs: fix highlights in `client-preset`

.changeset/orange-tables-cry.md, packages/presets/client/src/index.ts, packages/presets/client/src/persisted-documents.ts, packages/presets/client/tests/client-preset.spec.ts
Proposal to add the ability to specify the hash algorithm used for persisted documents as mentioned by #9108.
Ideally, we would like the ability to pass our own `generateDocumentHash` function so consumers could use their own hash implementation. But, I figured we mostly want to comply with Apollo Server and/or still rely on `crypto` and therefore to avoid the dance with `crypto`: `createHash`, `update`, and `digest`, it should be more friendly to accept an algorithm directly.
```diff
import { type CodegenConfig } from '@graphql-codegen/cli'
const config: CodegenConfig = {
schema: 'schema.graphql',
documents: ['src/**/*.tsx'],
generates: {
'./src/gql/': {
preset: 'client',
presetConfig: {
-       persistedDocuments: true
+       persistedDocuments: {
+         hashAlgorithm: 'sha256',
+ …
```
=> feat: implement `persistedDocuments.hashAlgorithm`

.changeset/quiet-rocks-sin.md, packages/graphql-codegen-cli/src/codegen.ts, packages/graphql-codegen-cli/tests/generate-and-save.spec.ts, packages/graphql-codegen-cli/tests/test-files/graphql.config.json
When using general graphql configs (eg. graphql.config.json) instead of codegen configs (eg. codegen.ts), `ignoreNoDocuments` option and CLI flag are not working. Additional guard was added when loading documents to not throw error when `ignoreNoDocuments` option is needed.
#9368
added additional test
- OS: MacOS
- `@graphql-codegen/...`: @latest
- NodeJS: 18
=> fix: ignoreNoDocuments option usage when using graphql configs

.changeset/four-buckets-carry.md, dev-test/gql-tag-operations-masking/gql/fragment-masking.ts, dev-test/gql-tag-operations-urql/gql/fragment-masking.ts, dev-test/gql-tag-operations/gql/fragment-masking.ts, dev-test/gql-tag-operations/graphql/fragment-masking.ts, examples/persisted-documents-string-mode/src/gql/fragment-masking.ts, examples/persisted-documents/src/gql/fragment-masking.ts, examples/programmatic-typescript/src/gql.generated.ts, examples/react/apollo-client-defer/src/gql/fragment-masking.ts, examples/react/apollo-client-defer/tsconfig.json, examples/react/apollo-client-swc-plugin/src/gql/fragment-masking.ts, examples/react/apollo-client/src/gql/fragment-masking.ts, examples/react/http-executor/src/gql/fragment-masking.ts, examples/react/nextjs-swr/gql/fragment-masking.ts, examples/react/tanstack-react-query/src/gql/fragment-masking.ts, examples/react/urql/src/gql/fragment-masking.ts, examples/typescript-esm/src/gql/fragment-masking.ts, examples/typescript-graphql-request/src/gql/fragment-masking.ts, examples/vite/vite-react-cts/src/gql/fragment-masking.ts, examples/vite/vite-react-mts/src/gql/fragment-masking.ts, examples/vite/vite-react-ts/src/gql/fragment-masking.ts, examples/vue/apollo-composable/src/gql/fragment-masking.ts, examples/vue/urql/src/gql/fragment-masking.ts, examples/vue/villus/src/gql/fragment-masking.ts, examples/yoga-tests/src/gql/fragment-masking.ts, packages/presets/client/src/fragment-masking-plugin.ts, packages/presets/client/tests/client-preset.spec.ts
Related https://github.com/dotansimha/graphql-code-generator/issues/9383
- OS:
- NodeJS:
=> Make isFragmentReady function work with enabled noUncheckedIndexedAccess tsc setting

.changeset/thin-berries-deny.md, packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts, packages/plugins/typescript/operations/tests/ts-documents.spec.ts
The behavior was dependent on the default pascalCase
namingConvention and would produce broken type names if
the "keep" convention was used.
We now apply similar removal of quotes and special
characters out of the box, ensuring we keep functioning even if "keep"
is selected as the naming convention.
Updated unit tests.
- OS: MacOS
- `@graphql-codegen/...`: @latest
- NodeJS: 18
=> fix: Don't generate invalid type names with mergeFragmentTypes

packages/plugins/typescript/typescript/src/config.ts
Fixes a typo in `typescript` plugin documentation.
=> docs: fix `inputMaybeValue` config typo

.changeset/chilly-moons-yawn.md, packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts, packages/presets/client/tests/client-preset.spec.ts, packages/presets/client/tests/fixtures/with-deferred-fragment.ts
=> Support defer directive on nested fragments

.changeset/breezy-rice-retire.md, packages/utils/plugins-helpers/src/types.ts, website/src/pages/docs/config-reference/schema-field.mdx
This PR improves schema Github Loader doc and TypeScript usability:
- clarifies the two ways of using GitHub Loader in the doc
- updates TypeScript type of GitHub loader
Related: https://github.com/dotansimha/graphql-code-generator/pull/9281
- OS: MacOS
- NodeJS: 18
=> [cli/docs]Add GitHub Loader TypeScript type, update usage docs

.changeset/gold-frogs-explain.md
This updates the changeset created in https://github.com/dotansimha/graphql-code-generator/pull/9375 to be major since it is a breaking change.
=> Fix Scalars input/output scalars to be major

packages/utils/plugins-helpers/src/types.ts
This fixes website deployment because `typescript-json-schema` does not work with template literal string in type key
Related discussion: https://github.com/dotansimha/graphql-code-generator/pull/9332#discussion_r1174565990
=> Fix broken website deployment due to typescript-json-schema requirement

website/src/pages/docs/custom-codegen/contributing.mdx
The current link is working on GitHub's viewer, but broken in the [document page](https://the-guild.dev/graphql/codegen/docs/custom-codegen/contributing).
I skimped to create an issue because this is just a document fix. Please tell me if I should do it.
Tested that the link keeps working on GitHub UI.
=> Fix link in contributing.mdx

website/src/pages/docs/guides/react-vue.mdx
This rephrases the "Usage with `@tanstack/react-query`" callout to make it clearer that it isn't recommending using `@tanstack/react-query` over other data fetching libraries.
The previous phrasing confused me. See https://github.com/dotansimha/graphql-code-generator/discussions/9482 discussion for context.
https://github.com/dotansimha/graphql-code-generator/discussions/9482
=> docs: make `react-query`/`graphql-request` recommendation clearer

website/src/pages/docs/guides/api-testing.mdx
`@graphql-codegen/client-preset` is mentioned twice in the installation instructions in [api-testing.mdx](https://github.com/dotansimha/graphql-code-generator/blob/2276708d0ea2aab4942136923651226de4aabe5a/website/src/pages/docs/guides/api-testing.mdx?plain=1#L31)
=> docs: remove duplicate package to install in api-testing.mdx

.changeset/five-spies-impress.md, packages/graphql-codegen-cli/package.json, packages/graphql-codegen-cli/src/utils/watcher.ts, website/route-lockfile.txt, website/src/pages/docs/getting-started/development-workflow.mdx, website/src/pages/docs/getting-started/installation.mdx, website/src/pages/docs/migration/_meta.json, website/src/pages/docs/migration/from-4-0.mdx
This is a new attempt to fix #9320. 
`@parcel/watcher` needs a whole lot of build dependencies on the system. Normally, it will just pull prebuilt binaries for your system. But currently there are no prebuilt binaries for linux on arm64: https://github.com/parcel-bundler/watcher/issues/130
In those environments, it tries to build it from source which means it needs python etc.
This makes `@parcel/watcher` optional, which should prevent these issues. The user is free to choose if they want to include `@parcel/watcher` as a dev dependency or take additional measures such as marking it …
=> Make @parcel/watcher optional

.changeset/large-wombats-beam.md, packages/utils/plugins-helpers/src/types.ts, website/public/config.schema.json
Related #9515
The `noSilentErrors` option has already been implemented but not in the config type.
(The "Bug fix" above is about fixing the type error.)
Sandbox: https://github.com/tnyo43/graphql-code-generator-issue-sandbox-no-silent-error
You will see that the `noSilentErrors` option works but is not included in the config type if you follow the example in the README.
1. prepare this repository
1.1. clone this repository and checkout to this branch (tnyo43:add-no-silent-errors-option-in-config-type)
1.2. update line 47 in "packages/graphql-codegen-cli/package.json" as `"@graphql-codegen/plugin-helpers": "file:../utils/plugins-helpers",`.
1.3. run `yarn build`.
2. prepare the sandbox
2.1. clone the sandbox …
=> Add `noSilentErrors` option to the config type

website/src/pages/docs/guides/react-vue.mdx
No issue created because this is just a small fix in docs.
Fixing a mistake in the docs.
The imported function should be `graphql` from the generated `gql.ts` file.
=> docs: generated graphql import example in react-vue.mdx

.changeset/stupid-onions-tap.md, packages/graphql-codegen-cli/src/utils/watcher.ts
A dependency `micromatch`  has a `scan` method used for parsing a given file and returning glob details. This method does not work with Windows path separator (`\`), causing issues with the watcher on a Windows platform where the watcher would not be able to find a highest common directory, and fall back to watching the `process.cwd()` instead.
From my testing, this is the only place where Windows separator is not supported and the watcher works as expected with the change made in this PR, where we temporarily convert the separators to `/`.
Related #9526
We have a big monorepo at work in which I verified my changes. It would be useful for someone to verify on MacOS to make sure non-Windows platforms are not affected
- OS: Windows
- `@graphql-codegen/cli`: 5.0.0
- …
=> fix(watcher): fix watcher unable to find highest common directory on Windows

.changeset/chilled-impalas-prove.md, packages/presets/client/src/index.ts, website/src/pages/plugins/presets/preset-client.mdx
Hook TypeScript's `futureProofEnums` config option to the client preset, which could be really useful without having to redefine `typescript` plugin.
Tested locally. Existing feature available on `typescript`, but it wasn't hooked up to `client-preset`.
=> Add `futureProofEnums` config to client preset

.changeset/perfect-forks-flash.md, dev-test/codegen.ts, dev-test/test-null-value/query.ts, dev-test/test-null-value/result.d.ts, dev-test/test-null-value/schema.graphql, packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts
tl;dr `visitor-plugin-common` tries to read from a variable that can be null in some situations. It's probably hard to reproduce since I'm using custom stuff. However, the change in this PR is just making the code more robust by moving 1 line that reads from a variable after an existing null check.
---
While working on codegen for Shopify/Hydrogen, I found that the following fragment breaks when using `typescript-operation` in `@graphql-codegen/cli` v4 and v5. It used to work in v3.3.1:
```ts
const CART_QUERY_FRAGMENT = `#graphql
fragment CartLine on CartLine {
id
quantity
}
fragment CartApiQuery on Cart {
id
lines {
nodes {
...CartLine
}
}
}
`
```
It throws with `[Codegen] Cannot read properties of null (reading 'union')`, which comes from [this …
=> fix(visitor-plugin-common): avoid reading from null values

.changeset/hip-garlics-invent.md, dev-test/gatsby/fragments.ts, dev-test/gatsby/schema.graphql, dev-test/githunt/types.flatten.preResolveTypes.ts, packages/graphql-codegen-cli/tests/codegen.spec.ts, packages/plugins/other/visitor-plugin-common/src/base-documents-visitor.ts, packages/plugins/other/visitor-plugin-common/src/base-visitor.ts, packages/plugins/other/visitor-plugin-common/src/selection-set-processor/base.ts, packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts, packages/plugins/other/visitor-plugin-common/src/utils.ts, packages/plugins/typescript/operations/src/visitor.ts, packages/plugins/typescript/operations/tests/extract-all-types.spec.ts, packages/presets/client/tests/client-preset.spec.ts
Related `stage/1-reproduction` issue: #7720
At Zendesk, we've been using `graphql-code-generator` for a few years now. Thank you to the creators and maintainers for the lovely tool! It's been a great help to have codegen work for us. 🥳 
As time went by, and our schemas and usage of GraphQL at the company has grown, we unfortunately started to experience increased codegen execution times, and TypeScript compilation times.
This has escalated to the point where engineers had to wait 4 minutes for codegen to complete on their high-spec engineering laptops, and the generated .ts files were over 35MB (yes, you read that right ❗). If that's not bad enough, executing TypeScript to typecheck our codebase on CI (`tsc --noEmit`) would take a whopping 6:36 minutes on the CI ‼️ 
Finally, we've hit a …
=> fix: out-of-memory crash (#7720) and significantly improve performance + feat: extracting fields to types

website/src/pages/plugins/typescript/typed-document-node.mdx, website/src/pages/plugins/typescript/typescript-operations.mdx, website/src/pages/plugins/typescript/typescript-resolvers.mdx, website/src/pages/plugins/typescript/typescript.mdx
as discussed in the meeting we will now recommend client and/or server presets on top of the low-level plugin pages that got superseded by the presets.
=> docs: recommend the client and server preset

website/src/pages/plugins/presets/preset-client.mdx
=> Consistent client-preset examples naming

website/src/pages/plugins/presets/preset-client.mdx
Updates Client Preset - Persisted Documents documentation
Updates documentation with `persistedDocuments.hashAlgorithm` options example from https://github.com/dotansimha/graphql-code-generator/pull/9353
* https://github.com/dotansimha/graphql-code-generator/issues/9759
=> Updates Client Preset Persisted Documents documentation with hashAlgorithm options

.changeset/late-olives-pull.md, packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
Makes it so arguments don't get wrapped with a `Partial` when configured to avoid optionals for input values. Without this change, `avoidOptionals = true` ends up being inconsistent since it will still use optional input values in the case there is only nullable arguments.
Related #9438
Added a test that avoid optionals does not wrap the arguments with a partial when configured.
- OS: macOS
- `@graphql-codegen/typescript-resolvers`: 4.0.1
- NodeJS: 16.x
I think this should be fairly uncontroversial since it is preserving the intention of the avoid optionals config.
=> Avoid wrapping args with partial when avoiding optionals

website/src/pages/docs/guides/react-vue.mdx
In GraphQLSP > 1.0.0, we don't require any config to support the `client-preset`, tracking field usage will default to true and so will checking for co-located fragments.
=> docs: latest GraphQLSP needs no config

website/src/pages/plugins/presets/preset-client.mdx
https://github.com/dotansimha/graphql-code-generator/issues/9763
The code example in the following document is incorrect.
https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#normalized-caches-urql-and-apollo-client
`addTypenameDocumentTransform` does not exist.
`addTypenameSelectionDocumentTransform` is correct
https://github.com/dotansimha/graphql-code-generator/issues/9763
Please …
=> docs: addTypenameDocumentTransform does not exist

.changeset/silly-glasses-thank.md, dev-test/gql-tag-operations-masking/gql/fragment-masking.ts, dev-test/gql-tag-operations-urql/gql/fragment-masking.ts, dev-test/gql-tag-operations/gql/fragment-masking.ts, dev-test/gql-tag-operations/graphql/fragment-masking.ts, examples/persisted-documents-string-mode/src/gql/fragment-masking.ts, examples/persisted-documents/src/gql/fragment-masking.ts, examples/react/apollo-client-defer/src/gql/fragment-masking.ts, examples/react/apollo-client-swc-plugin/src/gql/fragment-masking.ts, examples/react/apollo-client/src/gql/fragment-masking.ts, examples/react/http-executor/src/gql/fragment-masking.ts, examples/react/nextjs-swr/gql/fragment-masking.ts, examples/react/tanstack-react-query/src/gql/fragment-masking.ts, examples/react/urql/src/gql/fragment-masking.ts, examples/typescript-esm/src/gql/fragment-masking.ts, examples/typescript-graphql-request/src/gql/fragment-masking.ts, examples/vite/vite-react-cts/src/gql/fragment-masking.ts, examples/vite/vite-react-mts/src/gql/fragment-masking.ts, examples/vite/vite-react-ts/src/gql/fragment-masking.ts, examples/vue/apollo-composable/src/gql/fragment-masking.ts, examples/vue/urql/src/gql/fragment-masking.ts, examples/vue/villus/src/gql/fragment-masking.ts, examples/yoga-tests/src/gql/fragment-masking.ts, packages/presets/client/src/index.ts, packages/presets/client/tests/client-preset.spec.ts
Related #8819
- As discussed in #8819, using `add` plugin by user side is not helpful in this case.
- For consistency with other generated files by client preset.
- We can add fragment-masking.ts to .eslintignore but it is not consistent with other files. 
- https://github.com/dotansimha/graphql-code-generator/blob/7ba9d0ec129609cf013f9786cf150b4aa3c59c51/packages/presets/client/src/index.ts#L211
- https://github.com/dotansimha/graphql-code-generator/blob/7ba9d0ec129609cf013f9786cf150b4aa3c59c51/packages/presets/client/src/index.ts#L224
I think this is a trivial change. 🤔
- OS: macOS 13.4.1
- NodeJS: v18.16.1
=> Add eslint-disable comment to fragment-masking.ts

.changeset/mighty-doors-stare.md, packages/plugins/other/visitor-plugin-common/src/selection-set-processor/base.ts, packages/plugins/other/visitor-plugin-common/src/selection-set-processor/pre-resolve-types.ts, packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts, packages/plugins/typescript/operations/tests/ts-documents.spec.ts
We use GraphQL code generator heavily at our company and today ran into an issue where a field was conditional (using `@include` directive) but the types show it as being always present in the response.
Related issue: https://github.com/dotansimha/graphql-code-generator/issues/8461
Added a unit test to `ts-documents.spec.ts`
- OS: Sonoma
- NodeJS: v16.13.2
It's not clear if this fix wasn't made earlier. Was there some limitation that previous fixes ran into? I don't see any discussion in the original issue.
=> fix(typescript-operations): properly handle aliased conditionals

.changeset/lazy-laws-brake.md, packages/plugins/other/visitor-plugin-common/src/base-documents-visitor.ts, packages/plugins/typescript/operations/src/config.ts, packages/plugins/typescript/operations/src/visitor.ts, packages/plugins/typescript/operations/tests/ts-documents.spec.ts
For libraries like `react-query`, there is the option to disable a query if there is a dependency that hasn't been met. For example:
```
query getAuthUsers($userId: uuid!) {
authentication_users(where: { uuid: { _eq: $userId } }) {
uuid
}
}
```
```
type Props = {
userId: string | undefined;
}
...
const { data } = useGetAuthUsers({ userId }, { enabled: Boolean(userId) });
```
Unfortunately, this fails typechecking because the variables for the hook are defined as `Exact<{ userId: string>`. I'd like to be able to do something like the following.
```
const { data }  = useGetAuthUsers(userId ? { userId } : undefined, { enabled: Boolean(userId) });
```
This disables the query and maintains type safety.
This PR adds the ability to set `allowUndefinedQueryVariables` (boolean) in a codegen config …
=> adding allowUndefinedQueryVariables option to typescript-operations plugin

.changeset/light-clocks-rhyme.md, packages/presets/client/src/add-typename-selection-document-transform.ts, packages/presets/client/tests/client-preset.spec.ts, packages/presets/client/tests/fixtures/subscription-root-node.ts
The `__typename` should not be added to the root node of a subscription when using `addTypenameSelectionDocumentTransform` with `documentTransforms` since a single root node is expected and the code generator fails because of that (refer to [the specification](https://spec.graphql.org/draft/#sec-Single-root-field)).
dotansimha/graphql-code-generator#9888
[Issue Sandbox](https://github.com/Sojaner/graphql-code-generator-issue-sandbox-template)
The fix is also included in the issue sandbox. The code can be run in 3 setups for testing:
1. `yarn generate` which doesn't use the document transformer and works fine
2. `yarn generate --add-typenames` which uses the current faulty document transformer and fails
3. `yarn generate --add-fixed-typenames` which uses my fixed version …
=> Excluded the __typename from the root node of subscriptions when using addTypenameSelectionDocumentTransform with documentTransforms

.eslintrc.cjs, package.json, packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts, packages/plugins/typescript/typescript/src/visitor.ts, yarn.lock
Linting seems to be broken for a while. Looks like it's coming from a specific version of `@theguild/eslint-config` which applies `@typescript-eslint/prefer-optional-chain` to all code files (.js and .ts and their variants).
This PR applies the version of `@theguild/eslint-config` which moves said rule to dedicated `.ts` target.
This is a temporary fix because we still need to manually match `ignorePatterns` with `tsconfig.json`'s `excludes` which could be a bit annoying to maintain
=> Fix linting issue (temporary solution)

.github/workflows/main.yml
Currently, we run unit tests after examples tests (a.k.a. `dev-tests` step in CI ). This has a few quirks: 
- Examples tests take ~9mins whilst unit tests take ~2mins, so the total time to run tests sequentially is >11mins
- If examples tests fail, unit tests are not run. We recently had issues with examples tests, so unit tests were not run, and we didn't realise there were issues in unit tests after some package updates.
This PR removes examples tests as the dependency for unit tests:
- This should cut CI by 2mins
- This should show failing unit tests even when examples tests fail
| Before | After |
| -- | -- |
| <img width="874" alt="Screenshot 2024-04-25 at 9 54 45 pm" src="https://github.com/dotansimha/graphql-code-generator/assets/33769523/5d754585-f21e-47c4-bbcb-227333abc2a1"> | …
=> [CI] Let unit tests in parallel with examples test

.changeset/gentle-ladybugs-speak.md, dev-test/modules/types.ts, packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/typescript/resolvers/tests/__snapshots__/ts-resolvers.spec.ts.snap, packages/plugins/typescript/resolvers/tests/mapping.spec.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
`RefType` in `ResolversInterfaceTypes` and `ResolversUnionTypes` are unused if the possible types do not refer to other abstract types.
This is an issue for codebases using `noUnusedLocals: true`  and/or `noUnusedParameters: true` compiler options in their tsconfig.json because it'd throw TypeScript error:
```
TypeScript error TS6133: 'RefType' is declared but its value is never read
```
This PR prefixes `_` to `RefType` to signal that it _might_ not be used. We do this even when `RefType` is not used so the generated type has a consistent signature for all cases
Related https://github.com/dotansimha/graphql-code-generator/issues/9584
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please …
=> [typescript-resolvers] Add _ prefix to generated `RefType` as it is sometimes unused

.changeset/weak-kings-clap.md, packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/typescript/resolvers/tests/__snapshots__/ts-resolvers.spec.ts.snap, packages/plugins/typescript/resolvers/tests/mapping.spec.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
This PR fixes an issue where self-referencing and nested interfaces are not using resolver types correctly. 
Interface is an abstract type like union. So, we need to reference the `ResolversInterfaceTypes` whenever there's a object type with a field with type interface or an array of interfaces.
Otherwise, the wrapping object type would just refer to the base generated type, causing mappers for the interface to be ignored.
Related https://github.com/eddeee888/graphql-code-generator-plugins/issues/266
Note that this bug has been here for awhile. I can observe that in [this PR to rebase tests](https://github.com/dotansimha/graphql-code-generator/pull/9228). So at least it's been around before `ResolversInterfaceTypes` implementation
Given this schema:
```graphql
type Query {
node: Node …
```
=> [typescript-resolvers] Fix interfaces not handling nested correctly

.changeset/curvy-lobsters-kneel.md, .changeset/new-radios-flash.md, packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/typescript/resolvers/src/index.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts, packages/utils/plugins-helpers/src/types.ts
Currently, we don't know easily _what_ has been generated from the run without parsing through the output's content. 
This PR adds a new optional `meta` to allow plugins to report certain things about the run.
This PR also makes `@graphql-codegen/typescript-resolvers` report generated resolver type names - after applying `namingConvention` - to `meta`. This allows plugins/presets (e.g. Server Preset) that relies on `@graphql-codegen/typescript-resolvers` plugin to import the generated resolver types without trying to match the `namingConvention` logic manually.
=> [typescript-resolvers] Add meta field to typescript-resolvers plugin's output

.changeset/spicy-starfishes-press.md, packages/presets/client/src/index.ts, packages/presets/client/src/persisted-documents.ts, packages/presets/client/tests/client-preset.spec.ts, website/src/pages/plugins/presets/preset-client.mdx
This features allows for customization of the `hashAlgorithm` configuration for persisted documents in the client preset. This mitigates the need to support additional future algorithms beyond `sha1` and `sha256` and gives developers full flexibility for generating document hashes, unlocking new use-cases. 
Related #9994
Added three new test cases to `client-preset.spec.ts`. Ran `yarn test client-preset`.
- `custom hash remove whitespace` - This test case demonstrates basic functionality in a human-readable manner. Since the output is just the operation without whitespace, it's easy to tell if the custom hash function is broken.
- `custom hash sha256` - This test case replicates the existing test case `hashAlgorithm="sha256"` to ensure identical results.
- `custom hash docs sha512` - This …
=> Persisted document custom hash function

.changeset/polite-dancers-warn.md, packages/plugins/other/add/src/index.ts
Export config type for `@graphql-codegen/add`.
Related #9986 
I tested it by importing from another workspace.
- OS: macOS
- `@graphql-codegen/...`: latest
- NodeJS: v20.12.2
=> feat(plugin/add): export config type

.changeset/forty-cooks-build.md, packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/typescript/resolvers/src/index.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts
This PR extends `typescript-resolvers` plugin's meta to have the generated resolver map type. This is useful for Server Preset as it needs to refer to this type when generating `resolvers.generated.ts`
This changes the meta shape slightly to have user defined types in the schema under `generatedResolvers.userDefined` instead of `generatedResolvers`. New shape:
```ts
meta: {
generatedResolverTypes: {
resolversMap: { name: string };
userDefined: Record<string, { name: string }>;
}
}
```
=> Add generated resolversMap to typescript-resolvers plugin meta

.changeset/rotten-eels-eat.md, packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts
As mentioned in https://github.com/dotansimha/graphql-code-generator/issues/10018, `ClientSideBaseVisitor`'s `fragmentsGraph` is implemented as a getter, despite not depending on anything that changes after the class is first instantiated. Turning `fragmentsGraph` into a static property improved build time from ~130s to ~50s in a big monorepo.
This PR does that and it makes field `fragmentsGraph` depends on (`_fragments`) read-only to make sure we don't break the assumption behind pre-computing the former.
Related: #10018
- Run codegen on a mid-sized project using `client-preset` and measure the build time
- Make the …
=> Only compute `ClientSideBaseVisitor`'s `fragmentsGraph` once, at instantiation time

.changeset/forty-ears-rule.md, packages/plugins/other/schema-ast/src/index.ts, packages/plugins/other/schema-ast/tests/schema-ast.spec.ts
Allow .graphqls as extension for `schema-ast` plugin.
This is currently the unofficial extension for GraphQL schema files, and there's a push to make it the official extension.
=> Allow .graphqls as extension for schema-ast

website/src/pages/docs/custom-codegen/using-visitor.mdx
This PR contains an update to the documentation about custom visitors to make use of `oldVisit` instead of `graphql`'s `visit` function which causes issues in graphql@16.
Related #9230
Updating this Codesandbox in the same way as the documentation to verify this working.
https://codesandbox.io/p/sandbox/headless-cloud-6z6r45
- OS: Windows 10
- NodeJS: 16.20.0
A couple of the checkboxes are left unticked because I am not sure how they apply to pure documentation changes like in this case. Let me know if anything is missing!
=> fix: custom visitor documentation

.changeset/slimy-years-behave.md, packages/presets/client/src/index.ts
Forwarded `typescript-operations`'s `skipTypeNameForRoot` option to `client-preset`
Related #10135
- OS: macOS 14.6.1
- NodeJS: 20.15.1
=> fix(client-preset): forward `skipTypeNameForRoot` option

.changeset/twenty-spiders-sell.md, examples/persisted-documents-string-mode/src/gql/graphql.ts, examples/react/tanstack-react-query/src/gql/graphql.ts, examples/react/urql/src/gql/graphql.ts, examples/typescript-graphql-request/src/gql/graphql.ts, packages/plugins/typescript/typed-document-node/src/index.ts, packages/presets/client/tests/client-preset.spec.ts
(Sorry, this seemed simple enough that the discussion may as well happen here. Feel free to reject it if this is the wrong fix or you don't want to support [--isolatedDeclarations](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-5.html#isolated-declarations).)
Without this, building the generated types into a project that uses --isolatedDeclarations fails with
> Declaration emit for this parameter requires implicitly adding undefined to it's type. This is not supported with --isolatedDeclarations.
Please describe the tests that you ran to verify your changes. …
=> Add |undefined in the TypedDocumentString constructor to make it work with --isolatedDeclarations

.changeset/early-ducks-develop.md
=> Fix imported enums type naming

packages/plugins/other/visitor-plugin-common/src/base-documents-visitor.ts
_Note: Since this is a simple documentation fix, I didn't follow the pull request description template. I hope this is fine._
Currently, the missing code block ending leads to layout errors on https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-operations#customdirectives:
> ![image](https://github.com/user-attachments/assets/62ea8acc-6ea6-4a0b-adb8-958c92d23738)
=> Add missing code block ending

.changeset/swift-wasps-beam.md, packages/presets/client/src/index.ts
Passes through the `onlyOperationTypes` and `onlyEnumTypes` config options for the client preset.
`onlyOperationTypes` defaults to `false` however it would be useful focusing type generation on just the operations, reducing bundle size and developer error (a frequent one for us, building dependency on the wrong types).
As discussed in https://github.com/dotansimha/graphql-code-generator/discussions/8693
New feature (non-breaking change which adds functionality)
- OS:
- NodeJS:
If this is a relatively large or complex change, kick off the discussion by explaining why you …
=> Passthrough `onlyOperationTypes` and `onlyEnumTypes` in client-preset

website/package.json, website/src/components/index-page.tsx, yarn.lock
This fixes the browser intrinsic UI colors on landing page. i.e. scrollbars.
=> Set color-scheme: light and update Components

website/package.json, website/theme.config.tsx, yarn.lock
This PR brings in https://github.com/the-guild-org/docs/pull/1976 to fix text-decoration style in Neue Montreal in Safari.
I don't really like the contrast of the new blue with the current light mode background (it's a bit too low), so we might follow up with some more style tweaks later when the designers have a chance to take a look at it.
=> Update Components to 7.6.0 to use Hive-rebranding themed MDX link

.changeset/orange-pillows-decide.md, packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.federation.spec.ts
First implementation is https://github.com/dotansimha/graphql-code-generator/pull/9989
`__resolveReference`'s default behaviour when not declared is to pass the ref to subsequent resolvers i.e. becoming the `parent`. So, it means we don't have to make this resolver required.
This patch makes `__resolveReference` optional when `generateInternalResolversIfNeeded.__resolveReference` is set to true.
=> Fix `resolveReference` being generated as required when using `generateInternalResolversIfNeeded.__resolveReference`

.changeset/great-dancers-pump.md, packages/presets/client/src/index.ts, packages/presets/client/tests/client-preset.spec.ts
This is a continuation of https://github.com/dotansimha/graphql-code-generator/pull/10163
Related issue https://github.com/dotansimha/graphql-code-generator/issues/10245
The previous PR added support for `unmask` directive in `typescript-operations`. However, we need to forward it to the client preset for it to take effect. This PR adds that and unit test that covers the recommended config:
```
presetConfig: { fragmentMasking: false },
config: {
inlineFragmentTypes: 'mask',
customDirectives: { apolloUnmask: true },
},
```
=> Forward customDirectives in client preset to support Apollo unmask directive

.github/workflows/main.yml, scripts/print-example-ci-command.js
Examples test is taking ~9mins and is the longest step in the pipeline:
A quick look showed us that:
- We needed to build SWC which takes ~4mins...
- But was only used for 1 or 2 SWC tests
So, we can speed up CI by splitting the Examples tests to 2 parts: 
- "normal" packages  a.k.a packages without `@graphql-codegen/client-preset-swc-plugin` dep
- "swc" packages a.k.a. packages with `@graphql-codegen/client-preset-swc-plugin` dep
This change also keeps the default behaviour where example commands target all examples a.k.a "all" packages
Result: Testing workflow takes ~5min . Meaning **44% reduction in CI time!** (and makes me **100% happier**)
=> Split examples test for speed

.changeset/loud-suits-admire.md, packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/other/visitor-plugin-common/src/types.ts, packages/plugins/typescript/resolvers/src/index.ts, packages/plugins/typescript/resolvers/src/visitor.ts, packages/plugins/typescript/resolvers/tests/__snapshots__/ts-resolvers.spec.ts.snap, packages/plugins/typescript/resolvers/tests/ts-resolvers.config.avoidOptionals.spec.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.federation.interface.spec.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.federation.spec.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.interface.spec.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.mapping.spec.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts, packages/utils/plugins-helpers/src/federation.ts
TODO: video walkthrough
This PR ensures correct types for Interfaces:
Federation Checklist: https://github.com/dotansimha/graphql-code-generator/issues/10206
```graphql
interface User @key(fields: "id") { # must generate `__resolveReference` for User
}
```
https://www.apollographql.com/docs/graphos/schema-design/federated-schemas/entities/interfaces#example-schemas
Related PR: https://github.com/dotansimha/graphql-code-generator/pull/5666
```graphql
interface User { 
id: ID!
name: String!
}
```
As part of this work, we remove unnecessary config that could generate wrong types for both Federation and normal use cases:
- BREAKING CHANGES: Deprecate `onlyResolveTypeForInterfaces` because majority of use cases cannot implement resolvers in Interfaces.
- BREAKING CHANGES: Deprecate …
=> [resolvers][federation] Add `__resolveReference` to applicable `Interface` entities, fix Interface types having non-meta resolver fields

.changeset/olive-geckos-relax.md, dev-test/gql-tag-operations-masking/gql/gql.ts, dev-test/gql-tag-operations-urql/gql/gql.ts, dev-test/gql-tag-operations/gql/gql.ts, dev-test/gql-tag-operations/graphql/gql.ts, examples/persisted-documents-string-mode/src/gql/gql.ts, examples/persisted-documents/src/gql/gql.ts, examples/react/apollo-client-defer/src/gql/gql.ts, examples/react/apollo-client-swc-plugin/src/gql/gql.ts, examples/react/apollo-client/src/gql/gql.ts, examples/react/http-executor/src/gql/gql.ts, examples/react/nextjs-swr/gql/gql.ts, examples/react/tanstack-react-query/src/gql/gql.ts, examples/react/urql/src/gql/gql.ts, examples/typescript-esm/src/gql/gql.ts, examples/typescript-graphql-request/src/gql/gql.ts, examples/vite/vite-react-cts/src/gql/gql.ts, examples/vite/vite-react-mts/src/gql/gql.ts, examples/vite/vite-react-ts/src/gql/gql.ts, examples/vue/apollo-composable/src/gql/gql.ts, examples/vue/urql/src/gql/gql.ts, examples/vue/villus/src/gql/gql.ts, examples/yoga-tests/src/gql/gql.ts, packages/plugins/typescript/gql-tag-operations/src/index.ts, packages/presets/client/tests/client-preset.spec.ts
Add type generation to gql-tag-operation
https://github.com/dotansimha/graphql-code-generator/issues/10191
Works as a yarn patch. This upstream the fix
=> Have gql-tag-operations generate the type for document registry

.changeset/weak-lions-occur.md, packages/presets/client/src/index.ts
Correct the name of the config to:
https://the-guild.dev/graphql/codegen/plugins/typescript/typescript#onlyenums
Related #10155 
- OS:
- NodeJS:
=> fix `onlyEnums` passthrough in client-preset

.changeset/hungry-ties-press.md, packages/graphql-codegen-cli/src/utils/helpers.ts, packages/graphql-codegen-cli/src/utils/patterns.ts, packages/graphql-codegen-cli/tests/watcher.spec.ts
Partial fix for #10281. This PR makes sure that schema URLs are __not__ being treated as file paths when creating a watcher for `--watch`. This allows the common watched directory to be a nested directory, which in turn dramatically increases performance of the watcher as it doesn't have to watch all the extra directories (like `node_modules`).
- OS: macOS
- `@graphql-codegen/...`: master
- NodeJS: 20.15.1
As I said, it's only a partial fix. This resolves the issue of schema URL being treated as a file, which forces the watcher to watch the project root. However, …
=> fix: Don't treat schema URLs as relative file paths for the watcher

.changeset/funny-monkeys-hide.md, packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts, packages/plugins/typescript/operations/tests/ts-documents.apolloUnmask.spec.ts, packages/presets/client/tests/client-preset.spec.ts
When using Apollo masking features, an `@unmask` fragment is the same as inlined i.e.
- should not have `$fragmentRefs`
- selection node fields are inlined
Reference: https://github.com/dotansimha/graphql-code-generator/issues/10299
=> [operations] CODEGEN-784 - Fix Apollo @unmask fragmentRefs

dev-test/test-schema/resolvers-federation.ts, packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.federation.interface.spec.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.federation.mappers.spec.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.federation.spec.ts, packages/utils/plugins-helpers/src/federation.ts
Ref CODEGEN-512
A Federation entity's resolvers may be triggered by one of these two paths:
1. From the same subgraph - if there's a path from the operation root to the relevant field in the query plan
2. From a different subgraph - after gateway calls `__resolveReference` to resolve the relevant field
Let's look at this example: 
```graphql
type Query {
me: User
}
type User @key(fields: 'id') {
id: ID!
name: String!
}
type Query {
book: Book
}
type Book {
id: ID!
author: User!
}
type User @key(fields: 'id', resolvable: false) {
id: ID!
}
```
---
The following query triggers the 1st scenario for `User.name`:
```graphql
query {
me {
id
name # triggers `User.name` from within the same subgraph
}
}
```
When the 1st scenario triggers, it behaves like a non-Federated Graph i.e. `User.name`'s …
=> [resolvers][federation] Bring Federation reference selection set to ResolversParentTypes instead of each resolver

packages/plugins/typescript/operations/src/config.ts
Following on from #10323, this helps by better defining what an "error handling client" is (since this is new terminology) and gives examples at different layers of granularity. It further clarifies additional text that might be interpreted ambiguously or confusingly.
Documentation only.
Documentation only.
cc @eddeee888 and @martinbonnin
=> Crisp up the wording around error handling clients

.changeset/stale-swans-serve.md, packages/presets/graphql-modules/src/index.ts, packages/presets/graphql-modules/tests/integration.spec.ts
If start codegen with `emitLegacyCommonJSImports: false` for `graphql-modules` preset imports with `.js`  extension should be generated.
[#8806](https://github.com/dotansimha/graphql-code-generator/issues/8806)
Wrote new test and checked that each module types contain correct import with `.js` extension.
=> Fix: add file extenstions to import for ESM modules

packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/other/visitor-plugin-common/src/selection-set-to-object.ts, packages/plugins/typescript/operations/src/ts-selection-set-processor.ts, packages/plugins/typescript/operations/tests/__snapshots__/ts-documents.spec.ts.snap, packages/plugins/typescript/operations/tests/extract-all-types.spec.ts, packages/plugins/typescript/operations/tests/ts-documents.spec.ts, packages/plugins/typescript/resolvers/tests/__snapshots__/ts-resolvers.spec.ts.snap, packages/plugins/typescript/resolvers/tests/ts-resolvers.spec.ts, packages/utils/graphql-codegen-testing/src/index.ts
:heavy_check_mark: Acknowledged. Think of this _as_ the issue, to open the discussion via demonstration.
**Please ignore whitespace changes when reviewing this PR.**
To make `git` management of changes easier, it's nice if lines aren't too long. Some of the lines emitted by graphql-code-generator can be excessively large which results in hard to review diffs. This PR aims to introduce newline splits in a few more places to make changes more surgical.
Tests have been updated.
- OS: Ubuntu 24.04
- `master` branch
- NodeJS: v20.18.0
Notes:
- `TypeScript GraphQL Request tests › works without variables` and …
=> Split large unions over multiple lines

.changeset/twenty-planets-complain.md, dev-test/test-schema/resolvers-federation.ts, packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.config.customDirectives.spec.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.federation.spec.ts, packages/utils/plugins-helpers/src/federation.ts
When a field or type is marked with `@external`, the resolver should not be generated (unless part of `@provides`). This PR takes care of the following scenarios:
- The return type of `User.placeOfBirth` points to the base `PlaceOfBirth`, i.e. we don't need to generate `PlaceOfBirthResolvers` because it is unused.
- It should work the same way as normal `@provides`
Related https://github.com/dotansimha/graphql-code-generator/issues/10206
=> [resolvers][federation] Fix fields or types being wrong generated when marked with @external

.changeset/tidy-cows-knock.md, packages/graphql-codegen-cli/src/utils/watcher.ts
When running `--watch` with missing `@parcel/watcher`, the error message can be noisy.
This PR improves the messaging and logging.
Related to https://github.com/dotansimha/graphql-code-generator/issues/10305
=> CODEGEN-787 - Improve handling of missing @parcel/watcher scenario

website/next.config.js
Adds redirect for old style URL. Broken link reported
Issue filed in The Guild website repo: https://github.com/the-guild-org/website/issues/1465
This PR resovles that issue.
Tested locally.
=> Fixes https://github.com/the-guild-org/website/issues/1465

.changeset/small-fans-cross.md, .github/workflows/pr.yml, dev-test/test-schema/resolvers-federation.ts, packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/typescript/resolvers/src/index.ts, packages/plugins/typescript/resolvers/tests/__snapshots__/ts-resolvers.spec.ts.snap, packages/plugins/typescript/resolvers/tests/ts-resolvers.federation.interface.spec.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.federation.mappers.spec.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.federation.spec.ts, packages/utils/plugins-helpers/src/federation.ts
- Creates `FederationReferenceTypes` to declare the type of references of each object. This is used by all generated types, and can be used in mappers. [More details in comment](https://github.com/dotansimha/graphql-code-generator/pull/10366#discussion_r2135735298)
- Correctly finds all combinations of selection sets declared by `@requires` in different fields and put them in `FederationReferenceTypes`. [More details in comment](https://github.com/dotansimha/graphql-code-generator/pull/10366#discussion_r2142881641)
Related https://github.com/dotansimha/graphql-code-generator/issues/10206
=> [resolvers][federation] Fix federation @requires type

.changeset/wicked-timers-eat.md, .github/workflows/main.yml, .github/workflows/pr.yml, .github/workflows/release.yml, .github/workflows/website-integrity.yml, .github/workflows/website.yml
Node 18 is has reached EOL so we should avoid using it or test it.
=> Drop Node 18 support

.changeset/brave-meals-brake.md, packages/graphql-codegen-cli/package.json, packages/graphql-codegen-cli/src/graphql-config.ts, packages/graphql-codegen-cli/src/load.ts
This PR drops `@graphql-tools/prisma-loader` for next major version: it seems it's not being used by anyone.
Related # https://github.com/dotansimha/graphql-code-generator/pull/10218
=> Drop graphql tools prisma loader

.changeset/tiny-avocados-applaud.md, .github/workflows/main.yml, packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.federation.spec.ts, packages/plugins/typescript/resolvers/tests/ts-resolvers.meta.spec.ts
This PR ensures `typescript-resolvers` plugin reports whether user defined objects have `__isTypeOf` or not.
This helps downstream plugins and presets (such as Server Preset) handle correct typing without parsing the schema again.
=> [resolvers] Report if an object can have `__isTypeOf` resolver to output meta

website/src/pages/plugins/typescript/typescript-react-apollo.mdx
We (the Apollo Client team) have seen some feedback a couple places ([example](https://www.reddit.com/r/graphql/comments/1n7p2j7/apollo_client_40_a_leaner_and_cleaner_graphql/)) now where migrating to Apollo Client 4.0 breaks type usage in codebases that generate hooks using this plugin due to the change in where the old deprecated types are generated and with the new type structure. We now provide [guidance](https://www.apollographql.com/docs/react/migrating/apollo-client-4-migration#recommended-avoid-using-generated-hooks) in our migration guide to move away from them and I know a codemod was created to help modify this.
I'm proposing that we add this callout in the docs in addition to Apollo's docs so that we ensure this guidance can be seen as many places as possible.
Please delete …
=> Add callout for Apollo Client 4.0 compatibility with the `typescript-react-apollo` plugin

website/src/pages/docs/guides/react-vue.mdx
`pnpm add --dev typescript @graphql-codegen/cli @parcel/watcher`
=> ERROR  Unknown option: 'dev'
=> Fix: react-vue.mdx (--save-dev instead of --dev)

.changeset/lemon-insects-attend.md, dev-test/modules/blog/generated.ts, dev-test/modules/dotanions/generated.ts, dev-test/modules/users/generated.ts, packages/presets/graphql-modules/src/builder.ts, packages/presets/graphql-modules/tests/__snapshots__/integration.spec.ts.snap, packages/presets/graphql-modules/tests/builder.spec.ts, packages/presets/graphql-modules/tests/integration.spec.ts
This PR fixes `__isTypeOf` getting picked from all objects.
With https://github.com/dotansimha/graphql-code-generator/releases/tag/release-1757264511789 release, `__isTypeOf` is only generated for implementing types and union members.
This PR applies the same logic to `graphql-modules-preset` to make sure it's correctly picked.
Related https://github.com/dotansimha/graphql-code-generator/issues/10438
=> CODEGEN-859 [graphql-modules-preset] Fix __isTypeOf getting picked from from all objects
